Repository playcanvas/engine, pull requests merged in 2018-11, with the labels that each got.

#1426 Handle missing bones of skeletal animations more gracefully
  src/anim/skeleton.js
Labels: enhancement

#1430 [FIX] Prevent exception on calling pc.Application#destroy
  src/framework/application.js
Labels: bug

#1439 [FIX] Copy layers when there are more than one.
  src/framework/components/model/component.js
Labels: bug

#1440 EntityRef memory leak issue fixed
  src/framework/utils/entity-reference.js
Labels: bug

#1446 Defer high precision floating point rendering test
  src/graphics/device.js
  src/graphics/post-effect.js
  src/graphics/simple-post-effect.js
Labels: performance

#1450 Revert sync queue optimization.
  src/framework/application.js
  src/framework/components/element/component.js
  src/framework/entity.js
  src/scene/graph-node.js
Labels: bug
