Repository playcanvas/engine, pull requests merged in 2018-03, with the labels that each got.

#1119 Support for webglcontextlost
  src/framework/application.js
  src/graphics/device.js
  src/graphics/index-buffer.js
  src/graphics/render-target.js
  src/graphics/shader.js
  src/graphics/texture.js
  src/graphics/vertex-buffer.js
Labels: enhancement

#1128 Reinstate dt clamping and expose ability to set upper bound.
  src/framework/application.js
Labels: enhancement

#1105 Add stencilFront and stencilBack properties to mesh instance
  src/scene/forward-renderer.js
  src/scene/mesh.js
Labels: enhancement

#1118 UI masks per mesh instance
  examples/masking/index.html
  src/framework/components/element/component.js
  src/framework/components/element/image-element.js
  src/framework/components/element/system.js
  src/framework/components/element/text-element.js
  src/framework/components/sprite/system.js
  src/scene/forward-renderer.js
Labels: feature request

#1147 [FIX] assets.remove does not remove asset
  src/asset/asset-registry.js
Labels: bug

#1148 Hide pc.AudioSourceComponent and pc.Listener from API docs.
  src/framework/components/audio-source/component.js
  src/framework/components/audio-source/system.js
  src/sound/listener.js
  src/sound/manager.js
Labels: enhancement

#1143 [FIX] Unhook asset event callbacks when destroying model component.
  src/framework/components/model/system.js
Labels: bug

#1146 Add support for vertex color attribute when batching.
  src/scene/batching.js
Labels: enhancement

#1145 [FIX] Copy layer property when creating a batched mesh instance.
  src/scene/batching.js
Labels: bug

#1142 Minification via package.json
  package.json
Labels: enhancement

#1149 Reorganize transform chunks to avoid combinatorial explosion
  src/graphics/program-lib/chunks/normal.vert
  src/graphics/program-lib/chunks/transform.vert
  src/graphics/program-lib/chunks/transformBatchSkinned.vert
  src/graphics/program-lib/chunks/transformInstanced.vert
  src/graphics/program-lib/chunks/transformPixelSnap.vert
  src/graphics/program-lib/chunks/transformScreenSpace.vert
  src/graphics/program-lib/chunks/transformScreenSpaceBatchSkinned.vert
  src/graphics/program-lib/chunks/transformSkinned.vert
  src/graphics/program-lib/chunks/transformUv1.vert
  src/graphics/program-lib/depth-rgba.js
  src/graphics/program-lib/depth.js
  src/graphics/program-lib/pick.js
  src/graphics/program-lib/standard.js
  src/scene/batching.js
  src/scene/lightmapper.js
Labels: enhancement
