Repository playcanvas/engine, pull requests merged in 2018-09, with the labels that each got.

#1333 Only call _updateMesh in the Image Element when the rect, sprite or spriteFrame actually change
  src/framework/components/element/component.js
  src/framework/components/element/image-element.js
  src/framework/components/element/system.js
  tests/framework/components/element/test_element.js
  tests/framework/components/element/test_imageelement.js
Labels: performance

#1335 Only call setParameter in text element when color and opacity actualy change, Fix aabb errors when using multiple font textures
  src/framework/components/element/system.js
  src/framework/components/element/text-element.js
  tests/framework/components/element/test_textelement.js
Labels: bug, performance

#1334 Only call setParameter if the color or opacity of an image element actually change
  src/framework/components/element/image-element.js
  src/framework/components/element/system.js
  tests/framework/components/element/test_imageelement.js
Labels: performance

#1351 Convert forEach to for loop in component systems.
  src/framework/components/camera/system.js
  src/framework/components/collision/system.js
  src/framework/components/light/system.js
  src/framework/components/model/system.js
  src/framework/components/rigid-body/system.js
  src/framework/components/system.js
Labels: performance

#1353 Disable tangent generation in JSON model parser.
  src/resources/parser/json-model.js
Labels: performance

#1327 Remove typed arrays from pc.Vec2/3/4 and pc.Color.
  src/backwards-compatibility.js
  src/core/color.js
  src/framework/components/button/component.js
  src/framework/components/camera/component.js
  src/framework/components/camera/post-effect-pass.js
  src/framework/components/element/component.js
  src/framework/components/element/element-drag-helper.js
  src/framework/components/element/image-element.js
  src/framework/components/element/text-element.js
  src/framework/components/layout-group/layout-calculator.js
  src/framework/components/particle-system/system.js
  src/framework/components/scroll-view/component.js
  src/framework/components/sprite/component.js
  src/framework/components/sprite/system.js
  src/input/element-input.js
  src/math/mat3.js
  src/math/mat4.js
  src/math/quat.js
  src/math/vec2.js
  src/math/vec3.js
  src/math/vec4.js
  src/scene/batching.js
  src/scene/camera.js
  src/scene/forward-renderer.js
  src/scene/graph-node.js
  src/scene/layer.js
  src/scene/light.js
  src/scene/lightmapper.js
  src/scene/materials/basic-material.js
  src/scene/materials/standard-material.js
  src/scene/particle-emitter.js
  src/scene/sprite.js
  src/script/script.js
  src/shape/bounding-box.js
  src/shape/frustum.js
  src/vr/vr-display.js
  tests/framework/components/layout-group/test_layoutcalculator.js
  tests/math/test_quat.js
  tests/math/test_vec2.js
  tests/math/test_vec3.js
  tests/math/test_vec4.js
Labels: performance

#1355 Optimize pc.SceneParser#_openComponentData.
  src/framework/application.js
  src/framework/components/animation/system.js
  src/framework/components/audio-listener/system.js
  src/framework/components/audio-source/system.js
  src/framework/components/button/system.js
  src/framework/components/camera/system.js
  src/framework/components/collision/system.js
  src/framework/components/element/system.js
  src/framework/components/layout-child/system.js
  src/framework/components/layout-group/system.js
  src/framework/components/light/system.js
  src/framework/components/model/system.js
  src/framework/components/particle-system/system.js
  src/framework/components/registry.js
  src/framework/components/rigid-body/system.js
  src/framework/components/screen/system.js
  src/framework/components/script-legacy/system.js
  src/framework/components/script/system.js
  src/framework/components/scroll-view/system.js
  src/framework/components/scrollbar/system.js
  src/framework/components/sound/system.js
  src/framework/components/sprite/system.js
  src/framework/components/zone/system.js
  src/framework/utils/entity-reference.js
  src/resources/parser/scene.js
  tests/framework/test_entity.js
  tests/framework/utils/test_entityreference.js
  tests/helpers/dummy/system.js
Labels: performance

#1358 Reduce calls to this.data getter.
  src/framework/components/model/component.js
Labels: performance

#1357 Remove calls to pc.Component#onEnable/onDisable which do nothing.
  src/framework/components/audio-listener/component.js
  src/framework/components/audio-source/component.js
  src/framework/components/camera/component.js
  src/framework/components/collision/component.js
  src/framework/components/element/component.js
  src/framework/components/light/component.js
  src/framework/components/model/component.js
  src/framework/components/particle-system/component.js
  src/framework/components/rigid-body/component.js
  src/framework/components/script-legacy/component.js
  src/framework/components/script/component.js
  src/framework/components/sound/component.js
  src/framework/components/sprite/component.js
  src/framework/components/zone/component.js
Labels: performance

#1359 Strip .data from _shaderParams.
  src/scene/forward-renderer.js
Labels: bug

#1361 Fix VSM after .data changes.
  src/scene/forward-renderer.js
Labels: bug

#1365 [FIX] Restore legacy script attribute cloning for legacy scripts.
  src/framework/application.js
Labels: bug

#1366 [FIX] Particle emitter position can be updated again.
  src/scene/particle-emitter.js
Labels: bug

#1367 [FIX] Remove .data reference from layout calculator.
  src/framework/components/layout-group/layout-calculator.js
Labels: bug

#1372 [FIX] Pass Float32Array instead of pc.Vec4 to setValue.
  src/framework/components/camera/post-effect-pass.js
Labels: bug

#1371 Add support for textures with premultiplied alpha.
  src/graphics/device.js
  src/graphics/texture.js
Labels: feature request

#1373 Defer work done by material.update until a material is actually used.
  src/backwards-compatibility.js
  src/scene/forward-renderer.js
  src/scene/materials/basic-material.js
  src/scene/materials/depth-material.js
  src/scene/materials/material.js
  src/scene/materials/standard-material.js
Labels: performance

#1374 Enable parallel shader compilation.
  src/graphics/device.js
Labels: performance

#1376 Minor refactor of pc.StandardMaterial
  src/resources/material.js
  src/resources/parser/material/json-standard-material.js
  src/scene/materials/standard-material.js
Labels: performance

#1377 RBG -> RGB
  src/framework/components/text/canvas-font.js
Labels: bug
