Repository playcanvas/engine, pull requests merged in 2019-11, with the labels that each got.

#1730 [DOCS] Make scrollbar API reference docs public
  src/framework/components/scrollbar/component.js
  src/framework/components/scrollbar/system.js
Labels: enhancement

#1734 [FIX] This fixes a bug where setting the pivot of a pc.Element does not update the position of children pc.Elements
  src/framework/components/element/component.js
Labels: bug

#1732 Added width/height properties to the pc.SpriteComponent docs
  src/framework/components/sprite/component.js
Labels: docs

#1749 [FIX] some memory leaks with physics objects (ammo.js)
  src/framework/components/collision/system.js
  src/framework/components/collision/trigger.js
  src/framework/components/rigid-body/component.js
  src/framework/components/rigid-body/system.js
Labels: bug

#1752 Compound Collision Shapes
  src/framework/components/collision/component.js
  src/framework/components/collision/system.js
  src/framework/components/collision/trigger.js
  src/framework/components/rigid-body/system.js
Labels: enhancement

#1759 Add latest WASM build of Ammo
  examples/index.html
  examples/physics/falling_shapes.html
  examples/physics/falling_shapes/index.html
  examples/shared/example.js
  lib/ammo/ammo.js
  lib/ammo/ammo.wasm.js
  lib/ammo/ammo.wasm.wasm
Labels: enhancement

#1760 [DOCS] Expose pc.ModelComponent#material.
  src/framework/components/model/component.js
Labels: docs

#1762 Reduce the number of function calls into ammo.js when creating contacts
  src/framework/components/rigid-body/system.js
Labels: performance
