Repository playcanvas/engine, pull requests merged in 2019-03, with the labels that each got.

#1505 Fix post-effect-queue
  examples/post_effects/index.html
  src/framework/components/camera/post-effect-queue.js
Labels: bug

#1513 Optimize image element creation. Reduces creation cost by ~25-30%.
  src/framework/components/element/image-element.js
  tests/framework/components/element/test_imageelement.js
Labels: performance

#1516 Release API Ref docs for pc.ButtonComponent
  src/framework/components/button/component.js
  src/framework/components/button/constants.js
  src/framework/components/button/system.js
Labels: enhancement

#1522 Do not call keys.length multiple times
  src/math/curve.js
Labels: performance

#1524 Don't extract model if model is not loaded
  src/scene/batching.js
Labels: bug
