Repository playcanvas/engine, pull requests merged in 2020-10, with the labels that each got.

#2457 AnimComponent - State duration property fix
  src/framework/components/anim/controller.js
Labels: area: animation, bug

#2459 [FIX] Minor corrections to Typescript definitions
  src/core/tags.js
  src/framework/application.js
  src/scene/lightmapper.js
Labels: bug, docs

#2435 Optimized culling solution for skinned meshes
  src/framework/components/model/component.js
  src/scene/batching.js
  src/scene/forward-renderer.js
  src/scene/mesh-instance.js
  src/scene/skin-instance.js
Labels: area: graphics, enhancement

#2476 Improvements and fixes to Picker, new engine example
  examples/examples.js
  examples/graphics/area-picker.html
  src/scene/forward-renderer.js
  src/scene/mesh-instance.js
  src/scene/pick.js
Labels: bug, enhancement

#2474 fix for normals on two-sided materials with negative scale
  src/graphics/program-lib/programs/standard.js
  src/scene/forward-renderer.js
Labels: area: graphics, bug

#2480 Brush painting engine example using rendering to texture
  examples/examples.js
  examples/graphics/painter.html
Labels: area: graphics

#2490 Handle unicode control characters specially
  src/framework/components/element/text-element.js
Labels: bug

#2489 Added a material flag to disable material opacity fading out specular and added a value to specifically alpha fade out materials (including specular)
  examples/examples.js
  examples/graphics/material-translucent-specular.html
  src/graphics/program-lib/programs/standard.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
Labels: area: graphics, bug

#2498 Correctly unhook model asset from collision component
  src/framework/components/collision/component.js
Labels: area: physics, bug

#2502 Performance optimization of LayerComposition Update
  src/framework/application.js
  src/framework/components/particle-system/system.js
  src/scene/forward-renderer.js
  src/scene/layer-composition.js
  src/scene/layer.js
Labels: area: graphics, performance

#2510 Fixed typo in JSDocs anim component
  src/framework/components/anim/component.js
Labels: area: animation, docs
