Repository playcanvas/engine, pull requests merged in 2020-05, with the labels that each got.

#2040 [FIX] Don't free raycast structures twice
  src/framework/components/rigid-body/system.js
Labels: area: physics, bug

#2036 Fix getting transforms of inputSource after XR session is ended
  src/xr/xr-input-source.js
  src/xr/xr-manager.js
Labels: area: xr, bug

#2043 glTF default morph weights
  src/resources/parser/glb-parser.js
  src/scene/morph.js
  tools/glb-viewer/src/controls.js
  tools/glb-viewer/src/viewer.js
Labels: area: graphics, bug

#2041 More generic mesh batching
  src/graphics/graphics.js
  src/graphics/vertex-format.js
  src/graphics/vertex-iterator.js
  src/scene/batching.js
  src/scene/mesh.js
Labels: area: graphics, enhancement

#2050 RenderLine fix when no options specified
  src/scene/immediate.js
Labels: area: graphics, bug

#2051 add glb mime type
  src/net/http.js
Labels: bug

#2054 [FIX] glTF parser not handling vertex attributes that need normalizing
  src/resources/parser/glb-parser.js
Labels: area: graphics, bug

#2055 [FIX] Glb assets not loading when part of asset bundles
  src/resources/animation.js
  src/resources/model.js
Labels: bug

#2059 Particle world bounds cpu fix
  src/scene/particle-system/particle-emitter.js
Labels: area: graphics, bug

#2065 Add new compound collision example
  examples/examples.js
  examples/physics/compound-collision.html
Labels: area: physics, enhancement

#2068 [FIX] A rigid body's motion state no longer leaks
  src/framework/components/rigid-body/system.js
Labels: area: physics, bug

#2070 [FIX] removed basis URL from cache after transcode
  src/resources/basis.js
Labels: area: graphics, bug

#2009 Updated tests and docs for sceneRegistry loadScene* functions
  src/callbacks.js
  src/framework/scene-registry.js
  tests/framework/components/script/test_script_component.js
Labels: docs

#2075 Increasing num particles fix
  src/framework/components/particle-system/component.js
Labels: area: graphics, bug

#2074 Changed collision checks to properly check on each each internal physics world time step.
  src/framework/components/rigid-body/system.js
Labels: area: physics, bug

#2073 Extended the Outline post effect
  examples/assets/scripts/posteffects/posteffect-outline.js
  examples/graphics/model-outline.html
Labels: area: graphics, enhancement

#2080 [Physics] Fix Ammo dynamics world memory never being released
  src/framework/components/rigid-body/system.js
Labels: area: physics, bug

#2078 small reflection chunks cleanup
  src/graphics/program-lib/chunks/reflectionCC.frag
  src/graphics/program-lib/chunks/reflectionCube.frag
  src/graphics/program-lib/chunks/reflectionDpAtlas.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCube.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/reflectionSphere.frag
  src/graphics/program-lib/chunks/reflectionSphereLow.frag
Labels: area: graphics, enhancement

#1997 Physics engine optimizations
  examples/physics/falling-shapes.html
  src/backwards-compatibility.js
  src/framework/application.js
  src/framework/components/collision/component.js
  src/framework/components/collision/system.js
  src/framework/components/collision/trigger.js
  src/framework/components/rigid-body/component.js
  src/framework/components/rigid-body/system.js
Labels: area: physics, bug, performance

#2046 WebXR AR Light Estimation
  build/dependencies.txt
  src/xr/xr-light-estimation.js
  src/xr/xr-manager.js
Labels: area: xr, enhancement

#2056 Lossless image Optimization
  examples/assets/button/red_button_atlas.png
  examples/assets/fonts/arial.png
  examples/assets/fonts/courier.png
  examples/assets/models/playbot/26020276/head_N_clean.png
  examples/assets/models/playbot/26020277/head_E.png
  examples/assets/models/playbot/26020278/env_01.png
  examples/assets/models/playbot/26020279/arm_clean.png
  examples/assets/models/playbot/26020280/body_N_clean.png
  examples/assets/models/playbot/26020281/arm_E.png
  examples/assets/models/playbot/26020282/leg_N_clean.png
  examples/assets/models/playbot/26020284/leg_E.png
  examples/assets/models/playbot/26020286/head_clean.png
  examples/assets/models/playbot/26020287/body_clean.png
  examples/assets/models/playbot/26020288/body_E.png
  examples/assets/models/playbot/26020289/arm_N_clean.png
  examples/assets/models/playbot/26020290/leg_clean.png
  examples/assets/models/statue/26111212/statue-normal.jpg
  examples/assets/models/statue/26111213/statue-diffuse.jpg
  examples/assets/models/statue/26111214/statue-specular.jpg
  examples/assets/textures/blue-panel.png
  examples/assets/textures/clouds.jpg
  examples/assets/textures/flakes5c.png
  examples/assets/textures/flakes5n.png
  examples/assets/textures/flakes5o.png
  examples/assets/textures/heart.png
  examples/assets/textures/particles-bonus.png
  examples/assets/textures/particles-coins.png
  examples/assets/textures/particles-numbers.png
  examples/assets/textures/playcanvas-grey.png
  examples/assets/textures/snowflake.png
  examples/assets/textures/spark.png
  examples/playcanvas-favicon.png
  tests/test-assets/particlesystem/colormap.png
  tests/test-assets/particlesystem/normalmap.png
  tests/test-assets/sprite/red-atlas.png
Labels: area: graphics, enhancement

#2086 Reset state of button on enable
  src/framework/components/button/component.js
Labels: area: ui, bug

#2087 Cleanup loadFromUrl, construct relative asset URLs correctly
  src/asset/asset-registry.js
  src/asset/asset.js
  src/framework/components/model/component.js
  src/resources/material.js
  src/resources/model.js
Labels: bug

#2084 GPU Morph Targets
  build/dependencies.txt
  examples/examples.js
  examples/graphics/mesh-morph.html
  src/graphics/device.js
  src/graphics/graphics.js
  src/graphics/program-lib/chunks/normal.vert
  src/graphics/program-lib/chunks/transform.vert
  src/graphics/program-lib/standard.js
  src/graphics/vertex-format.js
  src/resources/parser/glb-parser.js
  src/resources/parser/json-model.js
  src/scene/forward-renderer.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  src/scene/mesh.js
  src/scene/morph-instance.js
  src/scene/morph-target.js
  src/scene/morph.js
  src/scene/scene.js
  src/shape/bounding-box.js
Labels: area: graphics, performance

#2089 [FIX] Ignore scale on entity transform when setting body transform
  src/framework/components/rigid-body/component.js
Labels: area: physics, bug

#2091 Update CircleCI configuration
  .circleci/config.yml
  package.json
Labels: enhancement

#2096 Expose the original browser TouchEvent
  src/input/touch.js
Labels: area: input, docs

#2099 Added command in readme to build playcanvas-extras
  README.md
Labels: docs

#2100 Added blob prefix check to absolute URL check
  src/asset/asset.js
Labels: bug

#2082 handle cubemap asset faces specified as urls
  src/resources/cubemap.js
Labels: area: graphics, bug

#2108 Cubemap load textures
  src/resources/cubemap.js
Labels: area: graphics, bug

#2112 [FIX] Exception on removing particlesystem component
  src/framework/components/particle-system/component.js
Labels: area: graphics, bug

#2113 Remove CircleCI
  .circleci/config.yml
Labels: enhancement
