Repository playcanvas/engine, pull requests merged in 2020-07, with the labels that each got.

#2229 [FIX] Correct type for autoWidth and autoHeight
  src/framework/components/element/component.js
Labels: area: ui, bug

#2236 Updated property documentation for pc.ModelComponent#material
  src/framework/components/model/component.js
Labels: docs

#2231 ImageBitmap loader
  src/graphics/device.js
  src/graphics/texture.js
  src/resources/parser/glb-parser.js
  src/resources/parser/texture/img.js
  src/resources/parser/texture/legacy-dds.js
Labels: area: graphics, enhancement

#2239 Cubemap update
  src/asset/asset-registry.js
  src/resources/cubemap.js
  src/resources/loader.js
  tests/bundles/test_bundle_loader.js
  tools/viewer/index.html
  tools/viewer/src/viewer.js
Labels: area: graphics, bug

#2241 lint fixes
  src/graphics/device.js
  src/resources/parser/texture/img.js
Labels: enhancement

#2238 Remove remaining occurrences of pc
  src/graphics/program-lib/standard.js
  src/graphics/texture.js
  src/graphics/vertex-format.js
  src/math/curve-evaluator.js
  src/math/curve-set.js
  src/math/curve.js
  src/math/mat4.js
  src/math/math.js
  src/resources/parser/texture/basis.js
  src/script/script-attributes.js
Labels: bug

#2242 IE11 compatibility: glb-parser and engine examples
  examples/graphics/mesh-decals.html
  examples/graphics/mesh-generation.html
  examples/graphics/particles-random-sprites.html
  examples/graphics/point-cloud-simulation.html
  src/resources/parser/glb-parser.js
Labels: bug

#2243 Glb-parser texture load fix
  src/resources/parser/glb-parser.js
Labels: area: graphics, bug

#2248 disable imagebitmap
  src/resources/parser/texture/img.js
Labels: bug

#2240 iOS particle velocity fix
  src/graphics/program-lib/chunks/particle.vert
  src/graphics/program-lib/chunks/particleUpdaterStart.frag
Labels: area: graphics, bug

#2249 fix pc variable reference
  src/resources/cubemap.js
Labels: dependencies

#2244 Anim component updates for the editor
  src/framework/components/anim/component.js
  src/framework/components/anim/controller.js
  src/framework/components/anim/data.js
  src/framework/components/anim/layer.js
  src/framework/components/anim/state-graph.js
  src/framework/components/anim/system.js
  src/framework/components/model/component.js
Labels: area: animation, enhancement

#2253 Fix example error accessing null object
  examples/graphics/material-anisotropic.html
  examples/graphics/material-clear-coat.html
  examples/graphics/material-physical.html
Labels: bug

#2255 Revert skybox mip fix
  src/scene/scene.js
Labels: bug

#2250 Add support for OES_vertex_array_object
  examples/graphics/hierarchy.html
  src/graphics/device.js
  src/graphics/graphics.js
  src/graphics/vertex-buffer.js
  src/graphics/vertex-format.js
  src/index.js
  src/polyfill/OESVertexArrayObject.js
  src/scene/forward-renderer.js
  src/scene/mesh-instance.js
Labels: area: graphics, performance

#2257 Freezing constant math objects
  src/core/color.js
  src/math/mat3.js
  src/math/mat4.js
  src/math/quat.js
  src/math/vec2.js
  src/math/vec3.js
  src/math/vec4.js
Labels: enhancement

#2258 Viewer, glTF processAsync changes
  src/resources/parser/glb-parser.js
  tools/viewer/asset_manifest.json
  tools/viewer/index.html
  tools/viewer/src/controls.js
  tools/viewer/src/viewer.js
Labels: enhancement

#2266 [FIX] Don’t capture Index Buffer in VAO
  src/graphics/device.js
Labels: area: graphics, bug

#2268 fix material resource loader
  src/resources/material.js
Labels: bug

#2272 Fix cubemap reload issue
  src/resources/cubemap.js
Labels: area: graphics, bug

#2252 Glb texture coordinate fix
  src/resources/cubemap.js
  src/resources/parser/glb-parser.js
  src/resources/parser/texture/img.js
  tools/viewer/src/viewer.js
Labels: bug, enhancement

#2274 Remove some shader-related circular dependencies
  src/deprecated.js
  src/framework/components/camera/post-effect-pass.js
  src/graphics/chunks.js
  src/graphics/device.js
  src/graphics/paraboloid.js
  src/graphics/prefilter-cubemap.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/particle.js
  src/graphics/program-lib/program-lib.js
  src/graphics/program-lib/programs/basic.js
  src/graphics/program-lib/programs/common.js
  src/graphics/program-lib/programs/particle.js
  src/graphics/program-lib/programs/skybox.js
  src/graphics/program-lib/programs/standard.js
  src/graphics/program-lib/skybox.js
  src/graphics/program-lib/utils.js
  src/graphics/reproject-texture.js
  src/graphics/transform-feedback.js
  src/index.js
  src/scene/batching.js
  src/scene/forward-renderer.js
  src/scene/lightmapper.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
  src/scene/morph-instance.js
  src/scene/particle-system/particle-emitter.js
Labels: area: graphics, enhancement

#2273 Remove type function
  src/framework/components/camera/system.js
  src/framework/components/collision/system.js
  src/framework/components/element/system.js
  src/framework/components/light/system.js
  src/framework/components/particle-system/system.js
  src/framework/components/rigid-body/system.js
  src/framework/components/script-legacy/system.js
  src/framework/components/sprite/system.js
  src/math/curve-set.js
Labels: performance

#2281 [FIX] pc.SoundComponent#resume/stop param type
  src/framework/components/sound/component.js
  src/scene/procedural.js
Labels: docs

#2282 Remove viewer
  package.json
  tools/viewer/asset_manifest.json
  tools/viewer/index.html
  tools/viewer/playcanvas-logo.png
  tools/viewer/src/controls.js
  tools/viewer/src/debug.js
  tools/viewer/src/graph.js
  tools/viewer/src/viewer.js
  tools/viewer/style.css
Labels: enhancement

#2278 Update the anim state graph to support the new data schema
  src/framework/components/anim/state-graph.js
Labels: area: animation, enhancement

#2284 [FIX] Make Transform Feedback work with VAOs
  src/graphics/transform-feedback.js
Labels: area: graphics, bug

#2285 [FIX] Correctly handle invalid cubemap texture assets
  src/resources/cubemap.js
Labels: area: graphics, bug

#2288 [FIX] Cubemap filtering on safari
  src/resources/cubemap.js
Labels: area: graphics, bug

#2291 [FIX] API ref docs for pc.Mesh#getIndices
  src/scene/mesh.js
Labels: area: graphics, bug, docs

#2289 Deprecate pc.makeArray
  src/core/core.js
  src/deprecated.js
  src/framework/components/script-legacy/component.js
  src/framework/components/script-legacy/system.js
  src/index.js
Labels: enhancement

#2297 Update NPM dependencies
  package-lock.json
  package.json
Labels: enhancement

#2303 Fix glTF texture transform
  .npmignore
  examples/graphics/shader-burn.html
  examples/graphics/shader-wobble.html
  package.json
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material.js
Labels: area: graphics, bug

#2305 Fix webxr rendering with vao
  src/graphics/device.js
  src/scene/forward-renderer.js
Labels: area: xr, bug

#2307 Apply flip v transform later in the pipeline
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material.js
Labels: area: graphics, bug

#2293 AnimBinder no model fix
  src/framework/components/anim/binder.js
Labels: area: animation, bug

#2310 Revert changes to texture coordinate flipping for glTF
  examples/graphics/shader-burn.html
  examples/graphics/shader-wobble.html
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material.js
Labels: area: graphics, bug

#2309 Fixed animation.currentTime for GLB animations
  src/framework/components/animation/component.js
Labels: area: animation, bug

#2306 Added extra documentation for supported markup tags in the text element
  src/framework/components/element/component.js
Labels: docs

#2296 Deprecate pc.Frustum#update
  src/deprecated.js
  src/scene/camera.js
  src/scene/forward-renderer.js
  src/shape/bounding-box.js
  src/shape/bounding-sphere.js
  src/shape/frustum.js
  src/shape/oriented-box.js
  src/shape/plane.js
  src/shape/ray.js
Labels: enhancement, performance

#2312 Expose glTF bufferView to callbacks
  extras/mini-stats/mini-stats.js
  src/deprecated.js
  src/resources/container.js
  src/resources/parser/glb-parser.js
Labels: area: graphics, enhancement

#2313 Add general support for sparse accessors
  src/resources/parser/glb-parser.js
Labels: area: graphics, bug

#2315 [DOCS] Improve docs for pc.Application#renderLines
  src/framework/application.js
Labels: bug, docs

#2317 Add vehicle physics example
  examples/assets/scripts/camera/tracking-camera.js
  examples/assets/scripts/physics/render-physics.js
  examples/assets/scripts/physics/reset-physics.js
  examples/assets/scripts/physics/vehicle.js
  examples/examples.js
  examples/physics/vehicle.html
Labels: area: physics, enhancement

#2318 Handle gltfTextures correctly and update process callbacks
  src/resources/container.js
  src/resources/parser/glb-parser.js
Labels: area: graphics, enhancement

#2319 Anim component api updates
  src/framework/components/anim/controller.js
  src/framework/components/anim/layer.js
  src/framework/components/anim/state-graph.js
Labels: area: animation, enhancement

#2324 GLTF empty node name fix
  src/resources/parser/glb-parser.js
Labels: area: animation, bug

#2327 Load gltf textures correctly
  src/resources/parser/glb-parser.js
Labels: bug, enhancement

#2299 Refactor camera code
  src/deprecated.js
  src/framework/components/camera/component.js
  src/framework/components/camera/data.js
  src/framework/components/camera/post-effect-queue.js
  src/framework/components/camera/system.js
  src/framework/components/element/component.js
  src/graphics/device.js
  src/scene/camera.js
  src/scene/forward-renderer.js
  src/scene/lightmapper.js
  src/scene/pick.js
Labels: area: graphics, performance

#2328 Smarter handling of cubemap texture state
  src/resources/cubemap.js
Labels: enhancement
