Repository playcanvas/engine, pull requests merged in 2020-11, with the labels that each got.

#2515 Don't crash when using destroyed textures
  src/graphics/texture.js
Labels: bug

#2517 Add debug message when using a destroyed texture
  src/graphics/device.js
Labels: enhancement

#2520 Fixed orientation on physics renders on capsules and cylinders based on axis creation
  examples/assets/scripts/physics/render-physics.js
Labels: area: physics, bug

#2521 Fix capsule debug physics render
  examples/assets/scripts/physics/render-physics.js
Labels: area: physics, bug

#2522 Prefiltered lighting updates
  src/graphics/program-lib/chunks/reflectionPrefilteredCube.frag
  src/graphics/program-lib/chunks/reproject.frag
  src/graphics/reproject-texture.js
Labels: area: graphics, enhancement

#2525 Assign better defaults to JSON script attribute fields
  src/script/script-attributes.js
  tests/framework/components/script/scriptWithAttributes.js
  tests/framework/components/script/test_script_component.js
Labels: bug

#2528 Further prefilter fixes
  src/graphics/program-lib/chunks/reproject.frag
Labels: bug

#2512 Add tweening example
  examples/animation/tweening.html
  examples/assets/scripts/animation/tween.js
  examples/examples.js
Labels: area: animation, enhancement

#2507 Update curve docs for tension
  src/math/curve.js
Labels: docs

#2495 Fixed WebVR transform update from vrDisplay
  src/framework/components/camera/system.js
Labels: area: graphics, bug

#2524 Null a potentially dangling screen entity reference on remove
  src/framework/components/element/component.js
Labels: area: ui, bug

#2530 fix for hdr post processes
  src/graphics/device.js
Labels: area: graphics, bug

#2531 Prefilter shader fix
  src/graphics/program-lib/chunks/fixCubemapSeamsNone.frag
  src/graphics/program-lib/chunks/fixCubemapSeamsStretch.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCube.frag
Labels: area: graphics, bug

#2532 ;
  src/graphics/program-lib/chunks/fixCubemapSeamsNone.frag
Labels: bug

#2543 Update NPM dependencies
  package-lock.json
  package.json
Labels: enhancement

#2537 Fix Bokeh Depth of Field post process
  examples/assets/scripts/posteffects/posteffect-bokeh.js
  examples/graphics/post-effects.html
Labels: area: graphics, bug

#2527 Add support for Cube Map Rotation and expose Skybox Rotation
  examples/graphics/material-physical.html
  src/framework/application.js
  src/graphics/program-lib/chunks/ambientPrefilteredCube.frag
  src/graphics/program-lib/chunks/ambientPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/ambientSH.frag
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/cubeMapProjectBox.frag
  src/graphics/program-lib/chunks/cubeMapProjectNone.frag
  src/graphics/program-lib/chunks/cubeMapRotate.frag
  src/graphics/program-lib/chunks/reflectionCube.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCube.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/skybox.vert
  src/graphics/program-lib/chunks/skyboxHDR.frag
  src/graphics/program-lib/programs/skybox.js
  src/graphics/program-lib/programs/standard.js
  src/graphics/texture.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
  src/scene/scene.js
Labels: area: graphics, enhancement

#2551 Fixed bug where animations are not correctly removed from component when asset is unloaded
  src/framework/components/animation/component.js
Labels: area: animation, bug

#2550 Added public API for Container resource
  src/resources/container.js
Labels: docs

#2558 fix shader compile error when forceUv1 option is used
  src/graphics/program-lib/programs/standard.js
Labels: area: graphics, bug

#2566 resource id fix
  src/resources/cubemap.js
Labels: area: graphics, bug

#2567 Update wasm modules
  .github/workflows/ci.yml
  examples/lib/basis/basis.js
  examples/lib/basis/basis.wasm.js
  examples/lib/basis/basis.wasm.wasm
Labels: area: graphics, enhancement
