Repository playcanvas/engine, pull requests merged in 2020-01, with the labels that each got.

#1800 [EXAMPLES] Add new baked lighting example
  build/dependencies.txt
  examples/examples.js
  examples/graphics/lights-baked.html
  examples/index.html
  src/polyfill/math-sign.js
Labels: enhancement

#1810 [FIX] Fix text element markup on IE11 which needs Array#find
  build/dependencies.txt
  src/polyfill/array-find.js
Labels: bug

#1814 Prevent attempting to load model twice from url
  src/asset/asset-registry.js
Labels: bug

#1790 Fix material loading from URL if textures already loaded
  src/asset/asset-registry.js
Labels: bug

#1829 [DOCS] Switch JSDoc comment blocks from HTML to Markdown
  conf-api.json
  src/asset/asset.js
  src/core/string.js
  src/core/uri.js
  src/framework/application.js
  src/framework/components/audio-source/component.js
  src/framework/components/camera/component.js
  src/framework/components/collision/component.js
  src/framework/components/element/component.js
  src/framework/components/layout-group/component.js
  src/framework/components/light/component.js
  src/framework/components/model/component.js
  src/framework/components/particle-system/component.js
  src/framework/components/rigid-body/component.js
  src/framework/components/scroll-view/component.js
  src/framework/components/scrollbar/component.js
  src/framework/components/sound/component.js
  src/framework/components/sprite/component.js
  src/framework/entity.js
  src/framework/script.js
  src/framework/utils/entity-reference.js
  src/graphics/device.js
  src/graphics/render-target.js
  src/graphics/texture.js
  src/graphics/transform-feedback.js
  src/graphics/vertex-format.js
  src/input/mouse.js
  src/math/curve-set.js
  src/math/curve.js
  src/resources/loader.js
  src/scene/batching.js
  src/scene/camera.js
  src/scene/layer.js
  src/scene/lightmapper.js
  src/scene/materials/material.js
  src/scene/materials/standard-material.js
  src/scene/mesh.js
  src/scene/procedural.js
  src/scene/scene.js
  src/scene/sprite.js
  src/script/script.js
  src/sound/instance3d.js
Labels: docs

#1830 [DOCS] Use spread operator for arbitrary argument functions
  src/asset/asset-registry.js
  src/backwards-compatibility.js
  src/core/path.js
  src/core/string.js
  src/core/tags.js
  src/sound/manager.js
Labels: docs

#1785 Animation playback ends normally
  src/framework/components/animation/system.js
Labels: bug

#1808 Add touch property to ElementTouchEvent
  src/input/element-input.js
Labels: enhancement

#1832 [FIX] Mouse wheel is now consistent across browsers
  src/core/platform.js
  src/input/element-input.js
  src/input/mouse.js
Labels: bug

#1835 Add optional custom calculation of MeshInstance render sort distance
  src/callbacks.js
  src/scene/layer.js
  src/scene/mesh.js
Labels: enhancement

#1838 [FIX] Restore skybox enabling behavior
  src/scene/scene.js
Labels: bug

#1843 [FIX] Fix to object culling when generating directional lightmap (1799)
  src/scene/forward-renderer.js
Labels: bug

#1840 Normals cleanup
  src/graphics/program-lib/chunks/normalMap.frag
  src/graphics/program-lib/chunks/normalMapFast.frag
  src/graphics/program-lib/chunks/normalMapFloatTBNfast.frag
  src/graphics/program-lib/chunks/specularAaToksvig.frag
  src/graphics/program-lib/chunks/specularAaToksvigFast.frag
  src/graphics/program-lib/standard.js
  src/scene/materials/standard-material-options-builder.js
Labels: enhancement
