Repository playcanvas/engine, pull requests merged in 2020-08, with the labels that each got.

#2331 [DOCS] Improve docs for pc.IndexBuffer
  src/graphics/graphics.js
  src/graphics/index-buffer.js
Labels: area: graphics, docs

#2333 [FIX] Spelling mistakes
  src/framework/application.js
  src/framework/components/button/component.js
  src/framework/components/camera/post-effect-queue.js
  src/framework/components/collision/component.js
  src/framework/components/element/component.js
  src/framework/components/light/component.js
  src/framework/components/particle-system/component.js
  src/framework/components/script/component.js
  src/framework/components/scroll-view/component.js
  src/framework/components/text/canvas-font.js
  src/framework/utils/entity-reference.js
  src/graphics/program-lib/programs/standard.js
  src/i18n/i18n.js
  src/input/constants.js
  src/input/touch.js
  src/math/constants.js
  src/net/http.js
  src/resources/loader.js
  src/resources/parser/texture/ktx.js
  src/scene/batching.js
  src/scene/constants.js
  src/scene/graph-node.js
  src/scene/layer-composition.js
  src/scene/layer.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  src/scene/particle-system/cpu-updater.js
  src/scene/particle-system/particle-emitter.js
  src/scene/procedural.js
  src/scene/scene.js
  src/script/script-type.js
Labels: bug, docs

#2339 [FIX] Update position of positional sound components
  src/framework/components/sound/system.js
Labels: area: sound, bug

#2316 Add WebXR Tracked Hands API
  examples/examples.js
  examples/xr/vr-hands.html
  src/xr/xr-finger.js
  src/xr/xr-hand.js
  src/xr/xr-input-source.js
  src/xr/xr-joint.js
  src/xr/xr-manager.js
Labels: area: xr, enhancement

#2342 Fix overbright cubemaps
  src/resources/cubemap.js
Labels: bug

#2358 Construct node hierarchy even when no model exists
  src/resources/container.js
Labels: enhancement

#2359 Specify basis URL config
  src/index.js
  src/resources/basis.js
Labels: area: graphics, enhancement

#2354 Anim optimizations
  src/framework/components/anim/binder.js
Labels: area: animation, performance

#2367 [FIX] handle patching container multiple times
  src/resources/container.js
Labels: area: graphics, bug

#2370 Update NPM dependencies
  package-lock.json
  package.json
  src/framework/components/anim/binder.js
Labels: enhancement

#2381 Add hit-test to optional XR features
  src/xr/xr-manager.js
Labels: area: xr, bug

#2390 AnimComponent - support for transitions from any state
  src/framework/components/anim/constants.js
  src/framework/components/anim/controller.js
Labels: area: animation

#2375 Fix normals when mesh has both two-sided material and negative scale
  src/graphics/program-lib/programs/standard.js
Labels: area: graphics, bug

#2377 Improve clear-coat material and add KHR_materials_clearcoat support in glTF parser
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/clearCoat.frag
  src/graphics/program-lib/chunks/clearCoatGloss.frag
  src/graphics/program-lib/chunks/clearCoatNormal.frag
  src/graphics/program-lib/chunks/gloss.frag
  src/graphics/program-lib/chunks/metalness.frag
  src/graphics/program-lib/chunks/normalMap.frag
  src/graphics/program-lib/chunks/normalMapFast.frag
  src/graphics/program-lib/chunks/normalVertex.frag
  src/graphics/program-lib/chunks/reflDir.frag
  src/graphics/program-lib/chunks/reflDirAniso.frag
  src/graphics/program-lib/chunks/reflectionCC.frag
  src/graphics/program-lib/chunks/specular.frag
  src/graphics/program-lib/chunks/start.frag
  src/graphics/program-lib/programs/standard.js
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
Labels: area: graphics, enhancement

#2395 WebXR Input Sources: retrieve most relevant transforms of the parent
  src/xr/xr-input-source.js
  src/xr/xr-joint.js
Labels: area: xr, bug
