Repository playcanvas/engine, pull requests merged in 2020-03, with the labels that each got.

#1905 WebXR: Avoid using deprecated vec3.data internaly.
  src/scene/forward-renderer.js
  src/xr/xr-manager.js
Labels: enhancement

#1913 Integration with SpectorJS markers
  src/graphics/device.js
  src/scene/forward-renderer.js
  src/scene/particle-system/gpu-updater.js
Labels: enhancement

#1911 Particle system randomize sprite animations
  examples/assets/textures/particles-bonus.png
  examples/assets/textures/particles-coins.png
  examples/graphics/particles-animation-index.html
  examples/graphics/particles-sprite-randomization.html
  src/framework/components/particle-system/component.js
  src/framework/components/particle-system/data.js
  src/framework/components/particle-system/system.js
  src/graphics/program-lib/chunks/particleAnimFrameClamp.vert
  src/graphics/program-lib/chunks/particleAnimFrameLoop.vert
  src/graphics/program-lib/chunks/particleAnimTex.vert
  src/graphics/program-lib/chunks/particle_cpu.vert
  src/graphics/program-lib/particle.js
  src/scene/particle-system/cpu-updater.js
  src/scene/particle-system/particle-emitter.js
Labels: enhancement

#1908 Add support for ES6 script classes
  build/dependencies.txt
  src/framework/components/script/component.js
  src/script/script-attributes.js
  src/script/script-registry.js
  src/script/script-type.js
  src/script/script.js
Labels: enhancement

#1904 Engine GLB support
  build/dependencies.txt
  examples/assets/scripts/camera/orbit-camera.js
  package.json
  src/anim/anim.js
  src/asset/asset-registry.js
  src/framework/application.js
  src/framework/components/animation/component.js
  src/framework/components/animation/data.js
  src/framework/components/animation/system.js
  src/graphics/texture.js
  src/graphics/vertex-format.js
  src/net/http.js
  src/resources/animation.js
  src/resources/container.js
  src/resources/loader.js
  src/resources/model.js
  src/resources/parser/glb-model.js
  src/resources/parser/glb-parser.js
  tests/anim/test_anim.js
  tools/glb-viewer/index.html
  tools/glb-viewer/src/controls.js
  tools/glb-viewer/src/graph.js
  tools/glb-viewer/src/viewer.js
  tools/glb-viewer/style.css
Labels: enhancement

#1916 [FIX] Mouse wheel events on elements
  src/input/element-input.js
Labels: bug

#1918 Optimize Grab-Pass for WebGL 2 and fix when using anti-aliased RenderTarget
  src/graphics/device.js
Labels: bug

#1920 Add pc.drawTexture to render texture to target using a shader
  src/graphics/device.js
  src/graphics/simple-post-effect.js
Labels: enhancement

#1922 [FIX] Updating of particle systems local bounds
  src/scene/particle-system/particle-emitter.js
Labels: bug

#1924 [DOCS] Make anim API private
  src/anim/anim.js
Labels: docs

#1940 Only invoke app.start() after resources are loaded in the engine examples
  examples/animation/blend.html
  examples/camera/first-person.html
  examples/graphics/loader-obj.html
  examples/graphics/model-asset.html
  examples/graphics/particles-anim-index.html
  examples/graphics/particles-random-sprites.html
  examples/graphics/point-cloud.html
  examples/graphics/portal.html
  examples/graphics/shader-burn.html
  examples/graphics/shader-toon.html
  examples/graphics/shader-wobble.html
  examples/sound/positional.html
  examples/user-interface/text-canvas-font.html
Labels: enhancement

#1943 [DOCS] Improve pc.BoundingBox documentation
  src/shape/bounding-box.js
Labels: docs

#1945 [DOCS] Make pc.Application#loadScene public
  src/callbacks.js
  src/framework/application.js
Labels: docs

#1935 Allow AnimController to support any target
  src/anim/anim.js
  src/framework/components/animation/component.js
  src/framework/components/animation/system.js
  src/resources/parser/glb-parser.js
  tests/anim/test_anim.js
  tools/glb-viewer/src/viewer.js
Labels: enhancement

#1950 Add pc.ScriptComponent#get
  src/framework/components/script/component.js
  src/script/script.js
Labels: enhancement

#1938 Model outline example
  examples/assets/scripts/posteffects/posteffect-outline.js
  examples/examples.js
  examples/graphics/model-outline.html
Labels: enhancement

#1909 Anisotropic specular and reflection approximation using GGX distribution and bent normals
  examples/examples.js
  examples/graphics/material-anisotropic.html
  src/graphics/program-lib/chunks/TBNObjectSpace.frag
  src/graphics/program-lib/chunks/lightSpecularAnisoGGX.frag
  src/graphics/program-lib/chunks/reflDirAniso.frag
  src/graphics/program-lib/chunks/tangentBinormal.vert
  src/graphics/program-lib/standard.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
Labels: enhancement

#1956 Small fixes to viewer and engine example
  examples/user-interface/text-canvas-font.html
  tools/glb-viewer/src/controls.js
  tools/glb-viewer/src/viewer.js
Labels: bug
