Repository playcanvas/engine, pull requests merged in 2021-09, with the labels that each got.

#3436 When entity is reparented, whole child hierarchy is notified
  src/scene/graph-node.js
Labels: bug, area: graphics, release: next patch

#3441 Revert "Prevent shapes creation on disabled entities (#3432)"
  src/framework/components/collision/system.js
Labels: bug, area: physics

#3442 Examples browser deployment readme
  examples/README.md
  examples/package.json
Labels: docs

#3329 AnimComponent transition updates
  src/anim/controller/anim-controller.js
  src/framework/components/anim/component.js
  src/framework/components/anim/system.js
Labels: enhancement, area: animation

#3443 [Fix] Glb loader example - enable lights that are by default disabled
  examples/src/examples/loaders/glb.tsx
Labels: bug, area: graphics

#3447 Revert anim transition change
  src/anim/controller/anim-controller.js
Labels: bug, area: animation

#3454 [AnimComponent] Fix for transitions
  src/anim/controller/anim-controller.js
Labels: bug, area: animation

#3458 [Fix] Use correct UV transform for tiled normal map of clear coat
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#3463 Fix for cloned anim and render components
  src/framework/components/anim/component.js
  src/framework/components/render/component.js
  src/framework/entity.js
  src/resources/container.js
Labels: bug, area: graphics, area: animation

#3464 [Fix] Fix shadow not rendering in Editor in some cases
  src/scene/renderer/shadow-renderer.js
Labels: bug, area: graphics

#3444 Engine example Shadow Cascades has HUD controls
  examples/src/examples/graphics/shadow-cascades.tsx
Labels: enhancement, area: graphics, release: next minor

#3453 Update var to let and const in deprecated.js
  src/deprecated.js
Labels: enhancement

#3465 Added documentation example on accessing mesh instances of a render hierarchy
  src/resources/container.js
Labels: docs

#3466 [Fix] Disable skybox from picker
  src/scene/scene.js
Labels: bug, area: graphics

#3468 [Fix] Avoid crash in Animation blending under certain conditions
  src/framework/components/animation/system.js
Labels: bug, area: animation

#3455 Track active StandardMaterial parameters correctly
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#3471 [Fix] Fix to insert and remove events when reparenting
  src/framework/components/model/component.js
  src/framework/components/render/component.js
  src/scene/graph-node.js
Labels: bug

#3473 Converted more classes in scene folder to use let and const
  src/scene/batching/batch-manager.js
  src/scene/batching/batch.js
  src/scene/batching/skin-batch-instance.js
  src/scene/graph-node.js
  src/scene/layer.js
  src/scene/mesh.js
  src/scene/model.js
  src/scene/sprite.js
  src/scene/texture-atlas.js
Labels: enhancement, area: graphics

#3484 Fix shadow cascades, to respect chunks overrides.
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#3495 [Fix] Fixes to Application.Destroy to destroy in correct order
  src/framework/application.js
  src/graphics/graphics-device.js
  src/scene/particle-system/particle-emitter.js
Labels: bug, area: graphics

#3478 Use mouse scroll wheel events to navigate content in scroll-view UI component.
  examples/src/examples/user-interface/scroll-view.tsx
  src/framework/components/scroll-view/component.js
  src/framework/components/scroll-view/system.js
Labels: area: ui

#3496 [Fix] Fix to calculateTangent function was hiden by local variable when creating primitives
  src/scene/procedural.js
Labels: bug, area: graphics

#3497 Issue error when attempting to load a KTX2 file without transcoder support
  src/resources/basis-worker.js
Labels: enhancement, area: graphics

#3498 [Fix] Fixes texture memory leak when window is resized and posteffect uses depth buffer
  src/framework/scene-depth.js
Labels: bug, area: graphics

#3472 Forward renderer - cleanup, separated static-meshes functionality
  src/framework/application.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/static-meshes.js
Labels: area: graphics

#3510 Improvements to shadow-cascades engine example
  examples/assets/models/terrain.glb
  examples/assets/models/terrain.txt
  examples/src/examples/graphics/shadow-cascades.tsx
  src/framework/components/light/component.js
Labels: enhancement, area: graphics

#3513 [Fix] Fixes an issue with cloning a model component with customAabb
  examples/src/examples/graphics/model-asset.tsx
  src/framework/components/model/system.js
Labels: bug, area: graphics

#3516 Include scripts in npm package
  package.json
Labels: enhancement

#3235 Shadow atlas for clustered spot lights
  examples/src/examples/graphics/clustered-shadows.tsx
  examples/src/examples/graphics/lights.tsx
  src/framework/components/light/component.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/chunks/clusteredLightLoop.frag
  src/graphics/program-lib/chunks/float-unpacking.frag
  src/graphics/program-lib/programs/standard.js
  src/graphics/vertex-format.js
  src/math/float-packing.js
  src/math/math.js
  src/scene/area-light-luts.js
  src/scene/camera.js
  src/scene/light.js
  src/scene/lighting/light-texture-atlas.js
  src/scene/morph.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-map.js
  src/scene/renderer/shadow-renderer.js
  src/scene/world-clusters.js
Labels: feature request, area: graphics, release: next minor

#3521 Spot light cookies support by the Clustered lighting.
  examples/assets/textures/channels.png
  examples/src/examples/graphics/clustered-shadows.tsx
  src/framework/components/light/component.js
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/chunks/cookie.frag
  src/graphics/program-lib/programs/standard.js
  src/graphics/simple-post-effect.js
  src/math/float-packing.js
  src/scene/area-light-luts.js
  src/scene/light.js
  src/scene/lighting/light-texture-atlas.js
  src/scene/morph.js
  src/scene/renderer/cookie-renderer.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
  src/scene/world-clusters.js
Labels: enhancement, area: graphics, release: next minor

#2838 Lightmapper improvements - soft shadow & Ambient Occlusion support
  examples/assets/models/house.glb
  examples/assets/models/house.txt
  examples/src/examples/graphics/lights-baked-ao.tsx
  examples/src/examples/graphics/lights.tsx
  scripts/camera/orbit-camera.js
  src/framework/application.js
  src/framework/components/light/component.js
  src/graphics/program-lib/chunks/bilateralDeNoise.frag
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/dilate.frag
  src/graphics/program-lib/programs/standard.js
  src/index.js
  src/math/random.js
  src/scene/constants.js
  src/scene/light.js
  src/scene/lightmapper/bake-light-ambient.js
  src/scene/lightmapper/bake-light-simple.js
  src/scene/lightmapper/bake-light.js
  src/scene/lightmapper/bake-mesh-node.js
  src/scene/lightmapper/lightmap-cache.js
  src/scene/lightmapper/lightmap-filters.js
  src/scene/lightmapper/lightmapper.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/mesh-instance.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
Labels: enhancement, area: graphics, release: next minor

#3523 Better shader compilation error reporting
  src/graphics/graphics-device.js
Labels: enhancement, area: graphics
