Repository playcanvas/engine, pull requests merged in 2021-04, with the labels that each got.

#3057 [FIX] Fix previous refactor of platform API
  src/core/platform.js
Labels: bug

#3058 [FIX] Suppress warning from rollup-plugin-replace
  rollup.config.js
Labels: bug

#3066 [Fix] RenderAction is reset when being reused, fixes issue with non-existing lights exception
  src/scene/layer-composition.js
  src/scene/render-action.js
Labels: area: graphics, bug

#3059 Add support for a few more ktx pixel formats
  src/graphics/graphics-device.js
  src/resources/parser/texture/ktx.js
Labels: enhancement

#3064 Corrected BODYTYPE_KINEMATIC documentation
  src/framework/components/rigid-body/component.js
Labels: area: physics, docs

#3067 Also store max msaa samples on device
  src/graphics/graphics-device.js
Labels: enhancement

#3035 Template JS docs now public
  src/templates/template.js
Labels: bug, docs

#3069 Post-effects can be applied on camera with render target
  src/framework/components/camera/post-effect-queue.js
  src/graphics/post-effect.js
  src/scene/layer-composition.js
Labels: area: graphics, bug

#3080 Updated docs for pc.SpriteComponent.spriteAsset to allow for pc.Asset or Number
  src/framework/components/sprite/component.js
Labels: docs

#3074 fix material asset unload and reload
  src/resources/material.js
  src/resources/parser/material/json-standard-material.js
Labels: bug

#3083 cubemap resources set directly in material handler
  src/resources/material.js
Labels: bug

#3086 Consider webgl1 when getting max_samples.
  src/graphics/graphics-device.js
Labels: bug

#3094 Support glTF morph target animations which control multiple mesh instances
  src/anim/binder/default-anim-binder.js
Labels: area: animation, bug

#3097 Implementation of set.equals
  src/core/set-utils.js
Labels: enhancement

#3098 Implementation of floor / ceil / round / min / max functions for Vec2/3/4
  src/math/vec2.js
  src/math/vec3.js
  src/math/vec4.js
  tests/math/test_vec2.js
  tests/math/test_vec3.js
  tests/math/test_vec4.js
Labels: enhancement

#3102 [FIX] Reproject error
  src/graphics/program-lib/chunks/reproject.frag
Labels: area: graphics, bug

#3104 Moved .fill for type arrays to separate file
  src/index.js
  src/polyfill/array-fill.js
  src/polyfill/typedarray-fill.js
Labels: enhancement

#3105 WebXR ES6 changes
  src/xr/xr-depth-sensing.js
  src/xr/xr-hand.js
  src/xr/xr-hit-test-source.js
  src/xr/xr-hit-test.js
  src/xr/xr-image-tracking.js
  src/xr/xr-input-source.js
  src/xr/xr-input.js
  src/xr/xr-joint.js
  src/xr/xr-light-estimation.js
  src/xr/xr-manager.js
  src/xr/xr-tracked-image.js
Labels: enhancement

#3106 Add awesome-playcanvas list to README and Editor screenshot.
  README-zh.md
  README.md
Labels: enhancement

#3108 Simplify README.md
  README-zh.md
  README.md
Labels: enhancement

#2990 Clustered lights - Version 1 (No Specular, No shadows, No area lights)
  examples/examples.js
  examples/graphics/clustered-lighting.html
  src/framework/application.js
  src/framework/stats.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/chunks/clusteredLightLoop.frag
  src/graphics/program-lib/programs/standard.js
  src/index.js
  src/scene/forward-renderer.js
  src/scene/layer-composition.js
  src/scene/layer.js
  src/scene/light-composition-data.js
  src/scene/picker.js
  src/scene/render-action.js
  src/scene/scene.js
  src/scene/shadow-casters.js
  src/scene/world-clusters.js
Labels: area: graphics, feature request, performance

#3111 Improve WebGL context creation
  src/graphics/graphics-device.js
Labels: area: graphics, bug

#2995 Collision component support of Meshes specified using Render instead of Model
  examples/assets/models/torus.glb
  examples/physics/falling-shapes.html
  src/framework/components/collision/component.js
  src/framework/components/collision/data.js
  src/framework/components/collision/system.js
  src/framework/components/model/component.js
  src/framework/components/render/component.js
  src/resources/container.js
  src/resources/parser/glb-parser.js
  src/resources/render.js
Labels: area: graphics, area: physics, enhancement

#3116 Picker refactoring
  examples/graphics/area-picker.html
  src/framework/components/camera/component.js
  src/math/vec2.js
  src/math/vec3.js
  src/math/vec4.js
  src/scene/graph-node.js
  src/scene/layer-composition.js
  src/scene/layer.js
  src/scene/picker.js
Labels: area: graphics

#3123 Lightmapper prints warning for mesh without uv1
  src/scene/lightmapper.js
Labels: area: graphics, enhancement

#3122 [FIX] Restore properties to support profiler
  src/framework/application.js
  src/scene/forward-renderer.js
Labels: area: graphics, bug

#2947 WebXR Depth Sensing update to match latest Specs
  src/framework/components/camera/component.js
  src/xr/constants.js
  src/xr/xr-depth-sensing.js
  src/xr/xr-manager.js
Labels: area: xr, bug

#3125 Remove unused ComponentData class
  src/deprecated.js
  src/framework/components/component.js
  src/framework/components/data.js
  src/framework/components/rigid-body/data.js
  src/framework/components/system.js
  src/index.js
  tests/helpers/dummy/data.js
Labels: enhancement

#3126 Environment BRDF chunks
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/envBrdfApprox.frag
  src/graphics/program-lib/chunks/envBrdfNone.frag
  src/graphics/program-lib/chunks/reflectionCC.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCube.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCubeLod.frag
  src/graphics/program-lib/programs/standard.js
Labels: area: graphics, enhancement

#3050 Improve CJK character line breaking
  src/framework/components/element/text-element.js
Labels: area: ui, bug

#3131 Fix recent change in Oculus Browser regarding Hands
  src/xr/xr-hand.js
Labels: area: xr, bug

#3132 Depth rendering refactor
  src/framework/application.js
  src/framework/components/camera/component.js
  src/framework/components/camera/post-effect-queue.js
  src/framework/scene-depth.js
  src/graphics/render-target.js
  src/scene/procedural.js
Labels: area: graphics, bug, enhancement

#3134 Engine Examples updated to official RenderTarget constructor form
  examples/graphics/model-outline.html
  examples/graphics/painter.html
  examples/graphics/render-to-texture.html
  scripts/posteffects/posteffect-bloom.js
  scripts/utils/cubemap-renderer.js
Labels: area: graphics, enhancement

#3135 Engine uses up to date RenderTarget constructor
  src/framework/components/camera/post-effect-queue.js
  src/graphics/graphics-device.js
  src/graphics/paraboloid.js
  src/graphics/prefilter-cubemap.js
  src/graphics/reproject-texture.js
  src/scene/lightmapper.js
  src/scene/particle-system/particle-emitter.js
  src/scene/picker.js
Labels: area: graphics

#3137 RenderTarget constructor - deprecated warning
  src/graphics/render-target.js
Labels: area: graphics, enhancement

#3124 Remove gl canvas dependency resize
  src/framework/application.js
  src/graphics/graphics-device.js
Labels: area: graphics, feature request

#3138 Fix to obj format parser when there are no uvs
  scripts/parsers/obj-model.js
Labels: area: graphics, bug

#3139 [Fix] Fixing recently indtroduced bug into default-anim-binder
  src/anim/binder/default-anim-binder.js
Labels: area: animation, bug
