Repository playcanvas/engine, pull requests merged in 2021-02, with the labels that each got.

#2814 Update vr-movement.html
  examples/xr/vr-movement.html
Labels: bug

#2827 Improved point cloud simulation example to use built in camera position uniform
  examples/graphics/point-cloud-simulation.html
Labels: area: graphics, enhancement

#2828 [Fix] removed old in Editor wireframe behaviour
  src/framework/components/render/component.js
Labels: area: graphics

#2772 [Animation] Binding updates and bug fixes
  src/anim/binder/anim-binder.js
  src/anim/binder/default-anim-binder.js
  src/anim/controller/anim-controller.js
  src/anim/controller/anim-state.js
  src/anim/evaluator/anim-evaluator.js
  src/anim/evaluator/anim-target.js
  src/framework/components/anim/component-binder.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/model/component.js
  src/resources/parser/glb-parser.js
  src/scene/graph-node.js
  tests/anim/test_anim.js
Labels: area: animation, bug, enhancement

#2806 Add endVS chunk allowing vertex shader extensions to use lighting and normals
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/end.vert
  src/graphics/program-lib/programs/standard.js
Labels: area: graphics, enhancement

#2831 Improvements to RenderComponent API
  examples/graphics/mesh-decals.html
  examples/graphics/mesh-generation.html
  examples/graphics/mesh-morph-many.html
  examples/graphics/mesh-morph.html
  examples/graphics/point-cloud-simulation.html
  examples/graphics/render-to-cubemap.html
  examples/graphics/transform-feedback.html
  scripts/parsers/obj-model.js
  scripts/physics/render-physics.js
  src/framework/application.js
  src/framework/components/element/image-element.js
  src/framework/components/element/text-element.js
  src/framework/components/model/component.js
  src/framework/components/render/component.js
  src/framework/components/render/system.js
  src/framework/components/sprite/component.js
  src/graphics/transform-feedback.js
  src/resources/container.js
  src/resources/parser/glb-parser.js
  src/resources/parser/json-model.js
  src/scene/batching/batch-manager.js
  src/scene/forward-renderer.js
  src/scene/immediate.js
  src/scene/mesh-instance.js
  src/scene/model.js
  src/scene/particle-system/particle-emitter.js
  src/scene/scene.js
Labels: area: graphics, enhancement

#2829 Added note about drawOrder only working if layer is set to manual sorting
  src/framework/components/sprite/component.js
Labels: docs

#2830 Added examples to the HTTP API docs
  src/net/http.js
Labels: docs

#2779 Lightmapper refactor and cleanup
  examples/graphics/lights-baked-ao.html
  src/graphics/render-target.js
  src/scene/forward-renderer.js
  src/scene/lightmapper.js
  src/scene/mesh-instance.js
Labels: area: graphics, enhancement

#2836 Handling non-uniform scaling when batching
  src/math/mat3.js
  src/scene/batching/batch-manager.js
Labels: area: graphics, enhancement

#2837 Renamed Mat3.transform to Mat3.transformVector
  src/math/mat3.js
  src/scene/batching/batch-manager.js
Labels: area: graphics

#2840 Animation curve path fix
  src/resources/parser/glb-parser.js
Labels: area: animation, bug

#2843 Anim binder debug fix
  src/anim/binder/default-anim-binder.js
Labels: area: animation, bug

#2846 Fixed URL to examples source
  examples/index.html
Labels: docs

#2851 Stop playback of sounds on load if stop was called before load finished
  src/sound/instance.js
Labels: area: sound, bug

#2864 Added extra param docs for scriptType swap
  src/script/script-type.js
Labels: bug, docs

#2874 [FIX] Mipmapping non-power-of-two texture on WebGL 2
  src/graphics/graphics-device.js
Labels: area: graphics, bug

#2877 Rename area light project setting
  src/framework/application.js
Labels: area: graphics, feature request

#2880 Migrate WebXR Hands to new Specs
  src/xr/xr-hand.js
  src/xr/xr-joint.js
Labels: area: xr, enhancement

#2878 [FIX] Several fixes reported by checkJs
  package.json
  src/anim/controller/anim-blend-tree.js
  src/anim/controller/anim-controller.js
  src/anim/controller/anim-node.js
  src/anim/evaluator/anim-evaluator.js
  src/core/string.js
  src/graphics/graphics-device.js
  src/graphics/prefilter-cubemap.js
  src/graphics/texture.js
  src/math/curve-set.js
  src/math/mat3.js
  src/resources/parser/glb-parser.js
  src/resources/template.js
  src/scene/camera.js
  src/scene/scene.js
  src/scene/skin-partition.js
  src/shape/bounding-sphere.js
  src/xr/xr-input-source.js
Labels: bug

#2879 Add/use init methods for ScriptType and EventHandler
  src/core/event-handler.js
  src/script/script-type.js
  src/script/script.js
Labels: bug

#2884 [FIX] Fix I18n#destroy
  src/i18n/i18n.js
Labels: bug

#2887 [FIX] Fix all checkJs errors in uri.js
  src/core/uri.js
Labels: bug

#2860 Keyboard - remove presses when window is blurred or becomes hidden
  src/input/keyboard.js
Labels: area: input, bug

#2885 Asset unload event moved to public API
  src/asset/asset.js
Labels: enhancement

#2845 Refactor of debug rendering private API
  src/framework/application.js
  src/scene/immediate.js
Labels: area: graphics, enhancement

#2844 Fix extra shader variants appearing from materials that switch shading models
  src/scene/materials/standard-material.js
Labels: area: graphics, bug

#2888 [Fix] Removed duplicate destructor in the scene
  src/scene/scene.js
Labels: area: graphics, bug

#2882 Refactor of post-effects to integrate better with RenderActions and LayerComposition
  examples/graphics/post-effects.html
  scripts/posteffects/posteffect-bloom.js
  src/framework/application.js
  src/framework/components/camera/component.js
  src/framework/components/camera/post-effect-pass.js
  src/framework/components/camera/post-effect-queue.js
  src/framework/components/camera/system.js
  src/graphics/render-target.js
  src/index.js
  src/scene/forward-renderer.js
  src/scene/layer-composition.js
  src/scene/layer.js
  src/scene/render-action.js
Labels: area: graphics, bug

#2894 [Fix] Changing affectDynamic updates lighting
  src/framework/components/light/component.js
  src/scene/light.js
Labels: area: graphics, bug

#2849 Support for octahedral projection when projecting textures
  examples/graphics/render-to-cubemap.html
  src/graphics/constants.js
  src/graphics/program-lib/chunks/reproject.frag
  src/graphics/reproject-texture.js
  src/graphics/texture.js
Labels: area: graphics

#2895 [FIX] Fix various function declarations
  src/scene/particle-system/gpu-updater.js
  src/scene/particle-system/particle-emitter.js
  src/script/script-registry.js
  src/xr/xr-hand.js
  src/xr/xr-input-source.js
  src/xr/xr-tracked-image.js
Labels: area: xr, bug

#2886 AnimComponent fixes
  src/anim/binder/default-anim-binder.js
  src/anim/controller/anim-blend-tree-1d.js
  src/anim/controller/anim-blend-tree-2d-cartesian.js
  src/anim/controller/anim-blend-tree-2d-directional.js
  src/anim/controller/anim-blend-tree-direct.js
  src/anim/controller/anim-blend-tree.js
  src/anim/controller/anim-controller.js
  src/anim/controller/anim-node.js
  src/anim/controller/anim-state.js
  src/anim/controller/constants.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/math/math.js
  src/math/vec2.js
Labels: area: animation, bug

#2893 Assets fix
  src/asset/asset.js
Labels: bug

#2737 Attempt to fix canvas font emoji alignment
  src/font/canvas-font.js
Labels: area: ui, bug

#2899 [Fix] Updated handling of ovrride clear settings on the layer
  src/scene/forward-renderer.js
  src/scene/layer-composition.js
  src/scene/layer.js
  src/scene/picker.js
Labels: area: graphics, bug

#2901 Enable type-checking in VS Code
  jsconfig.json
Labels: enhancement

#2902 loadFromUrl fix
  src/asset/asset-registry.js
Labels: bug

#2903 [Fix] when no projection is set for 2d texture, equirect is assumed
  src/graphics/texture.js
Labels: area: graphics, bug

#2908 Remove index.d.ts file
  index.d.ts
  package.json
Labels: enhancement

#2913 Prevent the use of cubemap rotation on non-skybox cubemaps
  src/scene/materials/standard-material-options-builder.js
Labels: area: graphics, bug

#2915 Docs fix: Fixed type on pc.Collision.asset as it can be a number or pc.Asset
  src/framework/components/collision/component.js
Labels: docs
