Repository playcanvas/engine, pull requests merged in 2021-12, with the labels that each got.

#3764 [Fix] Fixed standard shader generation when GGX is enabled but there are no lights
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#3761 Always fire element set:color and set:opacity event when color and opacity is set
  src/framework/components/element/image-element.js
Labels: bug, area: ui

#3767 Assign animations events when animation asset is loaded
  src/framework/components/anim/component.js
Labels: bug, area: animation

#3766 Make text-element color and opacity setter consistent with image-element.
  src/framework/components/element/text-element.js
Labels: area: ui

#3753 Revamp User Interface examples.
  examples/assets/textures/checkboard.png
  examples/assets/textures/playcanvas.png
  examples/src/examples/user-interface/button-basic.tsx
  examples/src/examples/user-interface/button-sprite.tsx
  examples/src/examples/user-interface/custom-shader.tsx
  examples/src/examples/user-interface/layout-group.tsx
  examples/src/examples/user-interface/particle-system.tsx
  examples/src/examples/user-interface/scroll-view.tsx
  examples/src/examples/user-interface/text-auto-font-size.tsx
  examples/src/examples/user-interface/text-basic.tsx
  examples/src/examples/user-interface/text-canvas-font.tsx
  examples/src/examples/user-interface/text-drop-shadow.tsx
  examples/src/examples/user-interface/text-emojis.tsx
  examples/src/examples/user-interface/text-localization.tsx
  examples/src/examples/user-interface/text-markup.tsx
  examples/src/examples/user-interface/text-outline.tsx
  examples/src/examples/user-interface/text-typewriter.tsx
  examples/src/examples/user-interface/text-wrap.tsx
  examples/src/examples/user-interface/text.tsx
  examples/src/examples/user-interface/world-screen.tsx
Labels: area: examples

#3757 Small refactor to ForwardRenderer.updateShaders
  src/scene/renderer/forward-renderer.js
Labels: enhancement, area: graphics

#3770 [AnimComponent] First frame bug fix
  src/anim/controller/anim-controller.js
Labels: bug, area: animation

#3754 Internal Debug logging functionality
  rollup.config.js
  src/core/debug.js
  src/deprecated/deprecated-log.js
  src/deprecated/deprecated.js
  src/framework/components/rigid-body/system.js
  src/framework/components/script-legacy/component.js
  src/framework/components/script-legacy/system.js
  src/graphics/prefilter-cubemap.js
  src/graphics/render-target.js
  src/graphics/reproject-texture.js
  src/graphics/texture.js
  src/scene/morph-target.js
  src/scene/picker.js
  src/scene/procedural.js
  src/shape/bounding-box.js
  src/shape/bounding-sphere.js
  src/shape/oriented-box.js
  src/shape/ray.js
Labels: enhancement

#3771 Create examples for the proper use of world-space screens and world to screen coordinates.
  examples/src/examples/user-interface/custom-shader.tsx
  examples/src/examples/user-interface/world-to-screen.tsx
  examples/src/examples/user-interface/world-ui.tsx
Labels: area: ui

#3774 [AnimComponent] Update the assignAnimation function signature and documentation with blend tree support
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
Labels: docs, area: animation

#3775 Debug logging - additional functionality
  rollup.config.js
  src/core/debug.js
  src/framework/application.js
  src/graphics/grab-pass.js
  src/graphics/texture.js
  src/graphics/transform-feedback.js
  src/scene/mesh.js
Labels: enhancement

#3779 [Fix] Fix to the way createMesh handles blend indices
  src/scene/procedural.js
Labels: bug, area: graphics

#3777 Engine is using Debug class to log warnings / errors to avoid #ifdef _DEBUG
  rollup.config.js
  src/anim/binder/default-anim-binder.js
  src/anim/controller/anim-controller.js
  src/animation/skeleton.js
  src/asset/asset-registry.js
  src/core/debug.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/animation/component.js
  src/framework/components/collision/system.js
  src/framework/components/element/component.js
  src/framework/components/element/image-element.js
  src/framework/components/element/text-element.js
  src/framework/components/joint/component.js
  src/framework/components/model/component.js
  src/framework/components/rigid-body/component.js
  src/framework/components/rigid-body/system.js
  src/framework/components/screen/component.js
  src/framework/components/sound/component.js
  src/framework/components/sound/slot.js
  src/framework/components/sound/system.js
  src/framework/components/sprite/component.js
  src/framework/entity.js
  src/framework/scene-registry.js
  src/graphics/graphics-device.js
  src/graphics/index-buffer.js
  src/graphics/program-library.js
  src/graphics/render-target.js
  src/graphics/texture.js
  src/graphics/vertex-buffer.js
  src/graphics/vertex-format.js
  src/graphics/vertex-iterator.js
  src/resources/basis.js
  src/resources/model.js
  src/resources/parser/glb-parser.js
  src/resources/parser/json-model.js
  src/resources/parser/texture/dds.js
  src/resources/parser/texture/hdr.js
  src/resources/parser/texture/ktx.js
  src/resources/parser/texture/ktx2.js
  src/scene/area-light-luts.js
  src/scene/batching/batch-manager.js
  src/scene/composition/layer-composition.js
  src/scene/layer.js
  src/scene/lightmapper/lightmapper.js
  src/scene/materials/standard-material-validator.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/forward-renderer.js
  src/scene/skin-instance.js
  src/script/script-attributes.js
  src/script/script-type.js
  src/script/script.js
Labels: enhancement

#3778 [AnimComponent] fix a bug with the assignAnimation function
  src/framework/components/anim/component.js
Labels: bug, area: animation

#3783 Refactor environment lighting
  src/deprecated/deprecated.js
  src/graphics/env-lighting.js
  src/graphics/graphics-device.js
  src/graphics/paraboloid.js
  src/graphics/prefilter-cubemap.js
  src/graphics/prefilter.js
  src/graphics/program-lib/chunks/ambientEnv.frag
  src/graphics/program-lib/chunks/ambientPrefilteredCube.frag
  src/graphics/program-lib/chunks/ambientPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/cubeMapProjectBox.frag
  src/graphics/program-lib/chunks/decode.frag
  src/graphics/program-lib/chunks/dpAtlasQuad.frag
  src/graphics/program-lib/chunks/genParaboloid.frag
  src/graphics/program-lib/chunks/prefilterCubemap.frag
  src/graphics/program-lib/chunks/reflectionCube.frag
  src/graphics/program-lib/chunks/reflectionDpAtlas.frag
  src/graphics/program-lib/chunks/reflectionEnv.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCube.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/reflectionSphere.frag
  src/graphics/program-lib/chunks/reflectionSphereLow.frag
  src/graphics/program-lib/chunks/reproject.frag
  src/graphics/program-lib/chunks/rgbm.frag
  src/graphics/program-lib/chunks/skyboxEnv.frag
  src/graphics/program-lib/programs/skybox.js
  src/graphics/program-lib/programs/standard.js
  src/graphics/program-library.js
  src/graphics/reproject-texture.js
  src/graphics/texture.js
  src/index.js
  src/math/random.js
  src/resources/cubemap.js
  src/resources/material.js
  src/resources/parser/material/json-standard-material.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/scene.js
Labels: enhancement, area: graphics

#3785 fix chunk naming
  src/graphics/program-lib/programs/skybox.js
Labels: bug, area: graphics

#3789 EnvAtlas lighting fix
  src/graphics/program-lib/chunks/decode.frag
  src/graphics/program-lib/chunks/reproject.frag
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#3763 Implementation of the final API for clustered lighting, shadowType support
  examples/src/examples/graphics/clustered-area-lights.tsx
  examples/src/examples/graphics/clustered-lighting.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/clustered-spot-shadows.tsx
  examples/src/examples/graphics/shadow-cascades.tsx
  src/framework/application.js
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/chunks/clusteredLightShadows.frag
  src/graphics/program-lib/programs/standard.js
  src/index.js
  src/scene/composition/layer-composition.js
  src/scene/constants.js
  src/scene/lighting/light-texture-atlas.js
  src/scene/lighting/lighting-params.js
  src/scene/lighting/lights-buffer.js
  src/scene/lighting/world-clusters.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
  src/scene/scene.js
Labels: enhancement, area: graphics

#3793 Clustered lighting uses single light texture on devices with small number of texture units
  src/scene/lighting/lights-buffer.js
Labels: enhancement, area: graphics

#3794 Clustered lighting uses textureLod to sample data textures to improve dynamic branching
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/chunks/gles3.frag
  src/graphics/program-lib/programs/standard.js
Labels: enhancement, performance, area: graphics

#3795 Anim controller update method fix
  src/anim/controller/anim-controller.js
Labels: bug, area: animation

#3797 Properly deprecated MeshInstance.syncAabb
  src/deprecated/deprecated.js
  src/scene/mesh-instance.js
Labels: docs

#3796 Updated cluster spot light example to add controls to add/remove light
  examples/src/examples/graphics/clustered-spot-shadows.tsx
Labels: area: examples

#3798 Search correctly when resolving nodes in default anim binder
  src/anim/binder/default-anim-binder.js
Labels: bug

#3799 Fix search by path when binding anims
  src/anim/binder/default-anim-binder.js
Labels: bug, area: animation

#3801 Refactored gpu markers using Debug module
  rollup.config.js
  src/core/debug.js
  src/framework/components/camera/post-effect-queue.js
  src/graphics/env-lighting.js
  src/graphics/grab-pass.js
  src/graphics/reproject-texture.js
  src/graphics/simple-post-effect.js
  src/graphics/transform-feedback.js
  src/scene/lightmapper/lightmapper.js
  src/scene/morph-instance.js
  src/scene/particle-system/gpu-updater.js
  src/scene/renderer/cookie-renderer.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: area: graphics

#3803 Load vox without palette correctly
  scripts/parsers/vox-parser.mjs
Labels: bug

#3806 Fix aligned array buffer access on vox models
  scripts/parsers/vox-parser.mjs
Labels: bug

#3812 Fix embedded ktx2 loading
  src/resources/parser/glb-parser.js
Labels: bug, area: graphics

#3791 Improved DefaultMaterial to avoid circular dependency
  src/framework/application.js
  src/scene/materials/default-material.js
Labels: enhancement

#3810 Improve environment reflection filtering quality
  src/graphics/env-lighting.js
  src/graphics/program-lib/chunks/ambientEnv.frag
  src/graphics/program-lib/chunks/decode.frag
  src/graphics/program-lib/chunks/reflectionEnv.frag
  src/graphics/program-lib/programs/standard.js
  src/resources/cubemap.js
Labels: enhancement, area: graphics

#3816 RenderCubemap example switched from model to render component
  examples/src/examples/graphics/render-cubemap.tsx
Labels: area: graphics, area: examples

#3818 Camera onPreRender and onPostRender callbacks
  src/framework/components/camera/component.js
  src/framework/components/camera/post-effect-queue.js
  src/scene/composition/layer-composition.js
  src/scene/composition/render-action.js
  src/scene/renderer/forward-renderer.js
Labels: enhancement, area: graphics

#3819 Added "Once" update option to probe in the Box Reflection example
  examples/src/examples/graphics/box-reflection.tsx
Labels: area: examples

#3822 Fix material emissive logic
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#3821 Added same sprite check in Button component to break circular dependency
  src/framework/components/button/component.js
Labels: bug, area: ui

#3817 Fixed circular call for image element 'set:color' and 'set:opac…
  src/framework/components/button/component.js
Labels: bug, area: ui

#3823 Fix clearcoat normals shader gen
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics, area: gltf

#3825 Examples - ignore ts warnings in few examples
  examples/src/examples/graphics/box-reflection.tsx
  examples/src/examples/graphics/clustered-area-lights.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/clustered-spot-shadows.tsx
Labels: area: examples

#3826 Migrate more JSDoc to ES6 format
  src/asset/asset-registry.js
  src/asset/asset.js
  src/bundles/bundle.js
  src/font/canvas-font.js
  src/framework/components/rigid-body/system.js
  src/framework/components/screen/component.js
  src/framework/components/sprite/component.js
  src/framework/entity.js
  src/framework/scene-registry.js
  src/framework/utils/entity-reference.js
  src/resources/basis.js
  src/resources/container.js
  src/resources/css.js
  src/resources/model.js
  src/resources/parser/material/json-standard-material.js
  src/scene/batching/batch-manager.js
  src/scene/camera.js
  src/scene/layer.js
  src/scene/light.js
  src/scene/materials/standard-material.js
  src/scene/morph-instance.js
  src/scene/morph.js
  src/script/script-attributes.js
  src/script/script-registry.js
  src/templates/template.js
  src/xr/xr-light-estimation.js
Labels: docs

#3828 Migrate namespaces to ES6 JSDoc comments
  src/asset/asset-registry.js
  src/core/core.js
  src/core/event-handler.js
  src/core/guid.js
  src/core/indexed-list.js
  src/core/path.js
  src/core/platform.js
  src/core/string.js
  src/framework/entity.js
  src/framework/script.js
  src/math/math.js
  src/math/random.js
  src/xr/constants.js
Labels: bug, docs

#3829 Tweak env shiny reflection filtering
  src/graphics/program-lib/chunks/reflectionEnv.frag
Labels: enhancement, area: graphics

#3807 Fix spelling of AnimComponent#layerIndices
  src/framework/components/anim/component.js
Labels: bug, area: animation

#3830 Improvements to internal implementation of debug line / mesh rendering
  examples/src/examples/graphics/render-cubemap.tsx
  src/deprecated/deprecated.js
  src/framework/application.js
  src/scene/composition/layer-composition.js
  src/scene/immediate/immediate-batch.js
  src/scene/immediate/immediate-batches.js
  src/scene/immediate/immediate.js
  src/scene/materials/material.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
Labels: enhancement, area: graphics

#3832 Migrate most remaining functions to ES6 JSDoc
  src/anim/binder/anim-binder.js
  src/anim/evaluator/anim-evaluator.js
  src/bundles/bundle-registry.js
  src/core/events.js
  src/core/time.js
  src/framework/application.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/particle-system/component.js
  src/framework/components/rigid-body/component.js
  src/graphics/program-lib/programs/standard.js
  src/i18n/i18n.js
  src/resources/audio.js
  src/resources/loader.js
  src/scene/composition/layer-composition.js
  src/script/script.js
  src/sound/manager.js
  src/vr/vr-manager.js
Labels: docs

#3833 Remove and repair some eslint directives
  src/framework/components/script/component.js
  src/resources/handler.js
  src/resources/texture.js
  src/script/script-attributes.js
  src/script/script-registry.js
  src/script/script.js
  src/xr/xr-depth-sensing.js
Labels: docs

#3834 Remove unused component JSDoc tags
  src/framework/components/anim/component.js
  src/framework/components/animation/component.js
  src/framework/components/audio-listener/component.js
  src/framework/components/audio-source/component.js
  src/framework/components/button/component.js
  src/framework/components/camera/component.js
  src/framework/components/collision/component.js
  src/framework/components/element/component.js
  src/framework/components/joint/component.js
  src/framework/components/layout-child/component.js
  src/framework/components/layout-group/component.js
  src/framework/components/light/component.js
  src/framework/components/model/component.js
  src/framework/components/particle-system/component.js
  src/framework/components/render/component.js
  src/framework/components/rigid-body/component.js
  src/framework/components/screen/component.js
  src/framework/components/script/component.js
  src/framework/components/scroll-view/component.js
  src/framework/components/scrollbar/component.js
  src/framework/components/sound/component.js
  src/framework/components/sprite/component.js
  src/framework/components/zone/component.js
Labels: enhancement, docs

#3836 Make components on Entity class visible to TS Compiler
  src/framework/components/system.js
  src/framework/entity.js
Labels: enhancement

#3835 Convert element properties to ES6 getters/setters
  src/framework/components/element/component.js
Labels: enhancement, area: ui

#3839 [Examples Browser] playcanvas-observer 1.3.0
  examples/package-lock.json
  examples/package.json
  examples/src/app/example-iframe.tsx
  examples/src/app/example.tsx
Labels: docs

#3840 Reflection env fix
  src/graphics/program-lib/chunks/reflectionEnv.frag
Labels: bug, area: graphics

#3841 Fix prefiltering bug
  src/graphics/program-lib/chunks/reproject.frag
  src/graphics/reproject-texture.js
Labels: bug, area: graphics

#3842 Followup change
  src/graphics/env-lighting.js
Labels: bug, area: graphics

#3843 Document math contructor default values
  src/framework/entity.js
  src/math/color.js
  src/math/curve-set.js
  src/math/curve.js
  src/math/quat.js
  src/math/vec2.js
  src/math/vec3.js
  src/math/vec4.js
Labels: bug, docs

#3846 Improve CameraComponent#screenToWorld docs
  src/framework/components/camera/component.js
Labels: enhancement, docs, area: graphics

#3845 Further improve TS declarations
  src/framework/application.js
  src/input/keyboard-event.js
  src/input/mouse-event.js
  src/input/touch-event.js
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  src/scene/mesh.js
  src/scene/morph-target.js
  src/shape/bounding-box.js
  src/shape/bounding-sphere.js
  src/shape/oriented-box.js
  src/shape/ray.js
Labels: enhancement, docs

#3848 Remove Model from ParticleSystemComponent
  src/framework/components/particle-system/component.js
  src/framework/components/particle-system/data.js
  src/framework/components/particle-system/system.js
Labels: enhancement, area: graphics

#3847 Correctly encode form postdata
  src/net/http.js
Labels: bug

#3851 Fix spelling of mantissa
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/chunks/float-unpacking.frag
  src/math/float-packing.js
  src/scene/lighting/lights-buffer.js
Labels: bug

#3852 Fix problematic use of indexOf
  src/framework/components/anim/component-binder.js
Labels: bug, area: animation

#3853 Refactor anim controller conditions code
  src/anim/controller/anim-controller.js
Labels: bug, area: animation
