Repository playcanvas/engine, pull requests merged in 2021-08, with the labels that each got.

#3380 Support ktx2 supercompressed textures
  examples/src/lib/basis/basis.js
  examples/src/lib/basis/basis.wasm.js
  examples/src/lib/basis/basis.wasm.wasm
  src/resources/basis-worker.js
  src/resources/basis.js
  src/resources/parser/glb-parser.js
  src/resources/parser/texture/basis.js
  src/resources/parser/texture/dds.js
  src/resources/parser/texture/ktx2.js
  src/resources/parser/texture/legacy-dds.js
  src/resources/texture.js
Labels: enhancement, area: graphics

#3381 Support browserless environment
  src/asset/asset-file.js
  src/asset/asset-registry.js
  src/asset/asset-variants.js
  src/asset/asset.js
  src/core/platform.js
  src/core/read-stream.js
  src/framework/application.js
  src/graphics/graphics-device.js
  src/graphics/prefilter-cubemap.js
  src/polyfill/OESVertexArrayObject.js
  src/resources/basis.js
  src/resources/container.js
  src/resources/loader.js
  src/resources/parser/glb-parser.js
  src/resources/parser/texture/basis.js
  src/resources/parser/texture/dds.js
  src/resources/parser/texture/hdr.js
  src/resources/parser/texture/img.js
  src/resources/parser/texture/ktx.js
  src/resources/parser/texture/ktx2.js
  src/resources/texture.js
  src/resources/untar.js
  src/scene/materials/standard-material.js
  src/xr/xr-depth-sensing.js
  src/xr/xr-dom-overlay.js
  src/xr/xr-hand.js
  src/xr/xr-hit-test.js
  src/xr/xr-image-tracking.js
  src/xr/xr-joint.js
  src/xr/xr-manager.js
  src/xr/xr-plane-detection.js
Labels: enhancement, area: graphics

#3382 Added retry behaviour to template asset handler
  src/resources/template.js
Labels: bug, area: assets

#3383 [FIX] Support for glTF extension KHR_mesh_quantization
  src/resources/parser/glb-parser.js
Labels: bug, area: graphics

#3384 Mesh particle texture fix
  src/scene/particle-system/particle-emitter.js
Labels: bug, area: graphics

#3386 Update JSDoc on procedural.js
  src/scene/procedural.js
Labels: docs, area: graphics

#3387 Added center and radius properties JS Docs/TSD for bounding box and sphere
  src/shape/bounding-box.js
  src/shape/bounding-sphere.js
Labels: docs

#3354 Support for cameras stored in the GLB file
  examples/assets/models/geometry-camera-light.glb
  examples/src/examples/loaders/glb.tsx
  src/resources/container.js
  src/resources/parser/glb-parser.js
Labels: area: graphics

#3362 Draco library updated to 1.4.1
  examples/assets/models/heart_draco.glb
  examples/src/examples/loaders/draco-glb.tsx
  examples/src/lib/draco/draco.js
  examples/src/lib/draco/draco.wasm.js
  examples/src/lib/draco/draco.wasm.wasm
Labels: area: graphics

#3390 Uniquify gltf texture asset names
  src/resources/parser/glb-parser.js
Labels: bug, area: graphics

#3349 Fixes for examples
  examples/src/examples/animation/events.tsx
  examples/src/examples/graphics/lights.tsx
  examples/src/examples/user-interface/various.tsx
  src/anim/controller/anim-blend-tree-2d-cartesian.js
Labels: bug, docs

#3391 StandardMaterial code cleanup
  src/resources/parser/material/json-standard-material.js
  src/scene/materials/basic-material.js
  src/scene/materials/material.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: enhancement, area: graphics

#3394 Support KHR_texture_transform
  src/graphics/program-lib/programs/standard.js
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
Labels: enhancement, area: graphics

#3395 Use the same prefiltered lighting data for options parsing as before
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#3397 Add map rotations to params list
  src/scene/materials/standard-material-parameters.js
Labels: bug, area: graphics

#3408 Fix enabled flag on camea and light component
  src/framework/components/camera/system.js
  src/resources/parser/glb-parser.js
Labels: bug, area: graphics

#3417 Invoke equals on internal property
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#3418 Fix retry attempts in scene loading
  src/resources/hierarchy.js
  src/resources/scene-settings.js
  src/resources/scene-utils.js
  src/resources/scene.js
Labels: bug, area: assets

#3420 [FIX] Force precision of depth texture to highp
  src/graphics/program-lib/chunks/screenDepth.frag
Labels: bug, area: graphics

#3424 Fix lighting basis during RTT
  src/graphics/program-lib/chunks/TBNderivative.frag
  src/scene/renderer/forward-renderer.js
Labels: bug, area: graphics

#3423 Migrate from babel-eslint to @babel/eslint-parser
  package-lock.json
  package.json
Labels: enhancement

#3425 Remove Babel class properties plugin
  package.json
  rollup.config.js
Labels: enhancement

#3432 Prevent collision data processing on disabled entities
  src/framework/components/collision/system.js
Labels: area: physics, release: next patch

#3439 [Fix] model->render in example comment
  src/resources/container.js
Labels: bug, docs, release: next patch
