Repository playcanvas/engine, pull requests merged in 2021-10, with the labels that each got.

#3482 Trigger events on world UI elements in the correct order.
  src/input/element-input.js
Labels: area: ui

#3537 Omni shadows for clustered lights
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/chunks/cookie.frag
  src/graphics/program-lib/chunks/shadowStandard.frag
  src/graphics/program-lib/programs/standard.js
  src/scene/constants.js
  src/scene/light.js
  src/scene/lighting/light-texture-atlas.js
  src/scene/renderer/cookie-renderer.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
  src/scene/world-clusters.js
Labels: enhancement, area: graphics

#3019 Refactoring, fixes and improvements of the line rendering
  examples/src/examples/graphics/lines.tsx
  examples/src/examples/graphics/post-effects.tsx
  examples/src/examples/graphics/render-cubemap.tsx
  examples/src/examples/loaders/glb.tsx
  src/deprecated.js
  src/framework/application.js
  src/framework/components/camera/system.js
  src/scene/immediate.js
  src/scene/immediate/immediate-batch.js
  src/scene/immediate/immediate-batches.js
  src/scene/immediate/immediate.js
Labels: enhancement, area: graphics, release: next minor

#3508 Removed PlayCanvas version logging
  src/framework/application.js
Labels: enhancement, release: next minor

#3517 More var to let and const
  src/framework/application.js
  src/framework/components/anim/component-binder.js
  src/framework/components/anim/system.js
  src/framework/components/animation/component.js
  src/framework/components/animation/system.js
  src/framework/components/audio-listener/component.js
  src/framework/components/audio-listener/system.js
  src/framework/components/audio-source/component.js
  src/framework/components/audio-source/system.js
  src/framework/components/button/component.js
  src/framework/components/button/system.js
  src/framework/components/camera/system.js
  src/framework/components/component.js
  src/framework/components/joint/system.js
  src/framework/components/layout-child/component.js
  src/framework/components/layout-child/system.js
  src/framework/components/layout-group/component.js
  src/framework/components/layout-group/system.js
  src/framework/components/registry.js
  src/framework/components/render/system.js
  src/framework/components/rigid-body/system.js
  src/framework/components/screen/component.js
  src/framework/components/screen/system.js
  src/framework/components/scroll-view/system.js
  src/framework/components/scrollbar/component.js
  src/framework/components/sprite/sprite-animation-clip.js
  src/framework/components/sprite/system.js
  src/framework/components/system.js
  src/framework/components/zone/component.js
  src/framework/components/zone/system.js
  src/framework/entity.js
  src/framework/scene-depth.js
  src/framework/scene-registry.js
  src/framework/script.js
  src/framework/utils/entity-reference.js
  src/scene/procedural.js
Labels: enhancement

#3545 [Fix] Lightmap size estimation is improved for render component
  src/scene/lightmapper/lightmapper.js
Labels: bug, area: graphics
