Repository playcanvas/engine, pull requests merged in 2021-06, with the labels that each got.

#3208 Revert recent material chunk changes
  examples/graphics/material-anisotropic.html
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/combineClearCoat.frag
  src/graphics/program-lib/chunks/combineDiffuseSpecular.frag
  src/graphics/program-lib/chunks/combineDiffuseSpecularNoConserve.frag
  src/graphics/program-lib/chunks/combineDiffuseSpecularNoRefl.frag
  src/graphics/program-lib/chunks/combineDiffuseSpecularNoReflSeparateAmbient.frag
  src/graphics/program-lib/chunks/combineDiffuseSpecularOld.frag
  src/graphics/program-lib/chunks/envBrdfApprox.frag
  src/graphics/program-lib/chunks/envBrdfNone.frag
  src/graphics/program-lib/chunks/fresnelSchlick.frag
  src/graphics/program-lib/chunks/lightSpecularAnisoGGX.frag
  src/graphics/program-lib/chunks/lightSpecularBlinn.frag
  src/graphics/program-lib/chunks/lightSpecularPhong.frag
  src/graphics/program-lib/chunks/ltc.frag
  src/graphics/program-lib/chunks/reflectionCC.frag
  src/graphics/program-lib/chunks/reflectionCube.frag
  src/graphics/program-lib/chunks/reflectionDpAtlas.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCube.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/reflectionSphere.frag
  src/graphics/program-lib/chunks/reflectionSphereLow.frag
  src/graphics/program-lib/chunks/reproject.frag
  src/graphics/program-lib/programs/standard.js
Labels: area: graphics

#3210 Fix: Compressed SceneItem cannot be reloaded
  src/resources/parser/scene.js
Labels: bug

#3195 Fix: standard material options created shader unexpectly
  src/scene/materials/standard-material-options-builder.js
Labels: area: graphics, bug

#3215 Minor fix
  src/framework/components/rigid-body/component.js
Labels: area: physics, enhancement

#3218 Suspend stop event on sound instance when setting currentTime
  src/sound/instance.js
Labels: area: sound, bug

#3223 [FIX] Image element crash on assigning new layer composition to scene
  src/framework/components/element/component.js
Labels: area: ui, bug

#3211 Add renderAsset property to particlesystem component
  src/framework/components/particle-system/component.js
  src/framework/components/particle-system/system.js
  src/scene/render.js
Labels: area: graphics, enhancement

#3219 Support a GamePads wasReleased function
  src/input/game-pads.js
Labels: area: input, enhancement

#3227 Moved content type served warning to debug builds only
  src/net/http.js
Labels: area: assets, enhancement

#3220 Add custom bounding box properties to model / render components
  src/deprecated.js
  src/framework/components/model/component.js
  src/framework/components/model/system.js
  src/framework/components/render/component.js
  src/framework/components/render/system.js
  src/scene/mesh-instance.js
Labels: area: graphics, enhancement

#3184 Cascaded shadow mapping
  examples/src/examples/graphics/clustered-lighting.tsx
  examples/src/examples/graphics/lights.tsx
  examples/src/examples/graphics/shadow-cascades.tsx
  src/framework/components/light/component.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/shadowCascades.frag
  src/graphics/program-lib/programs/standard.js
  src/graphics/program-library.js
  src/math/mat4.js
  src/scene/light.js
  src/scene/lightmapper.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
  src/shape/frustum.js
Labels: area: graphics, enhancement

#3233 examples browser fixes
  examples/README.md
  examples/src/app/menu.tsx
  examples/src/app/styles.css
  examples/thumbnails.js
  examples/webpack.config.js
Labels: bug, docs

#3230 Move app destroy to frame end
  src/framework/application.js
Labels: bug

#3128 AnimComponent events
  src/anim/controller/anim-controller.js
  src/anim/evaluator/anim-clip.js
  src/anim/evaluator/anim-events.js
  src/anim/evaluator/anim-track.js
  src/framework/components/anim/component.js
  src/index.js
Labels: area: animation, enhancement

#3068 WebXR Plane Detection
  src/framework/components/camera/component.js
  src/index.js
  src/xr/xr-manager.js
  src/xr/xr-plane-detection.js
  src/xr/xr-plane.js
Labels: area: xr, enhancement, release: next minor

#3238 Remove leftover code related to shadow coord generation in VS
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/shadowStandardGL2VS.frag
  src/graphics/program-lib/chunks/shadowStandardVS.frag
  src/graphics/program-lib/chunks/shadowVSMVS.frag
  src/graphics/program-lib/programs/standard.js
Labels: area: graphics

#3239 Examples browser updates
  examples/example-directory.js
  examples/src/app/code-editor.tsx
  examples/src/app/example-iframe.tsx
  examples/src/app/index.tsx
  examples/src/app/styles.css
Labels: bug, docs, enhancement

#3242 [Fix] Fixes warning for missing shadow map when light is not in the frustum
  src/scene/renderer/forward-renderer.js
Labels: area: graphics, bug

#3243 Fixed static method API docs for i18n.findAvailableLocale
  src/i18n/i18n.js
Labels: bug, docs

#3244 Reverts #3242 due to uintended impact
  src/scene/renderer/forward-renderer.js
Labels: area: graphics

#3246 Shadow rendering fixes
  src/graphics/program-lib/programs/standard.js
  src/scene/renderer/forward-renderer.js
Labels: area: graphics, bug

#3247 [Fix] Expand range for depth shadow map camera to avoid near plane clipping
  src/scene/renderer/shadow-renderer.js
Labels: area: graphics, bug

#3248 [Examples Browser] Bump the PlayCanvas dependency to v1.43.0
  examples/package-lock.json
  examples/package.json
Labels: dependencies

#3249 Anim events fix
  src/anim/evaluator/anim-clip.js
Labels: area: animation, bug

#3251 Ignore maxlines in linebreak logic on text elements
  src/framework/components/element/text-element.js
Labels: area: ui, bug

#3258 Example list file
  examples/example-directory.js
Labels: docs

#3256 Example to load point cloud stored in a file with draco file format (.drc)
  examples/assets/models/park_points.drc
  examples/src/examples/loaders/drc.tsx
Labels: area: graphics

#3257 Engine example - cleaned up and converted to render components
  examples/src/examples/camera/first-person.tsx
  examples/src/examples/camera/fly.tsx
  examples/src/examples/camera/orbit.tsx
  examples/src/examples/graphics/area-lights.tsx
  examples/src/examples/graphics/area-picker.tsx
  examples/src/examples/graphics/batching-dynamic.tsx
  examples/src/examples/graphics/grab-pass.tsx
  examples/src/examples/graphics/hardware-instancing.tsx
  examples/src/examples/graphics/mesh-decals.tsx
  examples/src/examples/graphics/mesh-deformation.tsx
  examples/src/examples/graphics/mesh-generation.tsx
  examples/src/examples/graphics/mesh-morph-many.tsx
  examples/src/examples/graphics/model-outline.tsx
  examples/src/examples/graphics/painter.tsx
  examples/src/examples/graphics/point-cloud-simulation.tsx
  examples/src/examples/graphics/post-effects.tsx
  examples/src/examples/graphics/render-asset.tsx
  examples/src/examples/graphics/render-cubemap.tsx
  examples/src/examples/graphics/render-to-texture.tsx
  examples/src/examples/graphics/shader-burn.tsx
  examples/src/examples/graphics/shader-toon.tsx
  examples/src/examples/graphics/shader-wobble.tsx
  examples/src/examples/graphics/shapes.tsx
  examples/src/examples/graphics/texture-basis.tsx
  examples/src/examples/graphics/transform-feedback.tsx
  examples/src/examples/graphics/video-texture.tsx
  examples/src/examples/input/gamepad.tsx
  examples/src/examples/input/keyboard.tsx
  examples/src/examples/input/mouse.tsx
  examples/src/examples/misc/mini-stats.tsx
  examples/src/examples/physics/compound-collision.tsx
  examples/src/examples/physics/raycast.tsx
  src/font/canvas-font.js
Labels: area: graphics

#3253 Support for KHR_lights_punctual extension
  examples/src/examples/graphics/model-asset.tsx
  src/framework/components/render/component.js
  src/resources/container.js
  src/resources/parser/glb-model.js
  src/resources/parser/glb-parser.js
  src/scene/skin-instance-cache.js
  src/scene/skin-instance.js
Labels: area: graphics, feature request

#3261 Updated post effects engine example to more showcase the effects
  examples/src/examples/graphics/post-effects.tsx
Labels: area: graphics, enhancement

#3241 Exposed additional public functions for mesh morphing
  src/deprecated.js
  src/scene/mesh-instance.js
  src/scene/morph-instance.js
  src/scene/morph.js
Labels: area: graphics

#3262 Fix WebXR AR quarter rendering issue
  src/framework/application.js
  src/xr/xr-plane-detection.js
Labels: area: graphics, area: xr, bug

#3237 [AnimComponent] Refactor and API update
  examples/src/examples/animation/events.tsx
  src/anim/controller/anim-controller.js
  src/anim/controller/anim-state.js
  src/anim/controller/anim-transition.js
  src/anim/evaluator/anim-evaluator.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/anim/data.js
  src/framework/components/anim/system.js
Labels: area: animation, bug, enhancement

#3265 Corrected Curve and CurveSet JSDocs
  src/math/curve-set.js
  src/math/curve.js
Labels: bug, docs

#3271 Clustered lighting does not use lights with intensity of zero
  src/scene/world-clusters.js
Labels: area: graphics

#3266 Screen Space Ambient Occlusion post effect
  examples/src/examples/graphics/post-effects.tsx
  scripts/posteffects/posteffect-ssao.js
Labels: area: graphics, feature request

#3274 Fix rollup without .git dir
  examples/package.json
  rollup.config.js
Labels: bug

#3276 Renamed last references of point light to omni light
  examples/src/examples/graphics/lights-baked.tsx
  src/framework/components/light/component.js
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/scene/lightmapper.js
  src/scene/renderer/shadow-map.js
Labels: area: graphics

#3279 Improved error reporting for missing / incorrect shader
  src/graphics/graphics-device.js
Labels: area: graphics, bug
