Repository playcanvas/engine, pull requests merged in 2021-03, with the labels that each got.

#2898 [AnimComponent] Sync BlendTree animation durations
  src/anim/controller/anim-blend-tree-1d.js
  src/anim/controller/anim-blend-tree-2d-cartesian.js
  src/anim/controller/anim-blend-tree-2d-directional.js
  src/anim/controller/anim-blend-tree-direct.js
  src/anim/controller/anim-blend-tree.js
  src/anim/controller/anim-controller.js
  src/anim/controller/anim-node.js
  src/anim/controller/anim-state.js
Labels: area: animation, enhancement

#2931 collision system fix
  src/framework/components/collision/system.js
Labels: area: physics, bug

#2934 Fixed typo in pc.getBasename docs
  src/core/path.js
Labels: docs

#2623 Scene data caching API
  README.md
  src/callbacks.js
  src/framework/application.js
  src/framework/scene-registry-item.js
  src/framework/scene-registry.js
  src/index.js
  src/resources/hierarchy.js
  src/resources/parser/scene.js
  src/resources/scene-settings.js
  src/resources/scene-utils.js
  src/resources/scene.js
  src/resources/template.js
  src/templates/template-utils.js
  tests/framework/scene-registry/test_scene_registry.js
Labels: enhancement

#2946 Add vector div and scalar ops
  src/deprecated.js
  src/math/color.js
  src/math/mat3.js
  src/math/mat4.js
  src/math/quat.js
  src/math/vec2.js
  src/math/vec3.js
  src/math/vec4.js
  tests/math/test_vec2.js
  tests/math/test_vec3.js
  tests/math/test_vec4.js
Labels: enhancement

#2733 Add video texture example
  examples/assets/models/tv.glb
  examples/assets/video/SampleVideo_1280x720_1mb.mp4
  examples/examples.js
  examples/graphics/video-texture.html
Labels: area: graphics, enhancement

#2914 Basis texture load should error if the Basis module isn't present
  src/resources/basis.js
  src/resources/parser/texture/basis.js
Labels: area: graphics, enhancement

#2955 [FIX] Remove unused imports and var
  src/resources/hierarchy.js
  src/resources/scene-settings.js
  src/resources/scene.js
  src/resources/template.js
Labels: bug

#2961 Added private renderWireSphere function
  src/framework/application.js
  src/scene/immediate.js
Labels: area: graphics, enhancement

#2966 pc.createMesh reimplemented using Mesh API
  src/scene/procedural.js
Labels: area: graphics

#2936 Shadow culling and rendering refactor
  examples/graphics/lights.html
  src/framework/components/light/component.js
  src/scene/forward-renderer.js
  src/scene/layer-composition.js
  src/scene/layer.js
  src/scene/light.js
  src/scene/lightmapper.js
  src/scene/render-action.js
  src/scene/shadow-casters.js
Labels: area: graphics

#2939 [Fix] camera stack does not propagate to cameras with different viewport
  src/scene/layer-composition.js
Labels: area: graphics, bug

#2970 [Fix] Fix engine crash by recent PR merge
  src/scene/light.js
Labels: bug

#2943 Making RenderComponent related API public
  src/framework/application.js
  src/framework/components/render/component.js
  src/framework/components/render/system.js
  src/framework/entity.js
  src/index.js
  src/resources/container.js
Labels: area: graphics, enhancement

#2973 Hdr parser
  src/index.js
  src/resources/parser/texture/basis.js
  src/resources/parser/texture/dds.js
  src/resources/parser/texture/hdr.js
  src/resources/parser/texture/img.js
  src/resources/parser/texture/ktx.js
  src/resources/texture.js
Labels: area: graphics, enhancement

#2979 Normalize text to work correctly with bidi
  src/framework/components/element/text-element.js
Labels: bug

#2980 Allow CJK characters to be treated like words when laying out lines of text
  src/framework/components/element/text-element.js
Labels: area: ui, bug

#2983 Update NPM dependencies
  package-lock.json
  package.json
Labels: enhancement

#2714 [AnimComponent] Public API and engine examples
  examples/animation/blend-trees-1d.html
  examples/animation/blend-trees-2d-cartesian.html
  examples/animation/blend-trees-directional.html
  examples/animation/component-properties.html
  examples/animation/locomotion.html
  examples/assets/animations/bitmoji/dance.glb
  examples/assets/animations/bitmoji/idle.glb
  examples/assets/animations/bitmoji/jump-flip.glb
  examples/assets/animations/bitmoji/run.glb
  examples/assets/animations/bitmoji/walk.glb
  examples/assets/models/bitmoji.glb
  examples/assets/scripts/asset-loader.js
  examples/examples.js
  src/anim/controller/constants.js
  src/anim/state-graph/anim-state-graph.js
  src/framework/application.js
  src/framework/components/anim/component-binder.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/anim/data.js
  src/framework/components/anim/system.js
  src/framework/components/animation/component.js
  src/framework/entity.js
  src/resources/parser/glb-parser.js
Labels: area: animation, docs

#2985 Anim transition to END state fix
  src/anim/controller/anim-controller.js
  src/anim/controller/anim-transition.js
Labels: area: animation, bug

#2938 Fixes gamepad crash with wasReleased
  src/input/game-pads.js
Labels: area: input, bug

#2977 Make area lights public
  examples/camera/fly.html
  examples/examples.js
  examples/graphics/area-picker.html
  examples/graphics/grab-pass.html
  examples/graphics/hardware-instancing.html
  examples/graphics/hierarchy.html
  examples/graphics/layers.html
  examples/graphics/lights-baked-ao.html
  examples/graphics/lights.html
  examples/graphics/mesh-decals.html
  examples/graphics/mesh-deformation.html
  examples/graphics/mesh-generation.html
  examples/graphics/model-asset.html
  examples/graphics/model-box.html
  examples/graphics/model-outline.html
  examples/graphics/model-textured-box.html
  examples/graphics/render-to-texture.html
  examples/graphics/shader-burn.html
  examples/graphics/shader-toon.html
  examples/graphics/shader-wobble.html
  examples/graphics/video-texture.html
  examples/input/gamepad.html
  examples/input/keyboard.html
  examples/input/mouse.html
  examples/loaders/loader-glb.html
  examples/loaders/loader-obj.html
  examples/misc/multi-application.html
  src/framework/application.js
  src/framework/components/light/component.js
  src/scene/constants.js
Labels: area: graphics

#2991 [Fix] Improved compatibility with older projects that use render target on a layer
  src/scene/layer-composition.js
Labels: area: graphics, enhancement

#2992 Private API app.renderDepthTexture to display depth buffer on the screen
  examples/graphics/post-effects.html
  src/framework/application.js
  src/scene/immediate.js
Labels: area: graphics

#2095 Add a physics joint component
  src/framework/application.js
  src/framework/components/joint/component.js
  src/framework/components/joint/constants.js
  src/framework/components/joint/data.js
  src/framework/components/joint/system.js
  src/index.js
Labels: area: physics, enhancement

#2909 Add mesh-based 3D text support
  package.json
  scripts/camera/follow-camera.js
  scripts/textmesh/earcut-license.txt
  scripts/textmesh/earcut.min.js
  scripts/textmesh/opentype-license.txt
  scripts/textmesh/opentype.min.js
  scripts/textmesh/text-mesh.js
Labels: area: graphics, enhancement

#2999 Normalize test
  src/framework/components/element/text-element.js
Labels: bug

#2998 Directional Blend Trees speed fix
  src/anim/controller/anim-blend-tree-2d-directional.js
Labels: area: animation, bug

#3000 Fix various IE11 compatibility problems
  examples/animation/blend-trees-1d.html
  examples/animation/blend-trees-2d-cartesian.html
  examples/animation/blend-trees-directional.html
  examples/animation/component-properties.html
  examples/animation/locomotion.html
  src/index.js
  src/polyfill/number-isfinite.js
Labels: bug

#3003 Update PCUI URL in examples to use https
  examples/animation/blend-trees-1d.html
  examples/animation/blend-trees-2d-cartesian.html
  examples/animation/blend-trees-directional.html
  examples/animation/component-properties.html
  examples/animation/locomotion.html
Labels: area: animation, bug

#3004 Fix blend tree URLs from the examples browser
  examples/examples.js
Labels: area: animation, bug

#3006 [FIX] Incorrect JSDoc for optional parameter
  src/framework/components/anim/component.js
Labels: bug

#3008 Better handling of line break
  src/framework/components/element/text-element.js
Labels: area: graphics, enhancement

#3012 [Fix] don’t skip directional shadow rendering it first layer is disabled
  src/scene/forward-renderer.js
Labels: area: graphics

#3009 fix: type argument for attributes had regressed from a union of strings to plain string
  src/script/script-attributes.js
Labels: enhancement

#3014 Use correct texture filtering defaults
  src/resources/parser/glb-parser.js
Labels: area: graphics, bug

#3015 Prefer clearer code
  src/resources/parser/glb-parser.js
Labels: enhancement

#3021 Update all calls of vector scale to mulScalar
  src/framework/components/element/component.js
  src/framework/components/element/element-drag-helper.js
  src/framework/components/rigid-body/component.js
  src/input/element-input.js
  src/math/mat4.js
  src/math/quat.js
  src/scene/camera.js
  src/scene/forward-renderer.js
  src/scene/graph-node.js
  src/scene/light.js
  src/scene/particle-system/cpu-updater.js
  src/scene/particle-system/particle-emitter.js
  src/scene/procedural.js
  src/shape/bounding-box.js
  src/shape/bounding-sphere.js
  src/shape/plane.js
  src/xr/xr-light-estimation.js
Labels: bug

#3020 Migrate core, math and shape source to use let and const
  src/core/core.js
  src/core/debug.js
  src/core/event-handler.js
  src/core/events.js
  src/core/guid.js
  src/core/indexed-list.js
  src/core/object-pool.js
  src/core/path.js
  src/core/platform.js
  src/core/sorted-loop-array.js
  src/core/string.js
  src/core/tags-cache.js
  src/core/tags.js
  src/core/time.js
  src/core/uri.js
  src/math/color.js
  src/math/curve-evaluator.js
  src/math/curve-set.js
  src/math/curve.js
  src/math/mat3.js
  src/math/mat4.js
  src/math/math.js
  src/math/quat.js
  src/math/vec2.js
  src/math/vec3.js
  src/math/vec4.js
  src/shape/bounding-box.js
  src/shape/bounding-sphere.js
  src/shape/frustum.js
  src/shape/oriented-box.js
  src/shape/plane.js
Labels: enhancement

#3022 [FIX] Type for TEXTUREPROJECTION constants is string, not number
  src/graphics/constants.js
Labels: area: graphics, bug

#3024 [FIX] Missing extension on some imports
  src/resources/hierarchy.js
  src/resources/scene-settings.js
  src/resources/scene-utils.js
  src/resources/scene.js
Labels: bug

#3025 Migrate SceneRegistryItem to ES6 class
  src/framework/scene-registry-item.js
Labels: bug

#3023 [FIX] Remove access to Vec4#data which is no longer API
  src/graphics/paraboloid.js
  src/graphics/prefilter-cubemap.js
Labels: area: graphics, bug

#3027 Update NPM dependences to latest
  package-lock.json
  package.json
Labels: enhancement

#3030 Remove SceneUtils from global export
  src/index.js
Labels: bug

#3032 Remove all redundant constructors
  src/anim/binder/anim-binder.js
  src/framework/components/anim/component.js
  src/framework/components/audio-listener/component.js
  src/framework/components/collision/system.js
  src/framework/components/element/markup.js
  src/framework/components/layout-group/layout-calculator.js
  src/i18n/i18n-parser.js
  src/net/http.js
  src/resources/folder.js
  src/resources/handler.js
  src/resources/parser/glb-parser.js
  src/resources/texture.js
  src/scene/materials/depth-material.js
Labels: enhancement

#3033 [FIX] Minor lint related fixes
  src/anim/controller/anim-node.js
  src/anim/controller/anim-state.js
  src/callbacks.js
  src/graphics/prefilter-cubemap.js
Labels: bug

#3034 Prefer const over let
  scripts/textmesh/text-mesh.js
  src/audio/channel3d.js
  src/framework/application.js
  src/framework/components/camera/component.js
  src/framework/components/camera/post-effect-queue.js
  src/framework/components/render/component.js
  src/graphics/reproject-texture.js
  src/scene/forward-renderer.js
  src/scene/immediate.js
  src/scene/layer-composition.js
  src/scene/light.js
  src/scene/lightmapper.js
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  src/scene/morph-instance.js
  src/scene/picker.js
  src/scene/render-action.js
Labels: enhancement

#3036 Make arrow function parentheses consistent
  rollup.config.js
  scripts/textmesh/text-mesh.js
  src/anim/evaluator/anim-evaluator.js
  src/framework/components/joint/component.js
  src/framework/components/render/component.js
  src/framework/components/render/system.js
  src/framework/components/screen/component.js
  src/graphics/graphics-device.js
Labels: enhancement

#3038 [FIX] Remove pc namespace from anim API constants
  src/anim/controller/constants.js
Labels: area: animation, bug

#3040 Spacing consistency fixes
  extras/mini-stats/word-atlas.js
  scripts/parsers/obj-model.js
  src/anim/controller/anim-blend-tree-2d-cartesian.js
  src/anim/controller/anim-blend-tree-2d-directional.js
  src/font/font.js
  src/framework/application.js
  src/framework/components/collision/system.js
  src/framework/components/element/markup.js
  src/framework/components/layout-group/system.js
  src/framework/components/screen/system.js
  src/framework/components/scroll-view/component.js
  src/framework/components/scrollbar/component.js
  src/framework/stats.js
  src/graphics/graphics-device.js
  src/graphics/index-buffer.js
  src/graphics/prefilter-cubemap.js
  src/graphics/program-lib/programs/standard.js
  src/graphics/render-target.js
  src/graphics/vertex-buffer.js
  src/graphics/vertex-format.js
  src/math/math.js
  src/resources/basis.js
  src/resources/container.js
  src/resources/cubemap.js
  src/resources/parser/glb-parser.js
  src/resources/parser/texture/img.js
  src/scene/forward-renderer.js
  src/scene/layer-composition.js
  src/scene/light.js
  src/scene/lightmapper.js
  src/scene/materials/standard-material.js
  src/scene/morph.js
  src/scene/particle-system/cpu-updater.js
  src/scene/particle-system/particle-emitter.js
  src/scene/picker.js
  src/scene/procedural.js
  src/scene/skin-partition.js
  src/vr/vr-display.js
Labels: enhancement

#3041 Update to latest ESLint config
  package-lock.json
  package.json
Labels: enhancement

#3042 All automated tests now run
  src/framework/scene-registry.js
  tests/framework/components/element/test_imageelement.js
  tests/framework/scene-registry/test_scene_registry.js
  tests/test-assets/scenes/test1.json
  tests/test-assets/scenes/test2.json
  tests/test-assets/scenes/test3.json
Labels: bug

#3045 Make JSDoc sentence format consistent
  scripts/posteffects/posteffect-outline.js
  src/anim/binder/anim-binder.js
  src/anim/controller/anim-blend-tree-2d-cartesian.js
  src/anim/controller/anim-blend-tree-direct.js
  src/anim/evaluator/anim-clip.js
  src/anim/evaluator/anim-curve.js
  src/anim/evaluator/anim-data.js
  src/anim/evaluator/anim-evaluator.js
  src/anim/evaluator/anim-snapshot.js
  src/anim/evaluator/anim-target.js
  src/anim/evaluator/anim-track.js
  src/asset/asset.js
  src/callbacks.js
  src/compress/compress-utils.js
  src/compress/decompress.js
  src/core/uri.js
  src/framework/application.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/camera/component.js
  src/framework/components/light/component.js
  src/framework/components/rigid-body/system.js
  src/framework/scene-registry-item.js
  src/graphics/constants.js
  src/graphics/reproject-texture.js
  src/graphics/texture.js
  src/graphics/vertex-format.js
  src/math/math.js
  src/resources/scene-utils.js
  src/resources/texture.js
  src/scene/graph-node.js
  src/scene/mesh.js
  src/script/script-type.js
  src/shape/bounding-box.js
  src/xr/constants.js
  src/xr/xr-depth-sensing.js
  src/xr/xr-finger.js
  src/xr/xr-hand.js
  src/xr/xr-hit-test-source.js
  src/xr/xr-hit-test.js
  src/xr/xr-input-source.js
  src/xr/xr-input.js
  src/xr/xr-joint.js
  src/xr/xr-manager.js
Labels: enhancement

#3046 Migrate resources codebase to let and const
  src/resources/anim-clip.js
  src/resources/anim-state-graph.js
  src/resources/animation.js
  src/resources/audio.js
  src/resources/basis.js
  src/resources/bundle.js
  src/resources/container.js
  src/resources/css.js
  src/resources/cubemap.js
  src/resources/font.js
  src/resources/hierarchy.js
  src/resources/json.js
  src/resources/loader.js
  src/resources/material.js
  src/resources/model.js
  src/resources/parser/glb-model.js
  src/resources/parser/glb-parser.js
  src/resources/parser/json-model.js
  src/resources/parser/material/json-standard-material.js
  src/resources/parser/scene.js
  src/resources/parser/texture/basis.js
  src/resources/parser/texture/dds.js
  src/resources/parser/texture/hdr.js
  src/resources/parser/texture/img.js
  src/resources/parser/texture/ktx.js
  src/resources/parser/texture/legacy-dds.js
  src/resources/render.js
  src/resources/scene-utils.js
  src/resources/scene.js
  src/resources/script.js
  src/resources/sprite.js
  src/resources/texture-atlas.js
  src/resources/texture.js
  src/resources/untar.js
Labels: enhancement

#3044 Prefer triple to double equals
  scripts/camera/orbit-camera.js
  scripts/utils/download-texture.js
  src/anim/evaluator/anim-clip.js
  src/framework/components/audio-source/component.js
  src/framework/components/screen/component.js
  src/graphics/prefilter-cubemap.js
  src/graphics/program-lib/programs/particle.js
  src/graphics/program-lib/programs/standard.js
  src/math/curve-evaluator.js
  src/math/math.js
  src/resources/parser/glb-parser.js
  src/resources/parser/texture/hdr.js
  src/resources/script.js
  src/resources/untar.js
  src/scene/batching/batch-manager.js
  src/scene/graph-node.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/mesh.js
  src/scene/particle-system/cpu-updater.js
  src/scene/particle-system/particle-emitter.js
  src/scene/procedural.js
  src/scene/skin-partition.js
Labels: enhancement

#3048 Fix for crash: unbind (texture) asset references when material is destroyed
  src/scene/materials/standard-material.js
Labels: area: graphics, bug

#3049 Update JSDoc template version
  package-lock.json
  package.json
Labels: docs, enhancement
