Repository playcanvas/engine, pull requests merged in 2021-11, with the labels that each got.

#3645 [Fix] Lightmapper no longer leaks shadow map GPU memory
  src/framework/components/anim/component.js
  src/scene/lightmapper/bake-light.js
  src/scene/lightmapper/lightmapper.js
Labels: bug, performance, area: graphics

#3644 [Examples Browser] UI updates
  examples/src/app/code-editor.tsx
  examples/src/app/control-panel.tsx
  examples/src/app/index.tsx
  examples/src/app/menu.tsx
  examples/src/app/sidebar.tsx
  examples/src/app/styles.css
  examples/src/examples/animation/blend-trees-2d-cartesian.tsx
Labels: enhancement, area: examples

#3646 AnimComponent syntax change
  src/framework/components/anim/component.js
Labels: enhancement, area: animation

#3655 Add vox loading script
  .gitignore
  package.json
  rollup.config.js
  scripts/parsers/vox-parser.mjs
  src/core/read-stream.js
  src/framework/application.js
  src/index.js
  src/resources/container.js
  src/resources/parser/glb-container-resource.js
  src/resources/parser/glb-model.js
  src/resources/parser/glb-parser.js
Labels: enhancement, area: graphics

#3656 Grabpass functionality refactor and mipmap support for webgl2
  examples/assets/textures/pc-gray.png
  examples/src/examples/graphics/grab-pass.tsx
  src/graphics/grab-pass.js
  src/graphics/graphics-device.js
Labels: enhancement, area: graphics

#3595 Small refactor to the way TextElement releases MeshInstances
  src/framework/components/element/text-element.js
Labels: release: next minor

#3653 Fix undefined positions bug
  src/framework/components/layout-group/layout-calculator.js
Labels: bug, area: ui

#3659 Refactor some single iteration loops
  src/framework/components/animation/component.js
  src/framework/components/element/markup.js
  src/framework/components/element/text-element.js
  src/i18n/i18n.js
  src/resources/untar.js
Labels: enhancement

#3662 Set and Map are officially permitted in the engine, with limitations
  .github/CONTRIBUTING.md
Labels: enhancement

#3667 Use blob instead of file
  src/resources/basis.js
Labels: bug, area: graphics

#3668 Specular & Clear-coat support for clusterted lights
  examples/src/examples/graphics/clustered-lighting.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/programs/standard.js
Labels: enhancement, area: graphics

#3669 When shader fails to link in debug mode, print out vertex/fragment shader source
  src/graphics/graphics-device.js
Labels: enhancement, area: graphics

#3670 Fixed jsdoc datatype on excludeFromLayout
  src/framework/components/layout-child/component.js
Labels: bug, docs

#3671 Reimplement skybox handling in application
  src/framework/application.js
Labels: bug, area: graphics

#3672 AnimComponentLayer - fix the pause function description
  src/framework/components/anim/component-layer.js
Labels: docs, area: animation

#3677 [Fix] Glb parser handles a scene without nodes
  src/resources/parser/glb-parser.js
Labels: bug, area: gltf

#3679 AnimComponent layer mask path fix
  src/framework/components/anim/system.js
Labels: bug, area: animation

#3680 Re-added entity references init event
  src/framework/application.js
  src/framework/scene-registry.js
  src/framework/utils/entity-reference.js
Labels: bug

#3690 Update release.js to check tag
  release.js
Labels: enhancement

#3692 Update release script to work without arguments
  release.js
Labels: enhancement

#3694 [AnimComponent] AnimStateGraph asset change fix
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
Labels: bug, area: animation

#3697 Layer mask blending fix
  src/anim/evaluator/anim-evaluator.js
  src/anim/evaluator/anim-target-value.js
Labels: area: animation

#3698 Anim mask blending fix
  src/anim/evaluator/anim-target-value.js
Labels: area: animation

#3700 Examples browser iOS 11 fix
  examples/src/app/control-panel.tsx
  examples/src/app/example-iframe.tsx
  examples/src/app/helpers/raw-file-loading.ts
  examples/src/app/styles.css
  examples/src/examples/graphics/grab-pass.tsx
  package-lock.json
  package.json
Labels: bug, area: examples

#3691 Clustered Area lights
  examples/src/examples/graphics/clustered-area-lights.tsx
  examples/src/examples/graphics/mesh-decals.tsx
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/programs/standard.js
  src/resources/parser/glb-parser.js
  src/scene/composition/layer-composition.js
  src/scene/light.js
  src/scene/lighting/light-texture-atlas.js
  src/scene/lighting/lights-buffer.js
  src/scene/lighting/world-clusters.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/renderer/forward-renderer.js
Labels: enhancement, area: graphics

#3701 Move the resizeobserver polyfill into the examples package.json
  examples/package-lock.json
  examples/package.json
  package-lock.json
  package.json
Labels: area: examples

#3696 Follow camera lerp function is framerate independent
  scripts/camera/follow-camera.js
Labels: bug

#3704 Small tweaks to clusered lighting to improve compatibility and performance
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/clustered-spot-shadows.tsx
  src/graphics/graphics-device.js
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/scene/composition/layer-composition.js
  src/scene/materials/standard-material-options-builder.js
Labels: performance, area: graphics

#3706 MeshInstance.skinInstance is now public
  src/scene/mesh-instance.js
Labels: docs

#3705 Clustered lighting honors MeshInstance.noShadow
  src/graphics/program-lib/programs/standard.js
Labels: area: graphics

#3707 Update to msdf font rendering shader to lower the smoothing
  src/graphics/program-lib/chunks/msdf.frag
Labels: enhancement, area: graphics

#3708 [Fix] Fix to lightmapper stats reporting
  src/framework/stats.js
Labels: bug, area: graphics

#3709 Deprecated Scene.defaultMaterial
  scripts/parsers/vox-parser.mjs
  src/deprecated/deprecated.js
  src/framework/application.js
  src/framework/components/model/system.js
  src/framework/components/render/system.js
  src/resources/container.js
  src/resources/model.js
  src/resources/parser/glb-parser.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
Labels: area: graphics

#3710 Area light optimization - shared functionality is executed one time for all lights
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/chunks/ltc.frag
  src/graphics/program-lib/programs/standard.js
Labels: performance, area: graphics

#3711 [Fix] Fix to sphere area light specular reflection
  src/graphics/program-lib/chunks/ltc.frag
Labels: bug, area: graphics

#3712 Fixed null exception when button component is used with element group
  src/framework/components/button/component.js
Labels: bug, area: ui

#3713 [Examples Browser] Debug build
  examples/debug/index.js
  examples/debug/index.mustache
  examples/lib/wasm-loader.js
  examples/package-lock.json
  examples/package.json
  examples/src/examples/animation/blend-trees-1d.tsx
  examples/src/examples/animation/blend-trees-2d-cartesian.tsx
  examples/src/examples/animation/blend-trees-2d-directional.tsx
  examples/src/examples/animation/component-properties.tsx
  examples/src/examples/animation/locomotion.tsx
  examples/src/examples/graphics/particles-random-sprites.tsx
  examples/src/examples/graphics/render-cubemap.tsx
Labels: area: examples

#3717 Improved clustered spot light engine example
  examples/src/examples/graphics/clustered-spot-shadows.tsx
Labels: area: graphics, area: examples

#3716 Calculate compressed mipmap sizes correctly
  src/graphics/graphics-device.js
  src/resources/basis-worker.js
Labels: bug, area: graphics

#3720 Improved lighting in Locomotion example
  examples/src/examples/animation/locomotion.tsx
Labels: area: examples

#3703 Updated description on follow camera script
  scripts/camera/follow-camera.js
Labels: bug

#3721 Examples browser debug mode watch task update
  examples/package-lock.json
  examples/package.json
Labels: enhancement, area: examples

#3722 Examples debug watch update
  examples/package.json
Labels: area: examples

#3728 Small improvements to clustered lighting
  src/graphics/program-lib/chunks/clusteredLight.frag
  src/graphics/program-lib/programs/standard.js
Labels: area: graphics

#3729 Don't allow clustered area lights if less than 8 texture units
  src/graphics/graphics-device.js
  src/scene/composition/layer-composition.js
  src/scene/materials/standard-material-options-builder.js
Labels: area: graphics

#3730 [Examples Browser] Debug es5 build
  examples/debug/index.mustache
  examples/package-lock.json
  examples/package.json
Labels: area: examples

#3731 Fallback to uncompressed with invalid texture dimensions
  src/graphics/graphics-device.js
  src/resources/basis-worker.js
Labels: enhancement, area: graphics

#3736 Rename skybox.frag -> skyboxHDR.frag
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/skyboxHDR.frag
  src/graphics/program-lib/programs/skybox.js
Labels: bug

#3737 [Examples Browser] Build update
  examples/package-lock.json
  examples/package.json
  examples/webpack.config.js
Labels: enhancement, area: examples

#3738 Improvement to clustered lighting shader loop
  src/graphics/program-lib/chunks/clusteredLight.frag
Labels: area: graphics

#3743 Add support for DDS rgba16
  src/resources/parser/texture/dds.js
Labels: enhancement, area: graphics

#3744 Correctly enable textureLod extension on webgl1
  src/graphics/program-lib/chunks/ambientPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/fixCubemapSeamsStretch.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCubeLod.frag
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#3750 [Fix] Corrected aabb computation for morphed meshes
  src/scene/morph.js
Labels: bug, area: graphics

#3752 Remove deprecated chunks
  src/graphics/program-lib/programs/standard.js
Labels: enhancement, area: graphics

#3751 Remove left handed cubemap sampling
  scripts/utils/cubemap-renderer.js
  src/graphics/program-lib/chunks/ambientPrefilteredCube.frag
  src/graphics/program-lib/chunks/ambientPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/reflectionCube.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCube.frag
  src/graphics/program-lib/chunks/reflectionPrefilteredCubeLod.frag
  src/graphics/program-lib/chunks/skybox.frag
  src/graphics/program-lib/programs/skybox.js
  src/graphics/program-lib/programs/standard.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
  src/scene/scene.js
Labels: enhancement, area: graphics
