Repository playcanvas/engine, pull requests merged in 2021-07, with the labels that each got.

#3245 findAvailableLocale refactor - Removed the static function from the API and added a member function
  src/i18n/i18n.js
  tests/i18n/test_i18n.js
Labels: area: localisation, enhancement, release: next minor

#3277 Basis worker fixes
  src/graphics/graphics-device.js
  src/index.js
  src/resources/basis-worker.js
  src/resources/basis.js
  src/resources/parser/texture/basis.js
  src/resources/texture.js
Labels: area: graphics, bug, enhancement

#3288 Basis lazyInit
  src/deprecated.js
  src/resources/basis.js
Labels: enhancement

#3289 Partially migrate graphics to let and const
  src/graphics/graphics-device.js
  src/graphics/index-buffer.js
  src/graphics/paraboloid.js
  src/graphics/post-effect.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/program-lib.js
  src/graphics/program-lib/programs/basic.js
  src/graphics/program-lib/programs/common.js
  src/graphics/program-lib/programs/particle.js
  src/graphics/program-lib/programs/skybox.js
  src/graphics/program-lib/utils.js
  src/graphics/program-library.js
  src/graphics/render-target.js
  src/graphics/scope-space.js
  src/graphics/simple-post-effect.js
  src/graphics/transform-feedback.js
  src/graphics/vertex-buffer.js
  src/graphics/vertex-format.js
  src/graphics/vertex-iterator.js
Labels: enhancement

#3292 Fix to primitives mesh ref-counting to avoid those getting released
  examples/src/examples/misc/hello-world.tsx
  src/scene/procedural.js
Labels: area: graphics, bug

#3293 [FIX] Handle inf on windows correctly
  src/graphics/program-lib/chunks/TBNderivative.frag
Labels: area: graphics, bug

#3295 Small refactoring of batching code
  examples/src/examples/graphics/batching-dynamic.tsx
  src/deprecated.js
  src/framework/application.js
  src/scene/batching/batch-manager.js
  src/scene/batching/batch.js
Labels: area: graphics

#3300 Expose node names to Spector captures in debug mode
  src/framework/components/camera/post-effect-queue.js
  src/graphics/reproject-texture.js
  src/scene/morph-instance.js
  src/scene/particle-system/gpu-updater.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
Labels: area: graphics, enhancement

#3299 Fix BasicMaterial for skinned and morphed meshes
  src/graphics/program-lib/programs/basic.js
  src/scene/materials/basic-material.js
Labels: area: graphics, bug

#3304 Few additional examples converted to use render component
  examples/src/examples/animation/tween.tsx
  examples/src/examples/graphics/area-lights.tsx
  examples/src/examples/graphics/lights.tsx
  examples/src/examples/graphics/material-anisotropic.tsx
  examples/src/examples/graphics/material-clear-coat.tsx
  examples/src/examples/graphics/material-physical.tsx
  examples/src/examples/graphics/material-translucent-specular.tsx
  examples/src/examples/graphics/model-box.tsx
  examples/src/examples/graphics/render-asset.tsx
  examples/src/examples/graphics/render-to-texture.tsx
  examples/src/examples/sound/positional.tsx
  examples/src/examples/xr/vr-basic.tsx
  examples/src/examples/xr/vr-controllers.tsx
Labels: docs, enhancement

#3302 Destroy all lightmaps when the Application is destroyed
  src/core/ref-counted-cache.js
  src/scene/lightmapper.js
  src/scene/mesh-instance.js
Labels: area: graphics, bug

#3305 [Examples Browser] Code editor horizontal scrollbar fix
  examples/src/app/code-editor.tsx
  examples/src/app/styles.css
Labels: bug, docs

#3306 MeshInstance - tiny refactor
  src/graphics/vertex-buffer.js
  src/scene/materials/material.js
  src/scene/mesh-instance.js
Labels: area: graphics, enhancement

#3307 [FIX] glb memory buffer fix
  src/resources/parser/glb-parser.js
Labels: area: graphics, bug

#3275 [Examples Browser] Debug mode
  examples/README.md
  examples/example-directory.js
  examples/src/app/example-iframe.tsx
  examples/src/app/example.tsx
  examples/src/app/helpers/loader.tsx
  examples/src/app/index.tsx
  examples/src/examples/camera/first-person.tsx
  examples/src/examples/graphics/lights.tsx
  examples/src/examples/misc/mini-stats.tsx
Labels: docs, enhancement

#3318 Video texture example now autoplays on Android and iOS
  examples/src/examples/graphics/video-texture.tsx
Labels: bug

#3319 Reverting JS docs for curveset but correcting the example code
  src/math/curve-set.js
Labels: docs

#3320 Handle etc2 extension without etc1 correctly
  src/resources/basis-worker.js
Labels: area: graphics, bug

#3327 Fix for animation loading in editor projects
  src/framework/components/anim/component.js
Labels: area: animation, bug

#3328 [FIX] Render handles ref counting of meshes
  src/resources/parser/glb-parser.js
  src/resources/render.js
  src/scene/render.js
Labels: area: graphics, bug

#3296 Bind assets to material fix - Fixes an issue that shows in Editor when changing textures
  src/resources/material.js
Labels: area: assets, bug

#3330 Fix to culling of non-moving skinned objects
  src/scene/batching/batch.js
  src/scene/mesh-instance.js
Labels: area: graphics, bug

#3332 Updated docs from array format of node.position to vec3
  src/scene/graph-node.js
Labels: bug, docs

#3333 [Examples Browser] Updates & fixes
  examples/package-lock.json
  examples/package.json
  examples/src/app/code-editor.tsx
  examples/src/app/control-panel.tsx
  examples/src/app/example-iframe.tsx
  examples/src/app/example.tsx
  examples/src/app/helpers/raw-file-loading.ts
  examples/src/app/index.tsx
  examples/src/app/menu.tsx
  examples/src/app/sidebar.tsx
  examples/src/app/styles.css
  examples/src/examples/graphics/clustered-lighting.tsx
  examples/src/examples/misc/mini-stats.tsx
Labels: bug, docs, enhancement

#3337 [Examples Browser] Controls for the post effects / lights examples
  examples/src/app/control-panel.tsx
  examples/src/app/styles.css
  examples/src/examples/graphics/lights.tsx
  examples/src/examples/graphics/post-effects.tsx
Labels: docs, enhancement

#3335 [FIX] Adopt top-left texture origin
  examples/assets/textures/playcanvas.basis
  examples/assets/textures/sea.basis
  examples/assets/textures/seaside-rocks01-color.basis
  examples/assets/textures/seaside-rocks01-gloss.basis
  examples/assets/textures/seaside-rocks01-normal.basis
  examples/src/examples/graphics/render-to-texture.tsx
  examples/src/examples/graphics/texture-basis.tsx
  src/framework/components/element/image-element.js
  src/framework/components/element/text-element.js
  src/graphics/program-lib/chunks/particle.frag
  src/graphics/program-lib/chunks/particle_cpu.vert
  src/graphics/program-lib/chunks/particle_normalMap.frag
  src/graphics/program-lib/chunks/reproject.frag
  src/graphics/program-lib/chunks/startNineSliced.frag
  src/graphics/program-lib/chunks/startNineSlicedTiled.frag
  src/graphics/texture.js
  src/resources/cubemap.js
  src/resources/parser/glb-parser.js
  src/resources/parser/json-model.js
  src/resources/parser/texture/img.js
  src/scene/immediate.js
  src/scene/procedural.js
  src/scene/sprite.js
Labels: area: graphics, enhancement

#3339 Update SSAO code to Use New RenderTarget API
  scripts/posteffects/posteffect-ssao.js
Labels: area: graphics, bug

#3343 Handle material offset correctly with reoriented textures
  src/scene/materials/standard-material.js
Labels: area: graphics, bug

#3344 Fix drop shadow
  src/framework/components/element/text-element.js
Labels: area: graphics, bug

#3345 flip Y defaults to false
  src/graphics/texture.js
Labels: area: graphics, docs

#3347 [Fix] Falling shapes example - larger shadow distance to cover the area
  examples/src/examples/physics/falling-shapes.tsx
Labels: area: graphics, bug

#3348 [Fix] Model parser releases meshes correctly
  src/resources/animation.js
  src/resources/container.js
  src/resources/parser/glb-model.js
  src/resources/parser/glb-parser.js
Labels: area: graphics, bug

#3346 RTT texture flip flag
  examples/src/examples/graphics/render-to-texture.tsx
  src/graphics/render-target.js
  src/scene/renderer/forward-renderer.js
Labels: area: graphics, bug

#3352 [FIX] Check _flipFaces on camera not camera component
  src/scene/renderer/forward-renderer.js
Labels: area: graphics, bug

#3356 [Fix] Drc loader example uses loaded colors correctly
  examples/src/examples/loaders/drc.tsx
Labels: area: graphics, bug

#3359 Moved layer-composition and light-composition-data to composition folder
  src/framework/application.js
  src/graphics/program-lib/programs/standard.js
  src/index.js
  src/scene/composition/layer-composition.js
  src/scene/composition/light-composition-data.js
  src/scene/picker.js
  src/scene/renderer/forward-renderer.js
Labels: area: graphics

#3360 Updated documentation to reflect the behaviour of asset.loaded
  src/asset/asset.js
Labels: docs

#3363 Invert TBN, glTF texture transform
  src/graphics/program-lib/chunks/TBNderivative.frag
  src/resources/parser/glb-parser.js
Labels: area: graphics, bug
