Repository playcanvas/engine, pull requests merged in 2022-03, with the labels that each got.

#4060 Remove unused auto instancing code
  src/framework/application.js
  src/graphics/webgl/webgl-graphics-device.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: enhancement, area: graphics

#4071 Fixes related to TypeScript compiler v4.6
  src/framework/components/anim/system.js
  src/framework/components/animation/system.js
  src/framework/components/camera/system.js
  src/framework/components/light/system.js
  src/framework/components/model/system.js
  src/framework/components/render/system.js
  src/framework/components/rigid-body/system.js
  src/scene/materials/material.js
Labels: bug

#4072 Capitalize callback types
  src/asset/asset-registry.js
  src/asset/asset.js
  src/core/event-handler.js
  src/framework/application.js
  src/framework/components/camera/component.js
  src/framework/scene-registry.js
  src/framework/script.js
  src/input/mouse.js
  src/net/http.js
  src/resources/handler.js
  src/resources/loader.js
  src/resources/model.js
  src/resources/texture.js
  src/scene/graph-node.js
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  src/vr/vr-display.js
  src/xr/xr-hit-test.js
  src/xr/xr-input-source.js
  src/xr/xr-manager.js
  types-fixup.mjs
Labels: enhancement

#4073 [Examples Browser] Update to the watch:iframes script
  examples/package.json
Labels: enhancement, area: examples

#4075 [AnimComponent] Fix for layer masks in cloned components
  src/framework/components/anim/system.js
Labels: bug, area: animation, release: next patch

#4057 anim-controller: fix transitions sorting / minimize code duplication
  src/anim/controller/anim-controller.js
  src/core/sort.js
  src/framework/components/camera/system.js
  src/scene/composition/layer-composition.js
Labels: bug, area: graphics, area: animation, release: next patch

#4074 Changes to make BoxReflection example work more reliably
  examples/src/examples/graphics/box-reflection.tsx
  src/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics, release: next patch

#4077 Not exporting internal cmpPriority
  src/core/sort.js
Labels: release: next patch

#4054 [Fix] Entity.enable=true does not activate enties not connected to scene hierarchy
  src/scene/graph-node.js
Labels: release: next patch

#4062 Fix AudioContext not being properly resumed on iOS 15.
  src/sound/manager.js
Labels: bug, release: next patch, area: audio

#4079 Remove legacy flipV code in glb-parser
  src/resources/parser/glb-parser.js
Labels: area: gltf

#4081 Fix EntityReference not finding the entity if the parent was not added to the scene yet.
  src/framework/utils/entity-reference.js
  tests/framework/utils/test_entityreference.js
Labels: bug

#4085 [FIX] Entity components and systems in the registry can be undefined
  src/framework/components/registry.js
  src/framework/entity.js
Labels: bug, docs

#4088 Add shader textureBias
  examples/package-lock.json
  src/graphics/program-lib/chunks/ao.frag.js
  src/graphics/program-lib/chunks/base.frag.js
  src/graphics/program-lib/chunks/diffuse.frag.js
  src/graphics/program-lib/chunks/metalness.frag.js
  src/graphics/program-lib/chunks/normalDetailMap.frag.js
  src/graphics/program-lib/chunks/normalMap.frag.js
  src/graphics/program-lib/chunks/normalMapFast.frag.js
  src/graphics/program-lib/chunks/opacity.frag.js
  src/graphics/program-lib/chunks/parallax.frag.js
  src/graphics/program-lib/chunks/reflectionEnv.frag.js
  src/graphics/program-lib/chunks/specular.frag.js
  src/graphics/webgl/webgl-graphics-device.js
  src/resources/parser/glb-parser.js
Labels: area: graphics

#4092 Force RGBA8 when RGB8 is used for cubemap faces
  src/resources/cubemap.js
Labels: bug, area: graphics

#4096 Disable depth write on semitransparent gltf materials
  src/resources/parser/glb-parser.js
Labels: bug, area: gltf

#4101 [Fix] Replacing incorrectly used `Debug.assert` by `Debug.error`
  src/graphics/graphics-device.js
Labels: bug

#4104 [FIX] Don't use bitwise op to set boolean
  src/framework/components/scroll-view/component.js
Labels: bug, area: ui

#4105 [FIX] Remove `pc.` from `WorldClustersDebug`
  src/scene/lighting/world-clusters-debug.js
Labels: bug, area: graphics

#4103 [FIX] Fix some typedefs
  src/font/canvas-font.js
  src/framework/components/light/component.js
  src/framework/components/particle-system/component.js
  src/graphics/grab-pass.js
Labels: bug

#4109 [FIX] Various type related errors reported by VS Code
  src/framework/app-base.js
  src/input/controller.js
  src/input/keyboard.js
  src/resources/container.js
  src/resources/material.js
  src/resources/texture.js
  src/scene/materials/material.js
  src/scene/mesh-instance.js
Labels: bug

#4108 Update ESLint and reenable check-types rule
  package-lock.json
  package.json
  src/core/indexed-list.js
  src/framework/app-base.js
  src/framework/components/animation/component.js
  src/framework/components/model/component.js
  src/framework/components/sound/component.js
  src/framework/components/sprite/component.js
  src/framework/entity.js
  src/graphics/program-lib/utils.js
  src/graphics/shader.js
  src/graphics/vertex-iterator.js
  src/scene/materials/standard-material.js
  src/xr/xr-hand.js
  src/xr/xr-manager.js
Labels: enhancement

#4116 Migrate `ComponentSystem` tests to Node
  test/framework/components/system.test.mjs
  tests/framework/components/test_componentsystem.js
Labels: enhancement

#4120 Revert change from #4047 related to enabled in hierarchy
  src/scene/graph-node.js
Labels: bug, area: graphics

#4119 Revert "Fix EntityReference not finding the entity if the parent was not added to the scene yet. (#4081)"
  src/framework/utils/entity-reference.js
  test/framework/utils/entity-reference.test.mjs
Labels: bug

#4121 [Fix] setting xr managed references to null after cleanup
  src/xr/xr-manager.js
Labels: bug, area: xr

#4122 Some minor type improvements
  examples/src/examples/graphics/area-picker.tsx
  examples/src/examples/graphics/shader-burn.tsx
  examples/src/examples/graphics/shader-toon.tsx
  examples/src/examples/graphics/shader-wobble.tsx
  examples/src/examples/loaders/obj.tsx
  src/framework/components/element/component.js
  src/framework/components/script/component.js
  src/scene/mesh-instance.js
Labels: enhancement

#4127 Moved additional webgl related members of Shader to WebglShader
  src/graphics/shader.js
  src/graphics/webgl/webgl-graphics-device.js
  src/graphics/webgl/webgl-shader.js
Labels: area: graphics

#4140 [FIX] Restore GitHub Actions after branch rename
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: bug

#4138 [FIX] Fall back to previous Web Audio API spec as required
  src/audio/channel3d.js
  src/sound/instance3d.js
  src/sound/listener.js
Labels: bug, area: audio

#4141 Turn off Antialiasing on webkit 15.4 to avoid rendering issues
  src/graphics/webgl/webgl-graphics-device.js
Labels: bug

#4126 Cleaned up material references in render component # onRemove
  src/framework/components/render/component.js
Labels: bug, area: assets

#4147 Workaround for Samsung Exynos particle rendering/crash
  src/graphics/webgl/webgl-graphics-device.js
  src/scene/particle-system/particle-emitter.js
Labels: bug, area: graphics, area: particles

#4084 Handle Area Lights LUT textures destruction when device is destroyed
  src/graphics/device-cache.js
  src/scene/area-light-luts.js
Labels: bug, area: graphics

#4150 Shader texture bias and ao fixes
  src/graphics/program-lib/chunks/ao.frag.js
  src/graphics/program-lib/chunks/aoDiffuseOcc.frag.js
  src/graphics/program-lib/chunks/aoSpecOccConstSimple.frag.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#4148 Add retry option for glue and fallback downloading methods
  src/resources/basis.js
Labels: bug, area: assets

#4152 [FIX] Superfluous argument to `WebglTexture` constructor
  src/graphics/texture.js
  src/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#4064 [Breaking][Anim Component] Layer blending update
  src/anim/evaluator/anim-evaluator.js
  src/anim/evaluator/anim-target-value.js
  src/anim/evaluator/anim-target.js
  src/framework/components/anim/component-binder.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/anim/system.js
Labels: enhancement, area: animation, release: next minor

#4086 Extracted WebglRenderTarget class from RenderTarget and WeblGraphicsDevice
  scripts/utils/download-texture.js
  src/deprecated/deprecated.js
  src/framework/scene-depth.js
  src/graphics/grab-pass.js
  src/graphics/prefilter-cubemap.js
  src/graphics/render-target.js
  src/graphics/webgl/webgl-graphics-device.js
  src/graphics/webgl/webgl-render-target.js
Labels: enhancement, area: graphics, release: next minor

#4154 Enforce single quotes and disallow `var` in unit tests
  test/.eslintrc.json
  test/anim/evaluator/anim-evaluator.test.mjs
  test/asset/asset-localized.test.mjs
  test/asset/asset-registry.test.mjs
  test/core/event-handler.test.mjs
  test/framework/components/element/component.test.mjs
  test/framework/components/layout-group/component.test.mjs
  test/framework/components/layout-group/layout-calculator.test.mjs
  test/framework/components/system.test.mjs
  test/framework/entity.test.mjs
  test/framework/utils/entity-reference.test.mjs
  test/math/mat4.test.mjs
  test/scene/composition/layer-composition.test.mjs
  test/test-component/system.mjs
Labels: enhancement

#4098 DepthFunc per material
  src/scene/materials/material.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material-validator.js
  src/scene/renderer/forward-renderer.js
  test/scene/materials/material.test.mjs
Labels: feature request, area: graphics, release: next minor

#3994 Implement/use defineProtoFunc for better polyfills
  src/math/mat3.js
  src/math/mat4.js
  src/polyfill/array-fill.js
  src/polyfill/array-find-index.js
  src/polyfill/array-find.js
  src/polyfill/defineProtoFunc.js
  src/polyfill/string.js
  src/polyfill/typedarray-fill.js
Labels: enhancement, release: next minor
