Repository playcanvas/engine, pull requests merged in 2022-02, with the labels that each got.

#3947 Reproject texture cache fix
  src/graphics/graphics-device.js
  src/graphics/reproject-texture.js
Labels: bug, area: graphics, release: next minor

#3976 [Examples Browser] Example iframe ie11 support and refactor
  examples/package-lock.json
  examples/package.json
  examples/scripts/iframe/index.mjs
  examples/scripts/iframe/index.mustache
Labels: area: examples

#3981 [FIX] Type of `cache` paramater for `Http` functions
  src/net/http.js
Labels: bug

#3980 Skybox intensity fix
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#3985 Examples: Fix to debug/profile iframe build
  examples/package.json
Labels: bug, area: examples

#3988 Examples browser iframe fixes
  examples/scripts/iframe/index.mjs
  examples/scripts/iframe/index.mustache
  examples/src/app/helpers/formatters.mjs
Labels: bug, area: examples

#3990 [FIX] Corrections to vector distance docs
  src/math/vec2.js
  src/math/vec3.js
Labels: bug, docs

#3982 Extracted webgl implementation of Vertex and Index buffer into separate modules
  src/graphics/graphics-device.js
  src/graphics/index-buffer.js
  src/graphics/transform-feedback.js
  src/graphics/vertex-buffer.js
  src/graphics/webgl/webgl-buffer.js
  src/graphics/webgl/webgl-index-buffer.js
  src/graphics/webgl/webgl-vertex-buffer.js
Labels: enhancement, area: graphics

#3952 Fix source maps
  .gitignore
  package.json
  rollup.config.js
Labels: bug

#3998 Ambient lighting fix
  src/graphics/program-lib/chunks/ambientEnv.frag.js
Labels: bug, area: graphics

#3999 Add build:publish script target
  package.json
Labels: enhancement

#4002 Improve ModelComponent typings
  examples/src/examples/animation/events.tsx
  src/framework/components/model/component.js
Labels: bug

#4004 [FIX] RenderComponent#clone should respect enabled property
  src/framework/components/render/system.js
Labels: bug, area: graphics

#4006 Set failed flag in setShader()
  src/graphics/graphics-device.js
  src/scene/renderer/forward-renderer.js
Labels: bug

#4008 Improve JSDoc comments for sound modules
  src/audio/channel3d.js
  src/sound/instance.js
  src/sound/instance3d.js
  src/sound/listener.js
  src/sound/manager.js
  src/sound/sound.js
Labels: enhancement, area: audio

#4012 Improve Application JSDoc comments
  src/framework/application.js
Labels: enhancement

#3992 Switch box-reflection example to refresh envmap every 10 frames
  examples/src/examples/graphics/box-reflection.tsx
Labels: area: examples

#4019 More IntelliSense improvements
  src/framework/components/camera/system.js
  src/framework/components/component.js
  src/framework/components/rigid-body/system.js
  src/framework/entity.js
  src/scene/layer.js
  src/vr/vr-display.js
  src/vr/vr-manager.js
Labels: enhancement

#4023 [FIX] Revert changes to ScriptType and patch type declarations
  src/script/script-type.js
  types.mjs
Labels: bug

#4014 Extracted WebglShader and WebglTexture from WebglGraphicsDevice
  examples/src/examples/misc/mini-stats.tsx
  src/graphics/grab-pass.js
  src/graphics/graphics-device.js
  src/graphics/index-buffer.js
  src/graphics/program-library.js
  src/graphics/shader.js
  src/graphics/texture.js
  src/graphics/vertex-buffer.js
  src/graphics/webgl/webgl-graphics-device.js
  src/graphics/webgl/webgl-shader.js
  src/graphics/webgl/webgl-texture.js
  tests/framework/components/element/test_imageelement.js
Labels: enhancement, area: graphics

#4029 Add missing component properties to typings
  src/framework/components/animation/component.js
  src/framework/components/component.js
  src/framework/components/particle-system/component.js
  src/framework/components/render/component.js
  src/framework/components/rigid-body/system.js
  src/framework/components/scrollbar/component.js
  src/framework/utils/entity-reference.js
  types.mjs
Labels: bug

#4036 [FIX] Return type for `AssetRegistry#find`
  src/asset/asset-registry.js
Labels: bug, area: assets

#4038 XR session requests stencil buffer
  src/xr/xr-manager.js
Labels: bug, area: xr

#4011 Remove type aliases from `build/playcanvas.d.ts`
  types_bundle_undollar.mjs
Labels: enhancement

#4039 instantiateRenderEntity sets up render assets on render components
  src/asset/asset.js
  src/resources/parser/glb-container-resource.js
Labels: bug, area: graphics

#4041 [Fix] Fix to render asset id assignment to component when creating glb instance
  src/framework/components/render/component.js
  src/resources/parser/glb-container-resource.js
Labels: bug, area: graphics

#4045 Recompile basis transcoder 1.16.2 with emsdk 3.1.5
  examples/src/lib/basis/basis.js
  examples/src/lib/basis/basis.wasm.js
  examples/src/lib/basis/basis.wasm.wasm
Labels: enhancement

#4046 Updated Portal example to use layers
  examples/src/examples/graphics/portal.tsx
Labels: area: graphics, area: examples

#4047 [Fix] Removed children are no longer marked as enabled in hierarchy
  src/scene/graph-node.js
Labels: bug, area: graphics

#4048 Add application bake settings
  src/framework/application.js
  src/scene/scene.js
Labels: enhancement

#4051 Simplification and visual improvements to the Portal example
  examples/assets/models/portal.glb
  examples/assets/models/portal.txt
  examples/src/examples/graphics/portal.tsx
Labels: area: examples

#4052 Deprecate DepthMaterial
  src/deprecated/deprecated.js
  src/index.js
  src/scene/materials/depth-material.js
  test/scene/materials/depth-material.test.mjs
Labels: area: graphics

#4055 Remove type aliases from TypeScript declarations
  package.json
  src/framework/components/sound/component.js
  types-fixup.mjs
  types-undollar.mjs
Labels: bug, enhancement

#3416 Spine engine example
  examples/assets/spine/license.txt
  examples/assets/spine/spineboy-pro.atlas
  examples/assets/spine/spineboy-pro.json
  examples/assets/spine/spineboy-pro.png
  examples/src/examples/misc/index.mjs
  examples/src/examples/misc/spineboy.tsx
  package.json
  scripts/spine/playcanvas-spine.3.8.js
Labels: area: examples

#4063 Lightmapper fixes
  src/framework/application.js
  src/scene/lightmapper/bake-light-ambient.js
  src/scene/lightmapper/lightmapper.js
  src/scene/scene.js
Labels: bug, area: graphics

#4065 Missed the d
  src/scene/scene.js
Labels: bug, area: graphics
