Repository playcanvas/engine, pull requests merged in 2022-08, with the labels that each got.

#4491 [Fix] Increase the shadow resolution in model-outline example to avoid banding
  examples/src/examples/graphics/model-outline.tsx
Labels: area: graphics

#4492 [Fix] Added deprecated private Scene._updateSkybox function to avoid Editor breaking
  src/deprecated/deprecated.js
Labels: bug

#4493 [FIX] Back out tuple notation which is not supported by JSDoc
  src/graphics/program-lib/programs/lit-shader.js
  src/graphics/webgl/webgl-shader.js
Labels: bug, docs

#4495 Revert "Make touch events passive like mouse events (#4279)"
  src/input/touch-device.js
Labels: bug

#4482 Polyfill for `Object.values`
  src/index.js
  src/polyfill/object-values.js
Labels: bug

#4499 Handle refractionIndex as being one over refraction index.
  src/scene/materials/standard-material.js
Labels: bug

#4501 Fix gltf ior
  src/resources/parser/glb-parser.js
Labels: bug, area: gltf

#4497 Support for Mesh UniformBuffer / BindGroup
  src/graphics/bind-group-format.js
  src/graphics/bind-group.js
  src/graphics/constants.js
  src/graphics/graphics-device.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/common/frag/webgpu.js
  src/graphics/program-lib/chunks/common/vert/webgpu.js
  src/graphics/program-lib/programs/basic.js
  src/graphics/program-lib/programs/common.js
  src/graphics/program-lib/programs/lit-shader.js
  src/graphics/program-lib/utils.js
  src/graphics/shader-processor.js
  src/graphics/shader.js
  src/graphics/uniform-buffer-format.js
  src/graphics/uniform-buffer.js
  src/graphics/webgl/webgl-graphics-device.js
  src/scene/composition/render-action.js
  src/scene/immediate/immediate.js
  src/scene/mesh-instance.js
  src/scene/renderer/forward-renderer.js
Labels: enhancement, area: graphics

#4500 Split the reflection and light sheen calculations
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/lit/frag/lightSheen.js
  src/graphics/program-lib/chunks/lit/frag/reflectionSheen.js
  src/graphics/program-lib/programs/lit-shader.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  types-fixup.mjs
Labels: bug

#4507 [Fix] Fix to recently introduced issue with Basic shader generator
  src/graphics/program-lib/programs/basic.js
Labels: bug, area: graphics

#4510 Fix glb-parser logic
  src/resources/parser/glb-parser.js
Labels: bug, area: gltf

#4511 Fixed nine-sliced tiled elements
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#4513 Add HQ reflections
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/lit/frag/reflectionEnvHQ.js
  src/graphics/program-lib/programs/lit-shader.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
Labels: enhancement, area: graphics

#4515 Updated REGEX for Samsung Exynos check for Snapchat Minis
  src/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#4519 Small refactorings to allow for RenderTarget support for WebGPU
  rollup.config.js
  src/core/debug.js
  src/graphics/graphics-device.js
  src/graphics/render-target.js
  src/graphics/texture.js
  src/graphics/webgl/webgl-graphics-device.js
  src/graphics/webgl/webgl-render-target.js
  src/resources/parser/texture/img.js
Labels: enhancement, area: graphics

#4524 When material is not set on mesh instance, warn and use default one.
  src/scene/mesh-instance.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: bug, area: graphics

#4526 [Fix] Fix error message accessing null in SkinInstance
  src/scene/skin-instance.js
Labels: bug, area: graphics

#4527 Clear wasm module global
  src/core/wasm-module.js
Labels: bug

#4530 Fix preprocessor regexp matching extensions
  src/core/preprocessor.js
Labels: bug

#4532 Morph target animation fix
  src/anim/binder/default-anim-binder.js
  src/resources/parser/glb-parser.js
Labels: bug, area: animation

#4533 Move SetIndex/VertexBuffer function from WebGl device to parent class
  src/graphics/graphics-device.js
  src/graphics/webgl/webgl-graphics-device.js
Labels: enhancement, area: graphics

#4537 [Fix] Added buffer allocation tracing, fixed Vertex buffer size stats
  src/core/constants.js
  src/core/tracing.js
  src/graphics/index-buffer.js
  src/graphics/texture.js
  src/graphics/vertex-buffer.js
  src/graphics/webgl/webgl-buffer.js
Labels: bug, area: graphics

#4535 Add support for KHR_materials_emissive_strength
  src/resources/parser/glb-parser.js
Labels: enhancement, area: gltf

#4541 When stringifying uniform format, ignore assigned values
  src/graphics/scope-id.js
  src/scene/immediate/immediate.js
Labels: bug, area: graphics

#4485 Add support for KHR_materials_volume
  src/graphics/constants.js
  src/graphics/program-lib/chunks/chunk-validation.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/lit/frag/refractionCube.js
  src/graphics/program-lib/chunks/lit/frag/refractionDynamic.js
  src/graphics/program-lib/chunks/standard/frag/thickness.js
  src/graphics/program-lib/programs/lit-shader.js
  src/graphics/program-lib/programs/standard.js
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
  test/scene/materials/standard-material.test.mjs
Labels: enhancement, area: graphics

#4545 Animation resource with events fix
  src/framework/components/anim/component.js
  src/resources/animation.js
Labels: bug, area: animation, area: assets

#4528 Add support for material variants
  src/resources/container.js
  src/resources/parser/glb-container-resource.js
  src/resources/parser/glb-parser.js
Labels: enhancement, area: graphics

#4548 AnimBinder path resolution update
  src/anim/binder/default-anim-binder.js
Labels: area: animation

#4534 Initial very basic implementation of WebGPU
  examples/webgpu-temp/index.html
  examples/webgpu-temp/libs/glslang.js
  examples/webgpu-temp/libs/glslang.wasm
  package.json
  src/graphics/uniform-buffer-format.js
  src/graphics/uniform-buffer.js
  src/graphics/webgpu/webgpu-bind-group-format.js
  src/graphics/webgpu/webgpu-bind-group.js
  src/graphics/webgpu/webgpu-buffer.js
  src/graphics/webgpu/webgpu-graphics-device.js
  src/graphics/webgpu/webgpu-index-buffer.js
  src/graphics/webgpu/webgpu-render-pipeline.js
  src/graphics/webgpu/webgpu-render-state.js
  src/graphics/webgpu/webgpu-render-target.js
  src/graphics/webgpu/webgpu-shader.js
  src/graphics/webgpu/webgpu-texture.js
  src/graphics/webgpu/webgpu-uniform-buffer.js
  src/graphics/webgpu/webgpu-utils.js
  src/graphics/webgpu/webgpu-vertex-buffer-layout.js
  src/graphics/webgpu/webgpu-vertex-buffer.js
Labels: feature request, area: graphics

#4549 Return null if no variants are present
  src/resources/parser/glb-container-resource.js
Labels: bug, area: gltf

#4550 Example controls fix
  examples/scripts/iframe/index.mustache
  examples/src/app/example.tsx
Labels: bug, area: examples

#4462 Fix AudioContext not resuming properly.
  src/sound/instance.js
  src/sound/manager.js
Labels: bug, area: audio

#4561 AssetListLoader fix
  src/asset/asset-list-loader.js
  test/asset/asset-list-loader.test.mjs
Labels: bug, area: assets

#4565 Unified standard + basic shader intro code
  src/graphics/program-lib/programs/basic.js
  src/graphics/program-lib/programs/common.js
  src/graphics/program-lib/programs/lit-shader.js
  src/graphics/shader.js
  src/scene/shader-pass.js
Labels: enhancement, area: graphics

#4210 Add layer check between Camera and Element when testing for input.
  src/framework/components/camera/component.js
  src/input/element-input.js
  src/scene/camera.js
Labels: bug, area: input, area: ui

#4568 Standard shader compatibility improvements for WebGPU
  examples/webgpu-temp/index.html
  src/graphics/graphics-device.js
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/common/frag/gles2.js
  src/graphics/program-lib/chunks/common/frag/gles3.js
  src/graphics/program-lib/chunks/common/frag/webgpu.js
  src/graphics/program-lib/chunks/standard/frag/ao.js
  src/graphics/program-lib/chunks/standard/frag/clearCoat.js
  src/graphics/program-lib/chunks/standard/frag/clearCoatGloss.js
  src/graphics/program-lib/chunks/standard/frag/clearCoatNormal.js
  src/graphics/program-lib/chunks/standard/frag/diffuse.js
  src/graphics/program-lib/chunks/standard/frag/diffuseDetailMap.js
  src/graphics/program-lib/chunks/standard/frag/emissive.js
  src/graphics/program-lib/chunks/standard/frag/gloss.js
  src/graphics/program-lib/chunks/standard/frag/lightmapDir.js
  src/graphics/program-lib/chunks/standard/frag/lightmapSingle.js
  src/graphics/program-lib/chunks/standard/frag/metalness.js
  src/graphics/program-lib/chunks/standard/frag/normalDetailMap.js
  src/graphics/program-lib/chunks/standard/frag/normalMap.js
  src/graphics/program-lib/chunks/standard/frag/opacity.js
  src/graphics/program-lib/chunks/standard/frag/parallax.js
  src/graphics/program-lib/chunks/standard/frag/sheen.js
  src/graphics/program-lib/chunks/standard/frag/sheenGloss.js
  src/graphics/program-lib/chunks/standard/frag/specular.js
  src/graphics/program-lib/chunks/standard/frag/specularityFactor.js
  src/graphics/program-lib/chunks/standard/frag/thickness.js
  src/graphics/program-lib/chunks/standard/frag/transmission.js
  src/graphics/program-lib/programs/common.js
  src/graphics/uniform-buffer-format.js
  src/graphics/uniform-buffer.js
  src/graphics/webgl/webgl-graphics-device.js
  src/graphics/webgpu/webgpu-graphics-device.js
  src/resources/parser/glb-parser.js
Labels: area: graphics

#4574 Print a warning when resource loader is not registered
  src/resources/loader.js
Labels: enhancement

#4578 Fix material thickness and texture transforms
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#4581 Export AppOptions
  src/index.js
Labels: enhancement

#4584 Enable ImageBitmap if interface is present
  src/resources/parser/texture/img.js
Labels: enhancement, area: graphics

#4586 Clustered lighting is enabled by default and public
  examples/src/examples/graphics/area-lights.tsx
  examples/src/examples/graphics/lights.tsx
  src/framework/app-base.js
  src/scene/lighting/lighting-params.js
  src/scene/scene.js
Labels: enhancement, docs, area: graphics

#4575 Refactoring to get more of the standard shader compile for WebGPU
  examples/webgpu-temp/index.html
  src/graphics/graphics-device.js
  src/graphics/program-lib/chunks/common/frag/webgpu.js
  src/graphics/shader-processor.js
  src/graphics/shader.js
  src/graphics/webgl/webgl-graphics-device.js
  src/graphics/webgpu/webgpu-graphics-device.js
  src/graphics/webgpu/webgpu-shader.js
Labels: enhancement, area: graphics

#4562 Fix UI Element input events on multiple touches.
  src/framework/components/element/element-drag-helper.js
  src/input/element-input.js
  tests/framework/components/element/test_elementdraghelper.js
Labels: bug, area: ui

#4588 Moved lightmapper only chunks to separate module to allow for their tree-shaking
  src/graphics/program-lib/chunks/chunks-lightmapper.js
  src/graphics/program-lib/chunks/chunks.js
  src/scene/lightmapper/lightmap-filters.js
  src/scene/lightmapper/lightmapper.js
Labels: enhancement, area: graphics

#4587 Register shader generators at the point of use instead of always
  src/framework/app-base.js
  src/scene/materials/basic-material.js
  src/scene/materials/standard-material.js
  src/scene/particle-system/particle-emitter.js
  src/scene/sky.js
Labels: enhancement, area: graphics

#4592 Fix missing chunk deprecations and updates.
  src/graphics/program-lib/chunks/chunk-validation.js
Labels: bug, area: graphics

#4594 Fix using fresnel incorrectly with lightmaps.
  src/graphics/program-lib/chunks/lit/frag/lightmapDirAdd.js
Labels: bug, area: graphics

#4596 Revert enabling image bitmap
  src/resources/parser/texture/img.js
Labels: bug, area: graphics

#4599 Small updates to improve WebGPU implementation
  examples/webgpu-temp/index.html
  src/graphics/program-lib/chunks/common/frag/webgpu.js
  src/graphics/program-lib/programs/lit-shader.js
  src/graphics/webgpu/webgpu-buffer.js
  src/scene/graph-node.js
  src/scene/renderer/forward-renderer.js
Labels: enhancement, area: graphics
