Repository playcanvas/engine, pull requests merged in 2022-10, with the labels that each got.

#4683 [Fix] GltfExporter correctly handles multiple mesh instances per entity
  extras/exporters/gltf-exporter.js
Labels: bug, area: graphics

#4689 Implementation of math.nerestPowerOfTwo function
  src/math/math.js
  test/math/math.test.mjs
Labels: enhancement

#4690 Texture related improvements to Gltf and USDZ Exporters
  examples/src/examples/loaders/gltf-export.tsx
  examples/src/examples/loaders/usdz-export.tsx
  extras/exporters/core-exporter.js
  extras/exporters/gltf-exporter.js
  extras/exporters/usdz-exporter.js
Labels: enhancement, area: graphics

#4691 Fix GLB punctual lights with physical units
  src/framework/components/light/system.js
  src/resources/parser/glb-parser.js
  src/scene/light.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/sky.js
Labels: bug, area: graphics

#4692 Refactored ProgramLibrary to use the DeviceCache
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/graphics/get-program-library.js
  src/graphics/graphics-device.js
  src/graphics/program-lib/utils.js
  src/graphics/program-library.js
  src/graphics/reproject-texture.js
  src/graphics/webgl/webgl-graphics-device.js
  src/graphics/webgl/webgl-shader.js
  src/scene/materials/basic-material.js
  src/scene/materials/default-material.js
  src/scene/materials/material.js
  src/scene/materials/standard-material.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/forward-renderer.js
  src/scene/sky.js
Labels: enhancement, area: graphics

#4697 Fixes sheen intensity
  src/graphics/program-lib/chunks/lit/frag/clusteredLight.js
  src/graphics/program-lib/chunks/lit/frag/combine.js
  src/graphics/program-lib/chunks/lit/frag/reflectionSheen.js
  src/graphics/program-lib/programs/lit-shader.js
Labels: bug, area: graphics

#4700 Small refactor in the way VertexBuffer for post effects is created.
  src/graphics/post-effect.js
Labels: enhancement, area: graphics

#4699 [Fix] GltfExporter correctly exports buffer views for non-interleaved vertex data
  extras/exporters/core-exporter.js
  extras/exporters/gltf-exporter.js
  extras/exporters/usdz-exporter.js
Labels: bug, area: gltf

#4702 Refactoring to remove dependency of WebglGraphicsDevice on shader chunks
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/common/frag/precisionTest.js
  src/graphics/program-lib/chunks/common/frag/precisionTest2.js
  src/graphics/webgl/webgl-graphics-device.js
Labels: enhancement, area: graphics

#4704 Moved /shape folder to /core/shape
  src/core/shape/bounding-box.js
  src/core/shape/bounding-sphere.js
  src/core/shape/frustum.js
  src/core/shape/oriented-box.js
  src/core/shape/plane.js
  src/core/shape/ray.js
  src/deprecated/deprecated.js
  src/framework/components/camera/component.js
  src/framework/components/element/element-drag-helper.js
  src/framework/components/element/text-element.js
  src/framework/components/model/component.js
  src/framework/components/model/system.js
  src/framework/components/render/component.js
  src/framework/components/render/system.js
  src/index.js
  src/input/element-input.js
  src/resources/parser/glb-parser.js
  src/resources/parser/json-model.js
  src/resources/parser/material/json-standard-material.js
  src/scene/batching/batch-manager.js
  src/scene/batching/batch.js
  src/scene/camera.js
  src/scene/lighting/world-clusters.js
  src/scene/lightmapper/bake-light.js
  src/scene/lightmapper/lightmapper.js
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  src/scene/mesh.js
  src/scene/morph-target.js
  src/scene/morph.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
  src/scene/renderer/static-meshes.js
  src/xr/xr-hit-test.js
  src/xr/xr-input-source.js
Labels: enhancement

#4705 Moved /template.js to /framework.template.js
  src/framework/template.js
  src/index.js
  src/resources/template.js
Labels: enhancement

#4706 Moved /script folder to /framework/script
  src/framework/app-base.js
  src/framework/components/script/component.js
  src/framework/script/script-attributes.js
  src/framework/script/script-registry.js
  src/framework/script/script-type.js
  src/framework/script/script.js
  src/index.js
  test/framework/application.test.mjs
  test/framework/entity.test.mjs
  types-fixup.mjs
Labels: enhancement

#4708 Enable lint checks for import statements
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement

#4707 Moved /input folder to /platform/input
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/framework/app-options.js
  src/framework/application.js
  src/framework/components/element/element-drag-helper.js
  src/framework/components/scroll-view/component.js
  src/index.js
  src/platform/input/constants.js
  src/platform/input/controller.js
  src/platform/input/element-input.js
  src/platform/input/game-pads.js
  src/platform/input/keyboard-event.js
  src/platform/input/keyboard.js
  src/platform/input/mouse-event.js
  src/platform/input/mouse.js
  src/platform/input/touch-device.js
  src/platform/input/touch-event.js
Labels: area: input

#4710 Moved /net, /audio and /sound folders to /platform/
  src/asset/asset.js
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/framework/app-options.js
  src/framework/application.js
  src/framework/components/audio-listener/system.js
  src/framework/components/audio-source/component.js
  src/framework/components/audio-source/data.js
  src/framework/components/audio-source/system.js
  src/framework/components/sound/component.js
  src/framework/components/sound/slot.js
  src/framework/components/sound/system.js
  src/index.js
  src/platform/audio/capabilities.js
  src/platform/audio/channel.js
  src/platform/audio/channel3d.js
  src/platform/audio/constants.js
  src/platform/net/http.js
  src/platform/sound/instance.js
  src/platform/sound/instance3d.js
  src/platform/sound/listener.js
  src/platform/sound/manager.js
  src/platform/sound/sound.js
  src/resources/anim-clip.js
  src/resources/anim-state-graph.js
  src/resources/animation.js
  src/resources/audio.js
  src/resources/basis.js
  src/resources/binary.js
  src/resources/bundle.js
  src/resources/css.js
  src/resources/font.js
  src/resources/html.js
  src/resources/json.js
  src/resources/material.js
  src/resources/model.js
  src/resources/parser/glb-parser.js
  src/resources/parser/texture/img.js
  src/resources/scene-utils.js
  src/resources/shader.js
  src/resources/sprite.js
  src/resources/template.js
  src/resources/text.js
  src/resources/texture-atlas.js
  test/asset/asset-registry.test.mjs
  test/net/http.test.mjs
Labels: area: sound, area: audio

#4713 Moved multiple files from /graphics to /scene level
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/index.js
  src/scene/graphics/env-lighting.js
  src/scene/graphics/post-effect.js
  src/scene/graphics/prefilter-cubemap.js
  src/scene/graphics/reproject-texture.js
  src/scene/materials/basic-material.js
  src/scene/materials/material.js
  src/scene/materials/standard-material.js
  src/scene/particle-system/particle-emitter.js
  src/scene/scene.js
  src/scene/shader-lib/get-program-library.js
  src/scene/shader-lib/program-library.js
  src/scene/shader-lib/utils.js
  src/scene/sky.js
Labels: area: graphics

#4717 Move /i18n to /framework/i18n
  src/asset/asset.js
  src/framework/app-base.js
  src/framework/i18n/constants.js
  src/framework/i18n/i18n-parser.js
  src/framework/i18n/i18n.js
  src/framework/i18n/utils.js
  src/index.js
  test/framework/application.test.mjs
Labels: area: localisation

#4718 Move /compress to /scene/compress
  src/resources/parser/scene.js
  src/scene/compress/compress-utils.js
  src/scene/compress/decompress.js
Labels: javascript

#4716 Fix lint issues in types-fixup.mjs
  types-fixup.mjs
Labels: docs

#4719 Moved /asset folder to /framework/asset
  examples/webgpu-temp/index.html
  src/bundles/bundle-registry.js
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/framework/asset/asset-file.js
  src/framework/asset/asset-list-loader.js
  src/framework/asset/asset-localized.js
  src/framework/asset/asset-reference.js
  src/framework/asset/asset-registry.js
  src/framework/asset/asset.js
  src/framework/asset/constants.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/animation/component.js
  src/framework/components/audio-source/component.js
  src/framework/components/button/component.js
  src/framework/components/collision/component.js
  src/framework/components/element/image-element.js
  src/framework/components/element/text-element.js
  src/framework/components/light/component.js
  src/framework/components/model/component.js
  src/framework/components/model/system.js
  src/framework/components/particle-system/component.js
  src/framework/components/particle-system/system.js
  src/framework/components/render/component.js
  src/framework/components/sound/slot.js
  src/framework/components/sprite/component.js
  src/framework/components/sprite/sprite-animation-clip.js
  src/framework/i18n/i18n.js
  src/framework/scene-registry.js
  src/framework/script/script-attributes.js
  src/index.js
  src/resources/cubemap.js
  src/resources/handler.js
  src/resources/loader.js
  src/resources/material.js
  src/resources/parser/glb-container-resource.js
  src/resources/parser/glb-parser.js
  src/resources/parser/texture/basis.js
  src/resources/parser/texture/dds.js
  src/resources/parser/texture/hdr.js
  src/resources/parser/texture/img.js
  src/resources/parser/texture/ktx.js
  src/resources/parser/texture/ktx2.js
  src/resources/texture.js
  src/scene/lightmapper/lightmapper.js
  test/asset/asset-list-loader.test.mjs
  test/asset/asset-localized.test.mjs
  test/asset/asset-registry.test.mjs
  test/asset/asset.test.mjs
  test/framework/application.test.mjs
  test/framework/components/model/component.test.mjs
  test/i18n/i18n.test.mjs
Labels: area: assets

#4720 Move /bundles folder to /framework/bundle
  src/framework/app-base.js
  src/framework/bundle/bundle-registry.js
  src/framework/bundle/bundle.js
  src/index.js
  src/resources/bundle.js
Labels: area: assets

#4725 Move folder /anim to /framework/anim
  src/framework/anim/binder/anim-binder.js
  src/framework/anim/binder/default-anim-binder.js
  src/framework/anim/constants.js
  src/framework/anim/controller/anim-blend-tree-1d.js
  src/framework/anim/controller/anim-blend-tree-2d-cartesian.js
  src/framework/anim/controller/anim-blend-tree-2d-directional.js
  src/framework/anim/controller/anim-blend-tree-direct.js
  src/framework/anim/controller/anim-blend-tree.js
  src/framework/anim/controller/anim-controller.js
  src/framework/anim/controller/anim-node.js
  src/framework/anim/controller/anim-state.js
  src/framework/anim/controller/anim-transition.js
  src/framework/anim/controller/constants.js
  src/framework/anim/evaluator/anim-cache.js
  src/framework/anim/evaluator/anim-clip.js
  src/framework/anim/evaluator/anim-curve.js
  src/framework/anim/evaluator/anim-data.js
  src/framework/anim/evaluator/anim-evaluator.js
  src/framework/anim/evaluator/anim-events.js
  src/framework/anim/evaluator/anim-snapshot.js
  src/framework/anim/evaluator/anim-target-value.js
  src/framework/anim/evaluator/anim-target.js
  src/framework/anim/evaluator/anim-track.js
  src/framework/anim/state-graph/anim-state-graph.js
  src/framework/components/anim/component-binder.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/animation/component.js
  src/framework/handlers/anim-clip.js
  src/framework/handlers/anim-state-graph.js
  src/framework/handlers/animation.js
  src/framework/parsers/glb-parser.js
  src/index.js
  test/anim/controller/anim-blend-tree.test.mjs
  test/anim/controller/anim-controller.test.mjs
  test/anim/controller/anim-node.test.mjs
  test/anim/controller/anim-state.test.mjs
  test/anim/controller/anim-transition.test.mjs
  test/anim/evaluator/anim-cache.test.mjs
  test/anim/evaluator/anim-clip.test.mjs
  test/anim/evaluator/anim-curve.test.mjs
  test/anim/evaluator/anim-data.test.mjs
  test/anim/evaluator/anim-evaluator.test.mjs
  test/anim/evaluator/anim-events.test.mjs
  test/anim/evaluator/anim-snapshot.test.mjs
  test/anim/evaluator/anim-target-value.test.mjs
  test/anim/evaluator/anim-target.test.mjs
  test/anim/evaluator/anim-track.test.mjs
  test/anim/state-graph/anim-state-graph.test.mjs
Labels: area: animation

#4729 Move /font folder to /framework/font
  src/framework/components/element/component.js
  src/framework/components/element/text-element.js
  src/framework/font/canvas-font.js
  src/framework/font/constants.js
  src/framework/font/font.js
  src/framework/handlers/font.js
  src/index.js
Labels: area: ui

#4730 Reorganized index.js to match the new folder structure
  src/index.js
Labels: javascript

#4727 Convert extras to modules
  examples/scripts/iframe/index.mustache
  extras/.eslintrc.js
  extras/exporters/gltf-exporter.js
  extras/exporters/usdz-exporter.js
  extras/mini-stats/cpu-timer.js
  extras/mini-stats/mini-stats.js
  extras/mini-stats/render2d.js
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement

#4733 Fix typo
  examples/scripts/iframe/index.mustache
Labels: bug

#4734 Moved lightmapper from /scene to /framework
  src/framework/app-base.js
  src/framework/app-options.js
  src/framework/application.js
  src/framework/lightmapper/bake-light-ambient.js
  src/framework/lightmapper/bake-light-simple.js
  src/framework/lightmapper/bake-light.js
  src/framework/lightmapper/bake-mesh-node.js
  src/framework/lightmapper/lightmap-filters.js
  src/framework/lightmapper/lightmapper.js
  src/index.js
  src/scene/graphics/lightmap-cache.js
  src/scene/mesh-instance.js
  test/framework/application.test.mjs
Labels: area: graphics

#4735 Moved PROJECTION_*** constants from /scene to /core/shape
  src/core/shape/constants.js
  src/core/shape/frustum.js
  src/deprecated/deprecated.js
  src/framework/lightmapper/lightmapper.js
  src/framework/parsers/glb-parser.js
  src/index.js
  src/scene/camera.js
  src/scene/constants.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/light-camera.js
Labels: javascript

#4736 Cleanup of Entity constructor to remove circular dependency
  src/framework/entity.js
Labels: javascript

#4737 Moved camera related functionality from Frustum to Camera class
  src/core/shape/constants.js
  src/core/shape/frustum.js
  src/deprecated/deprecated.js
  src/framework/lightmapper/lightmapper.js
  src/framework/parsers/glb-parser.js
  src/index.js
  src/scene/camera.js
  src/scene/constants.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/light-camera.js
  src/scene/renderer/shadow-renderer.js
Labels: area: graphics

#4739 [Fix] Switching directional light to a clustered local light works.
  src/scene/layer.js
Labels: bug, area: graphics

#4740 Move picker module from scene to framework
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/framework/graphics/picker.js
  src/framework/graphics/scene-grab.js
  src/index.js
Labels: area: graphics

#4741 Moved platform/input/element-input to /framework/input
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/framework/app-options.js
  src/framework/application.js
  src/framework/components/element/element-drag-helper.js
  src/framework/input/element-input.js
  src/index.js
Labels: area: input

#4743 Remove transmission factor gamma decoding
  src/scene/shader-lib/chunks/standard/frag/transmission.js
Labels: bug, area: graphics

#4744 Remove response type warning from http
  src/platform/net/http.js
Labels: enhancement

#4745 Anim folder circular dependency
  src/framework/anim/evaluator/anim-blend.js
  src/framework/anim/evaluator/anim-evaluator.js
  src/framework/anim/evaluator/anim-target-value.js
Labels: area: animation

#4746 ShaderUtils class to provide common shader creation functionality
  src/deprecated/deprecated.js
  src/platform/graphics/shader-chunks/frag/gles2.js
  src/platform/graphics/shader-chunks/frag/gles3.js
  src/platform/graphics/shader-chunks/frag/webgpu.js
  src/platform/graphics/shader-chunks/vert/gles3.js
  src/platform/graphics/shader-chunks/vert/webgpu.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/transform-feedback.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/programs/common.js
  src/scene/shader-lib/programs/particle.js
  src/scene/shader-lib/programs/skybox.js
  src/scene/shader-lib/utils.js
Labels: enhancement, area: graphics

#4748 Fix cubeMapRotation uniform
  src/scene/materials/standard-material.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
  src/scene/sky.js
Labels: bug, area: graphics

#4752 Switch the Loaders/glb example to use physical units
  examples/src/examples/loaders/glb.tsx
Labels: area: graphics, area: examples

#4753 Shader compilation timing and avoid compilation of unprocessed shaders
  src/core/constants.js
  src/core/tracing.js
  src/platform/graphics/webgl/webgl-shader.js
  src/scene/graphics/reproject-texture.js
  src/scene/shader-lib/program-library.js
  src/scene/shader-lib/utils.js
Labels: performance, area: graphics

#4754 [FIX] Various spelling mistakes
  src/core/preprocessor.js
  src/core/tracing.js
  src/platform/graphics/shader-processor.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-texture.js
  src/scene/frame-graph.js
  src/scene/renderer/forward-renderer.js
Labels: bug, docs

#4756 [FIX] Check docs build with Actions and make fixes
  .github/workflows/ci.yml
  src/platform/graphics/simple-post-effect.js
  src/scene/morph-target.js
Labels: bug, docs

#4750 Add missing material parameters
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/standard/frag/sheenGloss.js
Labels: bug, enhancement, area: graphics

#4765 Return a sensible value for animation component duration if no animation is playing
  src/framework/components/animation/component.js
Labels: bug, area: animation

#4768 Detect glb using file header
  src/framework/components/animation/component.js
  src/framework/parsers/glb-parser.js
Labels: enhancement, area: gltf

#4761 Improvements to clustered lighting shader compilation speed on Windows (DirectX)
  examples/src/examples/graphics/grab-pass.tsx
  src/platform/graphics/shader-chunks/frag/gles2.js
  src/platform/graphics/shader-chunks/frag/gles3.js
  src/platform/graphics/webgl/webgl-shader.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLightShadows.js
  src/scene/shader-lib/chunks/lit/frag/ltc.js
  src/scene/shader-lib/chunks/lit/frag/refractionDynamic.js
  src/scene/shader-lib/chunks/lit/frag/shadowStandard.js
  src/scene/shader-lib/chunks/lit/frag/shadowStandardGL2.js
Labels: performance, area: graphics

#4771 Glb parser: duplicate morph curve fix
  src/framework/parsers/glb-parser.js
Labels: bug, area: animation, area: gltf

#4773 WebGPU rendering improvements for GLB test files
  examples/webgpu-temp/one.html
  examples/webgpu-temp/two.html
  src/platform/graphics/webgpu/webgpu-buffer.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-texture.js
  src/scene/renderer/forward-renderer.js
Labels: bug, area: graphics

#4777 Improvement to vertex attribute types for WebGPU
  src/platform/graphics/webgpu/webgpu-vertex-buffer-layout.js
Labels: area: graphics

#4781 Identify glb header correctly
  src/framework/parsers/glb-parser.js
Labels: bug, area: gltf

#4783 Downscale oversized ImageBitmaps
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgl/webgl-texture.js
Labels: bug, area: graphics

#4785 AnimClip event cursor fix
  src/framework/anim/evaluator/anim-clip.js
  test/framework/anim/evaluator/anim-clip.test.mjs
Labels: bug, area: animation

#4788 Audio resume fix
  src/framework/application.js
  src/platform/sound/manager.js
Labels: bug, area: audio

#4789 Update audio manager suspend
  src/platform/sound/manager.js
Labels: area: audio

#4790 specify normal is swizzled
  examples/src/examples/graphics/texture-basis.tsx
Labels: area: graphics
