Repository playcanvas/engine, pull requests merged in 2022-04, with the labels that each got.

#4153 [FIX] Ensure consistent function return types
  rollup.config.js
  src/anim/controller/anim-controller.js
  src/anim/controller/anim-state.js
  src/framework/app-base.js
  src/framework/components/anim/component.js
  src/framework/components/collision/system.js
  src/framework/components/script-legacy/component.js
  src/framework/components/scroll-view/component.js
  src/framework/components/sound/slot.js
  src/graphics/program-lib/programs/standard.js
  src/graphics/reproject-texture.js
  src/graphics/texture.js
  src/resources/loader.js
  src/resources/texture.js
  src/scene/batching/batch-manager.js
  src/scene/materials/standard-material-options-builder.js
  src/vr/vr-display.js
Labels: bug

#4155 Partial migration to single quotes
  extras/mini-stats/cpu-timer.js
  extras/mini-stats/gpu-timer.js
  extras/mini-stats/graph.js
  extras/mini-stats/mini-stats.js
  extras/mini-stats/render2d.js
  extras/mini-stats/word-atlas.js
  rollup.config.js
  src/animation/animation.js
  src/animation/skeleton.js
  src/asset/asset-localized.js
  src/asset/asset-reference.js
  src/asset/asset-registry.js
  src/asset/asset.js
  src/core/core.js
  src/core/debug.js
  src/core/indexed-list.js
  src/core/path.js
  src/core/platform.js
  src/core/read-stream.js
  src/core/string.js
  src/core/uri.js
  src/deprecated/deprecated.js
  src/font/canvas-font.js
  src/input/constants.js
  src/input/controller.js
  src/input/keyboard.js
  src/input/mouse-event.js
  src/input/mouse.js
  src/math/color.js
  src/net/http.js
  src/script/script-type.js
  src/script/script.js
  src/shape/bounding-box.js
  src/shape/bounding-sphere.js
  src/shape/oriented-box.js
  src/shape/ray.js
  src/vr/vr-display.js
Labels: enhancement

#4165 [FIX] Declare standard material maps as nullable
  types-fixup.mjs
Labels: bug, area: graphics

#4168 Remove firing of redundant `frameEnd` event
  src/framework/app-base.js
Labels: enhancement

#4166 [FIX] Correct type of `AnimClip` eventHandler parameter
  src/anim/evaluator/anim-clip.js
Labels: bug, area: animation

#4171 support different sized env atlas
  src/graphics/env-lighting.js
Labels: enhancement, area: graphics

#4163 Migrate more unit tests from Karma to Node
  test/framework/components/model/component.test.mjs
  test/i18n/i18n.test.mjs
  test/net/http.test.mjs
  test/scene/batching/batch-manager.test.mjs
  test/test-assets/box/1/Box Material.json
  test/test-assets/box/box.json
  test/test-assets/box/box.mapping.json
  test/test-assets/box/src/box.fbx
  test/test-assets/plane/31208636/lambert1.json
  test/test-assets/plane/plane.json
  test/test-assets/plane/plane.mapping.json
  tests/batching/test_batching.js
  tests/i18n/test_i18n.js
  tests/net/test_http.js
Labels: enhancement

#4172 Update env-lighting API and documentation
  src/graphics/env-lighting.js
Labels: area: graphics

#4156 Preprocessor to resolve ifdefs is applied to shader programs
  rollup.config.js
  src/core/debug.js
  src/core/preprocessor.js
  src/graphics/program-lib/chunks/lit/clusteredLight.frag.js
  src/graphics/program-lib/chunks/lit/clusteredLightShadows.frag.js
  src/graphics/webgl/webgl-shader.js
  test/core/preprocessor.test.mjs
Labels: enhancement, area: graphics

#4177 Remove WebVR API support
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/framework/components/camera/component.js
  src/framework/components/camera/system.js
  src/index.js
  src/scene/camera.js
  src/scene/renderer/forward-renderer.js
  src/vr/vr-display.js
  src/vr/vr-manager.js
Labels: area: graphics

#4174 Update `AnimationComponent` to the new component format
  src/animation/skeleton.js
  src/framework/application.js
  src/framework/components/animation/component.js
  src/framework/components/animation/data.js
  src/framework/components/animation/system.js
  types-fixup.mjs
Labels: enhancement, area: animation

#4183 Export AppBase class to allow testing by external applications
  src/index.js
Labels: enhancement

#4186 Also set maxsamples to 1 on broken ios
  src/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#4187 Fix Readme - missing script: build:watch
  examples/README.md
Labels: bug, area: examples

#4191 Simplified glsl
  examples/src/examples/user-interface/custom-shader.tsx
Labels: feature request, area: graphics

#4190 Add constant blend mode and factor
  src/graphics/constants.js
  src/graphics/webgl/webgl-graphics-device.js
Labels: enhancement, area: graphics

#4193 Envatlas mipmap fix
  src/graphics/env-lighting.js
  src/graphics/program-lib/chunks/lit/reflectionEnv.frag.js
Labels: bug, area: graphics

#4188 enable support for retrying loading of container assets
  src/resources/container.js
  src/resources/parser/glb-parser.js
  test/asset/asset-registry.test.mjs
Labels: bug, area: assets, area: gltf

#4203 [Anim Component] Fix for the normalizeWeights property
  src/framework/components/anim/component.js
  src/framework/components/model/component.js
Labels: bug, area: animation

#4207 Destroy XR-DepthSensing texture when Application is destroyed
  src/font/canvas-font.js
  src/framework/app-base.js
  src/framework/components/element/system.js
  src/framework/components/sprite/system.js
  src/framework/scene-depth.js
  src/graphics/env-lighting.js
  src/graphics/prefilter-cubemap.js
  src/graphics/webgl/webgl-graphics-device.js
  src/resources/material.js
  src/resources/parser/texture/dds.js
  src/scene/area-light-luts.js
  src/scene/lightmapper/lightmapper.js
  src/scene/morph.js
  src/scene/particle-system/particle-emitter.js
  src/scene/picker.js
  src/scene/renderer/shadow-map.js
  src/scene/skin-instance.js
  src/xr/xr-depth-sensing.js
  src/xr/xr-manager.js
Labels: area: graphics

#4208 2D UI rendering honors RenderTarget.flipY option
  src/graphics/program-lib/chunks/transform.vert.js
  src/scene/renderer/forward-renderer.js
Labels: bug, area: ui

#4209 Improved vertex color handling for GLB files
  src/resources/parser/glb-parser.js
Labels: bug, area: graphics

#4206 Add fitMode property on Image Elements.
  src/framework/components/element/component.js
  src/framework/components/element/constants.js
  src/framework/components/element/image-element.js
  src/framework/components/element/system.js
  tests/framework/components/element/test_imageelement.js
Labels: area: ui

#4214 Fix tiled nineslice shader error
  src/graphics/program-lib/chunks/lit/base.frag.js
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#4215 Fix for invalid shaders with Ao
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#4217 Add bias version of rgbm helper
  src/graphics/program-lib/chunks/rgbm.frag.js
Labels: area: graphics
