Repository playcanvas/engine, pull requests merged in 2022-05, with the labels that each got.

#4205 Add more JSDoc types
  src/anim/binder/anim-binder.js
  src/framework/app-base.js
  src/framework/components/animation/system.js
  src/framework/components/system.js
Labels: enhancement

#4227 Support depth textures webgl1
  src/graphics/webgl/webgl-render-target.js
  src/graphics/webgl/webgl-texture.js
Labels: enhancement

#4226 chore: Set permissions for GitHub actions
  .github/workflows/ci.yml
Labels: feature request

#4234 Fix pc.SoundInstance end event suspension
  src/sound/instance.js
Labels: bug, area: audio

#4241 Convert stored line endings in repo to LF
  examples/src/examples/user-interface/scroll-view.tsx
  examples/src/examples/user-interface/text-localization.tsx
  examples/src/examples/user-interface/text-typewriter.tsx
  src/animation/animation.js
  src/animation/skeleton.js
  src/audio/channel.js
  src/audio/channel3d.js
  src/framework/components/animation/component.js
  src/framework/components/audio-listener/component.js
  src/framework/components/audio-listener/data.js
  src/framework/components/audio-source/component.js
  src/framework/components/audio-source/data.js
  src/framework/components/camera/data.js
  src/framework/components/camera/system.js
  src/graphics/post-effect.js
  src/graphics/program-lib/programs/basic.js
  src/graphics/program-lib/programs/particle.js
  src/graphics/program-lib/programs/skybox.js
  src/graphics/program-library.js
  src/graphics/vertex-iterator.js
  src/math/quat.js
  src/math/vec2.js
  src/math/vec3.js
  src/math/vec4.js
  src/resources/audio.js
  src/resources/script.js
  src/scene/materials/basic-material.js
  src/scene/mesh.js
  src/scene/skin-partition.js
  src/scene/skin.js
  src/sound/listener.js
  src/sound/manager.js
  src/sound/sound.js
  tests/framework/components/element/test_elementdraghelper.js
  tests/framework/components/element/test_textelement.js
Labels: bug

#4244 Refactored the grab pass and scene depth rendering
  examples/src/examples/graphics/grab-pass.tsx
  src/framework/app-base.js
  src/framework/components/camera/component.js
  src/framework/components/camera/post-effect-queue.js
  src/framework/scene-depth.js
  src/framework/scene-grab.js
  src/graphics/grab-pass.js
  src/graphics/program-lib/chunks/screenDepth.frag.js
  src/graphics/render-target.js
  src/graphics/webgl/webgl-graphics-device.js
  src/scene/layer.js
  src/scene/renderer/forward-renderer.js
Labels: enhancement, performance, area: graphics

#4253 [FIX] Move closing parentheses to the right place
  examples/src/app/helpers/formatters.mjs
Labels: bug, area: examples

#4255 Use script tag for engine in examples
  examples/scripts/example-data.mjs
  examples/scripts/example-directory/index.mjs
  examples/scripts/iframe/index.mjs
  examples/scripts/iframe/index.mustache
  examples/src/app/helpers/read-dir-names.mjs
Labels: area: examples

#4256 Update torus primitive
  examples/src/examples/graphics/lights-baked.tsx
  src/framework/components/model/component.js
  src/framework/components/render/component.js
  src/scene/procedural.js
Labels: enhancement, area: graphics

#4264 Upgrade Examples Browser to PCUI 2.3.1
  examples/package-lock.json
  examples/package.json
  examples/src/app/code-editor.tsx
  examples/src/app/control-panel.tsx
  examples/src/app/example.tsx
  examples/src/app/index.tsx
  examples/src/app/menu.tsx
  examples/src/app/sidebar.tsx
  examples/src/examples/animation/blend-trees-1d.tsx
  examples/src/examples/animation/component-properties.tsx
  examples/src/examples/animation/layer-masks.tsx
  examples/src/examples/animation/locomotion.tsx
  examples/src/examples/graphics/box-reflection.tsx
  examples/src/examples/graphics/clustered-area-lights.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/clustered-spot-shadows.tsx
  examples/src/examples/graphics/ground-fog.tsx
  examples/src/examples/graphics/lights-baked-a-o.tsx
  examples/src/examples/graphics/lights.tsx
  examples/src/examples/graphics/post-effects.tsx
  examples/src/examples/graphics/shadow-cascades.tsx
Labels: enhancement, area: examples

#4270 Remove many `ts-ignore` statements from examples
  examples/src/app/control-panel.tsx
  examples/src/examples/graphics/clustered-area-lights.tsx
  examples/src/examples/graphics/clustered-lighting.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/clustered-spot-shadows.tsx
  examples/src/examples/graphics/ground-fog.tsx
  examples/src/examples/graphics/lights-baked-a-o.tsx
  examples/src/examples/graphics/lights.tsx
  examples/src/examples/misc/spineboy.tsx
  examples/src/examples/user-interface/text-emojis.tsx
  examples/src/examples/user-interface/world-to-screen.tsx
Labels: enhancement, area: examples

#4273 Updated contribution guidelines regarding the enum format
  .github/CONTRIBUTING.md
Labels: docs

#4274 Small refactor to depth layer access to work with multiple applications
  src/framework/components/camera/post-effect-queue.js
Labels: area: graphics

#4272 Basic implementation of RenderPass based architecture
  examples/src/examples/graphics/post-effects.tsx
  rollup.config.js
  scripts/utils/cubemap-renderer.js
  src/core/debug.js
  src/framework/app-base.js
  src/framework/components/camera/component.js
  src/framework/components/camera/post-effect-queue.js
  src/scene/composition/layer-composition.js
  src/scene/composition/render-action.js
  src/scene/frame-graph.js
  src/scene/lightmapper/lightmapper.js
  src/scene/picker.js
  src/scene/render-pass.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
Labels: enhancement, area: graphics

#4285 Return original source if preprocessor fails
  src/core/preprocessor.js
Labels: enhancement, area: graphics

#4286 Remove codeql
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#4283 Fix color mix in the linear fog
  src/graphics/program-lib/chunks/lit/frag/fogLinear.js
Labels: bug, area: graphics

#4276 Update `substr` calls to `substring`
  src/graphics/program-lib/utils.js
  src/graphics/shader-input.js
  src/polyfill/string.js
  src/resources/untar.js
Labels: enhancement
