Repository playcanvas/engine, pull requests merged in 2022-09, with the labels that each got.

#4598 Test for ImageBitmap support at startup
  src/graphics/webgl/webgl-graphics-device.js
  src/graphics/webgpu/webgpu-graphics-device.js
  src/resources/parser/texture/img.js
  src/resources/texture.js
Labels: enhancement, area: graphics

#4601 Output treeshakeable module builds
  package.json
  rollup.config.js
Labels: enhancement

#4585 Physically based camera
  src/framework/components/camera/component.js
  src/framework/components/camera/system.js
  src/scene/camera.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
Labels: enhancement, area: graphics

#4567 Add the XXXMapTint and XXXMapVertexColor to the removed material parameters list
  src/scene/materials/standard-material-parameters.js
Labels: area: graphics

#4617 Use better defaults for physically based camera parameters
  src/framework/components/camera/component.js
  src/scene/camera.js
Labels: enhancement, area: graphics

#4619 Fix sheen glossiness and colour not getting applied correctly
  src/graphics/program-lib/programs/standard.js
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#4629 Fix bug where sheen wasn't appropriately layered
  src/graphics/program-lib/programs/lit-shader.js
Labels: bug, area: graphics

#4630 Fix energy preservation for clear coat
  src/graphics/program-lib/chunks/lit/frag/combine.js
  src/graphics/program-lib/programs/lit-shader.js
Labels: bug, area: graphics

#4631 Fix refraction bug
  src/graphics/program-lib/programs/lit-shader.js
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#4632 Add support for iridescence
  src/graphics/program-lib/chunks/chunks.js
  src/graphics/program-lib/chunks/lit/frag/fresnelSchlick.js
  src/graphics/program-lib/chunks/lit/frag/iridescenceDiffraction.js
  src/graphics/program-lib/chunks/standard/frag/iridescence.js
  src/graphics/program-lib/chunks/standard/frag/iridescenceThickness.js
  src/graphics/program-lib/programs/lit-shader.js
  src/graphics/program-lib/programs/standard.js
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
Labels: enhancement, area: graphics, area: gltf

#4640 Disable use of specularity factor if non-metalness workflow is used.
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#4636 Adds a texture mapping allowing us to combine sampler uniforms
  src/graphics/constants.js
  src/graphics/program-lib/chunks/chunk-validation.js
  src/graphics/program-lib/chunks/standard/frag/ao.js
  src/graphics/program-lib/chunks/standard/frag/clearCoat.js
  src/graphics/program-lib/chunks/standard/frag/clearCoatGloss.js
  src/graphics/program-lib/chunks/standard/frag/clearCoatNormal.js
  src/graphics/program-lib/chunks/standard/frag/diffuse.js
  src/graphics/program-lib/chunks/standard/frag/diffuseDetailMap.js
  src/graphics/program-lib/chunks/standard/frag/emissive.js
  src/graphics/program-lib/chunks/standard/frag/gloss.js
  src/graphics/program-lib/chunks/standard/frag/iridescence.js
  src/graphics/program-lib/chunks/standard/frag/iridescenceThickness.js
  src/graphics/program-lib/chunks/standard/frag/metalness.js
  src/graphics/program-lib/chunks/standard/frag/normalDetailMap.js
  src/graphics/program-lib/chunks/standard/frag/normalMap.js
  src/graphics/program-lib/chunks/standard/frag/opacity.js
  src/graphics/program-lib/chunks/standard/frag/parallax.js
  src/graphics/program-lib/chunks/standard/frag/sheen.js
  src/graphics/program-lib/chunks/standard/frag/sheenGloss.js
  src/graphics/program-lib/chunks/standard/frag/specular.js
  src/graphics/program-lib/chunks/standard/frag/specularityFactor.js
  src/graphics/program-lib/chunks/standard/frag/thickness.js
  src/graphics/program-lib/chunks/standard/frag/transmission.js
  src/graphics/program-lib/programs/standard.js
  src/resources/parser/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
Labels: bug, enhancement, area: graphics

#4646 Lint fixes to UsdzExportExample
  examples/src/examples/loaders/usdz-export.tsx
Labels: docs

#4648 Expose lightmapper chunks
  src/index.js
Labels: area: graphics

#4652 Fix lightmap chunk sampler
  src/graphics/program-lib/chunks/standard/frag/lightmapSingle.js
Labels: bug, area: graphics

#4643 pass area lights LUT directly
  examples/assets/binary/area-light-luts.bin
  examples/assets/json/area-light-luts.json
  examples/src/examples/graphics/area-lights.tsx
  examples/src/examples/graphics/clustered-area-lights.tsx
  src/framework/app-base.js
  src/scene/area-light-luts.js
Labels: enhancement, area: graphics, release: next minor

#4626 Added changeScene API
  src/framework/scene-registry.js
  test/framework/scene-registry.test.mjs
Labels: feature request, release: next minor, area: scripts

#4517 Fixed issue (#3733) that prevents XR from working in certain circumstances
  src/framework/app-base.js
  src/xr/xr-manager.js
Labels: bug, area: xr, release: next minor

#4655 Unset deleted render target
  src/graphics/render-target.js
Labels: bug, area: graphics

#4600 Fix unpacking of msdf markup params
  src/graphics/program-lib/chunks/common/vert/msdf.js
Labels: area: ui, release: next minor

#4657 Clear coat fresnel fix
  src/graphics/program-lib/chunks/lit/frag/combine.js
  src/graphics/program-lib/chunks/lit/frag/fresnelSchlick.js
  src/graphics/program-lib/chunks/lit/frag/reflectionCC.js
  src/graphics/program-lib/chunks/lit/frag/start.js
  src/graphics/program-lib/programs/lit-shader.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#4658 [Fix] Fixed Webgl’s shader handling of lost context
  src/graphics/shader.js
  src/graphics/webgl/webgl-shader.js
  src/graphics/webgpu/webgpu-shader.js
Labels: bug, area: graphics

#4661 Resolve render target before generating mips
  src/graphics/webgl/webgl-graphics-device.js
Labels: enhancement, area: graphics

#4618 Physically based light units
  examples/assets/models/Lights.glb
  examples/src/examples/graphics/index.mjs
  examples/src/examples/graphics/light-physical-units.tsx
  src/framework/app-base.js
  src/framework/components/light/component.js
  src/scene/light.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
  src/scene/sky.js
  types-fixup.mjs
Labels: enhancement, area: graphics, release: next minor, area: gltf

#4663 [Fix] Engine examples readme file specifies how to build the thubmnails
  examples/README.md
Labels: bug, docs, release: next minor

#4664 Fix typo in cloneSkinInstances to avoid double allocations
  src/framework/components/render/component.js
Labels: bug, area: graphics, release: next minor

#4665 GLB parser - check for empty curveData path arrays
  src/resources/parser/glb-parser.js
Labels: bug, area: animation

#4667 Fix screen-space UI not receiving events in AR mode.
  src/input/element-input.js
Labels: bug, area: ui

#4668 Added material tint support for diffuse and emissive to usdz-exporter
  extras/exporters/usdz-exporter.js
Labels: enhancement, area: graphics

#4662 Additional flexibility for Morph targets
  src/resources/container.js
  src/resources/parser/glb-parser.js
  src/scene/mesh-instance.js
  src/scene/morph-instance.js
  src/scene/morph-target.js
  src/scene/morph.js
Labels: enhancement, area: graphics, release: next minor

#4669 Only add the shared sampler if the chunk uses the $SAMPLER macro.
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#4670 Fix chunk decode calls
  src/graphics/program-lib/chunks/standard/frag/diffuse.js
  src/graphics/program-lib/chunks/standard/frag/diffuseDetailMap.js
Labels: bug, area: graphics

#4671 Fix warning for our GLB chunks not using the right API version
  src/resources/parser/glb-parser.js
Labels: bug, area: graphics

#4672 Use prefiltered cubemap format and type
  src/graphics/env-lighting.js
Labels: bug, area: graphics

#3366 Add glTF exporter
  examples/src/examples/loaders/gltf-export.tsx
  examples/src/examples/loaders/index.mjs
  extras/exporters/gltf-exporter.js
  extras/index.js
  src/shape/bounding-box.js
Labels: enhancement, area: graphics

#4679 Small improvements to physical lights units example
  examples/src/examples/graphics/light-physical-units.tsx
Labels: area: examples

#4674 Fix texture sharing change triggering shader build
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#4681 Fix issue with texture sharing not working consistently
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics
