Repository playcanvas/engine, pull requests merged in 2022-01, with the labels that each got.

#3863 Fix typo in `StandardMaterialValidator`
  src/scene/materials/standard-material-validator.js
Labels: bug, area: graphics

#3864 Minor standard.js refactor
  src/graphics/program-lib/programs/standard.js
Labels: bug, area: graphics

#3865 Improve variable scoping for StaticMeshes class
  src/scene/renderer/static-meshes.js
Labels: bug, area: graphics

#3855 Examples lint and spelling fixes
  examples/src/app/code-editor.tsx
  examples/src/app/example-iframe.tsx
  examples/src/app/example.tsx
  examples/src/app/helpers/loader.tsx
  examples/src/app/helpers/raw-file-loading.ts
  examples/src/app/index.tsx
  examples/src/examples/animation/blend-trees-2d-cartesian.tsx
  examples/src/examples/animation/blend-trees-2d-directional.tsx
  examples/src/examples/animation/component-properties.tsx
  examples/src/examples/animation/events.tsx
  examples/src/examples/animation/layer-masks.tsx
  examples/src/examples/animation/locomotion.tsx
  examples/src/examples/camera/first-person.tsx
  examples/src/examples/graphics/area-lights.tsx
  examples/src/examples/graphics/area-picker.tsx
  examples/src/examples/graphics/batching-dynamic.tsx
  examples/src/examples/graphics/clustered-area-lights.tsx
  examples/src/examples/graphics/clustered-lighting.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/clustered-spot-shadows.tsx
  examples/src/examples/graphics/grab-pass.tsx
  examples/src/examples/graphics/hardware-instancing.tsx
  examples/src/examples/graphics/hierarchy.tsx
  examples/src/examples/graphics/lights-baked-ao.tsx
  examples/src/examples/graphics/mesh-decals.tsx
  examples/src/examples/graphics/mesh-generation.tsx
  examples/src/examples/graphics/mesh-morph-many.tsx
  examples/src/examples/graphics/mesh-morph.tsx
  examples/src/examples/graphics/model-outline.tsx
  examples/src/examples/graphics/painter.tsx
  examples/src/examples/graphics/particles-anim-index.tsx
  examples/src/examples/graphics/point-cloud-simulation.tsx
  examples/src/examples/graphics/portal.tsx
  examples/src/examples/graphics/post-effects.tsx
  examples/src/examples/graphics/render-cubemap.tsx
  examples/src/examples/graphics/transform-feedback.tsx
  examples/src/examples/loaders/drc.tsx
  examples/src/examples/loaders/glb.tsx
  examples/src/examples/misc/mini-stats.tsx
  examples/src/examples/physics/falling-shapes.tsx
  examples/src/examples/user-interface/custom-shader.tsx
  examples/src/examples/user-interface/scroll-view.tsx
  examples/src/examples/xr/ar-basic.tsx
  examples/src/examples/xr/ar-hit-test.tsx
  examples/src/examples/xr/vr-basic.tsx
  examples/src/examples/xr/vr-controllers.tsx
  examples/src/examples/xr/vr-hands.tsx
  examples/src/examples/xr/vr-movement.tsx
  examples/src/examples/xr/xr-picking.tsx
Labels: bug, area: examples

#3867 Correctly named the class in box-reflection example
  examples/src/examples/graphics/box-reflection.tsx
Labels: bug, area: examples

#3869 Small updates to documentation text
  src/core/indexed-list.js
  src/graphics/vertex-buffer.js
Labels: docs

#3871 Fix spelling mistakes in GlbContainerResource
  src/resources/parser/glb-container-resource.js
Labels: bug, area: assets

#3873 Debug rendering of world clusters (clustered lighting)
  examples/src/examples/graphics/clustered-area-lights.tsx
  examples/src/examples/graphics/clustered-lighting.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/clustered-spot-shadows.tsx
  rollup.config.js
  src/scene/light.js
  src/scene/lighting/lighting-params.js
  src/scene/lighting/world-clusters-debug.js
  src/scene/lighting/world-clusters.js
  src/scene/renderer/forward-renderer.js
  src/shape/bounding-box.js
Labels: enhancement, area: graphics

#3875 Render target limits number of samples to supported maximum
  examples/src/examples/graphics/render-to-texture.tsx
  src/graphics/graphics-device.js
  src/graphics/render-target.js
Labels: bug, area: graphics

#3874 [Fix] Improved handling of the ownership of Morph by Mesh
  examples/src/examples/graphics/mesh-morph.tsx
  src/scene/mesh.js
Labels: bug, area: graphics

#3879 Fix call to `Array#concat` in `_findTransition`
  src/anim/controller/anim-controller.js
Labels: bug, area: animation

#3881 Misc fixes
  scripts/parsers/obj-model.js
  src/framework/components/anim/system.js
  src/framework/components/element/text-element.js
  src/framework/components/layout-group/layout-calculator.js
Labels: bug

#3882 Fix types for nullable return values
  src/asset/asset.js
  src/core/indexed-list.js
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/model/component.js
  src/framework/components/script/component.js
  src/framework/components/sound/component.js
  src/framework/components/sound/system.js
  src/framework/entity.js
  src/framework/scene-registry.js
  src/input/touch-event.js
  src/scene/batching/batch-manager.js
  src/scene/composition/layer-composition.js
  src/scene/graph-node.js
  src/script/script.js
  src/shape/bounding-sphere.js
  src/sound/instance.js
  src/xr/xr-image-tracking.js
Labels: bug

#3887 Fix calling `Keyboard#detach` twice
  src/input/keyboard.js
Labels: bug, area: input

#3891 Small refactor to StandardMaterial#chunks
  src/scene/materials/standard-material.js
Labels: enhancement, area: graphics

#3890 Fix shift out of range
  src/math/math.js
  test/math/math.test.mjs
Labels: enhancement

#3892 [AnimComponent] Transition bug fix
  src/anim/controller/anim-controller.js
Labels: area: animation

#3885 [Fix] Fix the way Immediate class was using visible list
  src/scene/immediate/immediate.js
Labels: bug, area: graphics

#3893 Move deprecated properties out of standard-material.js
  src/deprecated/deprecated.js
  src/scene/materials/standard-material.js
Labels: enhancement, area: graphics

#3896 Add test for null url in container loader
  src/resources/container.js
Labels: bug

#3895 Smart atlas slot distribution for clustered light shadows and cookies
  examples/src/examples/graphics/clustered-spot-shadows.tsx
  src/scene/camera.js
  src/scene/light.js
  src/scene/lighting/light-texture-atlas.js
  src/scene/lighting/lighting-params.js
  src/scene/lighting/lights-buffer.js
  src/scene/lighting/world-clusters.js
  src/scene/renderer/cookie-renderer.js
  src/scene/renderer/forward-renderer.js
Labels: enhancement, area: graphics

#3898 Refactor material cloning and add new public API for material copying
  src/scene/materials/basic-material.js
  src/scene/materials/depth-material.js
  src/scene/materials/material.js
  src/scene/materials/standard-material.js
  test/scene/materials/basic-material.test.mjs
  test/scene/materials/depth-material.test.mjs
  test/scene/materials/material.test.mjs
  test/scene/materials/standard-material.test.mjs
Labels: bug, enhancement, area: graphics

#3900 More Mat4 and Quat unit tests
  README-ja.md
  README-zh.md
  README.md
  test/README.md
  test/math/mat4.test.mjs
  test/math/quat.test.mjs
  test/scene/graph-node.test.mjs
  tests/math/test_mat4.js
  tests/math/test_quat.js
Labels: enhancement

#3903 Remove `Object.defineProperty` from `SoundComponent`
  src/framework/components/component.js
  src/framework/components/sound/component.js
Labels: enhancement

#3904 Device validates VBs and IBs are valid when rendering
  src/graphics/graphics-device.js
Labels: docs

#3902 Lightmapper is compatible with clustered light mode
  src/framework/components/light/component.js
  src/graphics/program-lib/chunks/clusteredLight.frag.js
  src/graphics/program-lib/programs/standard.js
  src/scene/constants.js
  src/scene/light.js
  src/scene/lighting/lights-buffer.js
  src/scene/lighting/world-clusters.js
  src/scene/lightmapper/bake-light.js
  src/scene/lightmapper/lightmapper.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/mesh-instance.js
  src/scene/renderer/forward-renderer.js
Labels: feature request, area: graphics

#3907 Delete call to `events.attach` for `ComponentSystem`
  src/framework/components/system.js
Labels: bug

#3908 Simplify LayoutGroupComponent initialization
  src/framework/components/layout-group/component.js
  src/framework/components/layout-group/system.js
Labels: enhancement, area: ui

#3909 [Fix] Change order of updates to fix some issues with lightmapper when using clustered lighting
  src/scene/lightmapper/lightmapper.js
Labels: bug, area: graphics

#3910 LayerComposition's constructor no longer requires device as a parameter
  src/framework/application.js
  src/scene/composition/layer-composition.js
  src/scene/renderer/forward-renderer.js
  src/scene/scene.js
Labels: enhancement, area: graphics

#3912 Restore `StandardMaterial#reset`
  src/scene/materials/standard-material.js
Labels: area: graphics

#3911 Remove `Object.defineProperty` from `LayoutChildComponent`
  src/framework/components/layout-child/component.js
  src/framework/components/layout-group/component.js
Labels: enhancement, area: ui

#3914 Fix XR JSDoc type tags
  src/xr/constants.js
Labels: bug, area: xr

#3919 Improve IntelliSense for some core classes
  src/core/debug.js
  src/core/ref-counted-cache.js
  src/core/ref-counted-object.js
  src/scene/mesh-instance.js
  src/scene/mesh.js
  src/scene/morph-instance.js
  src/scene/render.js
  src/scene/skin-instance-cache.js
Labels: enhancement

#3923 [Fix] Clustered lights don't support VSM filtering
  src/scene/renderer/shadow-renderer.js
Labels: bug, area: graphics

#3920 Improve various JSDoc blocks and unit tests
  src/audio/channel.js
  src/audio/channel3d.js
  src/core/tags.js
  src/math/curve-evaluator.js
  src/math/curve-set.js
  src/math/curve.js
  src/math/float-packing.js
  src/scene/graph-node.js
  test/scene/graph-node.test.mjs
  tests/scene/test_graphnode.js
Labels: enhancement, area: graphics

#3925 Refactored part of Debug class to DebugGraphics class
  rollup.config.js
  src/core/debug.js
  src/framework/components/camera/post-effect-queue.js
  src/graphics/debug-graphics.js
  src/graphics/env-lighting.js
  src/graphics/grab-pass.js
  src/graphics/reproject-texture.js
  src/graphics/simple-post-effect.js
  src/graphics/transform-feedback.js
  src/scene/lightmapper/lightmapper.js
  src/scene/morph-instance.js
  src/scene/particle-system/gpu-updater.js
  src/scene/renderer/cookie-renderer.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: docs, area: graphics

#3928 [FIX] Correctly convert 2 spaces to tabs for extras
  rollup.config.js
Labels: bug

#3931 fix cubemap rotation flag
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#3932 Standard shader ignores clustered light options when generating shaders
  src/graphics/program-lib/programs/standard.js
Labels: performance, area: graphics

#3782 Expand the public Anim Component API
  examples/src/examples/animation/layer-masks.tsx
  src/framework/components/anim/component-layer.js
  src/framework/components/anim/component.js
  src/framework/components/anim/system.js
Labels: docs, area: animation

#3935 Add script to generate a module treemap visualization
  .github/workflows/ci.yml
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement

#3937 Deprecated constants are now hidden from JSDoc
  src/math/constants.js
  src/scene/constants.js
Labels: docs

#3938 Combine ES5 and ES5 minified build configs
  package.json
  rollup.config.js
Labels: enhancement

#3940 GraphicsDevice uses 'high-performance' power preference by default
  src/graphics/graphics-device.js
Labels: performance, area: graphics

#3941 Use Rollup to bundle TypeScript declarations
  .github/workflows/ci.yml
  package-lock.json
  package.json
  rollup.config.js
  tsd.js
  types.mjs
Labels: enhancement

#3950 Added null check on the mesh before getting the graphics device on material#destroy
  src/scene/materials/material.js
Labels: bug, area: assets

#3929 Internal Ammo variables are initialized when Ammo loads
  src/framework/components/rigid-body/component.js
  src/framework/components/rigid-body/system.js
Labels: area: physics, release: next minor

#3953 Remove debug warning in `GraphNode#removeChild`
  src/scene/graph-node.js
Labels: bug

#3946 Add missing properties to TypeScript declarations
  examples/src/examples/graphics/render-asset.tsx
  src/framework/components/button/component.js
  src/framework/components/camera/component.js
  src/framework/components/element/component.js
  src/framework/components/light/component.js
  src/framework/entity.js
  src/scene/graph-node.js
  src/scene/materials/standard-material.js
  src/script/script-type.js
  types.mjs
Labels: bug, release: next minor

#3955 IBL aliasing fix
  src/graphics/program-lib/chunks/reflectionEnv.frag.js
Labels: bug, area: graphics

#3956 Remove many `@ts-ignore` statements from examples
  examples/src/examples/animation/blend-trees-2d-cartesian.tsx
  examples/src/examples/animation/blend-trees-2d-directional.tsx
  examples/src/examples/animation/component-properties.tsx
  examples/src/examples/animation/events.tsx
  examples/src/examples/animation/locomotion.tsx
  examples/src/examples/animation/tween.tsx
  examples/src/examples/graphics/area-picker.tsx
  examples/src/examples/graphics/layers.tsx
  examples/src/examples/graphics/mesh-morph-many.tsx
  examples/src/examples/graphics/mesh-morph.tsx
  examples/src/examples/graphics/model-outline.tsx
  examples/src/examples/graphics/render-cubemap.tsx
  examples/src/examples/graphics/render-to-texture.tsx
  examples/src/examples/graphics/shader-burn.tsx
  examples/src/examples/graphics/shader-toon.tsx
  examples/src/examples/graphics/shader-wobble.tsx
  examples/src/examples/graphics/texture-basis.tsx
  examples/src/examples/loaders/obj.tsx
  examples/src/examples/physics/falling-shapes.tsx
  examples/src/examples/physics/raycast.tsx
  examples/src/examples/xr/vr-movement.tsx
  examples/src/examples/xr/xr-picking.tsx
  src/framework/components/registry.js
Labels: bug, area: examples

#3961 Improve graphics-related JSDoc blocks
  src/graphics/grab-pass.js
  src/graphics/graphics-device.js
  src/graphics/index-buffer.js
  src/graphics/post-effect.js
  src/graphics/program-lib/utils.js
  src/graphics/render-target.js
  src/graphics/scope-space.js
  src/graphics/shader-input.js
  src/graphics/shader.js
  src/graphics/texture.js
  src/graphics/vertex-buffer.js
  src/graphics/vertex-format.js
  src/graphics/vertex-iterator.js
Labels: enhancement, docs, area: graphics

#3962 Enable IntelliSense for WebGL API
  src/graphics/graphics-device.js
  src/graphics/reproject-texture.js
Labels: enhancement, area: graphics

#3964 Type fixes for viewer
  src/net/http.js
  src/scene/mesh.js
Labels: bug

#3781 Update the AnimStateGraph class documentation
  src/anim/state-graph/anim-state-graph.js
Labels: docs, area: animation, release: next minor

#3784 [AnimComponent] Setting the activateStateCurrentTime property works when paused
  src/anim/controller/anim-controller.js
  src/framework/components/anim/component-layer.js
Labels: enhancement, area: animation, release: next minor

#3965 Anim state graph docs
  src/anim/state-graph/anim-state-graph.js
Labels: docs, area: animation

#3934 Anim component public api expansion follow up
  src/framework/components/anim/component-layer.js
Labels: docs, area: animation, release: next minor

#3780 Make the AnimTrack class public
  src/anim/evaluator/anim-curve.js
  src/anim/evaluator/anim-data.js
  src/anim/evaluator/anim-track.js
Labels: docs, area: animation, release: next minor

#3966 Updated JS Docs Template version to include the Discord link in the header
  package-lock.json
  package.json
Labels: feature request, docs
