Repository playcanvas/engine, pull requests merged in 2023-06, with the labels that each got.

#5362 MRT support for WebGL 1
  src/platform/graphics/shader-chunks/frag/gles2.js
  src/platform/graphics/shader-chunks/frag/gles3.js
  src/platform/graphics/shader-chunks/frag/webgpu.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-render-target.js
Labels: feature request, area: graphics

#5334 [Examples] Build update
  .github/workflows/ci.yml
  examples/README.md
  examples/package-lock.json
  examples/package.json
  examples/rollup.config.js
  examples/scripts/iframe/index.mjs
  examples/src/app/code-editor.tsx
  examples/src/app/control-panel.tsx
  examples/src/app/example.tsx
  examples/src/app/helpers/example-data.mjs
  examples/src/app/index.tsx
  examples/src/app/sidebar.tsx
  examples/src/examples/animation/blend-trees-2d-cartesian.tsx
  examples/src/examples/animation/blend-trees-2d-directional.tsx
  examples/src/iframe/index.html
  examples/src/iframe/index.mjs
Labels: area: examples

#5366 WebGPU handles texture filtering and addressing property changes
  src/platform/graphics/bind-group.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: area: graphics

#5363 Fix import of prettier
  examples/scripts/example-data.mjs
Labels: bug

#5369 Expanded Texture class by handling of WebGPU functionality
  src/platform/graphics/graphics-device.js
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics

#5368 Remove no longer compatible handling of deprecated parameter by RigidBody.raycastFirst
  src/framework/components/rigid-body/system.js
Labels: bug, area: physics

#5370 Initial setup to support compressed texture on WebGPU
  examples/src/examples/graphics/texture-basis.tsx
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: area: graphics

#5372 Improvements to Texture implementation of cubemaps for WebGPU
  examples/src/examples/graphics/reflection-cubemap.tsx
  src/platform/graphics/texture-utils.js
  src/platform/graphics/texture.js
  src/platform/graphics/webgpu/webgpu-mipmap-renderer.js
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: area: graphics

#5373 [Examples] iframe sourcemaps
  examples/README.md
  examples/package.json
  examples/rollup.config.js
  examples/src/iframe/index.mjs
Labels: area: examples

#5375 [Examples] Use debug engine in development mode
  examples/rollup.config.js
Labels: area: examples

#5343 Issue : Render Target Size (width and height) is reset to the graphic…
  src/framework/components/camera/post-effect-queue.js
Labels: bug, area: graphics, open source contribution

#5386 Improvements to texture export functionality to handle compressed textures
  extras/exporters/core-exporter.js
  extras/exporters/gltf-exporter.js
  extras/exporters/usdz-exporter.js
Labels: area: graphics, area: gltf

#5388 Shadow shader fix
  src/scene/shader-lib/chunks/lit/frag/clusteredLightShadows.js
Labels: bug, area: graphics

#5389 Reset sky when envAtlas changes
  src/scene/scene.js
Labels: bug, area: graphics

#5390 Prefiltered lighting fixes
  src/scene/materials/lit-options.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/scene.js
  src/scene/shader-lib/chunks/lit/frag/reflectionEnvHQ.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5391 Fix light size default value
  src/framework/components/light/component.js
  src/scene/light.js
Labels: bug, area: graphics

#5359 Support disabling specular highlights from directional lights
  src/framework/components/light/component.js
  src/scene/light.js
  src/scene/shader-lib/programs/lit-shader.js
  types-fixup.mjs
Labels: area: graphics

#5395 Do not declare MRT shader ouputs over the specified number
  src/platform/graphics/shader-chunks/frag/gles2.js
  src/platform/graphics/shader-chunks/frag/gles3.js
  src/platform/graphics/shader-utils.js
Labels: bug, area: graphics

#5396 Fix to recently introduced error related to postprocessing on a camera with RT
  src/framework/components/camera/post-effect-queue.js
Labels: bug, area: graphics

#5401 AnimBlendTree fix
  src/framework/anim/controller/anim-controller.js
  src/framework/components/anim/component.js
Labels: bug, area: animation

#5402 Fix to depth-grab pass on WebGl1
  src/scene/graphics/scene-grab.js
Labels: area: graphics

#5403 Fix PCSS with WebGL1
  src/scene/shader-lib/chunks/lit/frag/shadowPCSS.js
Labels: bug, area: graphics

#5404 [Fix] Define pc_fragColor in all cases
  src/platform/graphics/shader-chunks/frag/gles2.js
  src/platform/graphics/shader-chunks/frag/gles3.js
Labels: bug, area: graphics

#5405 Env bugfix
  src/scene/scene.js
Labels: area: graphics

#5407 Examples es5 build fix
  examples/rollup.config.js
  examples/src/iframe/index.mjs
  examples/src/iframe/pc-es5.mjs
  examples/src/iframe/pc-es6.mjs
Labels: bug, area: examples

#5410 [Fix] ReflectionPlanar example uses existing envAtlas
  examples/src/examples/graphics/reflection-planar.tsx
Labels: bug, area: examples

#5412 Additional envAtlas fixes
  src/framework/handlers/loader.js
  src/scene/scene.js
Labels: bug, area: graphics

#5416 Additional per camera uniforms added to the view bind group
  src/platform/graphics/constants.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
Labels: area: graphics

#5417 Disable normal bias with VSM
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5418 Support for powerPreference option for WebGPU
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics

#5419 Delete cache entry when setting null value
  src/framework/handlers/loader.js
Labels: area: assets

#5421 Change behaviour of lightSize
  examples/src/examples/graphics/contact-hardening-shadows.tsx
  src/framework/components/light/component.js
  src/scene/light.js
  src/scene/renderer/forward-renderer.js
  src/scene/shader-lib/chunks/lit/frag/shadowPCSS.js
  src/scene/shader-lib/chunks/standard/frag/litShaderArgs.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5425 Simplify the normal offset shadow coordinate method for clustered point lights
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLightShadows.js
Labels: area: graphics

#5414 Fix `Entity#destroy`
  src/framework/components/model/component.js
  src/framework/entity.js
  src/framework/scene-registry.js
  src/scene/graph-node.js
Labels: open source contribution

#5423 Updated the way WebGPU submits command buffers for rendering
  src/core/constants.js
  src/framework/app-base.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-buffer.js
  src/platform/graphics/webgpu/webgpu-clear-renderer.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-mipmap-renderer.js
  src/platform/graphics/webgpu/webgpu-texture.js
  src/scene/graphics/quad-render-utils.js
Labels: area: graphics

#5426 [Anim Component] Fix exit time conditions for non looping animations
  src/framework/anim/controller/anim-controller.js
Labels: bug, area: animation

#5427 Removed no longer needed temporarily WebGPU test code
  examples/webgpu-temp/assets/skinned-mesh-anim.glb
  examples/webgpu-temp/assets/skinned-mesh.glb
  examples/webgpu-temp/four.html
  examples/webgpu-temp/one.html
  examples/webgpu-temp/three.html
  examples/webgpu-temp/two.html
Labels: area: examples

#5429 Fix directional light not fading out with only a single cascade.
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5432 Fix point light shadows missing float packing
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5430 Fix comment for cascaded shadows
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5433 Fix float unpacking
  src/scene/shader-lib/chunks/lit/frag/shadowStandard.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5434 Correctly render textures using drawTexture
  src/framework/app-base.js
Labels: bug, area: graphics

#5435 Fix to drawDepthTexture to not rendered flipped
  src/framework/app-base.js
Labels: bug, area: graphics

#5436 Flip debug depth texture rendering in examples
  examples/src/examples/graphics/ground-fog.tsx
  examples/src/examples/graphics/post-effects.tsx
Labels: bug, area: graphics

#5439 [Examples Browser] Thumbnail generation fix
  examples/README.md
  examples/scripts/thumbnails.mjs
  examples/src/iframe/index.html
Labels: bug, area: examples

#5438 Bump allocation for Uniform Buffers on WebGPU
  package.json
  src/platform/graphics/bind-group.js
  src/platform/graphics/dynamic-buffers.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/texture.js
  src/platform/graphics/uniform-buffer.js
  src/platform/graphics/webgpu/webgpu-bind-group-format.js
  src/platform/graphics/webgpu/webgpu-bind-group.js
  src/platform/graphics/webgpu/webgpu-clear-renderer.js
  src/platform/graphics/webgpu/webgpu-dynamic-buffer.js
  src/platform/graphics/webgpu/webgpu-dynamic-buffers.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-texture.js
  src/scene/graphics/quad-render-utils.js
  src/scene/graphics/quad-render.js
  src/scene/mesh-instance.js
  src/scene/renderer/renderer.js
Labels: feature request, area: graphics

#5443 [Fix] Do not dispatch local lights when clustered lighting is enabled
  src/scene/renderer/forward-renderer.js
Labels: bug, area: graphics

#5442 Morph: fix options handling and targets validation
  src/scene/morph.js
Labels: bug, area: graphics

#5447 [Examples Browser] Engine sourcemaps fix
  examples/package-lock.json
  examples/package.json
  examples/rollup.config.js
Labels: bug, area: examples

#5448 Export TextureUtils.
  src/index.js
Labels: bug

#5446 Fix omni light shadows with PCSS and clustered
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5449 Update webgpu types package to latest version
  package-lock.json
  package.json
Labels: area: graphics

#5451 Don't write to FragDepth unless depth value is modified
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics
