Repository playcanvas/engine, pull requests merged in 2023-02, with the labels that each got.

#5021 Updated texture reprojection to work on WebGPU
  examples/src/examples/graphics/box-reflection.tsx
  examples/src/examples/graphics/material-basic.tsx
  examples/src/examples/graphics/render-cubemap.tsx
  src/platform/graphics/bind-group.js
  src/platform/graphics/shader-chunks/frag/webgpu.js
  src/platform/graphics/shader-processor.js
  src/scene/graphics/reproject-texture.js
  src/scene/shader-lib/chunks/common/frag/reproject.js
  src/scene/shader-lib/chunks/lit/frag/cubeMapProjectBox.js
Labels: area: graphics, area: examples

#5022 Multiple engine examples are converted to use createGraphicsDevice function
  examples/src/examples/graphics/area-lights.tsx
  examples/src/examples/graphics/area-picker.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/hierarchy.tsx
  examples/src/examples/graphics/layers.tsx
  examples/src/examples/graphics/lights-baked-a-o.tsx
  examples/src/examples/graphics/lights-baked.tsx
  examples/src/examples/graphics/material-anisotropic.tsx
  examples/src/examples/graphics/material-clear-coat.tsx
  examples/src/examples/graphics/material-physical.tsx
  examples/src/examples/graphics/material-translucent-specular.tsx
  examples/src/examples/graphics/mesh-decals.tsx
  examples/src/examples/graphics/mesh-generation.tsx
  examples/src/examples/graphics/model-asset.tsx
  examples/src/examples/graphics/model-textured-box.tsx
Labels: area: graphics, area: examples

#4954 Ignore custom .npmrc
  .gitignore
Labels: dependencies

#5025 Tint compiler updated to newer version
  examples/src/lib/twgsl/twgsl.wasm
Labels: area: graphics

#5026 Improved shadow cascades for WebGPU
  examples/src/examples/graphics/shadow-cascades.tsx
  src/platform/graphics/constants.js
  src/platform/graphics/uniform-buffer-format.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, area: examples

#5028 Add support for building the API reference with Typedoc
  package-lock.json
  package.json
  tsconfig.json
Labels: docs

#5029 Add types for WebGPU
  jsconfig.json
  package-lock.json
  package.json
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-texture.js
  tsconfig.json
Labels: area: graphics

#5030 Include WebGPU support in all built targets
  src/index.js
  src/platform/graphics/graphics-device-create.js
Labels: area: graphics

#5020 Fix gravity test
  src/framework/components/rigid-body/system.js
Labels: bug, area: physics

#5032 Fix warnings from Typedoc build
  package.json
  src/core/string.js
  src/framework/asset/asset-list-loader.js
  src/framework/components/light/component.js
  src/framework/entity.js
  src/framework/script/script.js
  src/platform/graphics/shader.js
  src/platform/input/touch-event.js
  src/scene/graph-node.js
Labels: bug, docs

#5031 Updated codebase to properly use WebGPU types
  src/platform/graphics/webgpu/webgpu-bind-group-format.js
  src/platform/graphics/webgpu/webgpu-bind-group.js
  src/platform/graphics/webgpu/webgpu-buffer.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/platform/graphics/webgpu/webgpu-render-target.js
  src/platform/graphics/webgpu/webgpu-vertex-buffer-layout.js
Labels: area: graphics

#5034 Add MDN links to Typedocs for browser APIs
  package-lock.json
  package.json
Labels: docs

#5035 Optimize createMorphTargetCurves
  src/framework/parsers/glb-parser.js
Labels: performance, area: animation

#5038 Fix many issues with API reference links
  src/framework/anim/constants.js
  src/framework/app-base.js
  src/framework/application.js
  src/framework/components/audio-listener/system.js
  src/framework/components/sound/system.js
  src/platform/graphics/graphics-device-create.js
  src/platform/input/mouse.js
  src/platform/input/touch-event.js
  src/scene/composition/layer-composition.js
  src/scene/mesh-instance.js
Labels: bug, docs

#5037 Optimize texture upload of morph targets
  src/scene/morph.js
Labels: performance, area: graphics

#5041 Switch Material to use field declarations
  src/scene/materials/material.js
Labels: docs

#5045 [Fix] Fix to the way morph weight name is looked up
  src/framework/parsers/glb-parser.js
Labels: area: animation

#5046 Added Container asset option skipMeshes, to ignore mesh loading from glb
  src/framework/handlers/container.js
  src/framework/parsers/glb-parser.js
Labels: area: gltf

#5047 Fix ao vertex colors
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#5048 Added a validation check on RenderComponent.meshInstances
  src/framework/components/render/component.js
Labels: area: graphics

#5053 [Fix] Delete old property when the new one already exists
  src/framework/parsers/material/json-standard-material.js
Labels: bug, area: graphics

#5056 Element internally uses tristrip instead of trifan to render quad, as trifan is not supported by WebGPU
  src/framework/components/element/image-element.js
Labels: area: graphics, area: ui

#5059 Updated all UI examples to use createGraphicsDevice function
  examples/src/examples/user-interface/button-basic.tsx
  examples/src/examples/user-interface/button-sprite.tsx
  examples/src/examples/user-interface/custom-shader.tsx
  examples/src/examples/user-interface/layout-group.tsx
  examples/src/examples/user-interface/particle-system.tsx
  examples/src/examples/user-interface/scroll-view.tsx
  examples/src/examples/user-interface/text-auto-font-size.tsx
  examples/src/examples/user-interface/text-emojis.tsx
  examples/src/examples/user-interface/text-localization.tsx
  examples/src/examples/user-interface/text-typewriter.tsx
  examples/src/examples/user-interface/text.tsx
  examples/src/examples/user-interface/world-to-screen.tsx
  examples/src/examples/user-interface/world-ui.tsx
Labels: area: examples

#5050 WebGPU support for int and uint vertex attributes
  src/platform/graphics/shader-processor-options.js
  src/platform/graphics/shader-processor.js
  src/platform/graphics/uniform-buffer-format.js
  src/platform/graphics/webgpu/webgpu-vertex-buffer-layout.js
  src/scene/materials/basic-material.js
  src/scene/materials/material.js
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  src/scene/shader-lib/chunks/common/vert/skinTex.js
Labels: area: graphics

#5060 Updated createGraphicsDevice with easier way to create WebGL1 device
  examples/src/examples/graphics/box-reflection.tsx
  examples/webgpu-temp/four.html
  examples/webgpu-temp/one.html
  examples/webgpu-temp/three.html
  examples/webgpu-temp/two.html
  src/platform/graphics/constants.js
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/vertex-format.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/frame-graph.js
  src/scene/graphics/quad-render-utils.js
  src/scene/graphics/scene-grab.js
  src/scene/renderer/renderer.js
  src/scene/renderer/shadow-map.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5051 Limit number of ‘ignored import property on standard material` warnings
  src/scene/materials/standard-material-validator.js
Labels: area: graphics

#5054 Further field declaration updates
  src/core/object-pool.js
  src/scene/batching/batch-group.js
  src/scene/batching/batch.js
  src/scene/graphics/post-effect.js
  src/scene/lighting/lighting-params.js
  src/scene/materials/lit-options.js
  src/scene/materials/material.js
  src/scene/materials/standard-material-options.js
  src/scene/scene.js
  src/scene/stencil-parameters.js
Labels: bug, docs

#5062 Input engine examples use createGraphicsDevice function
  examples/src/examples/input/gamepad.tsx
  examples/src/examples/input/keyboard.tsx
  examples/src/examples/input/mouse.tsx
Labels: area: examples

#5064 Fix extra 'ing' in property names
  src/platform/graphics/vertex-format.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-vertex-buffer-layout.js
Labels: bug, area: graphics

#5066 Fix another occurrence of inging
  src/platform/graphics/shader-processor-options.js
Labels: bug

#5058 Assert when required dependencies for LayoutGroup component are missing
  src/framework/components/layout-group/component.js
Labels: area: ui

#5057 Added dummy stencil functions for WebGPU to avoid crashes
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
Labels: area: graphics

#5063 WebXR - Fixed bug where the wrong number of views is being added
  src/framework/xr/xr-manager.js
Labels: bug, area: xr

#5068 Parameters for Object.assign in setXrProperties was wrong
  src/scene/camera.js
Labels: bug, area: xr

#5069 Warn and block Entity transform when Dynamic Rigid Body present
  src/framework/components/rigid-body/component.js
  src/scene/graph-node.js
Labels: bug, area: physics

#5070 Refactor `CameraComponent`
  src/framework/components/camera/component.js
  types-fixup.mjs
Labels: docs, area: graphics

#5071 BitPacking functionality
  src/core/math/bit-packing.js
  test/core/math/bit-packing.test.mjs
Labels: feature request

#5081 Only log error related to nested render passes once on WebGL
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: area: graphics

#5077 Fix the destroy callback in Bloom
  scripts/posteffects/posteffect-bloom.js
Labels: bug, area: graphics

#5088 [Fix] Adding early out for clustered lights to fix performance regression
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
Labels: performance, area: graphics

#5090 Add types to standard shader options to highlight their incorrect use
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/standard.js
Labels: docs

#5092 [Fix] Fix ParticleComponent documentation: ‘blend’ should be ‘blendType’
  src/framework/components/particle-system/component.js
Labels: bug, docs, area: particles

#5093 Use highp samplers for clustered light data to avoid precision issues on some devices
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
Labels: bug, area: graphics

#5094 Fix typo with lightMapVertexColors and refer to proper frontend option.
  src/scene/shader-lib/programs/standard.js
Labels: bug, area: graphics

#5099 Added convenience functions in SoundComponent
  src/framework/components/sound/component.js
Labels: feature request, release: next minor, area: audio

#5083 [BREAKING] Implementation of BlendState
  extras/mini-stats/render2d.js
  src/deprecated/deprecated.js
  src/framework/graphics/picker.js
  src/framework/lightmapper/lightmapper.js
  src/index.js
  src/platform/graphics/blend-state.js
  src/platform/graphics/constants.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/platform/graphics/webgpu/webgpu-render-state.js
  src/scene/graphics/post-effect.js
  src/scene/graphics/prefilter-cubemap.js
  src/scene/graphics/quad-render-utils.js
  src/scene/graphics/reproject-texture.js
  src/scene/graphics/scene-grab.js
  src/scene/materials/material.js
  src/scene/morph-instance.js
  src/scene/particle-system/gpu-updater.js
  src/scene/renderer/cookie-renderer.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
  test/platform/graphics/blend-state.test.mjs
Labels: area: graphics

#5100 Function RenderPass.execute is now optional
  src/platform/graphics/render-pass.js
Labels: area: graphics

#5103 Convert local light shadow rendering to use render passes
  src/framework/lightmapper/lightmapper.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer-local.js
Labels: area: graphics

#5110 Added Debug.gpuError to log out gpu validation errors in debug mode
  rollup.config.mjs
  src/core/debug.js
Labels: area: graphics

#5111 Added couple of additional GPU markers to forward renderer
  src/scene/renderer/forward-renderer.js
Labels: area: graphics
