Repository playcanvas/engine, pull requests merged in 2023-05, with the labels that each got.

#5291 Glb async loading
  src/framework/handlers/animation.js
  src/framework/handlers/container.js
  src/framework/handlers/model.js
  src/framework/handlers/texture.js
  src/framework/parsers/draco-decoder.js
  src/framework/parsers/glb-container-parser.js
  src/framework/parsers/glb-model.js
  src/framework/parsers/glb-parser.js
  src/framework/parsers/json-model.js
Labels: performance, area: gltf

#5300 Examples load envLighting without mipmaps
  examples/src/examples/animation/blend-trees-1d.tsx
  examples/src/examples/animation/blend-trees-2d-cartesian.tsx
  examples/src/examples/animation/blend-trees-2d-directional.tsx
  examples/src/examples/animation/events.tsx
  examples/src/examples/animation/layer-masks.tsx
  examples/src/examples/animation/locomotion.tsx
  examples/src/examples/graphics/area-lights.tsx
  examples/src/examples/graphics/area-picker.tsx
  examples/src/examples/graphics/asset-viewer.tsx
  examples/src/examples/graphics/ground-fog.tsx
  examples/src/examples/graphics/hardware-instancing.tsx
  examples/src/examples/graphics/light-physical-units.tsx
  examples/src/examples/graphics/lights-baked-a-o.tsx
  examples/src/examples/graphics/lines.tsx
  examples/src/examples/graphics/material-clear-coat.tsx
  examples/src/examples/graphics/material-physical.tsx
  examples/src/examples/graphics/material-translucent-specular.tsx
  examples/src/examples/graphics/mesh-deformation.tsx
  examples/src/examples/graphics/mesh-morph-many.tsx
  examples/src/examples/graphics/multi-view.tsx
  examples/src/examples/graphics/portal.tsx
  examples/src/examples/graphics/post-effects.tsx
  examples/src/examples/graphics/reflection-cubemap.tsx
  examples/src/examples/graphics/render-asset.tsx
  examples/src/examples/graphics/render-to-texture.tsx
  examples/src/examples/graphics/shader-compile.tsx
  examples/src/examples/graphics/shadow-cascades.tsx
  examples/src/examples/input/gamepad.tsx
  examples/src/examples/input/keyboard.tsx
  examples/src/examples/input/mouse.tsx
  examples/src/examples/loaders/gltf-export.tsx
  examples/src/examples/loaders/usdz-export.tsx
  examples/src/examples/physics/offset-collision.tsx
  examples/src/examples/physics/vehicle.tsx
Labels: area: graphics

#5298 WebGPU device now supports clustered omni light shadows
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/lights.tsx
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/platform/graphics/webgpu/webgpu-texture.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5299 Faster wireframe gen
  src/scene/mesh.js
Labels: area: graphics

#5301 Small fixes to WebGPU rendering to cubemap with mipmaps
  examples/src/examples/graphics/reflection-cubemap.tsx
  src/platform/graphics/webgpu/webgpu-render-target.js
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: area: graphics

#5302 Renamed disabled debug mode “Normal” to “None” to avoid confusion with WorldNormals
  examples/src/examples/graphics/multi-view.tsx
Labels: area: examples

#5305 [Examples Browser] Add overflow scroll bars into the examples browser
  examples/src/static/styles.css
Labels: area: examples

#5306 Update to draco v1.5.6
  examples/src/lib/draco/draco.js
  examples/src/lib/draco/draco.wasm.js
  examples/src/lib/draco/draco.wasm.wasm
Labels: area: graphics

#5308 Test for optional draco config
  src/framework/parsers/draco-decoder.js
Labels: bug

#5310 Fix for gltf unlit materials
  src/framework/parsers/glb-parser.js
Labels: bug, area: gltf

#5312 Downgrade draco assert to warning
  src/framework/parsers/glb-parser.js
Labels: area: gltf

#5315 Fix model loading
  src/framework/handlers/model.js
Labels: bug, area: gltf

#5316 Calculate draco indices
  src/framework/parsers/glb-parser.js
Labels: bug, area: gltf

#5320 Build with join
  src/framework/parsers/draco-decoder.js
Labels: bug

#5319 Update to vertex format handling and morphing on WebGPU
  examples/assets/models/morph-stress-test.glb
  examples/assets/models/morph-stress-test.txt
  examples/src/examples/graphics/mesh-morph-many.tsx
  src/platform/graphics/shader-chunks/vert/webgpu.js
  src/platform/graphics/shader-processor.js
  src/platform/graphics/webgpu/webgpu-buffer.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-mipmap-renderer.js
  src/platform/graphics/webgpu/webgpu-vertex-buffer-layout.js
  src/scene/morph.js
  src/scene/shader-lib/chunks/common/vert/transform.js
  src/scene/shader-lib/chunks/lit/vert/normal.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5321 Fixed incorrect indentation in normal.js chunk
  src/scene/shader-lib/chunks/lit/vert/normal.js
Labels: area: graphics

#5106 Fix memory leak on mesh collider destroy
  src/framework/components/collision/system.js
Labels: bug, area: physics, open source contribution

#5325 Draco url fix
  src/framework/parsers/draco-decoder.js
Labels: area: graphics

#5328 Give ministats consistent screen size
  extras/mini-stats/render2d.js
Labels: bug, area: graphics

#5330 Add support for PCF1 to directional / spot lights
  examples/src/examples/graphics/shadow-cascades.tsx
  src/scene/light.js
  src/scene/renderer/shadow-map.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/chunks/lit/frag/shadowStandard.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, area: examples

#5333 Refactor the shadow sampling coordinate code
  src/scene/renderer/forward-renderer.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/biasConst.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLightShadows.js
  src/scene/shader-lib/chunks/lit/frag/shadowCommon.js
  src/scene/shader-lib/chunks/lit/frag/shadowCoord.js
  src/scene/shader-lib/chunks/lit/frag/shadowCoordPerspZbuffer.js
  src/scene/shader-lib/chunks/lit/frag/shadowEVSM.js
  src/scene/shader-lib/chunks/lit/frag/shadowEVSMn.js
  src/scene/shader-lib/chunks/lit/frag/shadowSampleCoord.js
  src/scene/shader-lib/chunks/lit/frag/shadowStandard.js
  src/scene/shader-lib/chunks/lit/frag/shadowStandardGL2.js
  src/scene/shader-lib/chunks/lit/frag/shadowVSM8.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5335 Fix for PCF1 filtering of shadows
  src/scene/shader-lib/chunks/lit/frag/shadowStandard.js
Labels: area: graphics

#5270 AO Detail Map
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/standard/frag/ao.js
  src/scene/shader-lib/chunks/standard/frag/aoDetailMap.js
  src/scene/shader-lib/programs/standard.js
  test/scene/materials/standard-material.test.mjs
  types-fixup.mjs
Labels: feature request, area: graphics, open source contribution

#5337 PCF shadows webgpu fix
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5336 Initial MRT implementation for WebGPU
  examples/src/examples/graphics/index.mjs
  examples/src/examples/graphics/mrt.tsx
  examples/src/examples/graphics/reflection-planar.tsx
  src/platform/graphics/graphics-device.js
  src/platform/graphics/render-pass.js
  src/platform/graphics/render-target.js
  src/platform/graphics/shader-chunks/frag/webgpu.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/platform/graphics/webgpu/webgpu-render-target.js
  src/scene/frame-graph.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/output.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5345 Fix for multiple non clustered lights
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5346 Order draco vertex attributes correctly
  src/framework/parsers/draco-decoder.js
  src/framework/parsers/draco-worker.js
  src/framework/parsers/glb-parser.js
Labels: bug, area: gltf

#5349 createGraphicsDevice defaults options.xrCompatible to true
  src/platform/graphics/graphics-device-create.js
Labels: bug, area: graphics

#5350 Import types for JSDocs
  src/core/math/random.js
  src/framework/anim/controller/anim-blend-tree-1d.js
  src/framework/anim/controller/anim-blend-tree.js
  src/framework/anim/controller/anim-node.js
  src/framework/anim/controller/anim-state.js
  src/framework/components/button/component.js
  src/framework/components/collision/component.js
  src/framework/components/collision/trigger.js
  src/framework/components/element/component.js
  src/framework/components/model/component.js
  src/framework/components/sound/slot.js
  src/framework/components/sprite/component.js
  src/framework/xr/xr-hit-test-source.js
  src/framework/xr/xr-hit-test.js
  src/platform/sound/manager.js
  src/scene/compress/compress-utils.js
  src/scene/layer.js
  src/scene/scene.js
  src/scene/shader-pass.js
Labels: bug

#5351 Various @link and JSDoc type fixes
  src/core/shape/plane.js
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/graphics-device.js
  src/platform/input/mouse-event.js
  src/platform/input/mouse.js
  src/scene/materials/lit-options.js
  src/scene/materials/material.js
  src/scene/mesh-instance.js
Labels: bug, docs

#5360 Gltf parser supports EXT_texture_webp
  src/framework/parsers/glb-parser.js
Labels: area: gltf

#5353 MRT support for WebGL2
  examples/src/examples/graphics/mrt.tsx
  src/platform/graphics/graphics-device.js
  src/platform/graphics/shader-chunks/frag/gles2.js
  src/platform/graphics/shader-chunks/frag/gles3.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-render-target.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: feature request, area: graphics

#5358 Debug logging of textures with their sizes in vram
  src/core/constants.js
  src/core/tracing.js
  src/platform/graphics/graphics-device.js
Labels: feature request, area: graphics
