Repository playcanvas/engine, pull requests merged in 2023-08, with the labels that each got.

#5531 [Examples] Created a shared ignoreList for examples
  examples/scripts/example-data.mjs
  examples/scripts/example-directory/index.mjs
  examples/scripts/thumbnails.mjs
  examples/src/app/helpers/read-dir.mjs
  examples/src/examples/graphics/index.mjs
Labels: area: examples

#5494 Provide `litArgs` backwards compatibility
  src/deprecated/deprecated.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5533 Fix to the LitShader compatibility handling
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5534 Set ior when metalness is used
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#5550 [Fix] Avoid additional shaders creation caused by out of order lights
  src/platform/graphics/shader-processor-options.js
  src/scene/composition/layer-composition.js
  src/scene/shader-lib/program-library.js
  src/scene/shader-lib/programs/lit-options-utils.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/standard.js
Labels: bug, area: graphics

#5557 Fix some consistent-return lint errors
  src/framework/components/element/component.js
  src/framework/handlers/basis-worker.js
  src/framework/handlers/font.js
  src/framework/handlers/texture-atlas.js
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug

#5540 Layer composition does not maintain list of shadow casters per light
  src/framework/lightmapper/lightmapper.js
  src/scene/composition/layer-composition.js
  src/scene/composition/light-composition-data.js
  src/scene/layer.js
  src/scene/renderer/renderer.js
  src/scene/renderer/shadow-renderer-directional.js
  src/scene/renderer/shadow-renderer-local.js
  src/scene/renderer/shadow-renderer.js
Labels: performance, area: graphics

#5560 fix(examples): remove duplicate npm parameter
  examples/package.json
Labels: bug

#5562 GltfExporter supports BasicMaterial
  examples/src/examples/loaders/gltf-export.tsx
  extras/exporters/gltf-exporter.js
Labels: bug, area: gltf

#5563 NullGraphicsDevice implementation allowing to run the application without rendering
  examples/src/app/example.tsx
  examples/src/iframe/index.html
  src/index.js
  src/platform/graphics/constants.js
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/null/null-graphics-device.js
  src/platform/graphics/null/null-index-buffer.js
  src/platform/graphics/null/null-render-target.js
  src/platform/graphics/null/null-shader.js
  src/platform/graphics/null/null-texture.js
  src/platform/graphics/null/null-vertex-buffer.js
  src/scene/graphics/scene-grab.js
Labels: feature request, area: graphics

#5564 [Fix] Fix few shader chunks using removed IridescenceArgs struct
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/lit/frag/fresnelSchlick.js
  src/scene/shader-lib/chunks/lit/frag/iridescenceDiffraction.js
  src/scene/shader-lib/chunks/lit/frag/lightmapAdd.js
  src/scene/shader-lib/chunks/lit/frag/lightmapDirAdd.js
  src/scene/shader-lib/chunks/lit/frag/refractionCube.js
  src/scene/shader-lib/chunks/lit/frag/refractionDynamic.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5565 Fix to lightmapper when no baking lights
  src/framework/lightmapper/lightmapper.js
Labels: bug, area: graphics

#5566 JSDoc: Remove redundant default param values
  src/core/math/curve-evaluator.js
  src/core/math/mat4.js
  src/core/math/quat.js
  src/framework/components/sound/component.js
  src/framework/components/sound/slot.js
  src/platform/audio/channel.js
  src/platform/audio/channel3d.js
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/sound/instance.js
  src/platform/sound/instance3d.js
  src/scene/graph-node.js
  src/scene/layer.js
Labels: docs

#5568 JSDoc: Modernize some blocks
  src/framework/app-base.js
  src/framework/handlers/scene-utils.js
  src/scene/compress/compress-utils.js
  src/scene/constants.js
  src/scene/shader-lib/chunks/chunks.js
Labels: docs

#5569 WorldClusters allocation is now dynamic, removed from composition update
  src/framework/lightmapper/lightmapper.js
  src/scene/composition/layer-composition.js
  src/scene/composition/render-action.js
  src/scene/layer.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
  src/scene/renderer/world-clusters-allocator.js
Labels: area: graphics

#5570 Refactored and fixed the lightcube lighting for particle emitters
  src/framework/components/particle-system/system.js
  src/scene/graphics/light-cube.js
  src/scene/layer.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
Labels: bug, area: graphics

#5571 Remove unneeded indirection using light indices
  src/scene/composition/render-action.js
  src/scene/renderer/renderer.js
Labels: area: graphics

#5552 Shader generators are converted to modules
  src/deprecated/deprecated.js
  src/scene/shader-lib/program-library.js
  src/scene/shader-lib/programs/basic.js
  src/scene/shader-lib/programs/common.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/particle.js
  src/scene/shader-lib/programs/shader-generator.js
  src/scene/shader-lib/programs/skybox.js
  src/scene/shader-lib/programs/standard.js
  src/scene/shader-lib/utils.js
Labels: area: graphics

#5576 Improvement to light sorting when layer light hash is generated
  src/scene/layer.js
Labels: area: graphics

#5582 Refactor shader caching to handle mesh instance on layers with different lights
  src/deprecated/deprecated.js
  src/scene/materials/basic-material.js
  src/scene/materials/material.js
  src/scene/mesh-instance.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: area: graphics

#5583 Handle case of gl.getSupportedExtrentions returning null
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#5584 [Fix] Fix the Picker not restoring transparency flag
  src/framework/graphics/picker.js
Labels: bug, area: graphics

#5592 Refactored the way LightComponent changes notify the LayerComposition
  src/framework/components/light/component.js
  src/framework/components/light/system.js
  src/scene/layer.js
  src/scene/light.js
Labels: area: graphics

#5593 Refactored shadow casting directional lights collection
  src/scene/composition/layer-composition.js
  src/scene/composition/render-action.js
  src/scene/layer.js
  src/scene/light.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
  src/scene/renderer/shadow-renderer-directional.js
Labels: area: graphics

#5596 fix(docs): remove {{TYPE-ERROR}} warning
  src/scene/layer.js
Labels: bug, docs

#5597 [Fix] Make sure the non-clustered shadow allocates shadow map even when not rendered
  src/scene/renderer/renderer.js
Labels: bug, area: graphics

#5598 [Fix] Handle missing clusteredLightingEnabled in render settings
  src/scene/scene.js
Labels: bug, area: graphics

#5600 chore(examples): update playcanvas-spine.3.8.js
  scripts/spine/playcanvas-spine.3.8.js
Labels: bug, area: examples
