Repository playcanvas/engine, pull requests merged in 2023-01, with the labels that each got.

#4949 Add standard material invert for gloss channels
  examples/src/examples/graphics/material-clear-coat.tsx
  src/deprecated/deprecated.js
  src/framework/parsers/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-options.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/standard/frag/clearCoatGloss.js
  src/scene/shader-lib/chunks/standard/frag/gloss.js
  src/scene/shader-lib/chunks/standard/frag/sheenGloss.js
  src/scene/shader-lib/programs/standard.js
  test/scene/materials/standard-material.test.mjs
  types-fixup.mjs
Labels: bug, area: graphics

#4955 [Fix] Fix to light options processing causing clustered shaders compilation when lights change
  src/scene/shader-lib/programs/standard.js
Labels: bug, area: graphics

#4956 [Fix] Fix null access caused in clustered light code when no meshes use lights
  src/scene/composition/layer-composition.js
Labels: bug, area: graphics

#4959 Fix a few small material bits
  src/framework/parsers/glb-parser.js
  src/scene/materials/standard-material-parameters.js
Labels: area: graphics

#4960 Moved compiled shader cache from device to DeviceCache instance
  src/platform/graphics/device-cache.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-shader.js
  src/scene/shader-lib/program-library.js
Labels: area: graphics

#4962 Rename material uniform glossiness to gloss
  src/framework/parsers/glb-parser.js
  src/platform/graphics/constants.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/standard/frag/clearCoatGloss.js
  src/scene/shader-lib/chunks/standard/frag/gloss.js
  src/scene/shader-lib/chunks/standard/frag/sheenGloss.js
Labels: area: graphics

#4961 Fix light conservation also affecting ambient (diffuse) light.
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#4940 [BREAKING] UI Scroll Views now work in XR
  src/framework/components/element/element-drag-helper.js
  src/framework/input/element-input.js
Labels: release: next minor

#4967 Load old material glossiness correctly
  src/framework/parsers/material/json-standard-material.js
Labels: bug, area: graphics

#4968 Remove energy conservation for ambient light when using the phong model.
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#4972 [Fix] Fix to non-clustered omni shadow rendering
  examples/src/examples/graphics/lights.tsx
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/renderer/renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: bug, area: graphics

#4974 Examples browser dependency update
  examples/package-lock.json
  examples/package.json
  examples/scripts/iframe/index.mustache
  examples/src/app/code-editor.tsx
  examples/src/app/index.tsx
  examples/src/app/sidebar.tsx
  examples/src/examples/animation/blend-trees-1d.tsx
  examples/src/examples/animation/layer-masks.tsx
  examples/src/examples/animation/locomotion.tsx
  examples/src/examples/graphics/box-reflection.tsx
  examples/src/examples/graphics/clustered-area-lights.tsx
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  examples/src/examples/graphics/clustered-spot-shadows.tsx
  examples/src/examples/graphics/ground-fog.tsx
  examples/src/examples/graphics/light-physical-units.tsx
  examples/src/examples/graphics/lights-baked-a-o.tsx
  examples/src/examples/graphics/lights.tsx
  examples/src/examples/graphics/post-effects.tsx
  examples/src/examples/graphics/shadow-cascades.tsx
Labels: dependencies, area: examples

#4976 [Examples Browser] Build with local PCUI
  examples/package-lock.json
  examples/package.json
  examples/rollup.config.js
Labels: area: examples

#4977 Small docs fix for XrDomOverlay
  src/framework/xr/xr-dom-overlay.js
Labels: bug, docs, area: xr

#4980 [Fix] Fixed code examples for calculateTangents and calculateNormals
  src/scene/procedural.js
Labels: bug

#4964 Update to WebGL shader compilation and linking
  src/platform/graphics/device-cache.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-shader.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: performance, area: graphics

#4981 Shader*** examples updated to use createGraphicsDevice
  examples/src/examples/graphics/shader-burn.tsx
  examples/src/examples/graphics/shader-toon.tsx
  examples/src/examples/graphics/shader-wobble.tsx
Labels: area: examples

#4925 Plane/Ray add copy/clone methods + prefer ownership over references
  src/core/shape/plane.js
  src/core/shape/ray.js
Labels: feature request

#4983 [Fix] Fix to Grab-pass engine example on WebGL1
  examples/src/examples/graphics/grab-pass.tsx
Labels: area: examples

#4984 Added attributes parameter to createShaderFromCode
  examples/src/examples/graphics/shader-burn.tsx
  examples/src/examples/graphics/shader-toon.tsx
  examples/src/examples/graphics/shader-wobble.tsx
  src/platform/graphics/webgl/webgl-shader.js
  src/scene/graphics/reproject-texture.js
  src/scene/renderer/forward-renderer.js
  src/scene/shader-lib/utils.js
Labels: area: graphics, area: examples

#4985 Fix shadow map using vertex normals.
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#4986 Sparse accessor fix
  src/framework/parsers/glb-parser.js
Labels: bug, area: gltf

#4988 [Breaking] Quad render class, drawQuadWithShader refactor, Camera render events moved.
  examples/webgpu-temp/one.html
  src/deprecated/deprecated.js
  src/framework/lightmapper/lightmapper.js
  src/index.js
  src/platform/graphics/constants.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/render-pass.js
  src/platform/graphics/shader-processor-options.js
  src/platform/graphics/shader-processor.js
  src/platform/graphics/simple-post-effect.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-state.js
  src/platform/graphics/webgpu/webgpu-shader.js
  src/scene/graphics/post-effect.js
  src/scene/graphics/prefilter-cubemap.js
  src/scene/graphics/quad-render-utils.js
  src/scene/graphics/quad-render.js
  src/scene/graphics/reproject-texture.js
  src/scene/materials/material.js
  src/scene/morph-instance.js
  src/scene/particle-system/gpu-updater.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/cookie-renderer.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer-directional.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/program-library.js
  src/scene/shader-lib/utils.js
Labels: area: graphics

#4989 Texture based morphing support for WebGPU
  examples/src/examples/animation/blend-trees-1d.tsx
  examples/src/examples/graphics/mesh-morph-many.tsx
  examples/src/examples/graphics/mesh-morph.tsx
  src/platform/graphics/shader-chunks/frag/shared.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/platform/graphics/webgpu/webgpu-texture.js
  src/scene/morph-instance.js
  src/scene/morph.js
  src/scene/shader-lib/chunks/common/vert/transform.js
Labels: area: graphics

#4990 Exclude area lights LTC shader chunk if clustered area lights are disabled
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: performance, area: graphics

#4991 Clustered light cookie textures works on WebGPU
  src/platform/graphics/shader-chunks/frag/gles2.js
  src/platform/graphics/shader-chunks/frag/gles3.js
  src/platform/graphics/shader-chunks/frag/webgpu.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLightCookies.js
Labels: performance, area: graphics

#4992 Small polish to the ClusteredSpotShadows example
  examples/src/examples/graphics/clustered-spot-shadows.tsx
Labels: area: examples

#4994 Deprecated property: Layer.renderTarget
  src/deprecated/deprecated.js
  src/scene/layer.js
Labels: area: graphics

#4997 Improved documentation for Shader creation
  src/platform/graphics/shader.js
  src/scene/shader-lib/utils.js
Labels: docs

#4998 Fixed Camera Component API docs for scissorRect
  src/framework/components/camera/component.js
Labels: bug, docs

#4996 Smaller PostEffect refactor and simplification, WebGPU support
  scripts/posteffects/posteffect-outline.js
  src/deprecated/deprecated.js
  src/index.js
  src/scene/graphics/post-effect.js
Labels: area: graphics

#5000 ShaderCompile engine example to be used as a test for shader compilation speed
  examples/src/examples/graphics/index.mjs
  examples/src/examples/graphics/shader-compile.tsx
Labels: area: examples

#5002 Refactor all remaining posteffects to use drawQuad + simpler shader creation
  scripts/posteffects/posteffect-blend.js
  scripts/posteffects/posteffect-bloom.js
  scripts/posteffects/posteffect-bokeh.js
  scripts/posteffects/posteffect-brightnesscontrast.js
  scripts/posteffects/posteffect-edgedetect.js
  scripts/posteffects/posteffect-fxaa.js
  scripts/posteffects/posteffect-horizontaltiltshift.js
  scripts/posteffects/posteffect-huesaturation.js
  scripts/posteffects/posteffect-luminosity.js
  scripts/posteffects/posteffect-sepia.js
  scripts/posteffects/posteffect-ssao.js
  scripts/posteffects/posteffect-verticaltiltshift.js
  scripts/posteffects/posteffect-vignette.js
Labels: area: graphics

#5004 Updates to make PostEffects example working on WebGPU
  examples/src/examples/graphics/post-effects.tsx
  scripts/posteffects/posteffect-bloom.js
  scripts/posteffects/posteffect-ssao.js
  src/platform/graphics/bind-group.js
Labels: area: graphics

#4999 Added public API notes for the container resource
  src/framework/handlers/container.js
Labels: docs

#5008 Fix for draco vertex colors, which are stored as 16 bit for some reason
  src/framework/parsers/glb-parser.js
Labels: bug, area: gltf

#5010 Examples browser dependency upgrade
  examples/package-lock.json
  examples/package.json
Labels: dependencies, area: examples

#5005 Rearanged members of ClusterLightData structure to eliminate padding
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
Labels: area: graphics

#4837 Use hardware device properties (fov) when in XR
  src/framework/xr/xr-manager.js
  src/scene/camera.js
Labels: bug, area: xr, release: next minor

#5014 Variable rename in the clustered lighting shader to avoid the use of reserved word
  src/platform/graphics/webgpu/webgpu-texture.js
  src/scene/lighting/world-clusters.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
Labels: area: graphics

#5015 Transpile WebGPU SpirV shaders into WGSL
  examples/src/lib/twgsl/twgsl.js
  examples/src/lib/twgsl/twgsl.wasm
  examples/webgpu-temp/four.html
  examples/webgpu-temp/one.html
  examples/webgpu-temp/three.html
  examples/webgpu-temp/two.html
  package.json
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-shader.js
Labels: area: graphics

#5016 Update basis initialisation to work with facebook games
  src/framework/handlers/basis-worker.js
  src/framework/handlers/basis.js
Labels: bug, area: graphics
