Repository playcanvas/engine, pull requests merged in 2023-04, with the labels that each got.

#5233 WebGL device support passing in gl context
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: area: graphics

#5239 Check for ior 0
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#5238 Replaced debug logging of the Element component by Tracing
  src/core/constants.js
  src/framework/components/element/component.js
  src/framework/components/element/image-element.js
Labels: area: ui

#5241 sound currentTime needs to be called before state change
  src/platform/sound/instance.js
Labels: bug, release: next patch, area: audio

#5235 Disable ImageBitmap in Safari
  src/framework/parsers/texture/img-alpha-test.js
  src/framework/parsers/texture/img.js
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: area: graphics

#5243 StencilParameters support on WebGPU
  examples/src/examples/graphics/portal.tsx
  examples/src/examples/user-interface/scroll-view.tsx
  extras/mini-stats/render2d.js
  src/framework/components/element/component.js
  src/framework/components/element/image-element.js
  src/framework/lightmapper/lightmapper.js
  src/index.js
  src/platform/graphics/constants.js
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/stencil-parameters.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/scene/graphics/quad-render-utils.js
  src/scene/materials/material.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
  src/scene/stencil-parameters.js
  test/scene/materials/material.test.mjs
Labels: area: graphics

#5248 Fixed bug where raycast filter tags caused exception
  src/framework/components/rigid-body/system.js
Labels: bug, area: physics, release: next patch

#5250 Fixed PCF1 clustered shadow shader compile error
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
Labels: bug, area: graphics, release: next patch

#5254 Revert "Warn and block Entity transform when Dynamic Rigid Body present (#5069)"
  src/framework/components/rigid-body/component.js
  src/scene/graph-node.js
Labels: bug, release: next patch

#5257 Fixed a typo in a warning message about missing color texture.
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: docs

#5256 Refactor of private ShaderPass class to be dynamic instead of hardcoded
  src/deprecated/deprecated.js
  src/index.js
  src/scene/constants.js
  src/scene/materials/lit-options.js
  src/scene/materials/standard-material-options.js
  src/scene/materials/standard-material.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/program-library.js
  src/scene/shader-lib/programs/basic.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/standard.js
  src/scene/shader-pass.js
  src/scene/sky.js
Labels: area: graphics

#5260 Clean up event listeners on anim clip destroy
  src/framework/components/sprite/sprite-animation-clip.js
Labels: bug, area: sprites

#5255 Disable GPU particles on Mali G52 due to rendering artifacts
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, release: next patch, area: particles

#5261 Debug shader output functionality
  examples/src/examples/graphics/multi-view.tsx
  src/framework/components/camera/component.js
  src/scene/camera.js
  src/scene/constants.js
  src/scene/renderer/forward-renderer.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/debug-output.js
  src/scene/shader-lib/chunks/lit/frag/debug-process-frontend.js
  src/scene/shader-lib/programs/basic.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-pass.js
Labels: area: graphics

#5267 Generate define for each varying variable in standard fragment shader
  src/scene/shader-lib/chunks/lit/frag/debug-process-frontend.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5272 Add null check before unbinding events sprite animation clip
  src/framework/components/sprite/sprite-animation-clip.js
Labels: bug, release: next patch, area: sprites

#5288 [Fix] Apply VMS blur to spot lights when clustered lighting is off
  src/scene/renderer/shadow-renderer-directional.js
  src/scene/renderer/shadow-renderer-local.js
  src/scene/renderer/shadow-renderer.js
Labels: bug, area: graphics

#5109 Remove Material Asset on Material change
  src/framework/components/element/image-element.js
Labels: bug, area: ui

#5277 Limit allowed samples on WebGPU when using multisampled render target
  src/platform/graphics/render-target.js
Labels: area: graphics

#5289 Improved trace information for render pipeline allocation
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
Labels: area: graphics

#5290 WebGPU device correctly initializes ‘supportsStencil’
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics

#5292 Improvements to texture upload / cubemap support on WebGPU
  examples/src/examples/graphics/clustered-omni-shadows.tsx
  src/core/debug.js
  src/framework/handlers/cubemap.js
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/webgpu-mipmap-renderer.js
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: area: graphics
