Repository playcanvas/engine, pull requests merged in 2023-12, with the labels that each got.

#5871 Depth bias support for WebGPU and refactor to add it to the DepthState
  examples/src/examples/graphics/mesh-decals.mjs
  src/framework/components/light/system.js
  src/platform/graphics/depth-state.js
  src/platform/graphics/null/null-graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/scene/light.js
  src/scene/materials/material.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/render-pass-render-actions.js
  src/scene/renderer/shadow-renderer.js
Labels: feature request, area: graphics

#5791 WebXR Mesh Detection
  examples/src/examples/xr/ar-mesh-detection.mjs
  examples/src/examples/xr/index.mjs
  src/framework/xr/xr-manager.js
  src/framework/xr/xr-mesh-detection.js
  src/framework/xr/xr-mesh.js
Labels: feature request, area: xr

#5873 [Examples] Fix build time getting progressively slower
  examples/rollup.config.js
  rollup.config.mjs
  utils/rollup-build-target.mjs
  utils/rollup-es5-options.mjs
  utils/rollup-get-banner.mjs
  utils/rollup-module-options.mjs
  utils/rollup-script-target-es6.mjs
  utils/rollup-script-target.mjs
  utils/rollup-version-revision.mjs
Labels: feature request

#5877 [Fix] Fix compatibility with deprecated Layer.renderTarget
  src/scene/renderer/renderer.js
Labels: bug, area: graphics

#5879 XrAnchors - Availability flag
  src/framework/xr/xr-anchors.js
Labels: area: xr

#5880 Fix docs 404 for XrAnchorCreateCallback
  src/framework/xr/xr-anchors.js
Labels: bug, docs, area: xr

#5881 Introduction of RenderPassCamera - pass describing typical render passes for the camera
  examples/src/examples/graphics/post-processing.mjs
  extras/index.js
  extras/render-passes/render-pass-bloom.js
  extras/render-passes/render-pass-camera-frame.js
  src/platform/graphics/render-pass.js
  src/scene/frame-graph.js
  src/scene/renderer/render-pass-render-actions.js
Labels: feature request, area: graphics

#5868 Add JSDoc for extras/splat ply-reader/splat-material/splat
  extras/jsconfig.json
  extras/splat/ply-parser.js
  extras/splat/ply-reader.js
  extras/splat/splat-container-resource.js
  extras/splat/splat-data.js
  extras/splat/splat-instance.js
  extras/splat/splat-material.js
  extras/splat/splat.js
Labels: docs

#5891 PaintMesh engine example works on WebGPU
  examples/src/examples/graphics/paint-mesh.mjs
Labels: area: graphics

#5896 Video fix
  src/platform/graphics/webgl/webgl-texture.js
Labels: bug, area: graphics

#5897 Small cleanup of deprecated functionality and default parameters
  src/deprecated/deprecated.js
  src/framework/graphics/picker.js
  src/platform/graphics/texture.js
Labels: area: graphics

#5899 Disable MSAA for splat examples
  examples/src/examples/loaders/splat-many.mjs
  examples/src/examples/loaders/splat.mjs
Labels: performance, area: examples

#5900 Implementation of shader generator for Splat Materials supporting gamma and tonemapping options
  examples/src/examples/loaders/splat-many.mjs
  examples/src/examples/loaders/splat.mjs
  extras/splat/shader-generator-splat.js
  extras/splat/splat-material.js
  extras/splat/splat.js
  src/index.js
  src/scene/shader-lib/programs/shader-generator.js
Labels: area: graphics

#5901 Exposing sky for Editor
  src/scene/scene.js
  src/scene/skybox/sky.js
Labels: area: graphics

#5904 Exposing sky properties fixes
  src/scene/skybox/sky.js
Labels: area: graphics

#5903 Opacity dithering support
  examples/assets/models/glass-table.glb
  examples/assets/models/glass-table.txt
  examples/assets/textures/pc-gray.png
  examples/src/examples/graphics/dithered-transparency.mjs
  examples/src/examples/graphics/index.mjs
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/lit-material.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/bayer.js
  src/scene/shader-lib/chunks/standard/frag/opacity-dither.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/standard.js
  test/scene/materials/standard-material.test.mjs
  utils/types-fixup.mjs
Labels: feature request, area: graphics

#5911 Fix to fringe offset to be independent of the render target resolution
  extras/render-passes/render-pass-compose.js
Labels: bug, area: graphics

#5909 Initial experimental support for static TAA
  examples/src/examples/graphics/post-processing.mjs
  extras/index.js
  extras/render-passes/render-pass-camera-frame.js
  extras/render-passes/render-pass-taa.js
  src/framework/components/camera/component.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/camera.js
  src/scene/renderer/renderer.js
Labels: feature request, area: graphics
