Repository playcanvas/engine, pull requests merged in 2024-09, with the labels that each got.

#6899 Allow per camera fog settings
  examples/src/examples/graphics/shader-hatch.example.mjs
  src/deprecated/deprecated.js
  src/framework/lightmapper/lightmapper.js
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/shader-material.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/particle-system/particle-material.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/render-pass-forward.js
  src/scene/renderer/rendering-params.js
  src/scene/scene.js
Labels: area: graphics, enhancement

#6900 Propsal to update deprecated and removed functionality
  src/core/debug.js
  src/deprecated/deprecated.js
  src/scene/batching/batch.js
  utils/rollup-build-target.mjs
Labels: docs

#6901 Improved error message when basis wasm is not loaded
  examples/src/examples/loaders/gltf-export.example.mjs
  src/framework/parsers/texture/basis.js
  src/framework/parsers/texture/ktx2.js
Labels: area: graphics

#6905 [Fix] Correctly support sRGB DXT formats on WebGL
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-texture.js
Labels: bug, area: graphics

#6906 Fix initialization of __attributes in ScriptType class
  src/framework/script/script-type.js
Labels: bug

#6902 [Examples/Vehicle] Fix Ammo null function error on restart
  examples/src/examples/physics/vehicle.example.mjs
  src/framework/components/collision/system.js
  src/framework/components/rigid-body/component.js
  src/framework/components/rigid-body/system.js
Labels: bug, area: physics

#6907 Option to apply SSAO during lighting instead of during postprocessing
  examples/src/examples/graphics/ambient-occlusion.controls.mjs
  examples/src/examples/graphics/ambient-occlusion.example.mjs
  src/extras/index.js
  src/extras/render-passes/render-pass-camera-frame.js
  src/extras/render-passes/render-pass-ssao.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-options.js
  src/scene/renderer/rendering-params.js
  src/scene/shader-lib/chunks/standard/frag/ao.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/standard.js
Labels: feature request, area: graphics

#6910 [Fix] Changing default value of SSAO during shader generation to false
  src/scene/materials/standard-material-options-builder.js
  src/scene/renderer/rendering-params.js
Labels: bug, area: graphics

#6917 WebGPU partial support for multisampled RT using supplied depth texture
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/platform/graphics/webgpu/webgpu-render-target.js
Labels: area: graphics, enhancement

#6918 Automatically store depth if RT is used with a user supplied depth buffer
  src/platform/graphics/render-pass.js
Labels: area: graphics, enhancement

#6909 WebXR: fix depth sensing for Oculus Quest v68+
  examples/src/examples/xr/ar-camera-depth.example.mjs
  src/framework/xr/constants.js
  src/framework/xr/xr-manager.js
  src/framework/xr/xr-view.js
  src/framework/xr/xr-views.js
Labels: bug, area: xr

#6922 Update to ESLint 9
  eslint.config.mjs
  package-lock.json
  package.json
  src/framework/parsers/glb-parser.js
  src/framework/script/script-create.js
  src/framework/xr/xr-anchors.js
  src/framework/xr/xr-view.js
  test/.eslintrc.json
  test/fixtures.mjs
  utils/typedoc-plugin.mjs
Labels: enhancement

#6923 Simplify ESLint config and enforce no-var rule
  eslint.config.mjs
  package-lock.json
  package.json
  src/scene/shader-lib/programs/lit-shader.js
Labels: enhancement

#6925 Migrate 18 ElementComponent unit tests from Karma to Node
  eslint.config.mjs
  test/framework/components/element/draworder.test.mjs
  test/framework/components/element/maks.test.mjs
  tests/framework/components/element/test_draworder.js
Labels: enhancement

#6928 Enable loading of texture assets in unit tests
  package-lock.json
  package.json
  test/core/math/quat.test.mjs
  test/fixtures.mjs
  test/framework/anim/controller/anim-controller.test.mjs
  test/framework/anim/evaluator/anim-clip.test.mjs
  test/framework/anim/evaluator/anim-evaluator.test.mjs
  test/framework/application.test.mjs
  test/framework/asset/asset-list-loader.test.mjs
  test/framework/asset/asset-localized.test.mjs
  test/framework/asset/asset-registry.test.mjs
  test/framework/asset/asset.test.mjs
  test/framework/components/element/component.test.mjs
  test/framework/components/element/draworder.test.mjs
  test/framework/components/element/maks.test.mjs
  test/framework/components/layout-group/component.test.mjs
  test/framework/components/layout-group/layout-calculator.test.mjs
  test/framework/components/model/component.test.mjs
  test/framework/components/particlesystem/component.test.mjs
  test/framework/components/system.test.mjs
  test/framework/entity.test.mjs
  test/framework/i18n/i18n.test.mjs
  test/framework/scene-registry.test.mjs
  test/framework/utils/entity-reference.test.mjs
  test/platform/input/keyboard.test.mjs
  test/platform/input/mouse.test.mjs
  test/platform/net/http.test.mjs
  test/scene/batching/batch-manager.test.mjs
  test/test-assets/test.png
Labels: enhancement

#6919 [Fix] Do not try to resolve color buffer if the RT does not have any, WebGL
  src/platform/graphics/render-pass.js
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#6929 Use `@template` on `ObjectPool` for actual types
  src/core/object-pool.js
Labels: docs, enhancement

#6931 Small cleanup of the WebGL MSAA buffer allocation code
  src/platform/graphics/webgl/webgl-render-target.js
Labels: area: graphics, enhancement

#6932 Multisampled depth buffers can be shared between render targets on WebGPU
  src/core/ref-counted-cache.js
  src/core/ref-counted-key-cache.js
  src/extras/render-passes/render-pass-camera-frame.js
  src/extras/render-passes/render-pass-prepass.js
  src/platform/graphics/render-target.js
  src/platform/graphics/webgpu/webgpu-render-target.js
Labels: area: graphics, enhancement

#6915 fixed broken cubemaps due to incorrectly sized params uniform
  src/scene/shader-lib/chunks/common/frag/reproject.js
Labels: bug, area: graphics

#6946 Support GS spherical harmonics
  src/framework/parsers/ply.js
  src/scene/gsplat/gsplat-data.js
  src/scene/gsplat/gsplat-material.js
  src/scene/gsplat/gsplat.js
  src/scene/gsplat/shader-generator-gsplat.js
Labels: area: graphics, enhancement

#6947 [Fix] Small fix to just introduced issue with MRT
  src/platform/graphics/render-target.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/graphics/render-pass-quad.js
Labels: bug, area: graphics

#6952 [Fix] Fix of WebGPU not correctly matching render pipelines to render target requirements
  examples/thumbnails/graphics_outlines-colored_large.webp
  examples/thumbnails/graphics_outlines-colored_small.webp
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-target.js
Labels: bug, area: graphics

#6956 Small fog and shader generation fixes when custom render passes are used
  src/framework/components/camera/component.js
  src/scene/renderer/forward-renderer.js
Labels: bug, area: graphics

#6954 Gsplat followup orientation and shader update
  src/framework/parsers/gsplat-resource.js
  src/framework/parsers/ply.js
  src/scene/gsplat/gsplat-compressed-data.js
  src/scene/gsplat/gsplat-compressed-material.js
  src/scene/gsplat/gsplat-data.js
  src/scene/gsplat/gsplat-material.js
  src/scene/gsplat/gsplat.js
  src/scene/gsplat/shader-generator-gsplat.js
Labels: area: graphics

#6961 Fix typo
  src/scene/gsplat/gsplat.js
Labels: bug, area: graphics

#6963 Types fix
  src/scene/gsplat/gsplat.js
Labels: bug

#6962 Small improvement to saturation control in compose pass to avoid clipping
  examples/src/examples/graphics/post-processing.controls.mjs
  src/extras/render-passes/render-pass-compose.js
Labels: area: graphics, enhancement

#6957 Examples error handling fix
  examples/src/app/components/code-editor/CodeEditorDesktop.mjs
Labels: bug, area: examples

#6958 Examples thumbnail fix
  examples/scripts/thumbnails.mjs
  examples/thumbnails/misc_esm-script_large.webp
  examples/thumbnails/misc_esm-script_small.webp
Labels: area: examples

#6959 Examples engine bundled
  examples/rollup.config.js
  examples/scripts/utils.mjs
Labels: bug

#6967 Tint color added to the color grading in the composite pass
  src/extras/render-passes/render-pass-compose.js
Labels: feature request, area: graphics

#6968 [Fix] Fix to reporting renderable support for float16 format
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#6969 RenderPassCameraFrame exposes HDR formats
  src/extras/render-passes/render-pass-camera-frame.js
Labels: area: graphics, enhancement

#6970 Change examples default serving port
  examples/package.json
Labels: area: examples

#6973 Fix for -Infinity compressed GS data
  src/scene/gsplat/gsplat-compressed-data.js
Labels: bug

#6980 Add support for Chrome HDR mode for WebGPU
  examples/src/examples/graphics/clustered-area-lights.example.mjs
  examples/src/examples/graphics/clustered-lighting.example.mjs
  examples/src/examples/graphics/mesh-decals.example.mjs
  examples/src/examples/graphics/shader-burn.example.mjs
  examples/src/examples/graphics/shader-burn.shader.frag
  examples/src/examples/graphics/sky.example.mjs
  src/platform/graphics/constants.js
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/render-pass.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: feature request, area: graphics

#6983 MacBook Pro M1 Max, Sonoma 14.6.1 Version 129.0.6668.59 (Official Build) (arm64)
  src/scene/graphics/render-pass-shader-quad.js
Labels: bug, performance, area: graphics

#6988 Add support for BC6H and BC7 texture formats, rename of two DXT formats
  src/platform/graphics/constants.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/constants.js
Labels: feature request, area: graphics

#6979 Fix compound colliders
  src/framework/components/collision/system.js
Labels: bug, area: physics

#6992 Gizmo updates
  examples/src/examples/gizmos/transform-rotate.controls.mjs
  examples/src/examples/gizmos/transform-rotate.example.mjs
  examples/src/examples/gizmos/transform-scale.controls.mjs
  examples/src/examples/gizmos/transform-scale.example.mjs
  examples/src/examples/gizmos/transform-translate.controls.mjs
  examples/src/examples/gizmos/transform-translate.example.mjs
  examples/src/examples/misc/editor.example.mjs
  examples/src/examples/misc/editor.gizmo-handler.mjs
  src/extras/gizmo/axis-shapes.js
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/shape/arc-shape.js
  src/extras/gizmo/shape/arrow-shape.js
  src/extras/gizmo/shape/box-shape.js
  src/extras/gizmo/shape/boxline-shape.js
  src/extras/gizmo/shape/plane-shape.js
  src/extras/gizmo/shape/shape.js
  src/extras/gizmo/shape/sphere-shape.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
  src/extras/gizmo/tri-data.js
Labels: area: examples

#6997 Gizmo fixes
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/transform-gizmo.js
Labels: bug
