Repository playcanvas/engine, pull requests merged in 2024-07, with the labels that each got.

#6770 Invoke stopPropagation on pointer events handled by gizmo.
  src/extras/gizmo/gizmo.js
Labels: bug

#6743 Support for compressed sRGB formats
  examples/src/examples/graphics/shader-burn.shader.frag
  examples/src/examples/graphics/shader-wobble.shader.frag
  examples/src/examples/graphics/texture-basis.example.mjs
  src/framework/handlers/basis-worker.js
  src/framework/handlers/basis.js
  src/framework/parsers/glb-parser.js
  src/framework/parsers/texture/basis.js
  src/framework/parsers/texture/ktx.js
  src/framework/parsers/texture/ktx2.js
  src/platform/graphics/constants.js
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/constants.js
Labels: feature request, area: graphics

#6771 Fallback to int-texture based morphing instead of attribute when float texture rendering is not supported
  examples/src/examples/graphics/mesh-morph-many.example.mjs
  examples/src/examples/graphics/mesh-morph.example.mjs
  src/framework/parsers/glb-parser.js
  src/platform/graphics/bind-group-format.js
  src/platform/graphics/constants.js
  src/platform/graphics/null/null-graphics-device.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/constants.js
  src/scene/materials/basic-material.js
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/mesh-instance.js
  src/scene/morph-instance.js
  src/scene/morph-target.js
  src/scene/morph.js
  src/scene/renderer/renderer.js
  src/scene/shader-lib/chunks/common/vert/transform.js
  src/scene/shader-lib/chunks/lit/vert/normal.js
  src/scene/shader-lib/programs/basic.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#6752 Render targets can use sRGB color buffer
  examples/src/examples/graphics/reflection-planar.shader.frag
  examples/src/examples/graphics/render-to-texture.example.mjs
  scripts/utils/cubemap-renderer.js
  scripts/utils/planar-renderer.js
  src/framework/graphics/render-pass-picker.js
  src/framework/lightmapper/lightmapper.js
  src/platform/graphics/constants.js
  src/platform/graphics/render-target.js
  src/scene/gsplat/gsplat-compressed-material.js
  src/scene/gsplat/gsplat-material.js
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/rendering-params.js
  src/scene/skybox/sky-mesh.js
Labels: feature request, area: graphics

#6761 Elements need to set color uniforms in linear space
  src/framework/components/element/image-element.js
  src/framework/components/element/text-element.js
  tests/framework/components/element/test_imageelement.js
Labels: area: graphics, area: ui

#6773 WebXR - remove deprecated XrDepthSensing, XrView - should be used instead
  src/framework/components/camera/component.js
  src/framework/xr/xr-depth-sensing.js
  src/framework/xr/xr-manager.js
  src/index.js
Labels: area: xr, enhancement

#6775 Update Tags class to use spread instead of arguments
  src/core/tags.js
Labels: docs, enhancement

#6778 [Fix] Stencil clearing was not setting up the mask correctly
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#6779 [BREAKING] Remove CURVE_CATMULL and CURVE_CARDINAL
  src/core/math/constants.js
  src/core/math/curve-evaluator.js
  src/core/math/curve.js
Labels: enhancement

#6780 Minor refactor of Curve class
  src/core/math/curve.js
Labels: enhancement

#6783 Delete splat-related exports now that extras is part of core engine
  src/index.js
Labels: enhancement

#6784 Refactor `Frustum` to use `Plane`
  src/core/shape/frustum.js
  src/core/shape/plane.js
Labels: enhancement

#6788 Refactor `AppBase#preload`
  src/framework/app-base.js
Labels: enhancement

#6789 [Fix] Fix Entity.findComponent(s) functions
  src/framework/entity.js
Labels: bug, area: graphics

#6790 Gizmo event fix
  src/extras/gizmo/gizmo.js
Labels: bug, area: input

#6762 [BREAKING] Remove StandardMaterial.emissiveTint and simply always apply it
  examples/src/examples/graphics/integer-textures.example.mjs
  examples/src/examples/graphics/mesh-decals.example.mjs
  examples/src/examples/graphics/painter.example.mjs
  examples/src/examples/graphics/reflection-box.example.mjs
  examples/src/examples/graphics/render-to-texture.example.mjs
  examples/src/examples/graphics/texture-basis.example.mjs
  examples/src/examples/graphics/video-texture.example.mjs
  scripts/spine/playcanvas-spine.3.8.js
  src/deprecated/deprecated.js
  src/framework/components/element/system.js
  src/framework/components/sprite/system.js
  src/framework/parsers/glb-parser.js
  src/framework/parsers/material/json-standard-material.js
  src/scene/lighting/world-clusters-debug.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-options.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/renderer/forward-renderer.js
  src/scene/shader-lib/chunks/standard/frag/emissive.js
  test/scene/materials/standard-material.test.mjs
  utils/plugins/rollup-types-fixup.mjs
Labels: area: graphics, enhancement

#6794 Minor fixes to `AssetListLoader` and `AssetRegistry`
  src/framework/asset/asset-list-loader.js
  src/framework/asset/asset-registry.js
Labels: bug, enhancement

#6797 Remove Listener velocity
  src/platform/sound/listener.js
Labels: area: audio, enhancement

#6793 Remove WebGL1 support from RenderPassColorGrab
  src/scene/graphics/render-pass-color-grab.js
Labels: area: graphics

#6795 [BREAKING] Remove no longer needed shader defines: SUPPORTS_TEXLOD and SUPPORTS_MRT
  src/platform/graphics/shader-chunks/frag/gles3.js
  src/platform/graphics/shader-chunks/frag/webgpu.js
  src/scene/shader-lib/chunks/lit/frag/refractionDynamic.js
Labels: area: graphics, enhancement

#6796 Remove deprecated uniform for grab pass textures: uDepthMap and texture_grabPass
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/graphics/render-pass-color-grab.js
  src/scene/graphics/render-pass-depth-grab.js
Labels: area: graphics, enhancement

#6799 Edit pass on WebXR API docs
  src/framework/xr/xr-anchors.js
  src/framework/xr/xr-dom-overlay.js
  src/framework/xr/xr-finger.js
  src/framework/xr/xr-hand.js
  src/framework/xr/xr-hit-test-source.js
  src/framework/xr/xr-image-tracking.js
  src/framework/xr/xr-input-source.js
  src/framework/xr/xr-input.js
  src/framework/xr/xr-joint.js
  src/framework/xr/xr-light-estimation.js
  src/framework/xr/xr-manager.js
  src/framework/xr/xr-mesh-detection.js
  src/framework/xr/xr-mesh.js
  src/framework/xr/xr-view.js
  src/framework/xr/xr-views.js
Labels: docs, area: xr

#6800 Remove handling of deprecated form of MeshInstance.constructor
  src/scene/mesh-instance.js
Labels: area: graphics

#6801 Move `AppBase` constructor properties to class fields
  src/framework/app-base.js
  src/framework/stats.js
Labels: enhancement

#6806 Remove private StandardMaterial.tbnFast option support
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/lit-material.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/TBNfast.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#6810 Clean up some WebGL1 references from shadow type constants
  src/framework/app-base.js
  src/framework/components/light/component.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/constants.js
  src/scene/lighting/lighting-params.js
Labels: docs

#6811 Small gizmo event handler fix
  src/extras/gizmo/gizmo.js
Labels: bug

#6804 Refactor the way shaders get created for particle systems
  examples/src/examples/graphics/particles-mesh.controls.mjs
  examples/src/examples/graphics/particles-mesh.example.mjs
  src/framework/components/particle-system/component.js
  src/scene/particle-system/particle-emitter.js
  src/scene/particle-system/particle-material.js
Labels: area: particles, enhancement

#6807 Remove never used StandardMaterial.normalizeNormalMap
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
Labels: area: graphics

#6808 [Fix] Ignore the shape of light if area lights are disabled
  src/scene/lighting/lights-buffer.js
  src/scene/lighting/world-clusters.js
  src/scene/renderer/world-clusters-allocator.js
Labels: bug, area: graphics

#6809 [BREAKING] Remove StandardMaterial.sheenTint
  src/deprecated/deprecated.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/standard/frag/sheen.js
  utils/plugins/rollup-types-fixup.mjs
Labels: area: graphics

#6802 Move some of AppBase#init to class fields
  src/framework/app-base.js
  src/framework/application.js
Labels: enhancement

#6812 Remove opacityTint internal flag
  src/framework/components/element/system.js
  src/framework/components/sprite/system.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-options.js
  src/scene/shader-lib/chunks/standard/frag/opacity.js
Labels: area: graphics

#6815 Remove some redundant exports
  src/platform/graphics/render-pass.js
  src/platform/graphics/vertex-iterator.js
Labels: enhancement

#6816 [BREAKING] Remove `pc.type`
  src/core/core.js
  src/index.js
  src/platform/input/controller.js
  test/core/core.test.mjs
Labels: enhancement

#6818 Minor JSDoc fixes
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/layer.js
Labels: bug, docs

#6821 Removed helper functions on the chunks
  src/extras/mini-stats/render2d.js
  src/scene/shader-lib/utils.js
Labels: area: graphics

#5168 Support for OffscreenCanvas in Web Workers
  src/core/platform.js
  src/framework/app-base.js
  src/framework/application.js
  src/platform/graphics/graphics-device.js
Labels: feature request, area: graphics, open source contribution

#6824 Add gsplat mapping
  src/scene/gsplat/gsplat-instance.js
  src/scene/gsplat/gsplat-sorter.js
  src/scene/gsplat/shader-generator-gsplat.js
Labels: bug, area: graphics, enhancement

#6823 Array equals fix
  src/core/array-utils.js
Labels: bug

#6825 Gizmo small example
  examples/src/examples/misc/editor.controls.mjs
  examples/src/examples/misc/editor.example.mjs
  examples/src/examples/misc/editor.gizmo-handler.mjs
  examples/src/examples/misc/editor.grid.mjs
  examples/src/examples/misc/editor.selector.mjs
  examples/src/examples/misc/gizmo.example.mjs
  examples/thumbnails/misc_editor_large.webp
  examples/thumbnails/misc_editor_small.webp
  examples/thumbnails/misc_gizmos_large.webp
  examples/thumbnails/misc_gizmos_small.webp
  src/extras/gizmo/gizmo.js
Labels: area: examples

#6826 [BREAKING] Gizmo constants
  src/extras/gizmo/axis-shapes.js
  src/extras/gizmo/color.js
  src/extras/gizmo/constants.js
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
  src/extras/index.js
Labels: docs

#6589 Keep correct paths for build output even when build is invoked outside of repo root
  utils/rollup-build-target.mjs
Labels: enhancement

#6827 Followup Gizmo API changes
  src/extras/gizmo/constants.js
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
  src/extras/index.js
Labels: docs

#6831 [BREAKING] Implementation of ShaderMaterial - Material to be used with custom shaders
  examples/src/examples/compute/particles.example.mjs
  examples/src/examples/graphics/grab-pass.example.mjs
  examples/src/examples/graphics/ground-fog.example.mjs
  examples/src/examples/graphics/paint-mesh.example.mjs
  examples/src/examples/graphics/point-cloud-simulation.example.mjs
  examples/src/examples/graphics/point-cloud.example.mjs
  examples/src/examples/graphics/reflection-planar.example.mjs
  examples/src/examples/graphics/shader-burn.example.mjs
  examples/src/examples/graphics/shader-toon.example.mjs
  examples/src/examples/graphics/shader-wobble.example.mjs
  examples/src/examples/graphics/texture-array.example.mjs
  examples/src/examples/graphics/transform-feedback.example.mjs
  examples/src/examples/graphics/wgsl-shader.example.mjs
  examples/src/examples/loaders/loaders-gl.example.mjs
  examples/src/examples/user-interface/custom-shader.example.mjs
  examples/src/examples/xr/ar-camera-depth.example.mjs
  src/core/preprocessor.js
  src/deprecated/deprecated.js
  src/extras/gizmo/axis-shapes.js
  src/extras/mini-stats/render2d.js
  src/framework/app-base.js
  src/index.js
  src/platform/graphics/shader-processor.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/shader.js
  src/platform/graphics/webgl/webgl-shader.js
  src/platform/graphics/webgpu/webgpu-shader.js
  src/scene/gsplat/gsplat-compressed-material.js
  src/scene/gsplat/gsplat-material.js
  src/scene/immediate/immediate.js
  src/scene/materials/material.js
  src/scene/materials/shader-material.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/program-library.js
  src/scene/shader-lib/programs/shader-generator-shader.js
  src/scene/skybox/sky-mesh.js
  test/scene/materials/shader-material.test.mjs
Labels: feature request, area: graphics

#6833 Renamed internal ‘descr’ symbols to ‘desc’ for consistency
  src/platform/graphics/webgpu/webgpu-bind-group-format.js
  src/platform/graphics/webgpu/webgpu-bind-group.js
  src/platform/graphics/webgpu/webgpu-compute-pipeline.js
  src/platform/graphics/webgpu/webgpu-mipmap-renderer.js
  src/platform/graphics/webgpu/webgpu-pipeline.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: area: graphics

#6834 Custom line shader & handle gamma
  src/scene/immediate/immediate.js
  src/scene/shader-lib/programs/shader-generator-shader.js
Labels: area: graphics, enhancement

#6836 [Fix] Fix albedo debug output
  src/scene/shader-lib/chunks/lit/frag/debug-output.js
Labels: bug, area: graphics

#6837 Small gsplat fixes
  src/scene/gsplat/gsplat-compressed-data.js
  src/scene/gsplat/gsplat-data.js
Labels: bug, area: graphics

#6838 Support for sRGB framebuffer on WebGPU
  examples/src/examples/graphics/area-lights.example.mjs
  examples/src/examples/graphics/material-transparency.example.mjs
  examples/src/examples/graphics/particles-anim-index.example.mjs
  examples/src/examples/graphics/particles-random-sprites.example.mjs
  examples/src/examples/graphics/particles-snow.example.mjs
  examples/src/examples/graphics/particles-spark.example.mjs
  examples/src/examples/graphics/post-processing.example.mjs
  examples/src/examples/graphics/reflection-planar.shader.frag
  examples/src/examples/graphics/shader-burn.shader.frag
  examples/src/examples/graphics/shader-compile.example.mjs
  examples/src/examples/graphics/shader-toon.example.mjs
  examples/src/examples/graphics/shader-toon.shader.frag
  examples/src/examples/graphics/shader-wobble.shader.frag
  examples/src/examples/graphics/texture-array.example.mjs
  examples/src/examples/graphics/texture-array.ground.frag
  examples/src/examples/graphics/texture-array.shader.frag
  src/extras/gizmo/axis-shapes.js
  src/extras/render-passes/render-pass-compose.js
  src/framework/components/camera/post-effect-queue.js
  src/platform/graphics/constants.js
  src/platform/graphics/graphics-device-create.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/render-pass.js
  src/platform/graphics/render-target.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/constants.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-target.js
  src/scene/immediate/immediate.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/render-pass-forward.js
  src/scene/shader-lib/chunks/particle/frag/particle.js
  src/scene/shader-lib/chunks/standard/frag/opacity-dither.js
  src/scene/shader-lib/programs/particle.js
Labels: feature request, area: graphics

#6841 [BREAKING] Remove StandardMaterial.sheenGlossTint
  src/framework/parsers/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/standard/frag/sheenGloss.js
Labels: area: graphics, enhancement

#6843 Fix an issue with light baking if the clustered lighting has shadows disabled
  src/framework/lightmapper/bake-light-ambient.js
  src/framework/lightmapper/bake-light-simple.js
  src/framework/lightmapper/bake-light.js
  src/framework/lightmapper/lightmapper.js
  src/scene/renderer/forward-renderer.js
Labels: bug, area: graphics

#6845 Fix gsplat sorting bug
  src/scene/gsplat/gsplat-sorter.js
Labels: bug

#6844 [BREAKING] When material is cloned, its custom parameters are copied as well
  src/scene/materials/material.js
Labels: area: graphics, enhancement

#6846 Small fix to gsplat sorter
  src/scene/gsplat/gsplat-sorter.js
Labels: bug, area: graphics

#6847 Gizmo resize editor example fix
  examples/src/examples/misc/editor.controls.mjs
  examples/src/examples/misc/editor.example.mjs
  examples/src/examples/misc/editor.gizmo-handler.mjs
Labels: bug

#6849 Allow blit to backbuffer
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#6852 Small webgpu fixes
  src/platform/graphics/shader-processor.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: bug, area: graphics

#6853 Remove normalSkinned shader chunk which is never referenced
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/vert/normalSkinned.js
Labels: area: graphics

#6854 Remove unused transform instanced chunk
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/vert/normalInstanced.js
Labels: area: graphics

#6855 Skinning / morphing support for ShaderMaterial
  examples/assets/scripts/misc/hatch-material.mjs
  examples/assets/textures/hatch-0.jpg
  examples/assets/textures/hatch-1.jpg
  examples/assets/textures/hatch-2.jpg
  examples/assets/textures/hatch-3.jpg
  examples/assets/textures/hatch-4.jpg
  examples/assets/textures/hatch-5.jpg
  examples/assets/textures/hatch-textures.txt
  examples/src/examples/graphics/shader-hatch.controls.mjs
  examples/src/examples/graphics/shader-hatch.example.mjs
  examples/src/examples/graphics/shadow-cascades.example.mjs
  examples/src/examples/loaders/gltf-export.example.mjs
  src/core/preprocessor.js
  src/deprecated/deprecated.js
  src/platform/graphics/shader-utils.js
  src/scene/batching/batch-manager.js
  src/scene/constants.js
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/shader-material.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/mesh-instance.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/vert/normalCore.js
  src/scene/shader-lib/chunks/common/vert/transform.js
  src/scene/shader-lib/chunks/common/vert/transformCore.js
  src/scene/shader-lib/chunks/lit/vert/base.js
  src/scene/shader-lib/chunks/lit/vert/instancing.js
  src/scene/shader-lib/chunks/lit/vert/normal.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/shader-generator-shader.js
Labels: feature request, area: graphics

#6856 ShaderMaterial supports PICK shader pass
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/pick.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/shader-generator-shader.js
Labels: area: graphics, enhancement

#6857 [BREAKING] BasicMaterial has been deleted
  examples/src/examples/graphics/material-basic.example.mjs
  src/extras/exporters/gltf-exporter.js
  src/index.js
  src/scene/materials/basic-material.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/vert/transformDecl.js
  src/scene/shader-lib/programs/basic.js
  src/scene/shader-lib/programs/shader-generator.js
  test/scene/materials/basic-material.test.mjs
Labels: area: graphics, enhancement

#6858 Move parameters of getShaderVariant function to an object
  src/scene/gsplat/gsplat-compressed-material.js
  src/scene/gsplat/gsplat-material.js
  src/scene/materials/lit-material.js
  src/scene/materials/material.js
  src/scene/materials/shader-material.js
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  src/scene/particle-system/particle-material.js
  src/scene/skybox/sky-mesh.js
Labels: area: graphics, enhancement

#6861 Add missing example thumbnails
  examples/thumbnails/graphics_material-transparency_large.webp
  examples/thumbnails/graphics_material-transparency_small.webp
  examples/thumbnails/graphics_shader-hatch_large.webp
  examples/thumbnails/graphics_shader-hatch_small.webp
  examples/thumbnails/misc_gizmo_large.webp
  examples/thumbnails/misc_gizmo_small.webp
Labels: area: examples

#6862 Removed references to no longer used _shader from the Material
  src/scene/batching/batch-manager.js
  src/scene/materials/material.js
Labels: area: graphics, enhancement

#6863 Animation component asset null fix
  src/framework/components/anim/system.js
Labels: bug, area: animation

#6850 Gizmo examples restructure
  examples/src/examples/gizmos/transform-rotate.controls.mjs
  examples/src/examples/gizmos/transform-rotate.example.mjs
  examples/src/examples/gizmos/transform-scale.controls.mjs
  examples/src/examples/gizmos/transform-scale.example.mjs
  examples/src/examples/gizmos/transform-translate.controls.mjs
  examples/src/examples/gizmos/transform-translate.example.mjs
  examples/src/examples/misc/editor.controls.mjs
  examples/src/examples/misc/editor.example.mjs
  examples/src/examples/misc/editor.gizmo-handler.mjs
  examples/thumbnails/gizmos_transform-rotate_large.webp
  examples/thumbnails/gizmos_transform-rotate_small.webp
  examples/thumbnails/gizmos_transform-scale_large.webp
  examples/thumbnails/gizmos_transform-scale_small.webp
  examples/thumbnails/gizmos_transform-translate_large.webp
  examples/thumbnails/gizmos_transform-translate_small.webp
Labels: area: examples
