Repository playcanvas/engine, pull requests merged in 2024-10, with the labels that each got.

#6998 Improvements to non-clustered omni light shadows
  examples/src/examples/graphics/lights.example.mjs
  src/platform/graphics/shader-utils.js
  src/scene/light.js
  src/scene/renderer/shadow-map.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/packDepth.js
  src/scene/shader-lib/chunks/lit/frag/shadowStandard.js
  src/scene/shader-lib/chunks/particle/frag/particle.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: performance, area: graphics, enhancement

#7001 Improvement to layer handling by render passes
  src/extras/render-passes/render-pass-camera-frame.js
  src/framework/components/camera/component.js
  src/scene/composition/layer-composition.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/render-pass-forward.js
Labels: area: graphics, enhancement

#7003 Attach a label to WebGPU render pass encoder even in the release engine
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: performance, area: graphics

#7008 Improved missing texture uniform error handling
  src/extras/render-passes/render-pass-camera-frame.js
  src/platform/graphics/bind-group.js
  src/platform/graphics/built-in-textures.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/renderer/forward-renderer.js
Labels: area: graphics, enhancement

#7009 Do not allow gizmo rendering to use debug output
  src/extras/gizmo/shape/shape.js
Labels: bug, area: graphics

#7015 [Fix] Fix to area lights (disk, sphere) occasionally generating -Inf pixels
  src/scene/shader-lib/chunks/lit/frag/ltc.js
Labels: bug, area: graphics

#7011 CameraFrame script, to expose a simple to use version for the engine and the Editor
  examples/assets/scripts/misc/camera-frame.mjs
  examples/src/examples/camera/first-person.example.mjs
  examples/src/examples/graphics/ambient-occlusion.example.mjs
  examples/src/examples/graphics/clustered-area-lights.example.mjs
  examples/src/examples/graphics/dithered-transparency.example.mjs
  examples/src/examples/graphics/post-processing.controls.mjs
  examples/src/examples/graphics/post-processing.example.mjs
  examples/src/examples/graphics/taa.example.mjs
  src/extras/render-passes/render-pass-camera-frame.js
  src/framework/components/camera/component.js
  src/platform/graphics/graphics-device.js
Labels: feature request, area: graphics

#7020 Avoid spam from AnimBinder regarding duplicate nodes
  src/framework/anim/binder/default-anim-binder.js
Labels: area: animation

#7021 Update gsplat example shaders to latest structure
  examples/src/examples/loaders/gsplat-many.shader.frag
  examples/src/examples/loaders/gsplat-many.shader.vert
  src/scene/gsplat/shader-generator-gsplat.js
Labels: bug, area: graphics

#7022 [Fix] Fix to lightmapping not baking shadows on the following runs
  src/framework/lightmapper/bake-light.js
Labels: bug, area: graphics

#7024 Perform fuzzy test in material
  src/scene/materials/standard-material-options-builder.js
Labels: area: graphics, enhancement

#7013 Fix/local-axis-gizmo-error
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: bug

#7028 Support for GPU timing reporting for compute passes in WebGPU
  examples/src/examples/compute/histogram.example.mjs
  examples/src/examples/compute/particles.example.mjs
  examples/src/examples/compute/texture-gen.example.mjs
  examples/src/examples/compute/vertex-update.example.mjs
  src/platform/graphics/gpu-profiler.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: performance, area: graphics, enhancement

#7031 CameraFrame render pass rendering supports stencil buffer
  examples/assets/scripts/misc/camera-frame.mjs
  examples/src/examples/graphics/portal.example.mjs
  src/extras/render-passes/render-pass-camera-frame.js
  src/extras/render-passes/render-pass-prepass.js
Labels: area: graphics, enhancement

#7034 Fix text encoding in glTF exporter
  src/extras/exporters/gltf-exporter.js
Labels: bug, area: gltf

#7037 Optimized the creation of CommandEncoders on WebGPU
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-mipmap-renderer.js
  src/platform/graphics/webgpu/webgpu-query-set.js
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: performance, area: graphics

#7040 Combine render passes where feasible
  src/platform/graphics/render-pass.js
  src/scene/frame-graph.js
Labels: performance, area: graphics

#7044 [Fix] Fix to occasional black pixels with bloom and sharpening
  src/extras/render-passes/render-pass-compose.js
Labels: bug, area: graphics

#7043 Updated Events example to use render passes bloom
  examples/src/examples/animation/events.example.mjs
Labels: area: examples

#7045 Gizmo clipping plane fix
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/shape/shape.js
Labels: bug

#7049 Gizmo material chunks shader fix
  src/extras/gizmo/shape/shape.js
Labels: bug

#7050 Gizmo features
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/shape/plane-shape.js
  src/extras/gizmo/translate-gizmo.js
Labels: enhancement

#7051 Rendering to a single mip level of RenderTarget (WebGPU only)
  src/platform/graphics/render-pass.js
  src/platform/graphics/render-target.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-render-target.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-target.js
Labels: feature request, area: graphics

#7054 Fix gsplat material defines
  src/scene/gsplat/shader-generator-gsplat.js
Labels: bug, area: graphics

#7053 Modified the gsplat examples to create splat instances a more standard way
  examples/src/examples/loaders/gsplat-many.example.mjs
  examples/src/examples/loaders/gsplat.example.mjs
Labels: area: examples

#7055 Remove couple of unneeded lines from gsplat-many example
  examples/src/examples/loaders/gsplat-many.example.mjs
Labels: area: examples

#7059 Gizmo orthographic fix
  src/extras/gizmo/gizmo.js
Labels: bug

#7061 Fixed examples device type logging
  examples/iframe/utils.mjs
Labels: bug

#7063 Gizmos axis flipping
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/shape/arrow-shape.js
  src/extras/gizmo/shape/boxline-shape.js
  src/extras/gizmo/translate-gizmo.js
Labels: enhancement

#7064 Compressed ply orientation fix
  src/framework/parsers/gsplat-resource.js
  src/scene/gsplat/gsplat-compressed-data.js
Labels: bug

#7065 Gsplat shader fix for webgpu
  src/scene/gsplat/shader-generator-gsplat.js
Labels: bug

#7067 Somebody submitted a lint error to main_v1 branch
  examples/src/examples/misc/editor.selector.mjs
Labels: bug

#7068 Gizmo rotation fix
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: bug

#7070 Small fix for texture read
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#7069 Small type fix
  src/platform/graphics/texture.js
Labels: area: graphics

#7072 Gizmo rotation fix for orthographic
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/transform-gizmo.js
Labels: bug

#6642 ESM Multi camera
  examples/src/examples/camera/multi.controls.mjs
  examples/src/examples/camera/multi.example.mjs
  examples/thumbnails/camera_multi_large.webp
  examples/thumbnails/camera_multi_small.webp
  scripts/camera/base-camera.js
  scripts/camera/multi-camera.js
Labels: area: scripts, area: examples

#7077 getFrustumCorners fix
  src/scene/camera.js
Labels: bug

#7076 Gizmo rotation direction fix
  src/extras/gizmo/rotate-gizmo.js
Labels: bug

#7078 [BETA] ESM Multi-Camera script updates
  examples/src/examples/camera/multi.controls.mjs
  examples/src/examples/camera/multi.example.mjs
  scripts/camera/base-camera.js
  scripts/camera/multi-camera.js
  src/framework/components/script/component.js
Labels: enhancement
