Repository playcanvas/engine, pull requests merged in 2024-03, with the labels that each got.

#6104 GPU optimization to gsplat rendering
  examples/src/examples/loaders/gsplat-many/config.mjs
  examples/src/examples/loaders/gsplat/config.mjs
  src/core/math/mat3.js
  src/framework/parsers/gsplat-resource.js
  src/scene/gsplat/gsplat.js
  src/scene/gsplat/shader-generator-gsplat.js
Labels: performance, area: graphics

#6102 Examples build fixes
  examples/jsconfig.json
  examples/package.json
  examples/rollup.config.js
  examples/scripts/standalone-html.mjs
  examples/utils.mjs
Labels: bug, area: examples

#6108 Added worker environment
  src/core/platform.js
Labels: area: scripts, enhancement

#6111 Update banner to mention MIT license
  utils/rollup-get-banner.mjs
Labels: enhancement

#6112 Update README files to show ESM usage
  README-ja.md
  README-kr.md
  README-zh.md
  README.md
Labels: docs, enhancement

#5675 Bundles Refactor
  examples/assets/bundles/bundle.tar
  examples/bundle.tar
  examples/src/examples/loaders/bundle/config.mjs
  examples/src/examples/loaders/bundle/example.mjs
  src/core/event-handle.js
  src/framework/asset/asset-registry.js
  src/framework/asset/asset.js
  src/framework/bundle/bundle-registry.js
  src/framework/bundle/bundle.js
  src/framework/handlers/binary.js
  src/framework/handlers/bundle.js
  src/framework/handlers/css.js
  src/framework/handlers/html.js
  src/framework/handlers/json.js
  src/framework/handlers/loader.js
  src/framework/handlers/shader.js
  src/framework/handlers/template.js
  src/framework/handlers/text.js
  src/framework/handlers/untar.js
  tests/framework/bundles/test_bundle_loader.js
  tests/framework/bundles/test_bundle_registry.js
  tests/test-assets/bundles/bundle.tar
  tests/test-assets/bundles/bundle.tar.gz
  tests/test-assets/bundles/css.css
Labels: performance, area: assets

#6120 Examples action build fix
  .github/workflows/ci.yml
Labels: bug

#6121 Removes source mappings from unbundled builds
  utils/rollup-build-target.mjs
Labels: enhancement

#6127 Adding globalThis typeof check
  src/core/platform.js
Labels: bug

#6128 Add support for R16F and RG16F texture formats
  src/platform/graphics/constants.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/constants.js
Labels: area: graphics, enhancement

#6129 Use more compact texture formats storing GSplat data
  src/framework/parsers/gsplat-resource.js
  src/scene/gsplat/gsplat.js
  src/scene/gsplat/shader-generator-gsplat.js
Labels: performance, area: graphics

#6130 Enabled point cloud examples on WebGPU
  examples/src/examples/graphics/point-cloud-simulation/config.mjs
  examples/src/examples/graphics/point-cloud/config.mjs
Labels: area: examples

#6131 Fix the render target release in the RenderPassDepth (WebGL1 only)
  src/scene/graphics/render-pass-depth.js
Labels: bug, area: graphics

#6133 Migrate input unit tests from Karma to Node
  package-lock.json
  package.json
  test/fixtures.mjs
  test/platform/input/keyboard.test.mjs
  test/platform/input/mouse.test.mjs
  tests/platform/input/simulate_event.js
  tests/platform/input/test_input.js
  tests/platform/input/test_keyboard.js
  tests/platform/input/test_mouse.js
Labels: enhancement

#6132 Remove JSDoc
  .gitignore
  README-ja.md
  README-kr.md
  README-zh.md
  README.md
  conf-api.json
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#6134 Refactor input-related code
  src/platform/input/keyboard-event.js
  src/platform/input/keyboard.js
  src/platform/input/mouse-event.js
  src/platform/input/mouse.js
  src/platform/input/touch-event.js
Labels: enhancement

#6137 Examples root path fix
  examples/iframe/utils.mjs
  examples/src/app/paths.mjs
Labels: bug

#6139 Examples develop speedup
  examples/package.json
  examples/rollup.config.js
Labels: area: examples, enhancement

#6144 Support for sharpening inside the compose render pass, needed for TAA
  examples/src/examples/graphics/taa/controls.mjs
  examples/src/examples/graphics/taa/example.mjs
  extras/render-passes/render-pass-compose.js
Labels: feature request, area: graphics

#6146 [Fix] Fix the shader linking after the lost context has been restored.
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-shader.js
  src/scene/skybox/sky-mesh.js
Labels: bug, area: graphics

#6151 Support for KHR_materials_dispersion glTF extension
  examples/assets/models/dispersion-test.glb
  examples/src/examples/graphics/dispersion/config.mjs
  examples/src/examples/graphics/dispersion/example.mjs
  src/framework/parsers/glb-parser.js
  src/platform/graphics/constants.js
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/lit/frag/refractionCube.js
  src/scene/shader-lib/chunks/lit/frag/refractionDynamic.js
  src/scene/shader-lib/chunks/standard/frag/litShaderArgs.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/standard.js
  test/scene/materials/standard-material.test.mjs
  test/test-assets/box/1/Box Material.json
  tests/test-assets/box/1/Box Material.json
  utils/types-fixup.mjs
Labels: feature request, area: graphics, area: gltf

#6153 Add extras.mjs to exported files
  package.json
Labels: bug

#6154 Add publint
  package-lock.json
  package.json
Labels: enhancement

#6155 [Fix] reset internal cached state for face culling when the device is restored
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#6156 Added pre-build dispersion example thumbnails
  examples/thumbnails/graphics_dispersion_large.webp
  examples/thumbnails/graphics_dispersion_small.webp
Labels: area: examples

#6161 Typedoc hide exported classes
  extras/exporters/core-exporter.js
  extras/gizmo/mesh-tri-data.js
  src/framework/xr/xr-mesh.js
  src/platform/graphics/gpu-profiler.js
  src/platform/graphics/vertex-iterator.js
  src/scene/skybox/sky.js
Labels: docs

#6162 Hide data getter overrides in LightComponent and ParticleSystemComponent
  src/framework/components/light/component.js
  src/framework/components/particle-system/component.js
Labels: docs

#6166 Support for dithering using interleaved gradient noise
  examples/src/examples/graphics/dithered-transparency/controls.mjs
  src/scene/constants.js
  src/scene/graphics/blue-noise-texture.js
  src/scene/graphics/noise-textures.js
  src/scene/materials/standard-material.js
  src/scene/renderer/renderer.js
  src/scene/shader-lib/chunks/standard/frag/opacity-dither.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#6168 Removed circular self dependency
  package.json
Labels: bug

#6124 Removes vertex-format type fix
  src/platform/graphics/vertex-format.js
  utils/types-fixup.mjs
Labels: docs

#6170 Small refactor in preparation of context lost handling for WebGPU
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics, enhancement

#6175 Tidy up Karma tests
  package-lock.json
  package.json
  tests/framework/handlers/test_sprite_resource.js
  tests/karma.conf.cjs
  tests/setup.js
Labels: enhancement

#6177 Use @ignore over @hideconstructor
  src/framework/anim/evaluator/anim-track.js
  src/framework/anim/state-graph/anim-state-graph.js
  src/framework/app-base.js
  src/framework/components/anim/system.js
  src/framework/components/animation/system.js
  src/framework/components/audio-listener/system.js
  src/framework/components/audio-source/system.js
  src/framework/components/button/system.js
  src/framework/components/camera/system.js
  src/framework/components/collision/system.js
  src/framework/components/element/system.js
  src/framework/components/gsplat/system.js
  src/framework/components/joint/system.js
  src/framework/components/layout-child/system.js
  src/framework/components/layout-group/system.js
  src/framework/components/light/system.js
  src/framework/components/model/system.js
  src/framework/components/particle-system/system.js
  src/framework/components/render/system.js
  src/framework/components/rigid-body/system.js
  src/framework/components/screen/system.js
  src/framework/components/script/system.js
  src/framework/components/scroll-view/system.js
  src/framework/components/scrollbar/system.js
  src/framework/components/sound/system.js
  src/framework/components/sprite/system.js
  src/framework/components/zone/system.js
  src/framework/handlers/gsplat.js
  src/framework/lightmapper/lightmapper.js
  src/framework/parsers/gsplat-resource.js
  src/framework/xr/xr-anchor.js
  src/framework/xr/xr-anchors.js
  src/framework/xr/xr-depth-sensing.js
  src/framework/xr/xr-dom-overlay.js
  src/framework/xr/xr-finger.js
  src/framework/xr/xr-hand.js
  src/framework/xr/xr-hit-test-source.js
  src/framework/xr/xr-hit-test.js
  src/framework/xr/xr-image-tracking.js
  src/framework/xr/xr-input-source.js
  src/framework/xr/xr-input.js
  src/framework/xr/xr-joint.js
  src/framework/xr/xr-light-estimation.js
  src/framework/xr/xr-manager.js
  src/framework/xr/xr-mesh-detection.js
  src/framework/xr/xr-mesh.js
  src/framework/xr/xr-plane-detection.js
  src/framework/xr/xr-plane.js
  src/framework/xr/xr-tracked-image.js
  src/framework/xr/xr-view.js
  src/framework/xr/xr-views.js
  src/platform/input/game-pads.js
  src/scene/scene.js
  src/scene/skybox/sky.js
Labels: enhancement

#6178 Misc type fixes
  extras/gizmo/gizmo.js
  src/core/core.js
  src/core/object-pool.js
  src/core/read-stream.js
  src/core/shape/plane.js
  src/framework/script/script-registry.js
  src/platform/graphics/depth-state.js
  src/platform/graphics/uniform-buffer-format.js
  src/platform/graphics/version.js
Labels: bug

#6179 Improve typing for Anim APIs
  src/framework/anim/controller/anim-controller.js
  src/framework/anim/controller/anim-transition.js
  src/framework/components/anim/component-layer.js
Labels: bug, docs

#6180 Improve docs for Entity#destroy
  src/framework/entity.js
  src/scene/graph-node.js
Labels: bug, docs

#6181 WebXR XRSession.enabledFeatures missing workaround
  examples/src/examples/xr/ar-anchors-persistence/example.mjs
  examples/src/examples/xr/ar-hit-test-anchors/example.mjs
  examples/src/examples/xr/ar-hit-test/example.mjs
  package.json
  src/framework/xr/xr-anchors.js
  src/framework/xr/xr-hit-test.js
  src/framework/xr/xr-mesh-detection.js
  src/framework/xr/xr-plane-detection.js
  src/framework/xr/xr-views.js
Labels: bug, area: xr

#6183 A simple compute example, support for compute parameters
  examples/src/examples/compute/texture-gen/config.mjs
  examples/src/examples/compute/texture-gen/example.mjs
  examples/thumbnails/compute_texture-gen_large.webp
  examples/thumbnails/compute_texture-gen_small.webp
  src/platform/graphics/compute.js
  src/platform/graphics/webgpu/webgpu-shader.js
Labels: area: graphics, enhancement

#6185 More docs and types improvements
  src/platform/input/controller.js
  src/platform/net/http.js
  src/platform/sound/listener.js
  src/platform/sound/sound.js
  src/scene/mesh.js
Labels: bug, docs

#6186 Compute shaders support Uniform Buffer (WebGPU)
  examples/assets/models/icosahedron.glb
  examples/assets/models/icosahedron.txt
  examples/src/examples/compute/texture-gen/config.mjs
  examples/src/examples/compute/texture-gen/example.mjs
  examples/thumbnails/compute_texture-gen_large.webp
  examples/thumbnails/compute_texture-gen_small.webp
  src/platform/graphics/compute.js
  src/platform/graphics/webgpu/webgpu-compute.js
  src/platform/graphics/webgpu/webgpu-shader.js
  src/platform/graphics/webgpu/webgpu-uniform-buffer.js
Labels: area: graphics, enhancement

#6188 Remove json model mesh splitting to work around uniform limits
  src/deprecated/deprecated.js
  src/framework/parsers/json-model.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/skin-partition.js
Labels: area: graphics, enhancement

#6187 Dispatch multiple compute shaders in a single compute pass
  examples/src/examples/compute/texture-gen/config.mjs
  examples/src/examples/compute/texture-gen/example.mjs
  src/platform/graphics/bind-group-format.js
  src/platform/graphics/compute.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgpu/webgpu-compute.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics, enhancement

#6192 Fix example linting and remove unused packages
  examples/package-lock.json
  examples/package.json
  examples/src/app/components/CodeEditor.mjs
  examples/src/app/components/MainLayout.mjs
  examples/src/app/components/Menu.mjs
  examples/src/examples/animation/blend-trees-2d-cartesian/controls.mjs
  examples/src/examples/animation/events/example.mjs
  examples/src/examples/animation/layer-masks/example.mjs
  examples/src/examples/animation/locomotion/example.mjs
  examples/src/examples/animation/tween/example.mjs
  examples/src/examples/graphics/area-picker/example.mjs
  examples/src/examples/graphics/clustered-area-lights/example.mjs
  examples/src/examples/graphics/contact-hardening-shadows/example.mjs
  examples/src/examples/graphics/dithered-transparency/example.mjs
  examples/src/examples/graphics/grab-pass/example.mjs
  examples/src/examples/graphics/model-outline/example.mjs
  examples/src/examples/graphics/particles-random-sprites/example.mjs
  examples/src/examples/graphics/reflection-box/example.mjs
  examples/src/examples/graphics/reflection-planar/example.mjs
  examples/src/examples/graphics/taa/controls.mjs
  examples/src/examples/misc/gizmos/controls.mjs
  examples/src/examples/misc/mini-stats/example.mjs
  examples/src/examples/misc/spineboy/example.mjs
  examples/src/examples/physics/falling-shapes/example.mjs
  examples/src/examples/physics/raycast/example.mjs
  examples/src/examples/xr/ar-plane-detection/example.mjs
  examples/src/examples/xr/xr-hands/config.mjs
  examples/src/examples/xr/xr-hands/example.mjs
  examples/utils.mjs
Labels: bug, area: examples

#6197 Upgrade Chai to 5.x
  package-lock.json
  package.json
  tests/karma.conf.cjs
  tests/setup.js
Labels: enhancement

#6200 Small fixes to jsdocs
  src/framework/app-base.js
  src/framework/components/light/component.js
Labels: bug, docs

#6202 Simplify jsdocs types for the Mesh and VertexIterators API
  src/platform/graphics/vertex-iterator.js
  src/scene/mesh.js
Labels: docs

#6204 Use indexed rendering for gplats
  src/scene/gsplat/gsplat-instance.js
Labels: performance, area: graphics

#6206 Removed undollar script
  package.json
  src/framework/handlers/texture.js
  src/framework/parsers/texture/basis.js
  src/framework/parsers/texture/dds.js
  src/framework/parsers/texture/hdr.js
  src/framework/parsers/texture/img.js
  src/framework/parsers/texture/ktx.js
  src/framework/parsers/texture/ktx2.js
  src/framework/parsers/texture/texture.js
  src/index.js
  utils/types-undollar.mjs
Labels: enhancement

#6203 Tri class to core engine
  extras/gizmo/gizmo.js
  extras/gizmo/mesh-tri-data.js
  extras/gizmo/tri.js
  src/core/math/vec3.js
  src/core/shape/tri.js
  src/index.js
Labels: enhancement
