Repository playcanvas/engine, pull requests merged in 2024-05, with the labels that each got.

#6327 Remove parts of shader chunks only used on WebGL1
  examples/src/examples/graphics/grab-pass/config.mjs
  src/extras/gizmo/axis-shapes.js
  src/scene/shader-lib/chunks/common/frag/linearizeDepth.js
  src/scene/shader-lib/chunks/common/frag/msdf.js
  src/scene/shader-lib/chunks/common/frag/screenDepth.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLightShadows.js
  src/scene/shader-lib/chunks/lit/frag/shadowCascades.js
  src/scene/shader-lib/chunks/lit/frag/shadowPCSS.js
  src/scene/shader-lib/chunks/lit/frag/shadowStandard.js
Labels: area: graphics, enhancement

#6329 Remove support for few remaining WebGL1 extensions
  examples/src/examples/graphics/multi-render-targets/example.mjs
  src/deprecated/deprecated.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/null/null-graphics-device.js
  src/platform/graphics/render-target.js
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-render-target.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics, enhancement

#6330 Removed WebGL1 clustered lighting fallback for storing floats in 8bit texture
  examples/scripts/thumbnails.mjs
  src/scene/lighting/lights-buffer.js
  src/scene/morph.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#6333 Small refactor to separate composition update from framegraph building
  src/framework/app-base.js
  src/scene/renderer/forward-renderer.js
Labels: area: graphics, enhancement

#6331 Adding thumbnails for particle mesh example
  examples/thumbnails/graphics_particles-mesh_large.webp
  examples/thumbnails/graphics_particles-mesh_small.webp
Labels: area: examples

#6296 Bundled build options
  build.mjs
  examples/rollup.config.js
  rollup.config.mjs
  utils/rollup-build-target.mjs
Labels: enhancement

#6336 Remove final WebGL1 extensions and simplify code that used them
  src/deprecated/deprecated.js
  src/platform/graphics/blend-state.js
  src/platform/graphics/constants.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/null/null-graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/area-light-luts.js
  src/scene/constants.js
  src/scene/graphics/env-lighting.js
  src/scene/gsplat/gsplat.js
  src/scene/materials/material.js
  src/scene/morph.js
  src/scene/renderer/shadow-map.js
  src/scene/shader-lib/chunks/lit/frag/ltc.js
  src/scene/shader-lib/chunks/lit/frag/shadowPCSS.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#6340 Build fixes
  examples/rollup.config.js
  package.json
  rollup.config.mjs
  tsconfig.build.json
  utils/plugins/rollup-types-fixup.mjs
  utils/rollup-build-target.mjs
Labels: bug

#6341 Initial refactor to how bind groups can be used with non-persistent UBs
  src/platform/graphics/bind-group.js
  src/platform/graphics/dynamic-buffer.js
  src/platform/graphics/dynamic-buffers.js
  src/platform/graphics/uniform-buffer.js
  src/platform/graphics/webgpu/webgpu-bind-group.js
  src/platform/graphics/webgpu/webgpu-clear-renderer.js
  src/platform/graphics/webgpu/webgpu-dynamic-buffer.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: performance, area: graphics

#6343 Examples removed linux chrome fallback
  examples/iframe/utils.mjs
Labels: bug

#6348 Updated one missed VSM shader chunk for WebGPU compatibility
  src/scene/shader-lib/chunks/lit/frag/shadowEVSM.js
Labels: bug, area: graphics

#6353 Fix: Clean up lines for rendering even when the Layer is disabled
  src/scene/immediate/immediate-batch.js
  src/scene/immediate/immediate-batches.js
  src/scene/immediate/immediate.js
Labels: bug, area: graphics

#6349 Updated the way WebGPU dynamic UBs are used for rendering
  examples/src/examples/compute/particles.example.mjs
  examples/src/examples/compute/particles.shader-rendering.wgsl
  examples/src/examples/graphics/wgsl-shader.example.mjs
  examples/src/examples/graphics/wgsl-shader.shader.wgsl
  src/platform/graphics/constants.js
  src/platform/graphics/shader-processor.js
  src/platform/graphics/webgpu/webgpu-clear-renderer.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
  src/scene/graphics/quad-render.js
  src/scene/mesh-instance.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
Labels: performance, area: graphics, enhancement

#6351 Added docs for supported HDR formats
  src/platform/graphics/graphics-device.js
  src/platform/graphics/texture.js
Labels: docs, area: graphics

#6356 Remove handling of WebGL1 seamless cubemap sampling
  src/framework/handlers/cubemap.js
  src/platform/graphics/texture.js
  src/scene/graphics/env-lighting.js
  src/scene/graphics/reproject-texture.js
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/fixCubemapSeamsNone.js
  src/scene/shader-lib/chunks/common/frag/fixCubemapSeamsStretch.js
  src/scene/shader-lib/chunks/common/frag/reproject.js
  src/scene/shader-lib/chunks/lit/frag/reflectionCube.js
  src/scene/shader-lib/chunks/lit/frag/reflectionEnvHQ.js
  src/scene/shader-lib/chunks/skybox/frag/skyboxHDR.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/skybox.js
  src/scene/skybox/sky-mesh.js
Labels: area: graphics, enhancement

#6354 Fix buildUrl relative path support
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: bug, area: graphics

#6362 Reordered export types
  package.json
Labels: bug

#6391 Fix for glb load error
  src/framework/parsers/glb-container-resource.js
Labels: area: gltf

#6392 Fixing random JSDoc issues
  src/framework/asset/asset-reference.js
  src/framework/components/button/component.js
  src/framework/components/camera/component.js
  src/framework/components/light/component.js
  src/platform/graphics/graphics-device.js
  src/scene/graph-node.js
  src/scene/mesh-instance.js
  src/scene/renderer/forward-renderer.js
  src/scene/skin-instance.js
Labels: bug, docs

#6397 Fix for reloaded cubemaps assets
  src/framework/handlers/cubemap.js
Labels: bug

#6371 Render compressed GS data
  src/framework/parsers/gsplat-resource.js
  src/framework/parsers/ply.js
  src/scene/gsplat/gsplat-compressed-material.js
  src/scene/gsplat/gsplat-compressed.js
  src/scene/gsplat/gsplat-data.js
  src/scene/gsplat/gsplat-instance.js
  src/scene/gsplat/gsplat-material.js
  src/scene/gsplat/gsplat.js
  src/scene/gsplat/shader-generator-gsplat.js
Labels: area: graphics, enhancement

#6398 Remove last direct mentions of GL1
  README.md
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/gsplat/gsplat-instance.js
  src/scene/renderer/shadow-map.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#6402 Fix for gsplat shader
  src/scene/gsplat/shader-generator-gsplat.js
Labels: area: graphics

#6401 Fix device update in engine v1
  examples/iframe/utils.mjs
Labels: bug

#6404 Examples device selector fix main_v1
  examples/README.md
  examples/iframe/utils.mjs
  examples/src/examples/graphics/integer-textures.example.mjs
  examples/src/examples/graphics/transform-feedback.example.mjs
Labels: bug

#6406 Removed unused `extension` chunks
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/extension.js
  src/scene/shader-lib/chunks/lit/vert/extension.js
Labels: area: graphics

#6409 gs reorder fix
  src/scene/gsplat/gsplat-data.js
Labels: bug

#6410 GS reorder fix
  src/scene/gsplat/gsplat-data.js
Labels: bug, area: gltf

#6394 USDZ / GLTF exporter supports exposing of compressed textures on WebGPU
  examples/src/examples/loaders/gltf-export.example.mjs
  src/extras/exporters/core-exporter.js
Labels: area: gltf, enhancement

#6587 Gizmo Axis shape disable fix
  src/extras/gizmo/axis-shapes.js
Labels: bug

#6590 Gsplat rendering fix
  src/scene/gsplat/gsplat-data.js
  src/scene/gsplat/gsplat.js
  src/scene/gsplat/shader-generator-gsplat.js
Labels: bug, area: graphics

#6592 [Fix] Add missing exposure handling from the Neutral tonemapping
  src/scene/shader-lib/chunks/common/frag/tonemappingNeutral.js
Labels: bug, area: graphics

#6408 [BREAKING] Removed backwards compatibility for few functions
  src/framework/components/anim/component-layer.js
  src/framework/graphics/picker.js
  src/platform/graphics/render-target.js
  src/platform/graphics/texture.js
  src/platform/graphics/vertex-buffer.js
  src/scene/graphics/reproject-texture.js
  src/scene/morph-target.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/standard/frag/textureSample.js
  src/scene/shader-lib/programs/standard.js
Labels: docs

#6593 Fix to just submitted AO example to disabled baked in occlusion maps
  examples/src/examples/graphics/ambient-occlusion.example.mjs
Labels: bug, area: examples

#6594 Examples app bundle v1
  examples/package-lock.json
  examples/package.json
  examples/rollup.config.js
  examples/src/app/components/DeviceSelector.mjs
  examples/src/app/constants.mjs
Labels: enhancement

#6363 Publint CI
  .github/workflows/ci.yml
  .github/workflows/publish.yaml
  package.json
Labels: github_actions

#6595 Publint CI v1
  .github/workflows/ci.yml
  .github/workflows/publish.yaml
  package.json
Labels: github_actions

#6596 Fix types for calcAabb functions
  src/scene/gsplat/gsplat-data.js
Labels: bug

#6601 Treeshake plugin fix
  utils/plugins/rollup-treeshake-ignore.mjs
Labels: bug

#6603 Treeshake plugin fix v1
  utils/plugins/rollup-treeshake-ignore.mjs
Labels: bug

#6604 Examples iframe params fix
  examples/iframe/loader.mjs
Labels: bug

#6605 Examples iframe params fix v1
  examples/iframe/loader.mjs
Labels: bug

#6602 New texture formats: R8 and RG8
  src/platform/graphics/constants.js
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/constants.js
  src/scene/lighting/world-clusters.js
Labels: area: graphics, enhancement

#6607 Gizmo orthogonal facing direction translation
  examples/src/examples/misc/gizmos.controls.mjs
  src/extras/gizmo/axis-shapes.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: enhancement

#6621 Shader chunks type
  src/scene/shader-lib/chunks/chunks.js
Labels: bug

#6622 Gizmo example update
  examples/iframe/example.css
  examples/src/examples/misc/gizmos.example.mjs
  examples/src/examples/misc/gizmos.grid.mjs
  examples/src/examples/misc/gizmos.selector.mjs
Labels: bug, enhancement

#6623 Exports and types fixes
  examples/jsconfig.json
  package.json
  tsconfig.json
Labels: bug, enhancement

#6624 Exports and types fixes v1
  examples/jsconfig.json
  package.json
  tsconfig.json
Labels: bug, enhancement

#6629 Device Selector fallback options fix v1
  examples/src/app/components/DeviceSelector.mjs
Labels: bug

#6634 Examples imports fixes
  examples/iframe/observer.mjs
  examples/iframe/utils.mjs
  examples/jsconfig.json
  examples/package-lock.json
  examples/package.json
Labels: bug, area: examples

#6635 Examples imports fixes v1
  examples/iframe/observer.mjs
  examples/iframe/utils.mjs
  examples/jsconfig.json
  examples/package-lock.json
  examples/package.json
Labels: bug, area: examples

#6637 Examples gizmo selection fix
  examples/src/examples/misc/gizmos.selector.mjs
Labels: bug, area: examples

#6639 Fix URL handling in ScriptHandler
  src/framework/handlers/script.js
Labels: bug

#6640 First person script update
  examples/assets/models/fps-map.glb
  examples/assets/models/fps-map.txt
  examples/src/examples/camera/first-person.example.mjs
  examples/thumbnails/camera_first-person_large.webp
  examples/thumbnails/camera_first-person_small.webp
  scripts/camera/first-person-camera.js
Labels: area: scripts, area: examples

#6643 Fix transform not destroyed on Ammo Hull creation
  src/framework/components/collision/system.js
Labels: area: physics, open source contribution
