Repository playcanvas/engine, pull requests merged in 2024-02, with the labels that each got.

#6031 Extracted renderForwardLayer function to the renderer
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/render-pass-forward.js
Labels: area: graphics, enhancement

#6032 [Examples] Integer-texture (sand) Remove the quad mouse movement.
  examples/src/examples/graphics/integer-textures.mjs
Labels: area: examples, enhancement

#6033 GSplat mateirlal can create a PICK shader pass version of the shader
  src/scene/gsplat/shader-generator-gsplat.js
Labels: area: graphics, enhancement

#6034 Load compressed ply elements by default
  src/framework/parsers/ply.js
Labels: bug

#6035 Small refactor to ForwardRenderer.renderForwardLayer to allow additional options
  src/framework/lightmapper/render-pass-lightmapper.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/render-pass-forward.js
Labels: area: graphics, enhancement

#6037 Small clean up to depth rendering
  extras/render-passes/render-pass-camera-frame.js
  src/scene/graphics/render-pass-depth.js
  src/scene/mesh-instance.js
  src/scene/particle-system/particle-emitter.js
  src/scene/skybox/sky-mesh.js
Labels: area: graphics, enhancement

#6039 Make sure render pass name is valid for derived classes
  src/platform/graphics/render-pass.js
  src/platform/graphics/uniform-buffer.js
Labels: bug, area: graphics

#6040 RenderPassPrepass implementation
  examples/src/examples/graphics/post-processing.mjs
  extras/render-passes/render-pass-camera-frame.js
  extras/render-passes/render-pass-prepass.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/render-pass-forward.js
Labels: feature request, area: graphics

#6044 Examples WebGPU fix
  examples/iframe/example.html
Labels: bug, area: examples

#5574 Change ResourceHandler from interface to base class
  src/framework/handlers/anim-clip.js
  src/framework/handlers/anim-state-graph.js
  src/framework/handlers/animation.js
  src/framework/handlers/audio.js
  src/framework/handlers/binary.js
  src/framework/handlers/bundle.js
  src/framework/handlers/container.js
  src/framework/handlers/css.js
  src/framework/handlers/cubemap.js
  src/framework/handlers/folder.js
  src/framework/handlers/font.js
  src/framework/handlers/gsplat.js
  src/framework/handlers/handler.js
  src/framework/handlers/hierarchy.js
  src/framework/handlers/html.js
  src/framework/handlers/json.js
  src/framework/handlers/material.js
  src/framework/handlers/model.js
  src/framework/handlers/render.js
  src/framework/handlers/scene-settings.js
  src/framework/handlers/scene.js
  src/framework/handlers/script.js
  src/framework/handlers/shader.js
  src/framework/handlers/sprite.js
  src/framework/handlers/template.js
  src/framework/handlers/text.js
  src/framework/handlers/texture-atlas.js
  src/framework/handlers/texture.js
  utils/types-fixup.mjs
Labels: area: assets

#6046 [Fix] Fix to render composion update if multiple cameras use render passes
  src/scene/composition/layer-composition.js
Labels: bug, area: graphics

#6036 Gizmo grid and mesh shaders
  examples/src/examples/misc/gizmos.mjs
  extras/gizmo/axis-shapes.js
  extras/gizmo/default-colors.js
  extras/gizmo/rotate-gizmo.js
  extras/gizmo/scale-gizmo.js
  extras/gizmo/transform-gizmo.js
  extras/gizmo/translate-gizmo.js
Labels: area: graphics

#6051 Add Asset category for API reference
  src/framework/asset/asset-list-loader.js
  src/framework/asset/asset-reference.js
  src/framework/asset/asset-registry.js
  src/framework/asset/asset.js
  src/framework/asset/constants.js
Labels: docs, enhancement

#6057 publish on a new tag
  .github/workflows/publish.yaml
Labels: enhancement

#6063 ResourceHandler type fix (constructor parameters)
  src/framework/handlers/anim-clip.js
  src/framework/handlers/anim-state-graph.js
  src/framework/handlers/animation.js
  src/framework/handlers/audio.js
  src/framework/handlers/binary.js
  src/framework/handlers/bundle.js
  src/framework/handlers/container.js
  src/framework/handlers/css.js
  src/framework/handlers/cubemap.js
  src/framework/handlers/folder.js
  src/framework/handlers/font.js
  src/framework/handlers/gsplat.js
  src/framework/handlers/handler.js
  src/framework/handlers/hierarchy.js
  src/framework/handlers/html.js
  src/framework/handlers/json.js
  src/framework/handlers/material.js
  src/framework/handlers/model.js
  src/framework/handlers/render.js
  src/framework/handlers/scene-settings.js
  src/framework/handlers/scene.js
  src/framework/handlers/script.js
  src/framework/handlers/shader.js
  src/framework/handlers/sprite.js
  src/framework/handlers/template.js
  src/framework/handlers/text.js
  src/framework/handlers/texture-atlas.js
  src/framework/handlers/texture.js
Labels: bug

#6064 Small cleanup of SkinInstance
  src/scene/renderer/renderer.js
  src/scene/skin-instance.js
Labels: area: graphics, enhancement

#5818 Mesh collision improvements
  src/framework/components/collision/data.js
  src/framework/components/collision/system.js
Labels: area: physics

#6066 Fix issue with script name casing
  src/framework/handlers/script.js
Labels: bug, area: scripts

#6071 Update to WGSL shader creation - formats are passed in the shaderDefinition
  examples/src/examples/graphics/wgsl-shader.mjs
  src/index.js
  src/platform/graphics/webgpu/webgpu-shader.js
  src/scene/materials/material.js
  src/scene/shader-lib/utils.js
Labels: area: graphics

#6073 Added ES6 bundle output
  package.json
  rollup.config.mjs
  utils/rollup-build-target.mjs
Labels: area: scripts

#6074 WebXR - expose framebuffer scale factor
  src/framework/xr/xr-manager.js
Labels: area: xr, enhancement

#6076 Link WebGL shaders immediately after compilation
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-shader.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: performance, area: graphics

#6083 Small shader initialization cleanup / optimization
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-shader.js
Labels: performance, area: graphics

#6080 Object entries polyfill
  src/index.js
  src/polyfill/object-entries.js
Labels: bug

#6086 Remove section on source maps from README
  README-ja.md
  README-kr.md
  README-zh.md
  README.md
Labels: docs

#6089 When WebGPU validation fails, current markers are logged out
  examples/src/examples/graphics/shapes/example.mjs
  src/platform/graphics/webgpu/webgpu-debug.js
Labels: area: graphics, enhancement

#6091 Fix ENV var target
  rollup.config.mjs
Labels: bug

#6092 Assert when current version of Ammo does not implement now required triMesh.getIndexedMeshArray
  src/framework/components/collision/system.js
Labels: area: physics

#6093 [Fix] WebGPU mesh rendering uses primitive.base correctly
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: bug, area: graphics

#6087 Mesh collision optimization
  src/framework/components/collision/system.js
Labels: performance, area: physics

#6090 Add rollup import transform
  utils/rollup-build-target.mjs
  utils/rollup-dynamic-import-transform.mjs
Labels: bug

#6099 Allow graphics device to be provided to Application
  src/framework/application.js
Labels: area: graphics

#6103 WebGPU Transpiler absolute path
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics, enhancement

#6101 Small change to splat shader in a way model matrix is used
  examples/src/examples/loaders/gsplat-many/example.mjs
  src/scene/gsplat/shader-generator-gsplat.js
Labels: area: graphics
