Repository playcanvas/engine, pull requests merged in 2024-01, with the labels that each got.

#5923 Fix all linting errors in the examples
  .github/workflows/ci.yml
  examples/assets/scripts/asset-loader.js
  examples/rollup.config.js
  examples/src/importmap.js
  examples/src/pathes.js
Labels: bug, area: examples

#5887 WebXR HitTestSource fix
  examples/src/examples/xr/ar-hit-test.mjs
  src/framework/xr/xr-hit-test-source.js
  src/framework/xr/xr-hit-test.js
  src/framework/xr/xr-input-source.js
Labels: bug, area: xr

#5929 Fix thumbnail creation on Windows
  examples/scripts/thumbnails.mjs
Labels: bug, area: examples

#5919 Fix npm run build:thumbnails
  examples/rollup.config.js
Labels: bug, area: examples

#5915 Call adjustVramSizeTracking for WebGPU textures
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: bug, area: graphics

#5930 Correctly flip the depth texture in drawDepthTexture
  src/scene/immediate/immediate.js
Labels: bug, area: graphics

#5931 For WebGPU render to low res buffer to make PointCloudSimulation example visible
  examples/src/examples/graphics/point-cloud-simulation.mjs
Labels: area: graphics

#5932 WebGPU device exposes fragment/vertex-UniformsCount property
  examples/src/examples/sound/positional.mjs
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/reflectionSphereLow.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#5922 Show configurable example descriptions
  examples/scripts/generate-standalone-files.mjs
  examples/src/app/example.mjs
  examples/src/examples/animation/component-properties.mjs
  examples/src/static/styles.css
Labels: feature request, area: examples

#5920 Add example with multiple applications at the same time
  examples/scripts/generate-standalone-files.mjs
  examples/src/app/example.mjs
  examples/src/examples/misc/index.mjs
  examples/src/examples/misc/mini-stats.mjs
  examples/src/examples/misc/multi-app.mjs
  scripts/animation/tween.js
  src/scene/lighting/lights-buffer.js
Labels: area: examples

#5936 Store default instancing vertex format in device cache
  src/platform/graphics/vertex-format.js
Labels: area: graphics

#5935 Refactor of static functions of the LightsBuffer to avoid issues on the null device
  src/framework/app-base.js
  src/scene/lighting/lights-buffer.js
  src/scene/lighting/world-clusters.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#5941 Updated dithered transparency to support blue noise
  examples/src/examples/graphics/dithered-transparency.mjs
  extras/splat/shader-generator-splat.js
  extras/splat/splat-instance.js
  extras/splat/splat-material.js
  src/core/math/blue-noise.js
  src/scene/constants.js
  src/scene/graphics/blue-noise-texture.js
  src/scene/materials/lit-material.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-parameters.js
  src/scene/materials/standard-material.js
  src/scene/renderer/renderer.js
  src/scene/shader-lib/chunks/standard/frag/opacity-dither.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/standard.js
  test/scene/materials/standard-material.test.mjs
  utils/types-fixup.mjs
Labels: feature request, area: graphics

#5945 Small cleanup to splat rendering related to changes to dithering
  examples/src/examples/loaders/splat.mjs
  extras/splat/splat-data.js
  extras/splat/splat-instance.js
  extras/splat/splat-material.js
Labels: bug, area: graphics

#5946 Examples ar-link flag
  examples/scripts/generate-standalone-files.mjs
  examples/src/examples/loaders/gltf-export.mjs
  examples/src/examples/loaders/usdz-export.mjs
Labels: bug

#5947 Fixed name capitalization for Upsample and Downsample render passes
  extras/index.js
  extras/render-passes/render-pass-bloom.js
  extras/render-passes/render-pass-downsample.js
  extras/render-passes/render-pass-upsample.js
Labels: bug, area: graphics

#5952 [Fix] Fix additional shaders getting processed on WebGPU
  src/platform/graphics/shader-processor-options.js
  src/platform/graphics/vertex-format.js
Labels: bug, area: graphics

#5848 WebXR Depth Camera
  examples/src/examples/xr/ar-camera-depth.mjs
  examples/src/examples/xr/ar-depth-sensing-placer.mjs
  examples/src/examples/xr/index.mjs
  src/framework/xr/xr-depth-sensing.js
  src/framework/xr/xr-manager.js
  src/framework/xr/xr-view.js
  src/framework/xr/xr-views.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
Labels: feature request, area: xr

#5954 JSDocs for extras/exporters
  extras/exporters/core-exporter.js
  extras/exporters/gltf-exporter.js
  extras/exporters/usdz-exporter.js
Labels: area: graphics

#5956 Few additional dummy functions on the NullGraphicsDevice to handle engine examples failing.
  src/platform/graphics/null/null-graphics-device.js
Labels: bug, area: graphics

#5928 Gizmo System
  examples/src/examples/misc/gizmos.mjs
  examples/src/examples/misc/index.mjs
  extras/gizmo/axis-shapes.js
  extras/gizmo/gizmo-rotate.js
  extras/gizmo/gizmo-scale.js
  extras/gizmo/gizmo-transform.js
  extras/gizmo/gizmo-translate.js
  extras/gizmo/gizmo.js
  extras/gizmo/mesh-tri-data.js
  extras/gizmo/tri.js
  extras/index.js
  scripts/camera/orbit-camera.js
  src/scene/procedural.js
Labels: feature request, area: graphics, area: input, area: examples

#5959 Add module docs
  extras/index.js
  src/index.js
Labels: docs

#5957 Remove VertexArrayObject polyfill for IE11
  src/index.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/polyfill/OESVertexArrayObject.js
Labels: area: graphics

#5960 Fixes to automated testing to work without VAO extension
  src/platform/graphics/webgl/webgl-vertex-buffer.js
Labels: bug, area: graphics

#5953 Partial support for Lightmapper on WebGPU
  examples/src/examples/graphics/lights-baked-a-o.mjs
  examples/src/examples/graphics/lights-baked.mjs
  src/framework/lightmapper/lightmapper.js
  src/framework/lightmapper/render-pass-lightmapper.js
  src/scene/shader-lib/chunks/common/vert/transform.js
  src/scene/shader-lib/chunks/lightmapper/frag/bilateralDeNoise.js
  src/scene/shader-lib/chunks/lightmapper/frag/dilate.js
Labels: feature request, area: graphics

#5961 Use spread to handle variadic args of path.join
  src/core/path.js
Labels: docs

#5962 Updated babel target list to exlude dead browsers (IE11)
  utils/rollup-es5-options.mjs
Labels: performance

#5965 Small update to JSDocs of the exporters
  extras/exporters/core-exporter.js
  extras/exporters/gltf-exporter.js
  extras/exporters/usdz-exporter.js
Labels: docs

#5969 Expose EventHandle
  src/index.js
Labels: bug

#5970 Fix initial value of _assetReference in RenderComponent
  src/framework/components/render/component.js
Labels: bug, docs

#5974 Refactor JSDocs for events
  src/core/tags.js
  src/framework/asset/asset-registry.js
  src/framework/asset/asset.js
  src/framework/components/button/component.js
  src/framework/components/collision/component.js
  src/framework/components/element/component.js
  src/framework/components/element/element-drag-helper.js
  src/framework/components/rigid-body/component.js
  src/framework/components/rigid-body/system.js
  src/framework/components/script/component.js
  src/framework/components/scroll-view/component.js
  src/framework/components/scrollbar/component.js
  src/framework/components/sound/component.js
  src/framework/components/sound/slot.js
  src/framework/components/sprite/component.js
  src/framework/components/sprite/sprite-animation-clip.js
  src/framework/components/zone/component.js
  src/framework/entity.js
  src/framework/script/script-type.js
  src/framework/xr/xr-anchor.js
  src/framework/xr/xr-anchors.js
  src/framework/xr/xr-depth-sensing.js
  src/framework/xr/xr-hand.js
  src/framework/xr/xr-hit-test-source.js
  src/framework/xr/xr-hit-test.js
  src/framework/xr/xr-image-tracking.js
  src/framework/xr/xr-input-source.js
  src/framework/xr/xr-input.js
  src/framework/xr/xr-light-estimation.js
  src/framework/xr/xr-manager.js
  src/framework/xr/xr-mesh-detection.js
  src/framework/xr/xr-mesh.js
  src/framework/xr/xr-plane-detection.js
  src/framework/xr/xr-plane.js
  src/framework/xr/xr-tracked-image.js
  src/framework/xr/xr-view.js
  src/framework/xr/xr-views.js
  src/platform/graphics/graphics-device.js
  src/platform/input/game-pads.js
  src/platform/input/keyboard.js
  src/platform/input/mouse.js
  src/platform/sound/instance.js
  src/scene/render.js
  src/scene/scene.js
Labels: docs

#5977 Improve TypeDoc categories
  src/platform/graphics/graphics-device-create.js
  src/platform/input/touch-event.js
  src/scene/graphics/quad-render-utils.js
  src/scene/graphics/reproject-texture.js
  src/scene/procedural.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/utils.js
Labels: docs

#5976 GSplatComponent that allows native integration of splat tech with the Entity
  examples/src/examples/loaders/gsplat-many.mjs
  examples/src/examples/loaders/gsplat.mjs
  scripts/camera/orbit-camera.js
  src/framework/components/gsplat/component.js
  src/framework/components/gsplat/data.js
  src/framework/components/gsplat/system.js
  src/framework/entity.js
  src/framework/handlers/gsplat.js
  src/framework/parsers/gsplat-resource.js
  src/index.js
  src/scene/gsplat/gsplat-instance.js
  src/scene/gsplat/gsplat.js
  src/scene/mesh-instance.js
  src/scene/renderer/renderer.js
Labels: feature request, area: graphics

#5978 Small fix just introduced related to updating splat instances
  src/scene/renderer/renderer.js
Labels: bug, area: graphics

#5979 Fix the Sky example - it no longer needs to registerPlyParser
  examples/src/examples/graphics/sky.mjs
Labels: bug, area: examples

#5980 Adding GSplatComponentSystem to the Application by default
  src/framework/application.js
Labels: bug, area: graphics

#5982 Slight modifications to LoadersGL example to work on WebGPU
  examples/src/examples/loaders/loaders-gl.mjs
Labels: area: examples

#5981 Gizmos - Added render update event
  examples/src/examples/misc/gizmos.mjs
  extras/gizmo/gizmo.js
  extras/gizmo/rotate-gizmo.js
  extras/gizmo/transform-gizmo.js
Labels: feature request, area: graphics

#5984 Gizmo view
  extras/gizmo/gizmo.js
Labels: area: graphics

#5983 Exposed temporary API for custom shaders for the splat rendering
  examples/src/examples/loaders/gsplat-many.mjs
  src/framework/components/gsplat/component.js
  src/scene/gsplat/gsplat-instance.js
  src/scene/gsplat/gsplat.js
Labels: area: graphics

#5987 GSplat gizmo bug fixes
  examples/src/examples/misc/gizmos.mjs
  extras/gizmo/axis-shapes.js
  extras/gizmo/gizmo.js
  extras/gizmo/mesh-tri-data.js
  extras/gizmo/scale-gizmo.js
Labels: bug, area: graphics

#5988 Reverting recent glb alpha depth write change for transparent meshes
  src/framework/parsers/glb-parser.js
Labels: bug, area: graphics

#5990 Avoid using WebGPU 'timestamp-query' which has been removed in Chrome 121
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics

#5991 Small clean up and improvements to the MultiApplication example
  examples/src/examples/misc/multi-app.mjs
Labels: area: examples

#5992 Removed GraphicsDeviceAccess class used for compatibility reasons
  src/deprecated/deprecated.js
  src/framework/app-base.js
  src/framework/globals.js
  src/platform/graphics/graphics-device-access.js
  src/scene/mesh.js
  src/scene/morph.js
  src/scene/scene.js
Labels: area: graphics

#5994 [Fix] DepthGrab now supports render target without stencil
  examples/src/examples/graphics/post-effects.mjs
  src/scene/graphics/render-pass-depth-grab.js
Labels: bug, area: graphics

#5997 Simple polish to the IntegerTextures example
  examples/src/examples/graphics/integer-textures.mjs
Labels: area: examples

#5996 Polish to the texture-array engine example
  examples/src/examples/graphics/texture-array.mjs
Labels: area: examples

#5995 Gizmo transform shape toggling
  extras/gizmo/axis-shapes.js
  extras/gizmo/gizmo.js
  extras/gizmo/rotate-gizmo.js
  extras/gizmo/scale-gizmo.js
  extras/gizmo/transform-gizmo.js
  extras/gizmo/translate-gizmo.js
Labels: feature request, area: graphics

#6000 Export Gizmo constants correctly
  extras/gizmo/gizmo.js
  extras/index.js
Labels: bug

#5999 Gizmo uniform scaling update
  extras/gizmo/scale-gizmo.js
  extras/gizmo/transform-gizmo.js
Labels: area: graphics

#6008 Fix Gizmo nodes type
  extras/gizmo/gizmo.js
Labels: bug

#6010 Add API docs for MiniStats
  extras/mini-stats/mini-stats.js
Labels: docs

#6012 Assign categories to constants
  src/core/constants.js
  src/core/math/constants.js
  src/core/math/float-packing.js
  src/core/math/math.js
  src/core/tracing.js
  src/framework/anim/constants.js
  src/framework/anim/controller/constants.js
  src/framework/components/button/constants.js
  src/framework/components/element/constants.js
  src/framework/components/layout-group/constants.js
  src/framework/components/rigid-body/constants.js
  src/framework/components/screen/constants.js
  src/framework/components/script/component.js
  src/framework/components/script/system.js
  src/framework/components/scroll-view/constants.js
  src/framework/components/sprite/constants.js
  src/framework/handlers/script.js
  src/framework/script.js
  src/framework/script/script-attributes.js
  src/framework/script/script-registry.js
  src/framework/script/script-type.js
  src/framework/script/script.js
  src/framework/xr/constants.js
  src/platform/audio/constants.js
  src/platform/graphics/constants.js
  src/platform/input/constants.js
  src/scene/constants.js
  src/scene/shader-lib/utils.js
Labels: docs

#6013 Fix some developer site links
  src/framework/components/script-legacy/component.js
  src/framework/components/script-legacy/system.js
  src/scene/lighting/lighting-params.js
  src/scene/shader-lib/chunks/chunk-validation.js
Labels: docs

#6015 [Fix[ Fixed incorrect test for enabled shadow dithering
  src/scene/shader-lib/programs/standard.js
Labels: bug, area: graphics

#6014 Update some links embedded in the source
  src/core/math/math.js
  src/framework/components/element/component.js
  src/framework/components/rigid-body/component.js
  src/platform/input/keyboard.js
  src/scene/mesh.js
  src/scene/shader-lib/chunks/common/frag/reproject.js
  src/scene/shader-lib/chunks/skybox/vert/skybox.js
Labels: bug, docs

#6016 [Fix] Temporary fix to lightmapper for WebGL
  src/framework/lightmapper/lightmapper.js
Labels: bug, area: graphics

#6017 [Fix examples] Change the path to make sure it deploys
  examples/rollup.config.js
  examples/src/app/code-editor.mjs
Labels: bug, area: examples

#6007 Fix engine example ExampleOptions params
  examples/README.md
  examples/src/examples/animation/blend-trees-1d.mjs
  examples/src/examples/animation/layer-masks.mjs
  examples/src/examples/animation/locomotion.mjs
  examples/src/examples/camera/first-person.mjs
  examples/src/examples/camera/fly.mjs
  examples/src/examples/camera/orbit.mjs
  examples/src/examples/graphics/clustered-area-lights.mjs
  examples/src/examples/graphics/lights.mjs
  examples/src/examples/graphics/mesh-decals.mjs
  examples/src/examples/graphics/mesh-deformation.mjs
  examples/src/examples/graphics/video-texture.mjs
  examples/src/examples/input/keyboard.mjs
  examples/src/examples/loaders/gltf-export.mjs
  examples/src/examples/loaders/gsplat-many.mjs
  examples/src/examples/loaders/gsplat.mjs
  examples/src/examples/loaders/obj.mjs
  examples/src/examples/loaders/usdz-export.mjs
  examples/src/examples/misc/mini-stats.mjs
  examples/src/examples/physics/offset-collision.mjs
  examples/src/examples/physics/raycast.mjs
  examples/src/examples/physics/vehicle.mjs
  examples/src/examples/user-interface/button-basic.mjs
  examples/src/examples/user-interface/button-sprite.mjs
  examples/src/examples/xr/ar-anchors-persistence.mjs
  examples/src/examples/xr/ar-basic.mjs
  examples/src/examples/xr/ar-camera-color.mjs
  examples/src/examples/xr/ar-camera-depth.mjs
  examples/src/examples/xr/ar-depth-sensing-placer.mjs
  examples/src/examples/xr/ar-hit-test-anchors.mjs
  examples/src/examples/xr/ar-hit-test.mjs
  examples/src/examples/xr/ar-mesh-detection.mjs
  examples/src/examples/xr/ar-plane-detection.mjs
  examples/src/examples/xr/vr-basic.mjs
  examples/src/examples/xr/vr-controllers.mjs
  examples/src/examples/xr/vr-hands.mjs
  examples/src/examples/xr/vr-movement.mjs
  examples/src/examples/xr/xr-picking.mjs
  examples/src/options.mjs
Labels: area: examples

#6021 Expose docs for GSplatResource and GSplatComponent
  src/framework/parsers/gsplat-resource.js
  src/index.js
Labels: docs, area: graphics

#6001 Implement changes to WebGPU timestamp-query
  src/platform/graphics/webgpu/webgpu-gpu-profiler.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: bug, area: graphics

#6025 Double buffer TAA’s accumulation buffer in preparation for last frame reprojection
  extras/render-passes/render-pass-bloom.js
  extras/render-passes/render-pass-camera-frame.js
  extras/render-passes/render-pass-taa.js
Labels: area: graphics

#6005 Examples cleanup
  examples/scripts/example-data.mjs
  examples/scripts/example-directory.mjs
  examples/scripts/generate-standalone-files.mjs
  examples/scripts/thumbnails.mjs
  examples/src/app/MainLayout.mjs
  examples/src/app/code-editor.mjs
  examples/src/app/device-selector.mjs
  examples/src/app/error-boundary.mjs
  examples/src/app/events.js
  examples/src/app/example.mjs
  examples/src/app/helpers/example-data.mjs
  examples/src/app/helpers/strings.mjs
  examples/src/app/iframeUtils.mjs
  examples/src/app/index.mjs
  examples/src/app/jsx.mjs
  examples/src/app/menu.mjs
  examples/src/app/polyfillFunctionCall.mjs
  examples/src/app/polyfills.mjs
  examples/src/app/sidebar.mjs
  examples/src/app/utils.mjs
  examples/src/assetPath.mjs
  examples/src/iframe/index.html
  examples/src/iframe/index.mjs
  examples/src/importmap.js
  examples/src/loadES5.mjs
Labels: feature request

#6027 Gizmo Ortho Rotation fixes
  examples/src/examples/misc/gizmos.mjs
  extras/gizmo/rotate-gizmo.js
  extras/gizmo/transform-gizmo.js
Labels: bug, area: graphics

#6029 Simplify RenderPassDepth to use automatic render target resizing provided by the base class
  src/platform/graphics/render-pass.js
  src/scene/graphics/render-pass-depth.js
  src/scene/renderer/forward-renderer.js
Labels: area: graphics, enhancement

#6023 Add support for debug rendering obbs
  src/framework/app-base.js
  src/scene/immediate/immediate.js
Labels: area: graphics, enhancement
