Repository playcanvas/engine, pull requests merged in 2025-08, with the labels that each got.

#7881 Generate intervals texture for unified splat copying on GPU
  examples/src/examples/gaussian-splatting/lod.example.mjs
  src/scene/gsplat/unified/gspat-state.js
  src/scene/gsplat/unified/gsplat-info.js
  src/scene/gsplat/unified/gsplat-interval-texture.js
  src/scene/gsplat/unified/gsplat-manager.js
  src/scene/gsplat/unified/gsplat-unified-sort-worker.js
  src/scene/shader-lib/glsl/chunks/gsplat/frag/gsplatIntervalTexture.js
  src/scene/shader-lib/wgsl/chunks/gsplat/frag/gsplatIntervalTexture.js
Labels: performance, area: graphics

#7883 Tweak contributing guide and PR template
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#7887 Gizmo updates
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: enhancement

#7889 Camera controls fixes
  scripts/esm/camera-controls.mjs
Labels: bug

#7891 First Person Controller script fixes
  scripts/esm/first-person-controller.mjs
Labels: bug

#7893 Initial implementaion of octree for unified GSplat rendering
  examples/assets/splats/lod/lod0.json
  examples/assets/splats/lod/lod1.json
  examples/assets/splats/lod/logo.gsplat-octree.json
  examples/assets/splats/lod/means_l.webp
  examples/assets/splats/lod/means_l_1.webp
  examples/assets/splats/lod/means_u.webp
  examples/assets/splats/lod/means_u_1.webp
  examples/assets/splats/lod/quats.webp
  examples/assets/splats/lod/quats_1.webp
  examples/assets/splats/lod/scales.webp
  examples/assets/splats/lod/scales_1.webp
  examples/assets/splats/lod/sh0.webp
  examples/assets/splats/lod/sh0_1.webp
  examples/src/examples/gaussian-splatting/lod.example.mjs
  src/framework/app-base.js
  src/framework/components/gsplat/component.js
  src/framework/components/gsplat/gsplat-asset-loader.js
  src/framework/components/gsplat/system.js
  src/framework/handlers/gsplat.js
  src/framework/parsers/gsplat-octree.js
  src/scene/gsplat-unified/gspat-state.js
  src/scene/gsplat-unified/gsplat-asset-loader-base.js
  src/scene/gsplat-unified/gsplat-centers-buffer.js
  src/scene/gsplat-unified/gsplat-director.js
  src/scene/gsplat-unified/gsplat-info.js
  src/scene/gsplat-unified/gsplat-interval-texture.js
  src/scene/gsplat-unified/gsplat-manager.js
  src/scene/gsplat-unified/gsplat-octree-instance.js
  src/scene/gsplat-unified/gsplat-octree-node.js
  src/scene/gsplat-unified/gsplat-octree.js
  src/scene/gsplat-unified/gsplat-octree.resource.js
  src/scene/gsplat-unified/gsplat-placement.js
  src/scene/gsplat-unified/gsplat-renderer.js
  src/scene/gsplat-unified/gsplat-unified-sort-worker.js
  src/scene/gsplat-unified/gsplat-unified-sorter.js
  src/scene/gsplat-unified/gsplat-work-buffer.js
  src/scene/gsplat/gsplat-resource-base.js
  src/scene/gsplat/gsplat-resource.js
  src/scene/gsplat/unified/gspat-state.js
  src/scene/gsplat/unified/gsplat-lod-blocks.js
  src/scene/gsplat/unified/gsplat-placement.js
  src/scene/layer.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
Labels: feature, area: graphics

#7894 Don’t allocate default clustered lighting textures when clustered lighting is disabled
  src/scene/renderer/renderer.js
  src/scene/renderer/world-clusters-allocator.js
Labels: area: graphics, enhancement

#7900 Examples browser version fixes
  examples/rollup.config.mjs
  examples/src/app/components/Sidebar.mjs
  examples/src/app/constants.mjs
  utils/rollup-version-revision.mjs
Labels: bug, enhancement

#7905 Don’t destroy SOGS packing shader
  src/scene/gsplat/gsplat-sogs-data.js
Labels: area: graphics, enhancement

#7908 Gizmo span line fix
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: bug

#7901 [Fix] Changes to ParticleEmitter to properly destroy the meshInstance
  src/scene/particle-system/particle-emitter.js
Labels: bug, area: particles

#7913 Unified gsplat - use render pass to update work buffer
  src/scene/gsplat-unified/gsplat-info.js
  src/scene/gsplat-unified/gsplat-manager.js
  src/scene/gsplat-unified/gsplat-work-buffer-render-pass.js
  src/scene/gsplat-unified/gsplat-work-buffer.js
  src/scene/gsplat/gsplat-compressed-resource.js
  src/scene/gsplat/gsplat-resource-base.js
  src/scene/gsplat/gsplat-resource.js
  src/scene/gsplat/gsplat-sogs-resource.js
Labels: performance, area: graphics

#7914 Fix - missed default render state set up for rendering of splats to work buffer
  src/scene/gsplat-unified/gsplat-work-buffer-render-pass.js
Labels: bug, area: graphics

#7916 Gizmo camera overlap fix
  examples/src/examples/gizmos/transform-scale.controls.mjs
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: bug, release: next minor

#7917 Gizmo examples camera controls
  examples/src/examples/gizmos/transform-rotate.example.mjs
  examples/src/examples/gizmos/transform-scale.example.mjs
  examples/src/examples/gizmos/transform-translate.example.mjs
  examples/src/examples/misc/editor.example.mjs
Labels: area: examples

#7918 Gizmo infinity fix
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: bug
