Repository playcanvas/engine, pull requests merged in 2025-05, with the labels that each got.

#7636 [Fix] Fixes tags for assets
  src/framework/asset/asset-registry.js
Labels: bug, area: assets

#7637 Fixed typo in shader ifdef from yesterday
  src/scene/shader-lib/chunks-wgsl/lit/frag/litMain.js
  src/scene/shader-lib/chunks/lit/frag/litMain.js
Labels: bug, area: graphics

#7638 Example to demonstrate standard material chunk overrides
  examples/src/examples/graphics/instancing-gooch.example.mjs
  examples/src/examples/shaders/trees.example.mjs
  examples/thumbnails/shaders_trees_large.webp
  examples/thumbnails/shaders_trees_small.webp
Labels: feature, area: examples

#7642 [Fix] UV-coordinates debug rendering fix
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#7648 First few gsplat chunks converted to WGSL
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/gsplat/frag/gsplat.js
  src/scene/shader-lib/chunks-wgsl/gsplat/vert/gsplat.js
  src/scene/shader-lib/chunks-wgsl/gsplat/vert/gsplatCommon.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatCommon.js
Labels: area: graphics, enhancement

#7651 Shader creation no longer supplies dummy shader in none is specified
  src/platform/graphics/shader-utils.js
  src/platform/graphics/transform-feedback.js
Labels: area: graphics, enhancement

#7652 Renamed internal class ShaderUtils to ShaderDefinitionUtils
  src/platform/graphics/shader-definition-utils.js
  src/platform/graphics/shader.js
  src/platform/graphics/transform-feedback.js
  src/scene/materials/shader-material.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/particle.js
  src/scene/shader-lib/programs/shader-generator-shader.js
  src/scene/shader-lib/programs/standard.js
  src/scene/shader-lib/utils.js
Labels: area: graphics, enhancement

#7655 Support for unfiltrable texture in WGSL
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/immediate/immediate.js
Labels: area: graphics, enhancement

#7657 [BREAKING] Deprecated pc.createShader and pc.createShaderFromCode
  examples/src/examples/graphics/integer-textures.example.mjs
  scripts/posteffects/posteffect-blend.js
  scripts/posteffects/posteffect-bloom.js
  scripts/posteffects/posteffect-bokeh.js
  scripts/posteffects/posteffect-brightnesscontrast.js
  scripts/posteffects/posteffect-edgedetect.js
  scripts/posteffects/posteffect-fxaa.js
  scripts/posteffects/posteffect-horizontaltiltshift.js
  scripts/posteffects/posteffect-huesaturation.js
  scripts/posteffects/posteffect-luminosity.js
  scripts/posteffects/posteffect-outline.js
  scripts/posteffects/posteffect-sepia.js
  scripts/posteffects/posteffect-ssao.js
  scripts/posteffects/posteffect-verticaltiltshift.js
  scripts/posteffects/posteffect-vignette.js
  src/extras/exporters/core-exporter.js
  src/extras/renderers/outline-renderer.js
  src/framework/lightmapper/lightmap-filters.js
  src/index.js
  src/platform/graphics/shader.js
  src/scene/graphics/quad-render.js
  src/scene/graphics/render-pass-shader-quad.js
  src/scene/graphics/reproject-texture.js
  src/scene/materials/lit-material.js
  src/scene/materials/shader-material.js
  src/scene/materials/standard-material.js
  src/scene/morph-instance.js
  src/scene/particle-system/particle-emitter.js
  src/scene/particle-system/particle-material.js
  src/scene/renderer/render-pass-cookie-renderer.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/shader-utils.js
  src/scene/shader-lib/utils.js
Labels: feature, area: graphics

#7662 Sogs updates
  src/framework/parsers/sogs.js
  src/scene/gsplat/gsplat-data.js
  src/scene/gsplat/gsplat-sogs-data.js
  src/scene/gsplat/gsplat-sogs.js
  src/scene/shader-lib/chunks-glsl/gsplat/vert/gsplatCommon.js
  src/scene/shader-lib/chunks-glsl/gsplat/vert/gsplatCompressedData.js
  src/scene/shader-lib/chunks-glsl/gsplat/vert/gsplatData.js
  src/scene/shader-lib/chunks-glsl/gsplat/vert/gsplatSogsColor.js
  src/scene/shader-lib/chunks-glsl/gsplat/vert/gsplatSogsData.js
  src/scene/shader-lib/chunks-glsl/gsplat/vert/gsplatSogsSH.js
Labels: area: graphics, enhancement

#7661 docs: Document i18n's `change` event
  src/framework/asset/asset-localized.js
  src/framework/components/element/text-element.js
  src/framework/i18n/i18n.js
  test/framework/components/element/text-element.test.mjs
Labels: docs, area: localisation, enhancement

#7653 Rename Key and Node classes
  src/deprecated/deprecated.js
  src/framework/handlers/animation.js
  src/index.js
  src/scene/animation/animation.js
Labels: docs, area: animation, enhancement

#7671 Strip comments from WGSL chunks
  utils/plugins/rollup-shader-chunks.mjs
Labels: enhancement

#7670 [Fix] Fix uniform access in a new WGSL shader chunk
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-forward/litForwardBackend.js
Labels: bug, area: graphics

#7675 [Fix] Fixed particles update speed on high refresh screens
  src/framework/components/particle-system/system.js
Labels: bug, area: particles

#7680 Improved docs for the physical camera properties
  src/framework/components/camera/component.js
Labels: docs

#7679 Improved docs for Material.setDefine
  src/scene/materials/material.js
Labels: docs

#7681 SOGS chunks in WGSL format
  src/scene/shader-lib/chunks-wgsl/gsplat/vert/gsplatSogsColor.js
  src/scene/shader-lib/chunks-wgsl/gsplat/vert/gsplatSogsData.js
  src/scene/shader-lib/chunks-wgsl/gsplat/vert/gsplatSogsSH.js
Labels: area: graphics, enhancement

#7683 Converted TextureArray and ShaderToon example to use WGSL
  examples/src/examples/graphics/shader-toon.example.mjs
  examples/src/examples/graphics/shader-toon.shader.glsl.frag
  examples/src/examples/graphics/shader-toon.shader.glsl.vert
  examples/src/examples/graphics/shader-toon.shader.wgsl.frag
  examples/src/examples/graphics/shader-toon.shader.wgsl.vert
  examples/src/examples/graphics/texture-array.example.mjs
  examples/src/examples/graphics/texture-array.ground.glsl.frag
  examples/src/examples/graphics/texture-array.ground.wgsl.frag
  examples/src/examples/graphics/texture-array.shader.glsl.frag
  examples/src/examples/graphics/texture-array.shader.glsl.vert
  examples/src/examples/graphics/texture-array.shader.wgsl.frag
  examples/src/examples/graphics/texture-array.shader.wgsl.vert
Labels: area: examples

#7687 Sogs load fix
  src/scene/gsplat/gsplat-sogs-data.js
Labels: bug, area: graphics

#7665 [BREAKING] New public API to customize shader chunks (Material and global)
  examples/src/examples/graphics/instancing-custom.example.mjs
  examples/src/examples/graphics/multi-render-targets.example.mjs
  examples/src/examples/shaders/trees.example.mjs
  examples/src/examples/test/shader-compile.example.mjs
  scripts/posteffects/posteffect-bokeh.js
  scripts/posteffects/posteffect-ssao.js
  src/deprecated/deprecated.js
  src/extras/exporters/core-exporter.js
  src/extras/render-passes/render-pass-compose.js
  src/extras/render-passes/render-pass-taa.js
  src/extras/renderers/outline-renderer.js
  src/framework/app-base.js
  src/framework/components/particle-system/system.js
  src/framework/lightmapper/lightmap-filters.js
  src/framework/lightmapper/lightmapper.js
  src/framework/parsers/material/json-standard-material.js
  src/index.js
  src/platform/graphics/constants.js
  src/platform/graphics/shader-definition-utils.js
  src/scene/graphics/reproject-texture.js
  src/scene/gsplat/gsplat-compressed.js
  src/scene/gsplat/gsplat-material.js
  src/scene/gsplat/gsplat-sogs.js
  src/scene/gsplat/gsplat.js
  src/scene/immediate/immediate.js
  src/scene/lighting/lights-buffer.js
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/material.js
  src/scene/materials/shader-material.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/morph-instance.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/render-pass-cookie-renderer.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/chunk-utils.js
  src/scene/shader-lib/chunks-glsl/chunk-validation.js
  src/scene/shader-lib/chunks-glsl/chunks.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/collections/particle-chunks-glsl.js
  src/scene/shader-lib/collections/particle-chunks-wgsl.js
  src/scene/shader-lib/collections/shader-chunks-glsl.js
  src/scene/shader-lib/collections/shader-chunks-wgsl.js
  src/scene/shader-lib/programs/lit-options-utils.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/particle.js
  src/scene/shader-lib/programs/shader-generator-shader.js
  src/scene/shader-lib/programs/standard.js
  src/scene/shader-lib/shader-chunk-map.js
  src/scene/shader-lib/shader-chunks.js
  src/scene/shader-lib/shader-utils.js
  src/scene/skybox/sky-mesh.js
  test/scene/materials/standard-material.test.mjs
Labels: feature, area: graphics

#7693 Quad vertex chunk cleanup
  examples/src/examples/graphics/render-pass.example.mjs
  examples/src/examples/shaders/integer-textures.example.mjs
  examples/thumbnails/shaders_integer-textures_large.webp
  examples/thumbnails/shaders_integer-textures_small.webp
  src/extras/render-passes/render-pass-coc.js
  src/extras/render-passes/render-pass-compose.js
  src/extras/render-passes/render-pass-depth-aware-blur.js
  src/extras/render-passes/render-pass-dof-blur.js
  src/extras/render-passes/render-pass-downsample.js
  src/extras/render-passes/render-pass-ssao.js
  src/extras/render-passes/render-pass-taa.js
  src/extras/render-passes/render-pass-upsample.js
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/graphics/render-pass-shader-quad.js
  src/scene/shader-lib/chunks-glsl/common/vert/quad.js
  src/scene/shader-lib/chunks-wgsl/common/vert/quad.js
  src/scene/shader-lib/collections/shader-chunks-glsl.js
  src/scene/shader-lib/collections/shader-chunks-wgsl.js
  src/scene/shader-lib/shader-utils.js
Labels: area: graphics, enhancement

#7694 Using more recent addition to createShader API from chunks where possible
  src/extras/exporters/core-exporter.js
  src/extras/renderers/outline-renderer.js
  src/scene/graphics/reproject-texture.js
  src/scene/particle-system/particle-emitter.js
  src/scene/renderer/render-pass-cookie-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: area: graphics, enhancement

#7696 Gsplat fix
  src/scene/shader-lib/glsl/chunks/gsplat/vert/gsplatCorner.js
  src/scene/shader-lib/wgsl/chunks/gsplat/vert/gsplatCorner.js
Labels: area: graphics

#7699 Some tiny cleanup
  examples/src/examples/graphics/render-to-texture.example.mjs
  examples/src/examples/materials/material-anisotropic.example.mjs
  src/scene/graphics/render-pass-shader-quad.js
Labels: area: graphics

#7700 Small tweaks to anisotropy examples
  examples/src/examples/materials/anisotropy-lamp.example.mjs
  examples/src/examples/materials/anisotropy-strength.example.mjs
  examples/src/examples/materials/material-anisotropic.example.mjs
Labels: area: examples

#7714 Better version of nearestPowerOfTwo function
  src/core/math/math.js
Labels: performance

#7710 WorldClusterDebug compatibility with WebGPU
  src/scene/lighting/world-clusters-debug.js
Labels: area: graphics, enhancement

#7711 Support for treeflame (Flamegraph) build size visualisation
  build.mjs
  package.json
  utils/rollup-build-target.mjs
Labels: enhancement

#7713 Fix: Dynamic batching now uses skinning normal for lighting
  src/scene/shader-lib/glsl/chunks/common/vert/normalCore.js
  src/scene/shader-lib/wgsl/chunks/common/vert/normalCore.js
Labels: bug, area: graphics

#7722 Shader transpilers are optional now for WebGPU
  examples/src/examples/materials/material-refraction.example.mjs
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-shader.js
Labels: area: graphics, enhancement

#7725 Quat dot product and lerp
  src/core/math/quat.js
Labels: feature
