Repository playcanvas/engine, pull requests merged in 2025-01, with the labels that each got.

#7246 Store PLY header comments
  src/framework/parsers/gsplat-resource.js
  src/framework/parsers/ply.js
Labels: area: graphics, enhancement

#7247 [Fix] HDR lightmap baking is working
  src/framework/lightmapper/lightmap-filters.js
  src/framework/lightmapper/lightmapper.js
  src/scene/shader-lib/chunks/lightmapper/frag/bilateralDeNoise.js
  src/scene/shader-lib/chunks/lightmapper/frag/dilate.js
Labels: bug, area: graphics

#7204 ButtonComponent remove EntityReference & optimize add/remove speed.
  src/framework/components/button/component.js
  src/framework/components/button/system.js
  src/framework/components/element/system.js
  src/framework/components/system.js
  src/framework/entity.js
  src/scene/graph-node.js
Labels: performance, area: ui

#7248 Support 1 and 2 bands of SH in uncompressed gsplat data
  src/scene/gsplat/gsplat-data.js
  src/scene/gsplat/gsplat.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatSH.js
Labels: bug, area: graphics

#7251 ESM Script clone fix
  src/framework/components/script/system.js
Labels: bug

#7253 Fix Apple Silicon Tests
  package-lock.json
  package.json
Labels: bug

#7254 Use Dependabot to update NPM dependencies
  .github/dependabot.yml
Labels: enhancement

#7256 [Fix] Remove PVRT texture formats with sRGB encoding as not supported on any platform
  src/platform/graphics/constants.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgpu/constants.js
Labels: bug, area: graphics

#7259 Expose PLY load progress
  src/framework/asset/asset.js
  src/framework/parsers/ply.js
Labels: enhancement

#7258 Overhaul of directional PCSS shadows
  examples/src/examples/graphics/light-physical-units.example.mjs
  examples/src/examples/graphics/shadow-soft.controls.mjs
  examples/src/examples/graphics/shadow-soft.example.mjs
  examples/thumbnails/graphics_shadow-soft_large.webp
  examples/thumbnails/graphics_shadow-soft_small.webp
  src/framework/components/light/component.js
  src/framework/components/light/data.js
  src/scene/constants.js
  src/scene/light.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-map.js
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/float-as-uint.js
  src/scene/shader-lib/chunks/lit/frag/shadowPCSS.js
  src/scene/shader-lib/chunks/lit/frag/shadowSoft.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: feature, area: graphics

#7265 Renovate: Pin `devDependencies`
  renovate.json
Labels: enhancement

#7268 Remove Dependabot
  .github/dependabot.yml
Labels: enhancement

#7269 Move renovate.json to .github folder
  .github/renovate.json
Labels: enhancement

#7271 Request new feature "float32-blendable" for WebGPU device
  src/platform/graphics/webgpu/webgpu-graphics-device.js
Labels: area: graphics, enhancement

#7272 Added DOF support to CameraFrame script
  scripts/utils/camera-frame.mjs
Labels: feature, area: graphics

#7275 Added PCSS option to ShadowCascades example
  examples/src/examples/graphics/shadow-cascades.controls.mjs
  examples/src/examples/graphics/shadow-cascades.example.mjs
Labels: area: examples, enhancement

#7276 Support chunks to be included by VS of ShaderMaterial
  src/scene/shader-lib/programs/shader-generator-shader.js
Labels: area: graphics, enhancement

#7274 [Fix] Fixes to an issue causing the fringing to be upside down when TAA is enabled on WebGPU
  src/extras/render-passes/render-pass-compose.js
Labels: bug, area: graphics

#7252 ESM First Person Controller
  examples/src/examples/camera/first-person.example.mjs
  scripts/camera/first-person-camera.js
  scripts/esm/first-person-controller.mjs
Labels: enhancement

#7147 ESM Grid Mesh Script
  eslint.config.mjs
  examples/src/examples/gizmos/transform-rotate.example.mjs
  examples/src/examples/gizmos/transform-scale.example.mjs
  examples/src/examples/gizmos/transform-translate.example.mjs
  examples/src/examples/misc/editor.controls.mjs
  examples/src/examples/misc/editor.example.mjs
  examples/src/examples/misc/editor.grid.mjs
  scripts/esm/grid.mjs
Labels: enhancement

#7279 ShaderMaterial shader generator - remove manually specified chunk includes
  src/scene/shader-lib/programs/shader-generator-shader.js
Labels: area: graphics, enhancement

#7280 ShaderMaterial generator provides GAMMA and TONEMAPPING defines to VS
  src/scene/constants.js
  src/scene/gsplat/gsplat-material.js
  src/scene/shader-lib/programs/shader-generator-shader.js
Labels: area: graphics, enhancement

#7205 Camera controls updates
  examples/iframe/example.css
  examples/iframe/example.html
  examples/src/examples/camera/fly.controls.mjs
  examples/src/examples/camera/fly.example.mjs
  examples/src/examples/camera/multi.controls.mjs
  examples/src/examples/camera/multi.example.mjs
  examples/src/examples/camera/orbit.controls.mjs
  examples/src/examples/camera/orbit.example.mjs
  examples/src/examples/misc/editor.example.mjs
  examples/src/examples/misc/editor.gizmo-handler.mjs
  examples/src/examples/misc/editor.selector.mjs
  scripts/esm/camera-controls.mjs
Labels: enhancement

#7283 GSplat shader fixes
  src/framework/asset/asset.js
  src/scene/gsplat/gsplat.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplat.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatCenter.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatSH.js
Labels: bug, area: graphics

#7284 Updates to material chunks override functionality
  src/scene/materials/lit-material.js
  src/scene/materials/material.js
  src/scene/materials/shader-material.js
  src/scene/materials/standard-material.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/shader-generator-shader.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7286 Small gsplat init update
  src/scene/gsplat/gsplat-sorter.js
Labels: bug, area: graphics

#7290 [Fix] Splat shader didn’t have gamma decode functions when gamma output is disabled
  src/scene/shader-lib/chunks/gsplat/vert/gsplatOutput.js
Labels: bug, area: graphics

#7292 Gsplat chunk fix
  examples/src/examples/loaders/gsplat-many.shader.vert
Labels: bug, area: graphics

#7294 [Fix] Fix frequent shader variant invalidation
  src/scene/materials/material.js
  src/scene/materials/standard-material.js
  src/scene/renderer/shadow-renderer.js
Labels: bug, area: graphics

#7293 First Person Controller fixes
  scripts/esm/first-person-controller.mjs
Labels: bug

#7298 Unified handling of core shader generation defines
  examples/src/examples/test/global-shader-properties.controls.mjs
  examples/src/examples/test/global-shader-properties.example.mjs
  examples/thumbnails/test_global-shader-properties_large.webp
  examples/thumbnails/test_global-shader-properties_small.webp
  scripts/esm/camera-frame.mjs
  scripts/utils/cubemap-renderer.js
  src/core/preprocessor.js
  src/extras/render-passes/render-pass-compose.js
  src/extras/renderers/outline-renderer.js
  src/platform/graphics/constants.js
  src/platform/graphics/shader.js
  src/scene/camera-shader-params.js
  src/scene/gsplat/gsplat-material.js
  src/scene/materials/lit-material.js
  src/scene/materials/shader-material.js
  src/scene/materials/standard-material.js
  src/scene/particle-system/particle-material.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/fog.js
  src/scene/shader-lib/chunks/common/frag/gamma.js
  src/scene/shader-lib/chunks/common/frag/gamma1_0.js
  src/scene/shader-lib/chunks/common/frag/gamma2_2.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatOutput.js
  src/scene/shader-lib/chunks/lit/frag/fogExp.js
  src/scene/shader-lib/chunks/lit/frag/fogExp2.js
  src/scene/shader-lib/chunks/lit/frag/fogLinear.js
  src/scene/shader-lib/chunks/lit/frag/fogNone.js
  src/scene/shader-lib/chunks/skybox/frag/skybox.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/particle.js
  src/scene/shader-lib/programs/shader-generator-shader.js
  src/scene/shader-lib/programs/shader-generator.js
  src/scene/shader-lib/programs/skybox.js
  src/scene/shader-lib/programs/standard.js
  src/scene/shader-lib/utils.js
  src/scene/shader-pass.js
  src/scene/skybox/sky-mesh.js
Labels: area: graphics, enhancement

#7300 [Fix] Texture created by TextureAtlas respects its initial settings
  src/framework/handlers/texture-atlas.js
Labels: bug, area: graphics

#7301 Replace skybox shader generator with a ShaderMaterial using few defines
  src/scene/shader-lib/chunks/skybox/frag/skybox.js
  src/scene/shader-lib/programs/skybox.js
  src/scene/skybox/sky-mesh.js
Labels: area: graphics, enhancement

#7303 [Fix] Preprocessor correctly updates position for text replacement
  src/core/preprocessor.js
Labels: bug, area: graphics

#7302 GsplatMaterial interally uses ShaderMaterial to generate variants
  src/scene/gsplat/gsplat-material.js
Labels: area: graphics, enhancement

#7305 WarnOnce in debug mode if material parameter is being set to undefined
  src/scene/materials/material.js
Labels: area: graphics, enhancement

#7306 Do not log warning when material data contains sheenGlossTint, which was removed
  src/scene/materials/standard-material-parameters.js
Labels: area: graphics

#7310 Shader WGSL example - split single shader into vertex and fragment
  examples/src/examples/graphics/wgsl-shader.example.mjs
  examples/src/examples/graphics/wgsl-shader.shader.frag.wgsl
  examples/src/examples/graphics/wgsl-shader.shader.vert.wgsl
Labels: area: examples

#7311 Fix some issues with CameraFrame.enabled not working correctly
  examples/src/examples/graphics/ambient-occlusion.controls.mjs
  examples/src/examples/graphics/ambient-occlusion.example.mjs
  examples/src/examples/graphics/post-processing.controls.mjs
  examples/src/examples/graphics/post-processing.example.mjs
  src/extras/render-passes/camera-frame.js
Labels: bug, area: graphics

#7081 View Cube extra
  examples/src/examples/misc/editor.controls.mjs
  examples/src/examples/misc/editor.example.mjs
  src/extras/gizmo/view-cube.js
  src/extras/index.js
Labels: enhancement

#7316 Exported ESM Scripts fixes
  scripts/esm/camera-controls.mjs
  scripts/esm/first-person-controller.mjs
  scripts/esm/xr-controllers.mjs
  scripts/esm/xr-navigation.mjs
Labels: bug

#7312 VecN/Color array conversion support
  src/core/math/color.js
  src/core/math/vec2.js
  src/core/math/vec3.js
  src/core/math/vec4.js
  test/core/math/color.test.mjs
  test/core/math/vec2.test.mjs
  test/core/math/vec3.test.mjs
  test/core/math/vec4.test.mjs
Labels: enhancement

#7313 Camera controls focus damping
  examples/src/examples/camera/multi.controls.mjs
  examples/src/examples/camera/multi.example.mjs
  examples/src/examples/camera/orbit.controls.mjs
  examples/src/examples/camera/orbit.example.mjs
  examples/src/examples/misc/editor.example.mjs
  scripts/esm/camera-controls.mjs
Labels: enhancement

#7322 [Fix] When CameraFrame is disabled, disable SSAO being applied during forward pass
  src/extras/render-passes/camera-frame.js
Labels: bug, area: graphics

#7321 Easier to override render pass used by the CameraFrame
  src/extras/index.js
  src/extras/render-passes/camera-frame.js
Labels: area: graphics, enhancement
