Repository playcanvas/engine, pull requests merged in 2025-02, with the labels that each got.

#7325 Fix to msdf chunk to handle gamma space correctly
  src/scene/shader-lib/chunks/common/frag/msdf.js
Labels: bug, area: graphics

#7323 Improvements to sRGB support by the Texture
  src/framework/handlers/basis-worker.js
  src/framework/handlers/basis.js
  src/platform/graphics/constants.js
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-texture.js
Labels: bug, area: graphics, enhancement

#7320 Improved support for WGSL shaders.
  examples/src/examples/compute/particles.example.mjs
  examples/src/examples/compute/particles.shader-rendering.fragment.wgsl
  examples/src/examples/compute/particles.shader-rendering.vertex.wgsl
  examples/src/examples/compute/particles.shader-rendering.wgsl
  examples/src/examples/graphics/wgsl-shader.example.mjs
  examples/src/examples/graphics/wgsl-shader.shader.frag.wgsl
  examples/src/examples/graphics/wgsl-shader.shader.vert.wgsl
  src/platform/graphics/bind-group-format.js
  src/platform/graphics/constants.js
  src/platform/graphics/shader-processor.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/shader.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-resolver.js
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/platform/graphics/webgpu/webgpu-shader.js
  src/scene/materials/shader-material.js
Labels: feature, area: graphics

#7329 Improvement to internal WGSL shader processing to only replace whole words
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
Labels: area: graphics

#7331 [BREAKING] ShaderMaterial no longer auto includes gamma, tonemapping and fog code
  examples/assets/scripts/misc/gooch-material.mjs
  examples/assets/scripts/misc/hatch-material.mjs
  examples/src/examples/graphics/reflection-planar.shader.frag
  examples/src/examples/graphics/shader-burn.shader.frag
  examples/src/examples/graphics/shader-toon.shader.frag
  examples/src/examples/graphics/shader-wobble.shader.frag
  examples/src/examples/graphics/shader-wobble.shader.vert
  examples/src/examples/graphics/texture-array.ground.frag
  examples/src/examples/graphics/texture-array.shader.frag
  src/extras/gizmo/shape/shape.js
  src/scene/immediate/immediate.js
  src/scene/materials/shader-material.js
  src/scene/shader-lib/chunks/common/frag/decode.js
  src/scene/shader-lib/chunks/common/frag/gamma.js
  src/scene/shader-lib/chunks/skybox/frag/skybox.js
  src/scene/shader-lib/programs/shader-generator-shader.js
Labels: area: graphics, enhancement

#7333 Outline renderer supports morphed models
  src/extras/renderers/outline-renderer.js
Labels: bug, area: graphics

#7336 When Texture.srgb is changed, shaders are reevaluated to be recreated
  src/platform/graphics/graphics-device.js
  src/platform/graphics/texture.js
  src/scene/renderer/renderer.js
Labels: area: graphics, enhancement

#7339 Gsplat material creation no longer set undefined parameters on the material
  src/scene/gsplat/gsplat.js
Labels: area: graphics

#7340 Make Batch.destroy public as it’s useful for destroying manually created batch groups
  src/scene/batching/batch.js
Labels: docs, area: graphics

#7341 Image Element mask fix
  src/framework/components/element/image-element.js
Labels: bug

#7342 [Fix] Fixes to processing WGSL shader
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
Labels: bug, area: graphics

#7344 Refactor fragment shader generation of lit-material for few passes
  src/platform/graphics/constants.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/storeEVSM.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/shader-generator.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7350 Preprocessor handles || and && in the expressions
  src/core/preprocessor.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  test/core/preprocessor.test.mjs
Labels: area: graphics, enhancement

#7355 Immediate line rendering on WebGPU uses native WGSL shader
  src/scene/immediate/immediate.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/internal/frag/immediateLine.js
  src/scene/shader-lib/chunks-wgsl/internal/vert/immediateLine.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/internal/frag/immediateLine.js
  src/scene/shader-lib/chunks/internal/vert/immediateLine.js
Labels: area: graphics, enhancement

#7356 Ministats rendering shader uses WGSL on WebGPU
  src/extras/mini-stats/render2d.js
Labels: area: graphics, enhancement

#7360 OutlineRenderer meshInstances null check
  src/extras/renderers/outline-renderer.js
Labels: bug

#7352 Partially refactored the lighting / shadowing part of the lit-shader generation
  src/platform/graphics/graphics-device.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/constants.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/spherical.js
  src/scene/shader-lib/chunks/lit/frag/lightSheen.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lightDeclaration.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lighting.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowCascades.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowEVSM.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowPCF1.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowPCF3.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowPCF5.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowPCSS.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowSampleCoord.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowSoft.js
  src/scene/shader-lib/chunks/lit/frag/shadowEVSM.js
  src/scene/shader-lib/chunks/lit/frag/shadowEVSMn.js
  src/scene/shader-lib/chunks/lit/frag/shadowVSM_common.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7354 Moved zero render target checked to a better place
  src/platform/graphics/webgl/webgl-render-target.js
Labels: bug, area: graphics

#7369 [Fix] Generate valid shader when multiple lights with cascades are used at the same time
  src/scene/shader-lib/programs/lit-shader.js
Labels: bug, area: graphics

#7372 [Fix] Fixed incorrect 2D texture array setup with compressed format
  src/platform/graphics/webgl/webgl-texture.js
Labels: bug, area: graphics

#7373 Avoid using __ in defines to avoid GLSL warning
  src/core/preprocessor.js
  src/scene/shader-lib/chunks-wgsl/skybox/frag/skybox.js
  src/scene/shader-lib/chunks/skybox/frag/skybox.js
  src/scene/skybox/sky-mesh.js
  test/core/preprocessor.test.mjs
Labels: area: graphics

#7362 Examples disable user selection
  examples/iframe/main.css
Labels: area: examples

#7375 [Fix] Fix to texture upload issue on WebGPU
  src/platform/graphics/texture.js
Labels: bug, area: graphics

#7376 Shader allocation tracing now logs the language used (GLSL / WGSL)
  src/platform/graphics/shader.js
Labels: area: graphics, enhancement

#7380 Fix gsplat rounding issues
  src/scene/gsplat/gsplat.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatData.js
Labels: bug, area: graphics

#7377 Improvements to Preprocessor - spaces after #else, comments in #include blocks
  src/core/preprocessor.js
  src/extras/render-passes/render-pass-compose.js
Labels: area: graphics, enhancement

#7383 Fix gsplat discoloration
  src/scene/gsplat/gsplat.js
Labels: bug, area: graphics

#7382 [Fix] Create a dummy framebuffer on NullDevice to avoid undefined access
  src/platform/graphics/null/null-graphics-device.js
Labels: bug, area: graphics

#7381 Lit/Standard material vertex shader is now a chunk driven by defines
  src/core/preprocessor.js
  src/framework/lightmapper/lightmapper.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/vert/base.js
  src/scene/shader-lib/chunks/lit/vert/baseNineSliced.js
  src/scene/shader-lib/chunks/lit/vert/end.js
  src/scene/shader-lib/chunks/lit/vert/litMain.js
  src/scene/shader-lib/chunks/lit/vert/start.js
  src/scene/shader-lib/chunks/lit/vert/uvTransform.js
  src/scene/shader-lib/chunks/lit/vert/uvTransformUniforms.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/standard.js
Labels: feature, area: graphics

#7385 A step towards converting lit-shader fragment generator to be define driven
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7386 Adjusted syntax of variables the preprocessor uses for injection
  src/core/preprocessor.js
  src/scene/shader-lib/chunks-wgsl/skybox/frag/skybox.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/chunks/lit/vert/uvTransform.js
  src/scene/shader-lib/chunks/lit/vert/uvTransformUniforms.js
  src/scene/shader-lib/chunks/skybox/frag/skybox.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/skybox/sky-mesh.js
  test/core/preprocessor.test.mjs
Labels: area: graphics, enhancement

#7387 Futher refactoring of fragment part of the lit-shader
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7388 Refactor the way lit-shader integrates lightmapping
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/lightmapAdd.js
  src/scene/shader-lib/chunks/lit/frag/lightmapDirAdd.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#7389 Refactoring of TBN shader part of lit-shader
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/TBN.js
  src/scene/shader-lib/chunks/lit/frag/TBNObjectSpace.js
  src/scene/shader-lib/chunks/lit/frag/TBNderivative.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement
