Repository playcanvas/engine, pull requests merged in 2025-10, with the labels that each got.

#8008 Avoid gl_DrawID related warning during shader setup
  src/platform/graphics/webgl/webgl-shader.js
Labels: enhancement, area: graphics

#8022 Small optimization in the way the number of rendered splats is rendered
  src/scene/gsplat-unified/gsplat-manager.js
  src/scene/gsplat-unified/gsplat-renderer.js
Labels: enhancement, area: graphics

#8031 Unified splats support radial sorting
  src/scene/gsplat-unified/gsplat-manager.js
  src/scene/gsplat-unified/gsplat-params.js
  src/scene/gsplat-unified/gsplat-unified-sort-worker.js
  src/scene/gsplat-unified/gsplat-unified-sorter.js
Labels: enhancement, area: graphics

#8032 Remove obsolete parts of JSDocs on an internal function in ShaderDefinition
  src/platform/graphics/shader-definition-utils.js
Labels: area: graphics

#8034 Fix: Morph weights now respect animation layer weights
  src/framework/anim/binder/default-anim-binder.js
  src/framework/anim/evaluator/anim-evaluator.js
  src/framework/anim/evaluator/anim-target.js
Labels: bug, area: animation

#8017 Support loading bundled sog from request
  src/framework/parsers/sog-bundle.js
Labels: bug, area: graphics

#8038 [Fix] WebGPU: Use textureLoad for data textures instead of textureSample
  src/scene/constants.js
  src/scene/light.js
  src/scene/shader-lib/wgsl/chunks/common/frag/screenDepth.js
  src/scene/shader-lib/wgsl/chunks/common/vert/skin.js
  src/scene/shader-lib/wgsl/chunks/common/vert/skinBatch.js
  src/scene/shader-lib/wgsl/chunks/gsplat/vert/gsplatColor.js
  src/scene/shader-lib/wgsl/chunks/gsplat/vert/gsplatCompressedData.js
  src/scene/shader-lib/wgsl/chunks/gsplat/vert/gsplatData.js
  src/scene/shader-lib/wgsl/chunks/gsplat/vert/gsplatWorkBuffer.js
  src/scene/shader-lib/wgsl/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/wgsl/chunks/particle/frag/particleInputFloat.js
  src/scene/shader-lib/wgsl/chunks/particle/frag/particleInputRgba8.js
  src/scene/shader-lib/wgsl/chunks/particle/frag/particleUpdaterInit.js
  src/scene/shader-lib/wgsl/chunks/particle/frag/particleUpdaterStart.js
  src/scene/shader-lib/wgsl/chunks/particle/vert/particle.js
  src/scene/shader-lib/wgsl/chunks/particle/vert/particle_cpu.js
  src/scene/shader-lib/wgsl/chunks/particle/vert/particle_init.js
Labels: bug, area: graphics
