Repository playcanvas/engine, pull requests merged in 2025-09, with the labels that each got.

#7935 Gizmo style updates
  examples/src/examples/gizmos/transform-rotate.controls.mjs
  examples/src/examples/gizmos/transform-rotate.example.mjs
  examples/src/examples/gizmos/transform-scale.controls.mjs
  examples/src/examples/gizmos/transform-scale.example.mjs
  examples/src/examples/gizmos/transform-translate.controls.mjs
  examples/src/examples/gizmos/transform-translate.example.mjs
  src/extras/gizmo/mesh-line.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/shaders.js
  src/extras/gizmo/shape/shape.js
Labels: enhancement, release: next minor

#7936 Unified splats - replaced temporary hardcoded distance ranged by proper evaluation
  src/framework/components/gsplat/component.js
  src/framework/components/gsplat/system.js
  src/scene/gsplat-unified/gsplat-director.js
  src/scene/gsplat-unified/gsplat-info.js
  src/scene/gsplat-unified/gsplat-manager.js
  src/scene/gsplat-unified/gsplat-octree-instance.js
  src/scene/gsplat-unified/gsplat-octree.resource.js
  src/scene/gsplat-unified/gsplat-placement.js
  src/scene/gsplat-unified/gsplat-unified-sort-worker.js
  src/scene/gsplat-unified/gsplat-unified-sorter.js
Labels: enhancement, area: graphics

#7938 Small fix for example shader
  examples/src/examples/gaussian-splatting/multi-splat.shader.vert
Labels: bug, area: graphics

#7939 [Fix] - Fix related to behavior change where texture array no longer needs manual upload
  examples/assets/scripts/misc/hatch-material.mjs
  examples/src/examples/loaders/loaders-gl.example.mjs
  examples/src/examples/shaders/texture-array.example.mjs
  src/platform/graphics/webgl/webgl-texture.js
  src/scene/morph.js
Labels: bug, area: graphics

#7941 Fix to CameraFrame script to not allow blurLevel of 0
  scripts/esm/camera-frame.mjs
Labels: bug, area: graphics

#7942 Add xr-session.mjs script
  scripts/esm/xr-session.mjs
Labels: area: scripts

#7946 Gizmo fixes and updates
  examples/src/examples/gizmos/transform-rotate.controls.mjs
  examples/src/examples/gizmos/transform-rotate.example.mjs
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/shaders.js
  src/extras/gizmo/shape/arc-shape.js
  src/extras/gizmo/shape/arrow-shape.js
  src/extras/gizmo/shape/box-shape.js
  src/extras/gizmo/shape/boxline-shape.js
  src/extras/gizmo/shape/plane-shape.js
  src/extras/gizmo/shape/shape.js
  src/extras/gizmo/shape/sphere-shape.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: bug, enhancement

#7951 Fixes to SOGS data unloading
  src/framework/asset/asset.js
  src/framework/parsers/sogs.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/gsplat/gsplat-sogs-data.js
Labels: bug, area: graphics

#7955 GSplat using streaming LOD supports unloading files no longer needed
  examples/src/examples/gaussian-splatting/lod.example.mjs
  src/core/constants.js
  src/framework/components/gsplat/gsplat-asset-loader.js
  src/scene/gsplat-unified/gsplat-asset-loader-base.js
  src/scene/gsplat-unified/gsplat-director.js
  src/scene/gsplat-unified/gsplat-manager.js
  src/scene/gsplat-unified/gsplat-octree-instance.js
  src/scene/gsplat-unified/gsplat-octree.js
  src/scene/gsplat-unified/gsplat-unified-sorter.js
  src/scene/gsplat-unified/gsplat-world-state.js
  src/scene/renderer/renderer.js
Labels: enhancement, area: graphics

#7960 Gizmo fixes
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: bug

#7959 Public API to control unified gsplat behavior
  examples/src/examples/gaussian-splatting/lod.controls.mjs
  examples/src/examples/gaussian-splatting/lod.example.mjs
  src/framework/components/gsplat/component.js
  src/scene/gsplat-unified/gsplat-director.js
  src/scene/gsplat-unified/gsplat-manager.js
  src/scene/gsplat-unified/gsplat-octree-instance.js
  src/scene/gsplat-unified/gsplat-params.js
  src/scene/gsplat-unified/gsplat-placement.js
  src/scene/gsplat-unified/gsplat-work-buffer-render-pass.js
  src/scene/gsplat-unified/gsplat-work-buffer.js
  src/scene/gsplat/gsplat-resource-base.js
  src/scene/scene.js
  src/scene/shader-lib/glsl/chunks/gsplat/frag/gsplatCopyToWorkbuffer.js
  src/scene/shader-lib/wgsl/chunks/gsplat/frag/gsplatCopyToWorkbuffer.js
Labels: enhancement, area: graphics

#7972 Fix SH bug on SOG import
  src/scene/gsplat/gsplat-sogs-data.js
Labels: bug, area: graphics

#7973 Remove allocations in camera controls
  scripts/esm/camera-controls.mjs
Labels: area: scripts

#7982 Fix for bundled SOG loading
  src/framework/parsers/sog-bundle.js
Labels: bug, area: graphics

#7984 Gizmo angle guide fix
  src/extras/gizmo/rotate-gizmo.js
Labels: bug, release: next patch, area: extras

#7988 Log an error if orthographic camera uses cascades shadows, which are not supported
  src/scene/renderer/forward-renderer.js
Labels: area: graphics

#7989 Expose compose shader customization along with the example
  examples/src/examples/graphics/custom-compose-shader.controls.mjs
  examples/src/examples/graphics/custom-compose-shader.example.mjs
  examples/thumbnails/graphics_custom-compose-shader_large.webp
  examples/thumbnails/graphics_custom-compose-shader_small.webp
  src/extras/render-passes/render-pass-compose.js
  src/scene/shader-lib/glsl/chunks/render-pass/frag/compose/compose.js
  src/scene/shader-lib/glsl/collections/compose-chunks-glsl.js
  src/scene/shader-lib/wgsl/chunks/render-pass/frag/compose/compose.js
  src/scene/shader-lib/wgsl/collections/compose-chunks-wgsl.js
Labels: enhancement, area: graphics, area: examples

#7981 Unified gsplat rendering fixes and optimizations
  examples/src/examples/gaussian-splatting/lod-instances.example.mjs
  examples/src/examples/gaussian-splatting/lod-streaming.controls.mjs
  examples/src/examples/gaussian-splatting/lod-streaming.example.mjs
  src/scene/gsplat-unified/gsplat-manager.js
  src/scene/gsplat-unified/gsplat-octree-instance.js
  src/scene/gsplat-unified/gsplat-octree.js
  src/scene/gsplat-unified/gsplat-renderer.js
  src/scene/gsplat-unified/gsplat-unified-sorter.js
Labels: bug, enhancement, area: graphics

#7999 Generate SOG centers buffer on GPU instead of CPU
  src/scene/gsplat-unified/gsplat-unified-sorter.js
  src/scene/gsplat/gsplat-compressed-data.js
  src/scene/gsplat/gsplat-data.js
  src/scene/gsplat/gsplat-resource-base.js
  src/scene/gsplat/gsplat-sogs-data.js
  src/scene/shader-lib/glsl/chunks/gsplat/frag/gsplatSogsCenters.js
  src/scene/shader-lib/wgsl/chunks/gsplat/frag/gsplatSogsCenters.js
Labels: performance, area: graphics

#8004 Multi-draw support, WebGL & WebGPU
  examples/assets/textures/terrain/Canyon-Diffuse.jpg
  examples/assets/textures/terrain/Canyon-Height.jpg
  examples/assets/textures/terrain/Canyon-textures.txt
  examples/src/examples/graphics/multi-draw-instanced.example.mjs
  examples/src/examples/graphics/multi-draw.example.mjs
  examples/thumbnails/graphics_multi-draw-instanced_large.webp
  examples/thumbnails/graphics_multi-draw-instanced_small.webp
  examples/thumbnails/graphics_multi-draw_large.webp
  examples/thumbnails/graphics_multi-draw_small.webp
  src/index.js
  src/platform/graphics/constants.js
  src/platform/graphics/draw-commands.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/null/null-draw-commands.js
  src/platform/graphics/null/null-graphics-device.js
  src/platform/graphics/webgl/webgl-draw-commands.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-draw-commands.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/mesh-instance.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: enhancement, area: graphics
