Repository playcanvas/engine, pull requests merged in 2025-06, with the labels that each got.

#7728 Removed optional precision specifier
  examples/src/examples/graphics/transform-feedback.shaderCloud.frag
  examples/src/examples/shaders/point-cloud-simulation.shader.frag
  examples/src/examples/shaders/shader-toon.shader.glsl.frag
Labels: area: examples

#7720 Added color correction using LUT texture to CameraFrame postprocessing
  examples/assets/cube-luts/lut-blue.png
  examples/src/examples/graphics/hdr.controls.mjs
  examples/src/examples/graphics/hdr.example.mjs
  scripts/esm/camera-frame.mjs
  src/extras/render-passes/camera-frame.js
  src/extras/render-passes/render-pass-compose.js
  src/scene/shader-lib/glsl/chunks/render-pass/frag/compose/compose-color-lut.js
  src/scene/shader-lib/glsl/chunks/render-pass/frag/compose/compose.js
  src/scene/shader-lib/glsl/collections/compose-chunks-glsl.js
  src/scene/shader-lib/wgsl/chunks/render-pass/frag/compose/compose-color-lut.js
  src/scene/shader-lib/wgsl/chunks/render-pass/frag/compose/compose.js
  src/scene/shader-lib/wgsl/collections/compose-chunks-wgsl.js
Labels: area: graphics, enhancement

#7729 Mesh-based Skydome can write depth during prepass, to be comparible with DOF
  examples/src/examples/graphics/shadow-catcher.controls.mjs
  examples/src/examples/graphics/shadow-catcher.example.mjs
  src/scene/shader-lib/glsl/chunks/skybox/frag/skybox.js
  src/scene/shader-lib/glsl/chunks/skybox/vert/skybox.js
  src/scene/shader-lib/wgsl/chunks/skybox/frag/skybox.js
  src/scene/shader-lib/wgsl/chunks/skybox/vert/skybox.js
  src/scene/skybox/sky-mesh.js
  src/scene/skybox/sky.js
Labels: area: graphics, area: examples, enhancement

#7735 Optimize shader generation with many clustered lights
  src/scene/materials/standard-material-options-builder.js
Labels: performance, area: graphics

#7738 Hiding test only examples
  examples/src/examples/test/material-test.example.mjs
  examples/src/examples/test/shader-compile.example.mjs
Labels: area: examples

#7740 Small update to OutlineRenderer to avoid runtime uniform warning
  src/extras/renderers/outline-renderer.js
Labels: area: graphics

#7745 Fix to no shadows from clustered lights in a specific case
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics

#7746 Moved matrix_normal uniform declaration to more appropriate chunk
  examples/src/examples/shaders/trees.example.mjs
  src/scene/shader-lib/glsl/chunks/common/vert/normalCore.js
  src/scene/shader-lib/glsl/chunks/common/vert/transformCore.js
  src/scene/shader-lib/wgsl/chunks/common/vert/normalCore.js
  src/scene/shader-lib/wgsl/chunks/common/vert/transformCore.js
Labels: area: graphics

#7749 [BREAKING] Update gsplat component material API
  examples/src/examples/loaders/gsplat-many.example.mjs
  src/framework/components/gsplat/component.js
  src/framework/components/gsplat/system.js
  src/scene/gsplat/gsplat-compressed-resource.js
  src/scene/gsplat/gsplat-instance.js
  src/scene/gsplat/gsplat-resource-base.js
  src/scene/gsplat/gsplat-resource.js
  src/scene/gsplat/gsplat-sogs-resource.js
  src/scene/shader-lib/programs/shader-generator-shader.js
Labels: area: graphics

#7747 WebGPU supports internal multi-view rendering used by WebXR
  examples/src/examples/graphics/instancing-glb.example.mjs
  examples/src/examples/test/xr-views.example.mjs
  examples/thumbnails/test_xr-views_large.webp
  examples/thumbnails/test_xr-views_small.webp
  src/framework/graphics/render-pass-picker.js
  src/platform/graphics/graphics-device.js
  src/platform/graphics/null/null-graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/renderer/forward-renderer.js
  src/scene/renderer/renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: feature, area: graphics

#7756 Convert internal configureMaterial function to use options
  src/scene/gsplat/gsplat-instance.js
Labels: area: graphics

#7758 [Fix] Re-render cookie atlas use by clastered lighting when the device context is restored
  src/scene/renderer/render-pass-cookie-renderer.js
Labels: bug, area: graphics

#7762 Handle passing null entity to OutlineRenderer
  src/extras/renderers/outline-renderer.js
Labels: area: scripts

#7763 Fix sogs reorder during device lost
  src/scene/gsplat/gsplat-sogs-data.js
Labels: area: graphics

#7767 Small jsdocs update regarding wasm transpilation requirements
  src/platform/graphics/graphics-device-create.js
Labels: docs

#7770 Support gsplat worker on nodejs
  src/scene/gsplat/gsplat-sorter.js
Labels: area: graphics, enhancement

#7775 Fix to anisotropy-lamp example - layer order changed for sky to be captured by grab pass
  examples/src/examples/materials/anisotropy-lamp.example.mjs
Labels: bug, area: graphics, area: examples

#7781 Limit large gaussians
  src/scene/shader-lib/glsl/chunks/gsplat/vert/gsplatCorner.js
  src/scene/shader-lib/wgsl/chunks/gsplat/vert/gsplatCorner.js
Labels: area: graphics

#7782 Add support for texture async write
  src/platform/graphics/texture.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/platform/graphics/webgl/webgl-texture.js
Labels: area: graphics

#7778 Additional frustum culling events in order to better support indirect drawing
  src/scene/constants.js
  src/scene/renderer/renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: area: graphics, enhancement

#7779 Inputs overhaul (CameraControls updated)
  examples/src/examples/camera/fly.controls.mjs
  examples/src/examples/camera/fly.example.mjs
  examples/src/examples/camera/multi.controls.mjs
  examples/src/examples/camera/multi.example.mjs
  examples/src/examples/camera/orbit.controls.mjs
  examples/src/examples/camera/orbit.example.mjs
  examples/src/examples/misc/editor.example.mjs
  scripts/esm/camera-controls.mjs
  src/extras/index.js
  src/extras/input/controllers/fly-controller.js
  src/extras/input/controllers/focus-controller.js
  src/extras/input/controllers/orbit-controller.js
  src/extras/input/input.js
  src/extras/input/math.js
  src/extras/input/pose.js
  src/extras/input/sources/dual-gesture-source.js
  src/extras/input/sources/gamepad-source.js
  src/extras/input/sources/keyboard-mouse-source.js
  src/extras/input/sources/multi-touch-source.js
  src/extras/input/sources/single-gesture-source.js
  src/extras/input/sources/virtual-joystick.js
Labels: enhancement

#7793 Fix WebGPU profiler
  src/platform/graphics/gpu-profiler.js
Labels: bug, area: graphics

#7804 Gizmo WGSL shaders
  src/extras/gizmo/shape/shape.js
Labels: enhancement

#7805 Grids script WGSL Shader
  scripts/esm/grid.mjs
Labels: enhancement
