Repository playcanvas/engine, pull requests merged in 2025-03, with the labels that each got.

#7391 9-Sliced UI rendering engine example + related shader fix
  examples/assets/button/grey_button.png
  examples/src/examples/user-interface/panel.controls.mjs
  examples/src/examples/user-interface/panel.example.mjs
  examples/thumbnails/user-interface_panel_large.webp
  examples/thumbnails/user-interface_panel_small.webp
  src/scene/shader-lib/chunks/lit/vert/litMain.js
Labels: bug, area: graphics, area: examples

#7390 LitShader generator refactoring - the main is a single string now
  src/scene/constants.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/refractionDynamic.js
  src/scene/shader-lib/chunks/lit/frag/start.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/shader-generator.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7393 Further litShader refactoring
  src/framework/lightmapper/lightmapper.js
  src/platform/graphics/shader.js
  src/scene/constants.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/cubeMapProject.js
  src/scene/shader-lib/chunks/lit/frag/cubeMapProjectBox.js
  src/scene/shader-lib/chunks/lit/frag/cubeMapProjectNone.js
  src/scene/shader-lib/chunks/lit/frag/outputAlpha.js
  src/scene/shader-lib/chunks/lit/frag/outputAlphaOpaque.js
  src/scene/shader-lib/chunks/lit/frag/outputAlphaPremul.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7395 Update to the way we strip unused MRT outputs
  src/core/preprocessor.js
  src/platform/graphics/shader-chunks/frag/gles3.js
  src/platform/graphics/shader-chunks/frag/webgpu.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7396 Further lit-shader refactoring
  src/scene/shader-lib/chunks/common/frag/msdf.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7399 Refactoring fo envMultiply and envConst chunks
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/envMultiply.js
  src/scene/shader-lib/chunks-wgsl/common/frag/envProc.js
  src/scene/shader-lib/chunks-wgsl/skybox/frag/skybox.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/envConst.js
  src/scene/shader-lib/chunks/common/frag/envMultiply.js
  src/scene/shader-lib/chunks/common/frag/envProc.js
  src/scene/shader-lib/chunks/skybox/frag/skybox.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics

#7400 Refactor specular occlusions shader chunks
  src/scene/constants.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/aoSpecOcc.js
  src/scene/shader-lib/chunks/lit/frag/aoSpecOccConst.js
  src/scene/shader-lib/chunks/lit/frag/aoSpecOccConstSimple.js
  src/scene/shader-lib/chunks/lit/frag/aoSpecOccSimple.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7405 [Fix] StandardMaterial.useTonemap parameter is no longer ignored
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#7407 [Fix] Fix reversed face culling when rendering shadows on WebGPU
  examples/src/examples/graphics/lights.example.mjs
  src/scene/renderer/shadow-renderer.js
Labels: bug, area: graphics

#7408 Refactor of lit-shader generator, mostly related to the ambient lighting
  src/scene/constants.js
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/envAtlas.js
  src/scene/shader-lib/chunks/lit/frag/ambient.js
  src/scene/shader-lib/chunks/lit/frag/ambientConstant.js
  src/scene/shader-lib/chunks/lit/frag/ambientEnv.js
  src/scene/shader-lib/chunks/lit/frag/ambientSH.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7409 Preprocessor reports errors in mismatched #ifdef #endif
  src/core/preprocessor.js
Labels: enhancement

#7414 Refactoring the lighting code from lit-shader to defines driven chunks
  examples/src/examples/graphics/lights.example.mjs
  src/core/preprocessor.js
  src/scene/constants.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lightDeclaration.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lightEvaluation.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lightFunction.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lighting.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowPCF1.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowPCF3.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowPCSS.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowSampleCoord.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7416 Finalizing the lit-shader refactoring by moving shader code to chunks
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgl/webgl-graphics-device.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardBackend.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardDeclaration.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardMain.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardPostCode.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardPreCode.js
  src/scene/shader-lib/chunks/lit/frag/pass-other/litOtherMain.js
  src/scene/shader-lib/chunks/lit/frag/pass-shadow/litShadowMain.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: feature, area: graphics

#7418 Refactor new and existing internal lighting related chunks to avoid globals
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLightShadows.js
  src/scene/shader-lib/chunks/lit/frag/lightDiffuseLambert.js
  src/scene/shader-lib/chunks/lit/frag/lightDirPoint.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lightEvaluation.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lightFunctionLight.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lightFunctionShadow.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lighting.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowCascades.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowEVSM.js
  src/scene/shader-lib/chunks/lit/frag/ltc.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardDeclaration.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7422 More configurable order for mesh rendering
  src/scene/constants.js
  src/scene/layer.js
  src/scene/mesh-instance.js
  src/scene/renderer/renderer.js
  src/scene/renderer/shadow-renderer.js
Labels: feature, area: graphics

#7424 Pin monaco version to 0.33.0
  examples/package-lock.json
  examples/package.json
Labels: bug

#7425 Gsplat viewport size fix
  src/scene/gsplat/gsplat-instance.js
Labels: bug, area: graphics

#7427 Outline renderer prepares even disabled entities
  src/extras/renderers/outline-renderer.js
Labels: area: examples, enhancement

#7429 Small refactor of internal reproject code / shader
  src/scene/graphics/reproject-texture.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/reproject.js
  src/scene/shader-lib/chunks/common/vert/reproject.js
Labels: area: graphics, enhancement

#7432 Gizmo doc example update
  src/extras/gizmo/gizmo.js
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/transform-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: docs

#7433 Fix to Lightmapper’s ambient baking when clustered lighting is enabled
  examples/src/examples/graphics/lights-baked-a-o.example.mjs
  examples/src/examples/graphics/lights-baked.example.mjs
  src/framework/lightmapper/bake-light.js
Labels: bug, area: graphics

#7434 Reproject texture functionality uses native WGSL shaders on WebGPU
  src/platform/graphics/shader-chunks/frag/shared-wgsl.js
  src/platform/graphics/shader-utils.js
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/graphics/reproject-texture.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/decode.js
  src/scene/shader-lib/chunks-wgsl/common/frag/encode.js
  src/scene/shader-lib/chunks-wgsl/common/frag/fog.js
  src/scene/shader-lib/chunks-wgsl/common/frag/gamma.js
  src/scene/shader-lib/chunks-wgsl/common/frag/tonemapping/tonemapping.js
  src/scene/shader-lib/chunks-wgsl/common/frag/tonemapping/tonemappingAces.js
  src/scene/shader-lib/chunks-wgsl/common/frag/tonemapping/tonemappingAces2.js
  src/scene/shader-lib/chunks-wgsl/common/frag/tonemapping/tonemappingFilmic.js
  src/scene/shader-lib/chunks-wgsl/common/frag/tonemapping/tonemappingHejl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/tonemapping/tonemappingLinear.js
  src/scene/shader-lib/chunks-wgsl/common/frag/tonemapping/tonemappingNeutral.js
  src/scene/shader-lib/chunks-wgsl/common/frag/tonemapping/tonemappingNone.js
  src/scene/shader-lib/chunks-wgsl/internal/frag/reproject.js
  src/scene/shader-lib/chunks-wgsl/internal/vert/reproject.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/internal/frag/reproject.js
  src/scene/shader-lib/chunks/internal/vert/reproject.js
  src/scene/shader-lib/utils.js
Labels: area: graphics, enhancement

#7436 Fixes to VSM shadow sampling
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowEVSM.js
Labels: bug, area: graphics

#7437 [FIX] Allow GSplatComponent#clone to handle null instance
  src/framework/components/gsplat/system.js
Labels: bug, area: graphics

#7442 Use less memory loading compressed.ply
  src/framework/parsers/ply.js
  src/scene/gsplat/gsplat-compressed-data.js
  src/scene/gsplat/gsplat-compressed.js
  src/scene/gsplat/gsplat.js
Labels: area: graphics, enhancement

#7443 Fix for recent change
  src/scene/gsplat/gsplat-compressed.js
  src/scene/gsplat/gsplat.js
Labels: bug, area: graphics

#7444 [Fix] NullGraphicsDevice initializes device caps
  src/platform/graphics/null/null-graphics-device.js
Labels: area: graphics

#7446 Small internal refactor of ShaderProcessor
  src/platform/graphics/bind-group-format.js
  src/platform/graphics/shader-processor-glsl.js
  src/platform/graphics/uniform-buffer-format.js
  src/platform/graphics/webgpu/webgpu-shader.js
Labels: area: graphics, enhancement

#7445 Convert internal morph target blending shader to WGSL on WebGPU
  src/platform/graphics/shader-chunks/frag/shared-wgsl.js
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/morph-instance.js
  src/scene/morph.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/internal/morph/frag/morph.js
  src/scene/shader-lib/chunks-wgsl/internal/morph/frag/morphDeclaration.js
  src/scene/shader-lib/chunks-wgsl/internal/morph/frag/morphEvaluation.js
  src/scene/shader-lib/chunks-wgsl/internal/morph/vert/morph.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/internal/morph/frag/morph.js
  src/scene/shader-lib/chunks/internal/morph/frag/morphDeclaration.js
  src/scene/shader-lib/chunks/internal/morph/frag/morphEvaluation.js
  src/scene/shader-lib/chunks/internal/morph/vert/morph.js
Labels: area: graphics, enhancement

#7449 Moved ShaderCompile example to test folder
  examples/src/examples/test/shader-compile.example.mjs
  examples/thumbnails/test_shader-compile_large.webp
  examples/thumbnails/test_shader-compile_small.webp
Labels: area: examples

#7448 Improved validation of vertex attributes required by the shader
  src/platform/graphics/graphics-device.js
  src/platform/graphics/shader-processor-glsl.js
  src/platform/graphics/shader.js
  src/platform/graphics/webgl/webgl-shader-input.js
  src/platform/graphics/webgl/webgl-shader.js
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/platform/graphics/webgpu/webgpu-shader.js
Labels: area: graphics

#7439 [FIX] Ensure base URL is correctly when origin is null
  src/framework/handlers/script.js
Labels: bug

#7452 Updated HDR example to not allow control for UI tonemapping
  examples/src/examples/graphics/hdr.controls.mjs
  examples/src/examples/graphics/hdr.example.mjs
Labels: bug, area: examples

#7465 [Fix] Fix to StandardMaterial.useFog being ignored
  src/scene/materials/standard-material.js
Labels: bug, area: graphics

#7464 [Fix] Clarified the docs for the sort order of drawBucket
  src/scene/mesh-instance.js
Labels: docs, area: graphics

#7461 Shadow casting support for gsplat
  examples/src/examples/loaders/gsplat.example.mjs
  src/framework/components/gsplat/component.js
  src/framework/components/gsplat/system.js
  src/scene/gsplat/gsplat-instance.js
  src/scene/shader-lib/chunks/gsplat/frag/gsplat.js
Labels: area: graphics

#7468 [Fix] Fix the high quality morph option on WebGPU
  src/scene/morph.js
  src/scene/shader-lib/chunks-wgsl/internal/morph/frag/morphEvaluation.js
  src/scene/shader-lib/chunks/internal/morph/frag/morphEvaluation.js
Labels: bug, area: graphics

#7469 [Fix] Fix soft shadows on iOS devices
  examples/src/examples/graphics/shadow-cascades.example.mjs
  src/scene/renderer/shadow-map.js
Labels: bug, area: graphics

#7470 Updated spine script to the latest release
  scripts/spine/playcanvas-spine.3.8.js
Labels: area: examples

#7459 Clustered lighting optimisations - removed WebGL1 compatibility solutions
  examples/src/examples/graphics/clustered-spot-shadows.controls.mjs
  examples/src/examples/graphics/clustered-spot-shadows.example.mjs
  src/core/math/float-packing.js
  src/scene/light.js
  src/scene/lighting/lights-buffer.js
  src/scene/lighting/world-clusters.js
  src/scene/renderer/renderer.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLight.js
  src/scene/shader-lib/chunks/lit/frag/clusteredLightCookies.js
  src/scene/shader-lib/chunks/lit/frag/float-unpacking.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lighting.js
Labels: performance, area: graphics

#7474 [Fix] Fixed part of the image being upside down on WebGPU with DOF and TAA
  src/extras/render-passes/render-pass-compose.js
Labels: bug, area: graphics

#7472 Gsplat sorting update
  src/scene/gsplat/gsplat-compressed-data.js
  src/scene/gsplat/gsplat-compressed.js
  src/scene/gsplat/gsplat-instance.js
  src/scene/gsplat/gsplat-sorter.js
Labels: area: graphics, enhancement

#7475 Remove console log
  src/scene/gsplat/gsplat-sorter.js
Labels: bug, area: graphics

#7476 [Fix] Clear index buffer when the draw call is skipped
  src/platform/graphics/graphics-device.js
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/scene/renderer/renderer.js
Labels: bug, area: graphics

#7478 WebGPU support for indexed rendering using triangle or line strips
  src/platform/graphics/webgpu/webgpu-graphics-device.js
  src/platform/graphics/webgpu/webgpu-render-pipeline.js
Labels: area: graphics, enhancement

#7479 Instantiate GLB's with correct AppBase instance
  src/framework/parsers/glb-container-resource.js
  test/framework/asset/asset-list-loader.test.mjs
Labels: area: assets

#7483 GSplat shaders can output depth during Depth Prepass
  src/scene/shader-lib/chunks/common/frag/float-as-uint.js
  src/scene/shader-lib/chunks/gsplat/frag/gsplat.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplat.js
  src/scene/shader-lib/chunks/lit/frag/pass-other/litOtherMain.js
Labels: area: graphics

#7485 Update API reference manual to match published version
  package-lock.json
  package.json
  tsconfig.json
  typedoc.json
  utils/typedoc/favicon.ico
  utils/typedoc/typedoc-plugin.mjs
Labels: docs, enhancement

#7488 [Fix] Fixed hanling of texture.type
  src/framework/handlers/texture.js
  src/platform/graphics/texture.js
Labels: bug, area: graphics, area: assets

#7487 [BREAKING] Refactor standard material chunks dealing with texture channels
  src/scene/materials/standard-material-options-builder.js
  src/scene/shader-lib/chunks/standard/frag/ao.js
  src/scene/shader-lib/chunks/standard/frag/aoDetailMap.js
  src/scene/shader-lib/chunks/standard/frag/clearCoat.js
  src/scene/shader-lib/chunks/standard/frag/clearCoatGloss.js
  src/scene/shader-lib/chunks/standard/frag/clearCoatNormal.js
  src/scene/shader-lib/chunks/standard/frag/diffuse.js
  src/scene/shader-lib/chunks/standard/frag/diffuseDetailMap.js
  src/scene/shader-lib/chunks/standard/frag/emissive.js
  src/scene/shader-lib/chunks/standard/frag/gloss.js
  src/scene/shader-lib/chunks/standard/frag/ior.js
  src/scene/shader-lib/chunks/standard/frag/iridescence.js
  src/scene/shader-lib/chunks/standard/frag/iridescenceThickness.js
  src/scene/shader-lib/chunks/standard/frag/lightmapDir.js
  src/scene/shader-lib/chunks/standard/frag/lightmapSingle.js
  src/scene/shader-lib/chunks/standard/frag/metalness.js
  src/scene/shader-lib/chunks/standard/frag/normalDetailMap.js
  src/scene/shader-lib/chunks/standard/frag/normalMap.js
  src/scene/shader-lib/chunks/standard/frag/opacity.js
  src/scene/shader-lib/chunks/standard/frag/parallax.js
  src/scene/shader-lib/chunks/standard/frag/sheen.js
  src/scene/shader-lib/chunks/standard/frag/sheenGloss.js
  src/scene/shader-lib/chunks/standard/frag/specular.js
  src/scene/shader-lib/chunks/standard/frag/specularityFactor.js
  src/scene/shader-lib/chunks/standard/frag/thickness.js
  src/scene/shader-lib/chunks/standard/frag/transmission.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7490 Move CameraFrame to the Graphics category
  src/extras/render-passes/camera-frame.js
Labels: docs, enhancement

#7491 Restore missing StandardMaterial properties from API reference
  utils/typedoc/typedoc-plugin.mjs
Labels: bug, docs

#7494 Restore @ignore tags for classes that should not be in the API reference
  src/core/math/blue-noise.js
  src/core/math/curve-evaluator.js
  src/core/object-pool.js
  src/platform/graphics/bind-group.js
  src/platform/graphics/dynamic-buffer.js
  src/platform/graphics/dynamic-buffers.js
  src/platform/graphics/gpu-profiler.js
  src/platform/graphics/null/null-index-buffer.js
  src/platform/graphics/null/null-render-target.js
  src/platform/graphics/null/null-shader.js
  src/platform/graphics/null/null-texture.js
  src/platform/graphics/null/null-vertex-buffer.js
  src/platform/graphics/uniform-buffer.js
  src/platform/graphics/vertex-iterator.js
  src/platform/graphics/webgl/webgl-buffer.js
  src/platform/graphics/webgl/webgl-index-buffer.js
  src/platform/graphics/webgl/webgl-render-target.js
  src/platform/graphics/webgl/webgl-shader.js
  src/platform/graphics/webgl/webgl-texture.js
  src/platform/graphics/webgl/webgl-vertex-buffer.js
  src/platform/graphics/webgpu/webgpu-bind-group-format.js
  src/platform/graphics/webgpu/webgpu-bind-group.js
  src/platform/graphics/webgpu/webgpu-buffer.js
  src/platform/graphics/webgpu/webgpu-clear-renderer.js
  src/platform/graphics/webgpu/webgpu-compute.js
  src/platform/graphics/webgpu/webgpu-index-buffer.js
  src/platform/graphics/webgpu/webgpu-mipmap-renderer.js
  src/platform/graphics/webgpu/webgpu-pipeline.js
  src/platform/graphics/webgpu/webgpu-render-target.js
  src/platform/graphics/webgpu/webgpu-resolver.js
  src/platform/graphics/webgpu/webgpu-shader.js
  src/platform/graphics/webgpu/webgpu-texture.js
  src/platform/graphics/webgpu/webgpu-uniform-buffer.js
  src/platform/graphics/webgpu/webgpu-vertex-buffer.js
  src/platform/sound/listener.js
  src/scene/composition/render-action.js
  src/scene/frame-graph.js
  src/scene/graphics/light-cube.js
  src/scene/mesh-instance.js
  src/scene/render.js
  src/scene/renderer/render-pass-cookie-renderer.js
  src/scene/renderer/render-pass-shadow-directional.js
  src/scene/renderer/render-pass-shadow-local-clustered.js
  src/scene/renderer/render-pass-update-clustered.js
  src/scene/renderer/world-clusters-allocator.js
  src/scene/shader-pass.js
  src/scene/skybox/sky-mesh.js
Labels: bug, docs

#7499 API Reference improvements and fixes
  package.json
  src/core/event-handler.js
  src/extras/render-passes/camera-frame.js
  src/framework/app-base.js
  src/framework/app-options.js
  src/framework/application.js
  src/framework/components/audio-listener/component.js
  src/framework/components/camera/component.js
  src/framework/components/collision/component.js
  src/framework/components/element/component.js
  src/framework/components/gsplat/component.js
  src/framework/components/light/component.js
  src/framework/components/registry.js
  src/framework/components/render/component.js
  src/framework/components/rigid-body/component.js
  src/framework/components/script/component.js
  src/framework/components/sound/component.js
  src/framework/entity.js
  src/framework/handlers/container.js
  src/framework/handlers/handler.js
  src/framework/handlers/loader.js
  src/framework/xr/xr-hit-test-source.js
  src/framework/xr/xr-input-source.js
  src/framework/xr/xr-mesh.js
  src/framework/xr/xr-view.js
  src/platform/net/http.js
  src/scene/graph-node.js
  src/scene/mesh-instance.js
  src/scene/shader-lib/programs/lit-shader-options.js
Labels: bug, docs, enhancement

#7500 Refactor MiniStats options types
  src/extras/mini-stats/mini-stats.js
  src/framework/application.js
Labels: enhancement

#7501 Tweak Script class API docs
  src/framework/script/script.js
Labels: docs, area: scripts, enhancement

#7502 Add API reference overview
  src/index.js
Labels: docs

#7504 Hide RenderPassPicker and fix 2 link warnings
  src/framework/graphics/render-pass-picker.js
  src/platform/graphics/graphics-device.js
Labels: bug, docs, area: graphics
