Repository playcanvas/engine, pull requests merged in 2025-04, with the labels that each got.

#7503 Simple graphics tests for parallax and detail maps tests
  examples/assets/textures/seaside-rocks01-ao.jpg
  examples/assets/textures/seaside-rocks01-height.jpg
  examples/assets/textures/seaside-rocks01-roughness.jpg
  examples/src/examples/test/detail-map.controls.mjs
  examples/src/examples/test/detail-map.example.mjs
  examples/src/examples/test/opacity.example.mjs
  examples/src/examples/test/parallax-mapping.controls.mjs
  examples/src/examples/test/parallax-mapping.example.mjs
  examples/thumbnails/test_detail-map_large.webp
  examples/thumbnails/test_detail-map_small.webp
  examples/thumbnails/test_parallax-mapping_large.webp
  examples/thumbnails/test_parallax-mapping_small.webp
Labels: area: examples

#7506 Improve API docs for ModelComponent and RenderComponent
  src/framework/components/model/component.js
  src/framework/components/render/component.js
  src/scene/graph-node.js
Labels: docs, area: graphics, enhancement

#7507 [Fix] Fixed manual loading of .hdr files using incorrect type / encoding
  src/framework/parsers/texture/hdr.js
Labels: bug, area: graphics, area: assets

#7508 Refactor the way diffuse, opacity and parallax code is generated for Standard frontend
  examples/thumbnails/test_opacity_large.webp
  examples/thumbnails/test_opacity_small.webp
  src/platform/graphics/constants.js
  src/scene/constants.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/standard/frag/detailModes.js
  src/scene/shader-lib/chunks/standard/frag/diffuse.js
  src/scene/shader-lib/chunks/standard/frag/diffuseDetailMap.js
  src/scene/shader-lib/chunks/standard/frag/opacity-dither.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7509 Refactored the normal maps code generation for Standard frontend
  src/scene/materials/standard-material-options-builder.js
  src/scene/materials/standard-material-options.js
  src/scene/shader-lib/chunk-utils.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/decode.js
  src/scene/shader-lib/chunks/standard/frag/clearCoatNormal.js
  src/scene/shader-lib/chunks/standard/frag/normalDetailMap.js
  src/scene/shader-lib/chunks/standard/frag/normalMap.js
  src/scene/shader-lib/chunks/standard/frag/normalXY.js
  src/scene/shader-lib/chunks/standard/frag/normalXYZ.js
  src/scene/shader-lib/programs/standard.js
Labels: feature, area: graphics

#7511 Moved the contact hadening shadow example to tests / hidden from published builds
  examples/src/examples/test/contact-hardening-shadows.controls.mjs
  examples/src/examples/test/contact-hardening-shadows.example.mjs
  examples/thumbnails/graphics_contact-hardening-shadows_large.webp
  examples/thumbnails/graphics_contact-hardening-shadows_small.webp
  examples/thumbnails/test_contact-hardening-shadows_large.webp
  examples/thumbnails/test_contact-hardening-shadows_small.webp
  examples/thumbnails/test_opacity_large.webp
  examples/thumbnails/test_opacity_small.webp
Labels: area: examples

#7512 [Fix] Color and Depth Grab Pass would in some cases ignore being enabled
  src/framework/components/camera/component.js
  src/scene/composition/layer-composition.js
Labels: bug, area: graphics

#7513 Refactored standard material refraction / transmission + example
  examples/src/examples/graphics/material-refraction.controls.mjs
  examples/src/examples/graphics/material-refraction.example.mjs
  examples/thumbnails/graphics_material-refraction_large.webp
  examples/thumbnails/graphics_material-refraction_small.webp
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, area: examples, enhancement

#7510 Support sogs
  src/framework/handlers/gsplat.js
  src/framework/parsers/gsplat-resource.js
  src/framework/parsers/sogs.js
  src/framework/parsers/texture/img.js
  src/scene/gsplat/gsplat-instance.js
  src/scene/gsplat/gsplat-sogs-data.js
  src/scene/gsplat/gsplat-sogs.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatCommon.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatSogsColor.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatSogsData.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatSogsSH.js
Labels: area: graphics, enhancement

#7516 Improve Euler-related docs
  src/core/math/quat.js
  src/framework/entity.js
  src/scene/graph-node.js
Labels: docs, enhancement

#7517 Refactor Asset class
  src/framework/asset/asset-file.js
  src/framework/asset/asset.js
Labels: docs, area: assets, enhancement

#7519 Refactored dealing with specular chunks / textures in standard shader generator
  examples/src/examples/test/material-test.example.mjs
  examples/thumbnails/test_material-test_large.webp
  examples/thumbnails/test_material-test_small.webp
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardPostCode.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7520 Tweaks to Anim API docs
  src/framework/anim/controller/anim-blend-tree.js
  src/framework/anim/controller/anim-state.js
  src/framework/anim/evaluator/anim-cache.js
  src/framework/anim/evaluator/anim-events.js
  src/framework/components/anim/component.js
Labels: docs, area: animation, enhancement

#7522 Refactor the use of emissive data during shader generation
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7524 Refactored clearCoat shader generation
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7518 Ply fetch
  src/framework/parsers/ply.js
Labels: enhancement

#7528 Assign some missing category JSDoc tags
  src/extras/gizmo/constants.js
  src/extras/render-passes/constants.js
  src/framework/anim/controller/anim-blend-tree-1d.js
  src/framework/anim/controller/anim-blend-tree-2d-cartesian.js
  src/framework/anim/controller/anim-blend-tree-2d-directional.js
  src/framework/anim/controller/anim-blend-tree-direct.js
  src/framework/anim/controller/anim-blend-tree.js
  src/framework/anim/controller/anim-node.js
  src/framework/anim/controller/anim-state.js
  src/framework/anim/controller/anim-transition.js
  src/platform/graphics/constants.js
  src/platform/graphics/uniform-buffer-format.js
  src/scene/constants.js
Labels: bug, docs

#7527 Refactor lightmap part of shader generation by the standard materials
  src/framework/lightmapper/lightmapper.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/standard/frag/lightmap.js
  src/scene/shader-lib/chunks/standard/frag/lightmapDir.js
  src/scene/shader-lib/chunks/standard/frag/lightmapSingle.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7529 Fix for GS in XR
  src/scene/gsplat/gsplat-instance.js
Labels: bug, area: graphics

#7531 Final refactor of standard shader generator - shader code moved to chunks
  examples/src/examples/graphics/normals-and-tangents.example.mjs
  src/index.js
  src/scene/shader-lib/chunk-builder.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/standard/frag/stdDeclaration.js
  src/scene/shader-lib/chunks/standard/frag/stdFrontEnd.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/standard.js
Labels: feature, area: graphics

#7535 Convert JS based particle shader generator to define based
  src/scene/particle-system/particle-material.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/particle/frag/particle-shader.js
  src/scene/shader-lib/chunks/particle/vert/particle-shader.js
  src/scene/shader-lib/programs/particle.js
Labels: area: graphics, area: particles, enhancement

#7539 [Fix] Update to disk/sphere area lights to avoid NaN values
  src/scene/shader-lib/chunks/lit/frag/ltc.js
Labels: bug, area: graphics

#7538 WebGPU texture read fix
  src/platform/graphics/webgpu/webgpu-texture.js
Labels: bug, area: graphics

#7540 [Fix] Fix CameraComponent.fog behavior
  examples/src/examples/test/global-shader-properties.example.mjs
  src/framework/components/camera/system.js
  src/scene/renderer/forward-renderer.js
Labels: bug, area: graphics

#7544 Fix to Nan handling in area lights for WebGPU
  src/scene/shader-lib/chunks/lit/frag/ltc.js
Labels: bug, area: graphics

#7547 Removed obsolete jsdocs part from Layer class
  src/scene/layer.js
Labels: bug, docs

#7543 Simplified the ShaderMaterial API to better support GLSL and WGSL shaders
  examples/src/examples/graphics/shader-wobble.example.mjs
  examples/src/examples/graphics/shader-wobble.shader.glsl.frag
  examples/src/examples/graphics/shader-wobble.shader.glsl.vert
  examples/src/examples/graphics/shader-wobble.shader.wgsl.frag
  examples/src/examples/graphics/shader-wobble.shader.wgsl.vert
  scripts/esm/grid.mjs
  src/extras/gizmo/shape/shape.js
  src/extras/mini-stats/render2d.js
  src/scene/gsplat/gsplat-material.js
  src/scene/immediate/immediate.js
  src/scene/materials/shader-material.js
  src/scene/shader-lib/programs/shader-generator-shader.js
  src/scene/skybox/sky-mesh.js
Labels: area: graphics, enhancement

#7549 [FIX] Address Anim API related TypeDoc warnings
  src/framework/anim/controller/anim-blend-tree-1d.js
  src/framework/anim/controller/anim-blend-tree.js
  src/framework/anim/controller/anim-state.js
Labels: bug, docs

#7545 Fix: Updated picker ID decoding to handle sign bit
  src/framework/graphics/picker.js
Labels: bug, area: graphics

#7550 WGSL versions of code vertex shader funcionality
  examples/assets/scripts/misc/gooch-material.mjs
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/renderer/renderer.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/decode.js
  src/scene/shader-lib/chunks-wgsl/common/frag/spherical.js
  src/scene/shader-lib/chunks-wgsl/common/vert/normalCore.js
  src/scene/shader-lib/chunks-wgsl/common/vert/skin.js
  src/scene/shader-lib/chunks-wgsl/common/vert/transformCore.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/base.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/litShaderArgs.js
  src/scene/shader-lib/chunks/common/vert/skin.js
  src/scene/shader-lib/chunks/common/vert/skinBatch.js
  src/scene/skin-instance.js
Labels: area: graphics, enhancement

#7551 [FIX] Address some TypeDoc warnings related to TextureParser
  src/framework/parsers/texture/texture.js
Labels: bug, docs

#7552 Refactor CurveSet constructor
  src/core/math/curve-set.js
Labels: docs, enhancement

#7554 WGSL shaders expose inputs as globals + fog fix
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/fog.js
Labels: feature, area: graphics

#7553 Improve physics API docs
  src/core/wasm-module.js
  src/framework/components/rigid-body/system.js
Labels: docs, area: physics, enhancement

#7557 Remove redundant @type tags from constants
  src/core/constants.js
  src/core/math/constants.js
  src/extras/gizmo/constants.js
  src/extras/render-passes/constants.js
  src/framework/anim/constants.js
  src/framework/anim/controller/constants.js
  src/framework/asset/constants.js
  src/framework/components/button/constants.js
  src/framework/components/element/constants.js
  src/framework/components/joint/constants.js
  src/framework/components/layout-group/constants.js
  src/framework/components/rigid-body/constants.js
  src/framework/components/screen/constants.js
  src/framework/components/scroll-view/constants.js
  src/framework/components/sprite/constants.js
  src/framework/constants.js
  src/framework/xr/constants.js
  src/platform/audio/constants.js
  src/platform/graphics/constants.js
  src/platform/input/constants.js
  src/scene/constants.js
Labels: docs, enhancement

#7559 [FIX] 2 more TypeDoc warnings
  src/scene/materials/standard-material.js
  src/scene/mesh-instance.js
  utils/plugins/rollup-types-fixup.mjs
Labels: bug, docs, area: graphics

#7561 Only validate shader vertex attributes when vertex buffers are set
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: bug, area: graphics

#7562 Deprecate all remaining global event constants
  examples/src/examples/graphics/area-picker.example.mjs
  examples/src/examples/graphics/integer-textures.example.mjs
  examples/src/examples/physics/vehicle.example.mjs
  src/deprecated/deprecated.js
  src/framework/components/scroll-view/component.js
  src/platform/input/constants.js
  src/platform/input/controller.js
  src/platform/input/game-pads.js
  src/platform/input/keyboard-event.js
  src/platform/input/keyboard.js
  src/platform/input/mouse-event.js
  src/platform/input/mouse.js
  src/platform/input/touch-device.js
  src/platform/input/touch-event.js
  test/platform/input/keyboard.test.mjs
  test/platform/input/mouse.test.mjs
Labels: docs, area: input, enhancement

#7569 Rename TRACE_ID_ELEMENT to TRACEID_ELEMENT
  src/core/constants.js
  src/framework/components/element/component.js
  src/framework/components/element/image-element.js
Labels: docs, enhancement

#7566 Small gsplat fix
  src/framework/parsers/sogs.js
Labels: bug, area: graphics

#7567 Add aa rendering support
  src/scene/shader-lib/chunks/gsplat/vert/gsplat.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatCommon.js
  src/scene/shader-lib/chunks/gsplat/vert/gsplatCorner.js
Labels: area: graphics, enhancement

#7571 Document gsplat asset type
  src/framework/asset/asset.js
Labels: bug

#7573 Improve typing for XrManager#session
  src/framework/xr/xr-manager.js
Labels: docs, area: xr, enhancement

#7570 Use function overloads for better typing and docs
  src/core/math/color.js
  src/core/math/quat.js
  src/core/math/vec2.js
  src/core/math/vec3.js
  src/core/math/vec4.js
  src/framework/components/rigid-body/component.js
  src/scene/graph-node.js
Labels: docs, enhancement

#7572 [BREAKING][FIX] Specular and sheen texture correctly handle sRGB encoding
  src/framework/parsers/glb-parser.js
  src/scene/materials/standard-material-options-builder.js
Labels: bug, area: graphics, area: gltf

#7574 A way to force linear encoded spec textures
  src/scene/materials/standard-material-options-builder.js
  src/scene/scene.js
Labels: area: graphics

#7576 Updated examples to reflect the API changes
  examples/assets/scripts/misc/hatch-material.mjs
  examples/src/examples/compute/particles.example.mjs
  examples/src/examples/graphics/grab-pass.example.mjs
  examples/src/examples/graphics/ground-fog.example.mjs
  examples/src/examples/graphics/paint-mesh.example.mjs
  examples/src/examples/graphics/point-cloud-simulation.example.mjs
  examples/src/examples/graphics/point-cloud.example.mjs
  examples/src/examples/graphics/reflection-planar.example.mjs
  examples/src/examples/graphics/shader-burn.example.mjs
  examples/src/examples/graphics/shader-toon.example.mjs
  examples/src/examples/graphics/texture-array.example.mjs
  examples/src/examples/graphics/transform-feedback.example.mjs
  examples/src/examples/loaders/loaders-gl.example.mjs
  examples/src/examples/user-interface/custom-shader.example.mjs
  examples/src/examples/xr/ar-camera-depth.example.mjs
Labels: area: graphics, area: examples

#7577 [Fix] Fix to asset class refactor
  src/framework/asset/asset.js
Labels: bug, area: assets

#7578 Minor fixes to various toArray function docs
  src/core/math/color.js
  src/core/math/vec2.js
  src/core/math/vec3.js
  src/core/math/vec4.js
Labels: bug, docs

#7582 Enable debug warning if the required uniform is null or undefined
  src/platform/graphics/webgl/webgl-graphics-device.js
Labels: area: graphics, enhancement

#7583 Convert many StandardMaterial front end and required backend chunks to WGSL
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/bayer.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/aoDiffuseOcc.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/aoSpecOcc.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lightSheen.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lighting/lightFunctionLight.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/metalnessModulate.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/reflDirAniso.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/reflectionCC.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/reflectionSheen.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/refractionDynamic.js
  src/scene/shader-lib/chunks-wgsl/lit/vert/uvTransform.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/alphaTest.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/ao.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/clearCoat.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/clearCoatGloss.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/clearCoatNormal.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/detailModes.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/diffuse.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/emissive.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/gloss.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/ior.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/iridescence.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/iridescenceThickness.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/metalness.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/normalMap.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/opacity-dither.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/opacity.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/parallax.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/sheen.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/sheenGloss.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/specular.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/specularityFactor.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/stdDeclaration.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/stdFrontEnd.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/thickness.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/transmission.js
  src/scene/shader-lib/chunks/lit/frag/aoSpecOcc.js
  src/scene/shader-lib/chunks/lit/frag/lighting/lightFunctionShadow.js
  src/scene/shader-lib/chunks/standard/frag/detailModes.js
  src/scene/shader-lib/chunks/standard/frag/normalMap.js
  src/scene/shader-lib/chunks/standard/frag/parallax.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/standard.js
Labels: feature, area: graphics

#7584 Morphing uses texture array to store morph targets
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/morph-instance.js
  src/scene/morph-target.js
  src/scene/morph.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/internal/morph/frag/morph.js
  src/scene/shader-lib/chunks-wgsl/internal/morph/frag/morphDeclaration.js
  src/scene/shader-lib/chunks-wgsl/internal/morph/frag/morphEvaluation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/internal/morph/frag/morph.js
  src/scene/shader-lib/chunks/internal/morph/frag/morphDeclaration.js
  src/scene/shader-lib/chunks/internal/morph/frag/morphEvaluation.js
Labels: performance, area: graphics

#7579 Fix texture type type
  src/platform/graphics/texture.js
Labels: area: graphics

#7587 Gsplat rotation fix
  src/scene/shader-lib/chunks/gsplat/vert/gsplatData.js
Labels: bug, area: graphics

#7590 WGSL support for batching
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/vert/skinBatch.js
Labels: area: graphics, enhancement

#7591 WGSL clustered cookies
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/clusteredLightCookies.js
Labels: area: graphics, enhancement

#7592 More gsplat inf checks
  src/scene/gsplat/gsplat-data.js
Labels: bug, area: graphics

#7594 WGSL support for picker pass
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/pick.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-other/litOtherMain.js
  src/scene/shader-lib/chunks/common/frag/pick.js
Labels: area: graphics, enhancement

#7595 Improve Texture JSDocs (and some others)
  src/core/math/color.js
  src/framework/anim/binder/default-anim-binder.js
  src/platform/graphics/texture.js
  src/scene/materials/material.js
  src/scene/materials/standard-material.js
Labels: docs, enhancement

#7596 Histogram sort for uncompressed gsplat
  src/scene/gsplat/gsplat-sorter.js
Labels: area: graphics, enhancement

#7598 [Fix] Fix shader passes order
  src/scene/constants.js
  src/scene/shader-pass.js
Labels: bug, area: graphics

#7599 WGSL implementation of VSM shadows
  src/scene/renderer/shadow-renderer.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/vert/fullscreenQuad.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/blurVSM.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lighting/lightDeclaration.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lighting/shadowEVSM.js
  src/scene/shader-lib/chunks/common/vert/fullscreenQuad.js
  src/scene/shader-lib/chunks/lit/frag/blurVSM.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowEVSM.js
Labels: area: graphics, enhancement

#7600 Removed unused fullscreenQuadPS chunk
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/common/frag/fullscreenQuad.js
Labels: area: graphics, enhancement

#7601 Revert recent types
  src/platform/graphics/texture.js
Labels: enhancement

#7602 WGSL implementation of soft shadows
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/linearizeDepth.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/cubeMapRotate.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lighting/lightFunctionShadow.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lighting/lighting.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lighting/shadowSoft.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-shadow/litShadowMain.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/diffuse.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/emissive.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/sheen.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/specular.js
  src/scene/shader-lib/chunks/common/frag/linearizeDepth.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowPCSS.js
  src/scene/shader-lib/chunks/lit/frag/lighting/shadowSoft.js
  src/scene/shader-lib/chunks/lit/frag/pass-shadow/litShadowMain.js
Labels: area: graphics, enhancement

#7603 The built-in instancing works with WGSL
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/vert/transformInstancing.js
  src/scene/shader-lib/programs/lit-shader.js
Labels: area: graphics, enhancement

#7606 WGSL version of remaining reflection chunks
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/cubeMapProject.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/reflectionCube.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/reflectionEnvHQ.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/reflectionSphere.js
  src/scene/shader-lib/chunks/lit/frag/reflectionEnvHQ.js
  src/scene/shader-lib/chunks/lit/frag/reflectionSphere.js
Labels: area: graphics, enhancement

#7607 [FIX] Restore callback descriptions
  src/core/event-handler.js
  src/core/wasm-module.js
  src/framework/anim/evaluator/anim-target.js
  src/framework/app-base.js
  src/framework/asset/asset-registry.js
  src/framework/asset/asset.js
  src/framework/components/camera/component.js
  src/framework/handlers/handler.js
  src/framework/handlers/loader.js
  src/framework/handlers/model.js
  src/framework/scene-registry.js
  src/framework/script.js
  src/framework/xr/xr-anchor.js
  src/framework/xr/xr-anchors.js
  src/framework/xr/xr-hit-test.js
  src/framework/xr/xr-manager.js
  src/platform/input/mouse.js
  src/platform/net/http.js
  src/scene/graph-node.js
  src/scene/mesh-instance.js
Labels: bug, docs

#7608 WGSL chunks for msdf and nine-sliced UI rendering
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/msdf.js
  src/scene/shader-lib/chunks-wgsl/common/vert/msdf.js
  src/scene/shader-lib/chunks-wgsl/common/vert/transform.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/baseNineSliced.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/baseNineSlicedTiled.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-forward/litForwardBackend.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/startNineSliced.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/startNineSlicedTiled.js
  src/scene/shader-lib/chunks-wgsl/lit/vert/litMain.js
  src/scene/shader-lib/chunks-wgsl/lit/vert/uv0.js
  src/scene/shader-lib/chunks/common/frag/msdf.js
  src/scene/shader-lib/chunks/lit/frag/startNineSliced.js
Labels: area: graphics, enhancement

#7609 Gsplat render fix for wgpu
  src/scene/shader-lib/chunks/gsplat/vert/gsplatCenter.js
Labels: bug, area: graphics

#7610 WGSL version of few internal chunks
  src/platform/graphics/constants.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/vert/normalCore.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lightSpecularAnisoGGX.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-forward/litForwardBackend.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/twoSidedLighting.js
  src/scene/shader-lib/chunks-wgsl/lit/vert/litMain.js
  src/scene/shader-lib/chunks/chunk-validation.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/vert/litMain.js
  src/scene/shader-lib/chunks/lit/vert/tangentBinormal.js
Labels: area: graphics

#7612 WGSL version of screenDepth chunk and debug texture shaders
  src/scene/immediate/immediate.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/screenDepth.js
  src/scene/shader-lib/chunks/common/frag/screenDepth.js
Labels: area: graphics, enhancement

#7613 WGSL version of outputTex2DPS chunk used by outline-renderer
  src/extras/renderers/outline-renderer.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/outputTex2D.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-forward/litForwardBackend.js
Labels: area: graphics, enhancement

#7617 Improve JSDocs for Geometry classes
  src/scene/geometry/box-geometry.js
  src/scene/geometry/capsule-geometry.js
  src/scene/geometry/cone-base-geometry.js
  src/scene/geometry/cone-geometry.js
  src/scene/geometry/cylinder-geometry.js
  src/scene/geometry/dome-geometry.js
  src/scene/geometry/plane-geometry.js
  src/scene/geometry/sphere-geometry.js
  src/scene/geometry/torus-geometry.js
Labels: docs, area: graphics, enhancement

#7615 Use arrow functions in all example code
  src/framework/asset/asset-registry.js
  src/framework/asset/asset.js
  src/framework/bundle/bundle.js
  src/framework/components/camera/component.js
  src/framework/handlers/container.js
  src/framework/scene-registry.js
  src/framework/script.js
  src/framework/xr/xr-anchors.js
  src/framework/xr/xr-hit-test-source.js
  src/framework/xr/xr-hit-test.js
  src/framework/xr/xr-input-source.js
  src/scene/graph-node.js
Labels: docs, enhancement

#7619 More incremental improvements to JSDocs
  src/core/shape/tri.js
  src/core/tags.js
  src/extras/render-passes/camera-frame.js
  src/framework/components/scrollbar/data.js
  src/framework/components/sound/slot.js
  src/framework/components/sound/system.js
  src/framework/xr/xr-manager.js
  src/platform/sound/sound.js
  src/scene/materials/standard-material.js
Labels: docs, enhancement

#7620 Improve Gizmo API docs
  src/extras/gizmo/rotate-gizmo.js
  src/extras/gizmo/scale-gizmo.js
  src/extras/gizmo/translate-gizmo.js
Labels: docs, enhancement

#7621 Improve SoundSlot API docs
  src/framework/components/sound/slot.js
Labels: docs, area: audio, enhancement

#7622 Improve ScreenComponent API docs
  src/framework/components/camera/component.js
  src/framework/components/collision/component.js
  src/framework/components/element/component.js
  src/framework/components/gsplat/component.js
  src/framework/components/light/component.js
  src/framework/components/model/component.js
  src/framework/components/render/component.js
  src/framework/components/rigid-body/component.js
  src/framework/components/screen/component.js
  src/framework/components/script/component.js
  src/framework/components/sound/component.js
Labels: docs, area: ui, enhancement

#7623 CoreExporter image transformation uses WGSL shader on WebGPU
  src/extras/exporters/core-exporter.js
Labels: area: graphics, enhancement

#7605 Fix bloom artifacts appearing due to bad specular data
  src/scene/shader-lib/chunks/lit/frag/fresnelSchlick.js
Labels: bug, area: graphics

#7618 Misc types fixes
  src/core/string.js
  src/framework/components/scroll-view/component.js
  test/core/string.test.mjs
Labels: bug

#7625 WGSL version of LTC shader chunk used to evaluate area lights
  src/platform/graphics/webgpu/webgpu-shader-processor-wgsl.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/ltc.js
  src/scene/shader-lib/chunks/lit/frag/ltc.js
Labels: area: graphics, enhancement

#7627 Lightmapping WGSL chunks
  src/framework/lightmapper/lightmap-filters.js
  src/framework/lightmapper/lightmapper.js
  src/index.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/lightmapper/frag/bakeDirLmEnd.js
  src/scene/shader-lib/chunks-wgsl/lightmapper/frag/bakeLmEnd.js
  src/scene/shader-lib/chunks-wgsl/lightmapper/frag/bilateralDeNoise.js
  src/scene/shader-lib/chunks-wgsl/lightmapper/frag/dilate.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/lightmapAdd.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-forward/litForwardBackend.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-forward/litForwardDeclaration.js
  src/scene/shader-lib/chunks-wgsl/standard/frag/lightmap.js
  src/scene/shader-lib/chunks/chunks-lightmapper.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lightmapper/frag/bakeDirLmEnd.js
  src/scene/shader-lib/chunks/lightmapper/frag/bakeLmEnd.js
  src/scene/shader-lib/chunks/lightmapper/frag/bilateralDeNoise.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardBackend.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardDeclaration.js
Labels: area: graphics, enhancement

#7626 Update NPM dependencies
  package-lock.json
  package.json
Labels: dependencies

#7628 [Fix] More flexible Preprocessor handling of include directive
  src/core/preprocessor.js
Labels: bug, area: graphics

#7629 Strip comments from the chunk before the validation
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement

#7631 WGSL version of an internal floatAsUintPS shader chunk
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/common/frag/float-as-uint.js
  src/scene/shader-lib/chunks-wgsl/lit/vert/litMain.js
Labels: area: graphics, enhancement

#7632 Custom user chunks to customize lit / standard shaders
  src/scene/materials/lit-material-options-builder.js
  src/scene/materials/standard-material-options-builder.js
  src/scene/shader-lib/chunks-wgsl/chunks-wgsl.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/litMain.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-forward/litForwardMain.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-other/litOtherMain.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/pass-shadow/litShadowMain.js
  src/scene/shader-lib/chunks-wgsl/lit/frag/refractionDynamic.js
  src/scene/shader-lib/chunks-wgsl/lit/vert/litMain.js
  src/scene/shader-lib/chunks/chunks.js
  src/scene/shader-lib/chunks/lit/frag/litMain.js
  src/scene/shader-lib/chunks/lit/frag/pass-forward/litForwardMain.js
  src/scene/shader-lib/chunks/lit/frag/pass-other/litOtherMain.js
  src/scene/shader-lib/chunks/lit/frag/pass-shadow/litShadowMain.js
  src/scene/shader-lib/chunks/lit/vert/litMain.js
  src/scene/shader-lib/programs/lit-shader-options.js
  src/scene/shader-lib/programs/lit-shader.js
  src/scene/shader-lib/programs/lit.js
  src/scene/shader-lib/programs/standard.js
Labels: area: graphics, enhancement
